### ISSUE TITLE
The broker should detect overlapping cluster/service CIDRs

### ISSUE THREAD

**Issue by sheng-liang** [submariner-io/submariner#1]
Submariner does not function with overlapping cluster/service CIDRs.

**Comment by Oats87** [comment]
Overlap detection is a bit more difficult from the broker side, as the broker does not have any logic contained within it. Instead, Submariner should examine the broker to determine if there is any overlap.

**Comment by mkolesnik** [comment]
Technically the broker could detect an overlap in CIDRs, but what is it supposed to do with this information?

I see this as a more high level problem of the deployment of the multi-cluster, for which the solution should also come from a much higher level entity which manages the deployment.

At best, the broker could issue a warning to the log that this is the case, but IMHO this has little if any value.

**Comment by mangelajo** [comment]
This works now with subctl and the overlapping cidr support. Thanks :)
