### ISSUE TITLE
Question on Prerequisites

### ISSUE THREAD

**Issue by tibwiz** [submariner-io/submariner#10]
As part of the Prerequisites documentation its mentioned that 

> Submariner has a few requirements in order to get started:

> At least 3 Kubernetes clusters

We have a two kubernetes clusters and we want to extent the networking across the clusters. So can anybody confirm the requirement of 3 clusters is a hard requirement or it can work with 2 clusters also?

**Comment by Oats87** [comment]
You can technically elect one of your two clusters to be the "broker" but this doesn't resiliently scale past 2 clusters, because if that cluster dies you are left without connectivity.

**Comment by debianmaster** [comment]
@Oats87   im just trying out submariner and trying to install both  broker and gateway in 1 cluster.
but encountering this issue . https://github.com/submariner-io/submariner/issues/104

**Comment by tpantelis** [comment]
See resolution in https://github.com/submariner-io/submariner/issues/104.
