### ISSUE TITLE
Submariner IPsec cannot continue to retry the connections on Azure

### ISSUE THREAD

**Issue by skeeey** [submariner-io/submariner#1004]
**What happened**:
After I deployed the Submariner components on Azure, to make Submariner work, I create the required NSG rules and load balancing rules , but Submariner did not work, then I reinstall the Submariner, it works

**What you expected to happen**:
I don't need prepare the Submariner environment in advance 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

1. I use below command to configure my Azure
```
az network lb rule create --resource-group wlazurecluster-pmfkq-rg --lb-name wlazurecluster-pmfkq \
    --name submariner-ipsec-500 \
    --protocol Udp --frontend-port 500 --backend-port 500 \
    --frontend-ip-name public-lb-ip-v4 --backend-pool-name wlazurecluster-pmfkq
az network lb rule create --resource-group wlazurecluster-pmfkq-rg --lb-name wlazurecluster-pmfkq \
    --name submariner-ipsec-4500 \
    --protocol Udp --frontend-port 4500 --backend-port 4500 \
    --frontend-ip-name public-lb-ip-v4 --backend-pool-name wlazurecluster-pmfkq

az network nsg rule create --resource-group wlazurecluster-pmfkq-rg --nsg-name wlazurecluster-pmfkq-nsg --priority 400 \
    --name submariner-udp-500-in --direction Inbound --access Allow --protocol Udp --destination-port-ranges 500 
az network nsg rule create --resource-group wlazurecluster-pmfkq-rg --nsg-name wlazurecluster-pmfkq-nsg --priority 401 \
    --name submariner-udp-4500-in --direction Inbound --access Allow --protocol Udp --destination-port-ranges 4500
az network nsg rule create --resource-group wlazurecluster-pmfkq-rg --nsg-name wlazurecluster-pmfkq-nsg --priority 402 \
    --name submariner-udp-4800-in --direction Inbound --access Allow --protocol Udp --destination-port-ranges 4800

az network nsg rule create --resource-group wlazurecluster-pmfkq-rg --nsg-name wlazurecluster-pmfkq-nsg --priority 400 \
    --name submariner-udp-500-out --direction Outbound --access Allow --protocol Udp --destination-port-ranges 500 
az network nsg rule create --resource-group wlazurecluster-pmfkq-rg --nsg-name wlazurecluster-pmfkq-nsg --priority 401 \
    --name submariner-udp-4500-out --direction Outbound --access Allow --protocol Udp --destination-port-ranges 4500
az network nsg rule create --resource-group wlazurecluster-pmfkq-rg --nsg-name wlazurecluster-pmfkq-nsg --priority 402 \
    --name submariner-udp-4800-out --direction Outbound --access Allow --protocol Udp --destination-port-ranges 4800
```
2. I only test this case on Azure

**Environment**:
- Submariner version (use `subctl version`): `subctl version: v0.8.0-rc0`
- Kubernetes version (use `kubectl version`): `v1.19`
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sridhargaddam** [comment]
Ideally, I would expect it to work even if the NSG/LB rules are added later. But if you are seeing this behavior, then it needs some investigation.

**Comment by nyechiel** [comment]
@skeeey do you know if this issue is reproducible? can you please test this again with Azure or other provider?

**Comment by skeeey** [comment]
@nyechiel yes, we will test this again

**Comment by skeeey** [comment]
@nyechiel I retested this with `subctl version: v0.8.0`,  this issue can not be reproduced again, so close this
