### ISSUE TITLE
Cannot install submariner-operator from OCP OperatorHub

### ISSUE THREAD

**Issue by skeeey** [submariner-io/submariner#1015]
**What happened**:
When I install submariner-operator from OCP OperatorHub, the below error occurred

```
error creating clusterrolebinding submariner-lighthouse: ClusterRoleBinding.rbac.authorization.k8s.io "submariner-lighthouse" is invalid: subjects[0].namespace: Required value
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): 
- Kubernetes version (use `kubectl version`): ocp-4.6.4/kube-v1.19
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by SteveMattar** [comment]
https://github.com/operator-framework/community-operators/pull/2829

**Comment by skeeey** [comment]
tested with the fix
