### ISSUE TITLE
CI test failure debug:  GlobalNet connectivity - From Netshoot pod To Nginx service  by its Global IP:

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/submariner#1019]
Testing GlobalNet connectivity - From Netshoot pod netshoot-cl-a (IP 169.254.5.30) on cluster A
  To Nginx service on cluster B, by its Global IP: 
curl: (28) Connection timed out after 30000 milliseconds
command terminated with exit code 28

from this job : https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-Globalnet/37/Test-Report/

I dont see the service cluster ip actually :
[r@r20 submariner_ci]$   kubectl get service --all-namespaces|grep 8080
openshift-monitoring                                    cluster-monitoring-operator                              ClusterIP      None             <none>                                 8080/TCP                     28d
openshift-monitoring                                    prometheus-operator                                      ClusterIP      None             <none>                                 8080/TCP                     28d
submariner-operator                                     submariner-engine-metrics                                ClusterIP      100.96.115.107   <none>                                 8080/TCP                     28h
test-submariner-headless                                nginx-cl-b                                               ClusterIP      None             <none>                                 8080/TCP                     4h9m
test-submariner                                         nginx-cl-b                                               ClusterIP      100.96.13.240    <none>                                 8080/TCP                     4h19m
pkomarov  4 minutes ago

supposed to be 169.254.33.173,

**Comment by pinikomarov** [comment]
Hi @nyechiel , not sure how to ping people about this , so I posted on slack also , 
Is there anyone in particular I should debug this with ? to help speed things up in case this is a known issue , or a real bug ?
Thanks

**Comment by sridhargaddam** [comment]
@pinikomarov I dont see the service in the list of services. First, we have to understand why the Service is not created. Can you please check it.

**Comment by sridhargaddam** [comment]
From a quick look at the setup, the issue was that connection was not established between the clusters.

```
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
default-cl1                   10.166.0.217    66.187.232.129  libreswan           local           
nmanos-cluster-a              10.166.125.26   13.56.156.120   libreswan           remote          

GATEWAY                         CLUSTER                 REMOTE IP       CABLE DRIVER        SUBNETS                                 STATUS          
ip-10-166-125-26                nmanos-cluster-a        10.166.125.26   libreswan           169.254.0.0/19                          connecting 
```

We have to investigate why the connection failed.

**Comment by sridhargaddam** [comment]
Looks like some SG/ACL issue. IPsec traffic from default-cl1 is not seen on nmanos-cluster-a (and vice-versa). Please check your SG/ACLs rules.

```
12:57:25.406754 Out fa:16:3e:e9:56:c2 ethertype IPv4 (0x0800), length 868: 10.166.0.217.4501 > 13.56.156.120.4501: UDP, length 824
12:57:25.907428 Out fa:16:3e:e9:56:c2 ethertype IPv4 (0x0800), length 868: 10.166.0.217.4501 > 13.56.156.120.4501: UDP, length 824
12:57:26.408093 Out fa:16:3e:e9:56:c2 ethertype IPv4 (0x0800), length 868: 10.166.0.217.4501 > 13.56.156.120.4501: UDP, length 824
12:57:27.409084 Out fa:16:3e:e9:56:c2 ethertype IPv4 (0x0800), length 868: 10.166.0.217.4501 > 13.56.156.120.4501: UDP, length 824
12:57:29.411212 Out fa:16:3e:e9:56:c2 ethertype IPv4 (0x0800), length 868: 10.166.0.217.4501 > 13.56.156.120.4501: UDP, length 824
12:57:33.413058 Out fa:16:3e:e9:56:c2 ethertype IPv4 (0x0800), length 868: 10.166.0.217.4501 > 13.56.156.120.4501: UDP, length 824
12:57:41.414254 Out fa:16:3e:e9:56:c2 ethertype IPv4 (0x0800), length 868: 10.166.0.217.4501 > 13.56.156.120.4501: UDP, length 824
```

**Comment by pinikomarov** [comment]
Thanks @sridhargaddam , 
Because of lack of time , I  couldn't get the logs needed for your question.
Since this did not reproduce in the net run, I'm closing this for now and will reopen if this issue comes up again , this way we could at least track it.

**Comment by pinikomarov** [comment]
@sridhargaddam with this card maybe next time we'll have logs or info into the cluster env , so we can take a llok back and see what happened : https://github.com/submariner-io/shipyard/issues/381
