### ISSUE TITLE
OVN: The ovn loadbalancers (ClusterIP) seem to choke on jumboframes / icmp requesting frag to the service

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1022]
**What happened**:

Our E2E tests fail since we test jumboframe fragmentation. (by chance... not by design)

https://mail.openvswitch.org/pipermail/ovs-discuss/2020-December/050834.html

iptables -I FORWARD -o ovn-k8s-gw0 -p tcp --tcp-flags SYN,RST SYN -j TCPMSS  --set-mss 1398   

**What you expected to happen**:

Service tests to work

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Something that seems to workaround this, although it's not perfect, is to find the PMTU to the destination cluster....
```
sh-4.4# tracepath 10.133.2.2
 1?: [LOCALHOST]                      pmtu 8938
 1?: [LOCALHOST]                      pmtu 1438
 1:  ip-10-133-2-2.us-east-2.compute.internal              0.440ms reached
 1:  ip-10-133-2-2.us-east-2.compute.internal              0.410ms reached
     Resume: pmtu 1438 hops 1 back 1 
```

And then clamp TCP/MSS with pmtu-40 (40 = IP + TCP overhead)
```
iptables -I FORWARD -o ovn-k8s-gw0 -p tcp --tcp-flags SYN,RST SYN -j TCPMSS  --set-mss 1398
```

This won't help with UDP, but will help until we can figure out a solution in ovn. (if it's really in ovn.)

This was tried without success:
```
iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS  --clamp-mss-to-pmtu
```

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sridhargaddam** [comment]
@mangelajo can you try if the following solution works with OVN?

https://github.com/submariner-io/submariner/issues/995#issuecomment-738010826

**Comment by mangelajo** [comment]
> @mangelajo can you try if the following solution works with OVN?
> 
> [#995 (comment)](https://github.com/submariner-io/submariner/issues/995#issuecomment-738010826)

I tried, it doesn't work in this case with OVN.

**Comment by mangelajo** [comment]
I will be using this instead (note the -d) to be more selective on what's exactly clamped
```
iptables -I FORWARD -o ovn-k8s-gw0 -d 172.30.0.0/16 -p tcp --tcp-flags SYN,RST SYN -j TCPMSS  --set-mss 1398    
```

**Comment by mangelajo** [comment]
The MSS clamping workaround is in place, so we can close this one for now, although we must keep an eye on OVN for a proper fix.
