### ISSUE TITLE
D/S CI tests failures debug: e2e with cubctl command :Failed to find pods for app nginx-demo

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/submariner#1024]
Testing Submariner End-to-End tests with SubCtl command :

https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-No-Overlapping/112/Test-Report/

Summarizing 6 Failures:

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159
[] E2E failed

maybe this is why : 
during the test buildup : 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:22
  when a pod tries to resolve a service in a remote cluster
  /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:26
    should be able to discover the remote service successfully [It]
    /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:27

    Failed to find pods for app nginx-demo. Status for pod "nginx-demo-5598bbc5d7-xlvvq" is Pending
    Unexpected error:
        <*errors.errorString | 0xc00045c060>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    occurred

still investigating...

**Comment by pinikomarov** [comment]
duration : past three days

**Comment by pinikomarov** [comment]
@manosnoam  what do make of this  : ? 


from the test_report: 

https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-No-Overlapping/111/Test-Report/

• Failure [240.357 seconds]
[discovery] Test Service Discovery Across Clusters
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:22
  when a pod tries to resolve a service in a remote cluster
  /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:26
    should be able to discover the remote service successfully [It]
    /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:27

    Failed to find pods for app nginx-demo. Status for pod "nginx-demo-5598bbc5d7-xlvvq" is Pending
    Unexpected error:
        <*errors.errorString | 0xc00045c060>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    occurred

**Comment by nyechiel** [comment]
@manosnoam @pinikomarov 0.8.0-rc1 is tagged now and includes all the right fixes. I ran E2E with OCP on AWS and don't see any failures. Can you retest?
