### ISSUE TITLE
Duplicated connections on upgrade test (re-enable-upgrade-test)

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1031]
**What happened**:

The upgrade tests on the submariner repo are failing , for example: 
https://github.com/submariner-io/submariner/pull/1030/checks?check_run_id=1556110859

This change to shipyard probably unveils it:
https://github.com/submariner-io/shipyard/pull/380

After being applied, we wee the upgrade jobs timeout sometimes, and also:

```
[submariner]$ [cluster3] grep connected
cluster1-worker                 cluster1                172.17.0.8      libreswan           100.1.0.0/16, 10.1.0.0/16               connected       
cluster2-worker                 cluster2                172.17.0.5      libreswan           100.2.0.0/16, 10.2.0.0/16               connected       
cluster2-worker                 cluster2                172.17.0.5      libreswan           100.2.0.0/16, 10.2.0.0/16               connected       
cluster3-worker                 cluster3                172.17.0.11     libreswan           100.3.0.0/16, 10.3.0.0/16               connected       
cluster1-worker                 cluster1                172.17.0.8      libreswan           100.1.0.0/16, 10.1.0.0/16               connected       
cluster3-worker                 cluster3                172.17.0.11     libreswan           100.3.0.0/16, 10.3.0.0/16               connected
```

**What you expected to happen**:

Upgrade test passing

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tpantelis** [comment]
Is this still an issue? The upgrade test is passing now.

**Comment by skitt** [comment]
> Is this still an issue? The upgrade test is passing now.

We worked around this by waiting for the CR deletion to be complete before creating the new one; ideally we should be capable of handling simultaneous additions and removals of CRs.
