### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner#1032]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nyechiel** [comment]
Hi @Jaanki - just wanted to make sure you have seen this one: https://github.com/submariner-io/submariner/pull/1010

**Comment by dfarrell07** [comment]
This has been fixed :heavy_check_mark:

**Comment by Jaanki** [comment]
Closing this, Fixed with #1010
