### ISSUE TITLE
[E2E] Test "cluster to cluster heartbeats" updates the lighthouse DNS when cluster is down

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#1041]
Please add E2E test for https://github.com/submariner-io/submariner/issues/821

_Originally posted by @nyechiel in https://github.com/submariner-io/submariner/issues/821#issuecomment-746926516_

**Comment by nyechiel** [comment]
@aswinsuryan is this something you can explore?

**Comment by aswinsuryan** [comment]
> @aswinsuryan is this something you can explore?

Yes I can, I have assigned it to me.
