### ISSUE TITLE
ovn-nbctl in fedora:33 image fails talking to ovn-kubernetes

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1063]
**What happened**:

```
I0104 16:45:58.900913       1 nbctl.go:57] ovn-nbctl [--db=tcp:172.17.0.10:6641 lr-policy-add ovn_cluster_router 20000 ip4.dst == 100.2.0.0/16 reroute 169.254.254.1]
E0104 16:45:58.913724       1 nbctl.go:64] error running ovn-nbctl exit status 1, output:
2021-01-04T16:45:58Z|00002|ovsdb_idl|WARN|Load_Balancer table in OVN_Northbound database lacks options column (database needs upgrade?)
2021-01-04T16:45:58Z|00003|ovsdb_idl|WARN|Logical_Router_Policy table in OVN_Northbound database lacks nexthops column (database needs upgrade?)
2021-01-04T16:45:58Z|00004|ovsdb_idl|WARN|transaction error: {"details":"No column nexthops in table Logical_Router_Policy.","error":"unknown column","syntax":"{\"action\":\"reroute\",\"match\":\"ip4.dst == 100.2.0.0/16\",\"nexthops\":\"169.254.254.1\",\"priority\":20000}"}
ovn-nbctl: transaction error: {"details":"No column nexthops in table Logical_Router_Policy.","error":"unknown column","syntax":"{\"action\":\"reroute\",\"match\":\"ip4.dst == 100.2.0.0/16\",\"nexthops\":\"169.254.254.1\",\"priority\":20000}"}
E0104 16:45:58.913791       1 endpoint_created.go:22] Error handling created endpoint: RemoteEndpointCreated failed: "ovn-sync-handler" returned error: error adding the "100.2.0.0/16" routing rule to router "ovn_cluster_router": exit status 1
I0104 16:45:58.913813       1 resource_syncer.go:352] Syncer "Endpoint watcher for networkplugin-syncer registry": transform function returned nil - not syncing - requeue: true
I0104 16:45:58.913842       1 queue.go:88] Endpoint watcher for networkplugin-syncer registry: enqueued "submariner-operator/cluster2-submariner-cable-cluster2-172-17-0-6" for retry - # of times re-queued: 17
```

**What you expected to happen**:

For lr-policy-add in network plugin syncer to work.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy shipyard with ovn, from: https://github.com/submariner-io/shipyard/pull/387, and deploy  submariner-devel.
 

**Anything else we need to know?**:
opened a bug in ovn: https://github.com/ovn-org/ovn/issues/70

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mangelajo** [comment]
Probably the simplest alternative is downgrading to fedora:32 for now on this container. And long term implement those functions on go-ovn, and make go-ovn smart about the scheme version.

**Comment by mangelajo** [comment]
@skitt what do you think about the workaround I'm proposing?, I'm going to test locally

**Comment by skitt** [comment]
> @skitt what do you think about the workaround I'm proposing?, I'm going to test locally

If I’ve understood this correctly, we need `ovn-nbctl` in the container image to match the version expected by https://github.com/ovn-org/ovn-kubernetes/blob/master/dist/images/Dockerfile.fedora, is that correct? If so, then yes, downgrading to `fedora:32` would work for now.

**Comment by mangelajo** [comment]
> > @skitt what do you think about the workaround I'm proposing?, I'm going to test locally
> 
> If I’ve understood this correctly, we need `ovn-nbctl` in the container image to match the version expected by https://github.com/ovn-org/ovn-kubernetes/blob/master/dist/images/Dockerfile.fedora, is that right? If so, then yes, downgrading to `fedora:32` would work for now.

It seems that so far ovn-nbctl is compatible with newer versions of the DB (up to some degree, I'm talking with the ovn folks to determine this) @numansiddique may be you can elaborate on this when you read... but at least not the other way around.

Thanks for the pointer, it seems like they use fedora:32 for now.

**Comment by numansiddique** [comment]
A simple workaround would be to create router policy as:

ovn-nbctl -- --id=@lrp create Logical_Router_Policy
match="ip4.dst == 100.2.0.0/16" priority=20000 action=reroute nexthop=169.254.254.1 -- add Logical_Router
ovn_cluster_router policies @lrp

**Comment by mangelajo** [comment]
Oh, I think I will go with this option better:

https://github.com/ovn-org/ovn/issues/70#issuecomment-754444595

So we don't need to mix image versions around, or depend on the exact ovn-nbctl version in place

**Comment by mangelajo** [comment]
> Oh, I think I will go with this option better:
> 
> > A simple workaround would be to create router policy as:
> > ovn-nbctl -- --id=@lrp create Logical_Router_Policy
> > match="ip4.dst == 100.2.0.0/16" priority=20000 action=reroute nexthop=169.254.254.1 -- add Logical_Router
> > ovn_cluster_router policies @lrp
> 
> So we don't need to mix image versions around, or depend on the exact ovn-nbctl version in place

Ok, I'm going back to the initial approach of switching to the fedora:32 image for now. I realized that I will need to change also the lr-policy-del & lr-policy-list functions here: https://github.com/submariner-io/submariner/blob/e523f9a0531c89a43558f89ecdc4b90b495d0438/pkg/networkplugin-syncer/handlers/ovn/nbctl/nbctl.go#L134

Since ovn-nbctl is just a workaround until I add policy funcionality into go-ovn I believe It's better to invest coding time in there and switch the image for the time being.
