### ISSUE TITLE
Endpoint HealthcheckIP should use globalIP in Globalnet Deployments

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1068]
**What would you like to be added**:
Currently, while creating a localEndpoint in a cluster, the HealthCheckIP points to the cniInterfaceIP of the node. This is all done in the GatewayEngine component. While this works fine for vanilla Submariner deployments, when using Globalnet, the HealthCheckIP should be pointing to the globalIP assigned to the node.

**Why is this needed**:
So that we can enable HealthCheck even with Globalnet deployments.

**Comment by tpantelis** [comment]
bump

**Comment by sridhargaddam** [comment]
The necessary enhancement is already implemented and merged.
