### ISSUE TITLE
Globalnet fails to annotate service without port name

### ISSUE THREAD

**Issue by mkimuram** [submariner-io/submariner#1091]
**What happened**: If service without port name is created, globalnet fails to annotate
service, as a result, the service can't be accessed from another cluster.

**What you expected to happen**: The service is annotated properly and be accessible from another cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Create service without port name in an environment where submariner w/ globalnet is enabled.
```
$ kubectl create ns ns1
$ kubectl run my-pod1 -n ns1
--image=registry.access.redhat.com/ubi7/ubi:latest --command -- python
-m SimpleHTTPServer 80
$ kubectl expose pod my-pod1 -n ns1 --name=my-service1 --port=80
```
Then, check that the service isn't annotated with `submariner.io/globalIP`.
```
$ kubectl get svc -n ns1 my-service1 -o jsonpath='{.metadata.annotations}'
```

**Anything else we need to know?**:

iptables rule for the service is as follows: 
```
# iptables -t nat -nvL --line-numbers | grep my-service1
1        0     0 KUBE-MARK-MASQ  all  --  *      *       10.44.0.12
      0.0.0.0/0            /* ns1/my-service1 */
2        0     0 DNAT       tcp  --  *      *       0.0.0.0/0
0.0.0.0/0            /* ns1/my-service1 */ tcp to:10.44.0.12:80
19       0     0 KUBE-MARK-MASQ  tcp  --  *      *      !10.44.0.0/16
      10.45.55.222         /* ns1/my-service1 cluster IP */ tcp dpt:80
20       0     0 KUBE-SVC-YNXEIGB6TEIVWVFA  tcp  --  *      *
0.0.0.0/0            10.45.55.222         /* ns1/my-service1 cluster IP
*/ tcp dpt:80
1        0     0 KUBE-SEP-ELHPCOKDLRTOJBKE  all  --  *      *
0.0.0.0/0            0.0.0.0/0            /* ns1/my-service1 */
```

`KUBE-SVC-YNXEIGB6TEIVWVFA` chain was created for the service `ns1/my-service1`.
On the other hand, the chain name is compared with the name created by https://github.com/submariner-io/submariner/blob/b7f429f2d2577243e23f5829ad746bfa62d13a46/pkg/globalnet/controllers/ipam/globalnet_ingress.go#L55 . However, `ns1/my-service1:tcp` will be converted to `U4TEEQ5E44SMEE7G`, not `YNXEIGB6TEIVWVFA`. And it seems that `ns1/my-service1tcp`(without ':') is converted to `YNXEIGB6TEIVWVFA`. (':' shouldn't be added if port name is empty?)

See https://play.golang.org/p/bLR6IMyiffV

In addition, service with port name doesn't reproduce this issue.
```
cat << EOF  | kubectl create -f -
apiVersion: v1
kind: Service
metadata:
   namespace: ns1
   name: my-service2
spec:
   ports:
   - port: 80
     protocol: TCP
     targetPort: 80
     name: http
   selector:
     run: my-pod1
   type: ClusterIP
EOF
```

**Environment**:
- Submariner version (use `subctl version`):  `subctl version: v0.8.0`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20",
GitVersion:"v1.20.0+k3s2",
GitCommit:"2ea6b16315c093d739c370f8f035ad3fa5eb5d11",
GitTreeState:"clean", BuildDate:"2020-12-22T02:10:12Z",
GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20",
GitVersion:"v1.20.0+k3s2",
GitCommit:"2ea6b16315c093d739c370f8f035ad3fa5eb5d11",
GitTreeState:"clean", BuildDate:"2020-12-22T02:10:12Z",
GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: KVM
- OS (e.g: `cat /etc/os-release`): 
```
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`): `Linux cl1 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: k3s 
```
k3s --version
k3s version v1.20.0+k3s2 (2ea6b163)
```
- Network plugin and version (if this is a network-related bug): flannel
- Others:

**Comment by mkimuram** [comment]
@sridhargaddam @mangelajo 

Please take a look at this issue.

**Comment by tpantelis** [comment]
kubeProxyClusterIpServiceChainName should check for empty/missing port name.

**Comment by mkimuram** [comment]
This looks like a compatibility issue on k8s side. There has been a breaking change. 

https://github.com/kubernetes/kubernetes/commit/341022f8d1361992f5c462d31cd0159a7c2e5a9f#diff-1ed5dacda632a4b7ba36564b1bd91174d5349f02e2085d75b871cf7134eb1483R52

**Comment by mkimuram** [comment]
If globalnet needs to support k8s before the patch (v1.19 < ?), chain name with ":" for a service without port name would also need to be checked.

**Comment by tpantelis** [comment]
Our code is built on kubernetes v1.17.0 although this is a runtime issue. We'd need to check both. @sridhargaddam  Ideally it would be best not to rely on checking for the kube proxy service chain.

**Comment by tpantelis** [comment]
> Our code is built on kubernetes v1.17.0 although this is a runtime issue. We'd need to check both. @sridhargaddam Ideally it would be best not to rely on checking for the kube proxy service chain.

Well we don't just check for existence - we also add ingress rules so I think we need to handle it.

**Comment by sridhargaddam** [comment]
Thanks for reporting the issue @mkimuram and for your detailed analysis. Great work.

**Comment by sridhargaddam** [comment]
> Our code is built on kubernetes v1.17.0 although this is a runtime issue. We'd need to check both. @sridhargaddam Ideally it would be best not to rely on checking for the kube proxy service chain.

Yes @tpantelis. We have roadmap plans to enhance Globalnet to annotate only exported services. Once that is done, we can avoid depending on the Kubeproxy chains and create our own chains. Doing such a change in the current design will not scale.

Thank you for pushing the fix.
