### ISSUE TITLE
Removal of strongSwan cable driver

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner#1094]
With 0.8 we announced deprecation of the strongSwan cable driver. Assuming all tests are green, we can go ahead and remove it with 0.9.

**Comment by skitt** [comment]
Shipyard: https://github.com/submariner-io/submariner/issues/1094.

**Comment by dfarrell07** [comment]
The linked PRs are all merged. ✅  Is this done @skitt?

**Comment by skitt** [comment]
> The linked PRs are all merged. white_check_mark Is this done @skitt?

It is, thanks @dfarrell07!
