### ISSUE TITLE
Capture the logs of all jobs in a single place

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1095]
**What would you like to be added**:

The ideal goal would be having something like http://logstash.openstack.org/ (ELK) stack.

It could be hosted by ourselves, or as a service (logz.io for example). 

**Why is this needed**:

It's hard to trace where or how an issue started happening, it could be a new
PR that has been merged, and it isn't always failing. It could be a problem
with a remote service (quay, docker, repositories...). Or something else.

Our current system doesn't allow any level of traceability beyond manually
looking at each job.

**Comment by sridhargaddam** [comment]
Its still valid

**Comment by tpantelis** [comment]
bump
