### ISSUE TITLE
Document the privilege requirements of the various images

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#1097]
We need to specify which images need to be privileged, and why, and which SAs need SCCs on OpenShift, and why. If any images are found to be currently more privileged than they need to be, other issues will be filed to make sure we reduce those privileges.

**Comment by nyechiel** [comment]
@skitt please let's also reduce privileges for those images who don't require full root, etc.

**Comment by skitt** [comment]
> @skitt please let's also reduce privileges for those images who don't require full root, etc.

Yes, “If any images are found to be currently more privileged than they need to be, other issues will be filed to make sure we reduce those privileges.” in the main description ;-).
