### ISSUE TITLE
no destroy-recreate objects in ovn under updates.

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1101]
**What would you like to be added**:
Avoid creating and destroying some ovn resources under the networkplugin-syncer as

**Why is this needed**:
that creates small downtime and can be handled with proper update support in go-ovn

Depends on #1100

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
We tried to triage this but don't have a lot of information, moving to prio:low for now.

**Comment by dfarrell07** [comment]
@astoycos has already fixed this in his OVN PR, he will close it.

**Comment by astoycos** [comment]
This should already be resolved by https://github.com/submariner-io/submariner/pull/1689 which converts the networkPluginSyncer to use libovsdb which will CreateORUpdate OVN objects rather than Delete and Recreate on every reconciliation loop.

**Comment by skitt** [comment]
Isn’t this still pending then, since #1689 isn’t merged yet? I’ll reopen the issue and indicate that #1689 fixes it, so that it gets closed when #1689 is merged.

**Comment by astoycos** [comment]
Ack sounds good to me, thanks @skitt!
