### ISSUE TITLE
Create videos for Red Hat Summit

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1104]
Submariner has a virtual booth in Community Central at the upcoming Red Hat Summit. We need to create video content.

@skitt has an outstanding, up-to-date, demo-heavy video that we might can reuse/re-edit: https://sk2.org/dc21sfinal.mp4

Might also want to update the Submariner in 60s video we created for last Summit, or create a slightly longer version: https://www.youtube.com/watch?v=pQgUWiGtKqM

**Comment by dfarrell07** [comment]
@nyechiel Per our discussion earlier today, it turns out we do have some additional information to provide for the Submariner booth (due for feedback 2/17, really due 2/24).

https://docs.google.com/document/d/1duh3zvw98kLWH-xWkT0B6Ku5KnuTLwKiOIvTYHLEtbk/edit#bookmark=id.6sjtx8gy7t6l

**Comment by nyechiel** [comment]
> @nyechiel Per our discussion earlier today, it turns out we do have some additional information to provide for the Submariner booth (due for feedback 2/17, really due 2/24).
> 
> https://docs.google.com/document/d/1duh3zvw98kLWH-xWkT0B6Ku5KnuTLwKiOIvTYHLEtbk/edit#bookmark=id.6sjtx8gy7t6l

Thanks @dfarrell07. Can you please draft something? I will be happy to review/help, just ping me if needed :)

**Comment by dfarrell07** [comment]
> > @nyechiel Per our discussion earlier today, it turns out we do have some additional information to provide for the Submariner booth (due for feedback 2/17, really due 2/24).
> > https://docs.google.com/document/d/1duh3zvw98kLWH-xWkT0B6Ku5KnuTLwKiOIvTYHLEtbk/edit#bookmark=id.6sjtx8gy7t6l
> 
> Thanks @dfarrell07. Can you please draft something? I will be happy to review/help, just ping me if needed :)

This is done, in addition to some other minor TODOs from the Summit team.

**Comment by dfarrell07** [comment]
We need to be sure the video embedded in the booth has a title slide as the first frame, so the preview shows as the Summit folks are requesting.

We can embed one video in the booth and link to 4 others. I think it would be fine to embed either the Submariner in 60s one we created last Summit or @skitt's newer, demo-focused DevConf talk. Either way, we can link to the one we don't embed on YouTube.

**Comment by dfarrell07** [comment]
@skitt I'm being told we need to submit the video by 16/03. As a simpler alternative, I could just cut the Devconf welcome message from the start of your current video.

**Comment by skitt** [comment]
> @skitt I'm being told we need to submit the video by 16/03. As a simpler alternative, I could just cut the Devconf welcome message from the start of your current video.

I’ve set aside time to take care of it tomorrow!

**Comment by skitt** [comment]
Here’s the video for RHS: https://sk2.org/rhs2021.mp4 (generic with Red Hat branding).

**Comment by skitt** [comment]
The audio is shifted, I’ll re-render it...

**Comment by skitt** [comment]
The final video is up! The URL is unchanged.

**Comment by dfarrell07** [comment]
NIce, thanks @skitt! I'm checking and submitting everything now.

**Comment by dfarrell07** [comment]
Okay I think everything they've asked for so far is submitted. :heavy_check_mark:

**Comment by dfarrell07** [comment]
I think this is done.
