### ISSUE TITLE
prep_for_subm attempts to use instance not available

### ISSUE THREAD

**Issue by cooktheryan** [submariner-io/submariner#1112]
Ran prep_for_subm.sh against a west1 cluster. The machinetype chosen was m5n.large which does not exist in that region

If the matter is security related, please disclose it privately to the
Submariner Owners: https://github.com/orgs/submariner-io/teams/submariner-core
-->

**What happened**: Improper machine type used

**What you expected to happen**: Machine type that is available in that region should be used

**How to reproduce it (as minimally and precisely as possible)**: Run prep_for_subm in west1

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nyechiel** [comment]
Thanks for testing Submariner, @cooktheryan!

The script deploys an m5n.large EC2 instance type by default for the Submariner gateway node. Alternatively, you can customize the AWS instance type by modifying the `GW_INSTANCE_TYPE` environment variable. This is documented here: https://submariner.io/getting-started/quickstart/openshift/aws/#prepare-aws-clusters-for-submariner

FYI, we are looking to replace the prep_for_subm script with something more robust we can maintain and support in 0.9 (https://github.com/submariner-io/submariner/issues/873), so there is no appetite to enhance this script.

**Comment by cooktheryan** [comment]
:+1: excited to follow the path from here
