### ISSUE TITLE
Use on.path GHA config to run fewer jobs

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1114]
**What would you like to be added**:

Use [`on.path` GitHub Action configuration](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) to run fewer jobs. For example, only trigger the Markdown linting/link check GHAs when `*.md` files are changed. Currently those jobs start only for the tests to detect no modified files and exit.

**Why is this needed**:

To run fewer jobs, saving resources.

**Comment by dfarrell07** [comment]
As @manosnoam pointed out, a related optimization would be not running most tests (except GitLint and DCO) when only the commit message is updated.

**Comment by manosnoam** [comment]
It should also be considered when modifying the Website pages or Readme files - unit-tests and e2e are not useful for Docs too.

**Comment by dfarrell07** [comment]
We don't run unnecessary tests in the website repo, but yes I agree overall.
