### ISSUE TITLE
Deploy multiple clustersets within the same "Submariner"

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner#1120]
**What would you like to be added**:

Within the same Submariner deployment, allow for multiple clustersets and ensure network connectivity is available within each clusterset but not across clustersets. 

**Why is this needed**:

Use clusterset as a boundary so that for e.g certain apps/workloads can only be placed within a clusterset.

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
With Submariner being deployed and managed through OCM (https://github.com/open-cluster-management/submariner-addon) it's already possible to spawn multiple clustersets (with one Broker namespace per clusterset running in the OCM Hub). @qiujian16 would you agree? Do you think that there is anything we should do better in this space?

**Comment by qiujian16** [comment]
yes I think so

**Comment by dfarrell07** [comment]
Can we close this? Given the other work going on outside of Submariner?

**Comment by nyechiel** [comment]
> Can we close this? Given the other work going on outside of Submariner?

The only reason to keep this open is to track a built-in solution in Submariner, for e.g via ``subctl``. I _think_ we can close this for now, and reopen if there is a concrete demand from users.
