### ISSUE TITLE
Add CI For un-encrypted tunnels

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner#1148]
**What would you like to be added**:
As a part of  https://github.com/submariner-io/submariner/issues/674 we are adding support for new Cable driver using vxlan . We need to have a dedicated CI job for this. Since there proposal to have a different kind of tunnels we could also have CI job in which one tunnel in un-encrypted.

**Why is this needed**:
To automate testing of  https://github.com/submariner-io/submariner/issues/674

- [x] Add `vxlan` option to shipyard Makefile.inc https://github.com/submariner-io/shipyard/pull/553
- [x] Add 'vxlan' to e2e test matrix https://github.com/submariner-io/submariner/pull/1171

**Comment by tpantelis** [comment]
bump

**Comment by Jaanki** [comment]
Add a temporary GH workflow (e2e-vxlan.yml) in Submariner to test vxlan only on PRs with `vxlan` label https://github.com/submariner-io/submariner/pull/1330

**Comment by Jaanki** [comment]
Add vxlan option to shipyard Makefile.inc https://github.com/submariner-io/shipyard/pull/553
