### ISSUE TITLE
vxlan cable driver metrics needs to be exported

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner#1150]
**What would you like to be added**:
vxlan cable driver metrics needs to be exported.
**Why is this needed**:
As a part of https://github.com/submariner-io/submariner/issues/674 a new vxlan cable driver will be supported. The metrics from these tunnel interfaces needs to be exported.

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
@maayanf24 do you have any update on this? @aswinsuryan told me that this one is a bit tricky because all cross-cluster connections share the same vxlan interface. Have you managed to find a solution for this?

**Comment by maayanf24** [comment]
@nyechiel I'm still looking into this

**Comment by maayanf24** [comment]
There are several metrics associate with each cable driver.
Two of them, `submariner_gateway_rx_bytes` and `submariner_gateway_tx_bytes`, are tricky to get data for.
The other metrics (`submariner_connections`, `submariner_connection_established_timestamp`, `submariner_connection_latency_seconds`) are already implemented by prev PR

**Comment by maayanf24** [comment]
The metrics `submariner_gateway_rx_bytes` and `submariner_gateway_tx_bytes` will not be supported for vxlan.
I'll add comment to the known issues
