### ISSUE TITLE
subctl should be able to create broker-info.subm even if subctl deploy-broker was NOT used

### ISSUE THREAD

**Issue by asanderson** [submariner-io/submariner#1152]
**What would you like to be added**:
subctl should be able to create the **_broker-info.subm_** file even if **_subctl deploy-broker_** was NOT used to deploy broker; e.g. if helm is used to deploy the broker.

**Why is this needed**:
Currently, subctl cannot be used afterwards, if helm is used to deploy the broker, since the **_broker-info.subm_** file is not generated.

**Comment by beergeek** [comment]
+1

**Comment by asanderson** [comment]
This issue is still valid.
