### ISSUE TITLE
Add sufficient details to Rancher Quick Start Guide for COMPLETE example

### ISSUE THREAD

**Issue by asanderson** [submariner-io/submariner#1153]
**What would you like to be added**:
Add sufficient details to Rancher Quick Start Guide that includes manual steps required to configure Rancher authorized cluster endpoints configuration including kubeconfig file port work-around. 

**Why is this needed**:
Currently, the Rancher Quick Start Guide does NOT provide sufficient detail to configure submariner to use Rancher-created clusters.  A COMPLETE working example with ALL necessary manual steps including the authorized cluster endpoints and manually adding the port number to the fqdn cluster URL in the kubeconfig file afterwards is necessary.  See Rancher issue [#28399](https://github.com/rancher/rancher/issues/28399).

**Comment by beergeek** [comment]
+1

**Comment by asanderson** [comment]
This issue is still valid.
