### ISSUE TITLE
Avoid dependency on the iptable chains programmed by IPtables kube-proxy driver.

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1166]
**What would you like to be added**:
Currently, Globalnet code uses the kube-proxy iptable chains for redirecting the incoming traffic destined to the globalIP of the Service. While this has its own advantages, the drawback is that when an exported service is deleted, until globalnet deletes the reference to the chain, kube-proxy will not be able to delete the corresponding chain.
This sometimes can cause kube-proxy to log an error and retry the operation after some specified interval.

Instead of depending on the kube-proxy IPTable chains for Services, this enhancement request is to modify Globalnet to create its own load-balancing chains for exported services.

**Comment by tpantelis** [comment]
bump

**Comment by mkimuram** [comment]
@sridhargaddam 

As you commented in the meeting, chain won't be recreated, if no [endpoint](https://github.com/kubernetes/kubernetes/blob/0a865b6e6e4a814c52313a2c24978843a756c400/pkg/proxy/iptables/proxier.go#L1048) exists. So, it won't be enough just to block deletion of service to avoid chain deletion until deleting globalnet's referencing chain.

**Comment by sridhargaddam** [comment]
> As you commented in the meeting, chain won't be recreated, if no [endpoint](https://github.com/kubernetes/kubernetes/blob/0a865b6e6e4a814c52313a2c24978843a756c400/pkg/proxy/iptables/proxier.go#L1048) exists. So, it won't be enough just to block deletion of service to avoid chain deletion until deleting globalnet's referencing chain.

Right @mkimuram. We will have to look for a better solution to this requirement. Thanks for looking into it in parallel.

**Comment by mkimuram** [comment]
To create submariner's own chain, there will be two approaches:
1) Copy the kube-proxy chain (Like [this](https://github.com/mkimuram/submariner/tree/issue/1166v1))
2) Implement the same logic as kube-proxy (Like [this](https://github.com/mkimuram/submariner/tree/issue/1166v2))

**Comment by mkimuram** [comment]
> 1. Copy the kube-proxy chain (Like this)
> 2. Implement the same logic as kube-proxy (Like this)

We are currently thinking about taking 2nd approach.

For current globalnet v2 code, instead of making a chain to jump to kube-proxy's chain [here](https://github.com/submariner-io/submariner/blob/devel/pkg/globalnet/controllers/global_ingressip_controller.go#L173), we will need to create our own chain and jump to it. And updating the chain should be done, on endpoint update or endpoint slice update, which means that we will need to add a new controller for it.

**Comment by sridhargaddam** [comment]
@mkimuram I pushed the PR which implements the feature, but I'm not able to add you as reviewer. Can you please review - https://github.com/submariner-io/submariner/pull/1643

**Comment by nyechiel** [comment]
@sridhargaddam I think this can be closed now? If there are any remaining work items (like docs), let's make sure they are being tracked separately.

**Comment by sridhargaddam** [comment]
Sure @nyechiel
