### ISSUE TITLE
Implement necessary e2e tests to validate various globalnet use-cases.

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1167]
**What would you like to be added**:
As part of [Globalnet Enhancement](https://github.com/submariner-io/enhancements/pull/22), GlobalnetEgressIP will enable users to create EgressIPs for inter-cluster communication. This request is to implement necessary e2e tests for validating various use-cases.

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by mkimuram** [comment]
https://github.com/submariner-io/submariner/pull/1455 is a part of this issue.

**Comment by nyechiel** [comment]
@sridhargaddam what else (if at all) needs to be done here?

**Comment by sridhargaddam** [comment]
@nyechiel GN 2.0 use-cases are validated in the current e2e. @mkimuram is adding some external network e2e tests, but they can be added as independent PRs and we can close this one.
