### ISSUE TITLE
Export tunnel interface errors as metrics

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#1198]
It would be useful to track errors, as shown by interface statistics under Linux.

**Comment by tpantelis** [comment]
bump

**Comment by sridhargaddam** [comment]
@skitt can you please elaborate the use-case a bit.

**Comment by dfarrell07** [comment]
Talking about this on the scrub today, we think tunnels don't provide this error count like other linux interfaces. @skitt will double check.

**Comment by skitt** [comment]
@sridhargaddam the idea is to ake this kind of information available as metrics:

```
5: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:65:fb:5e brd ff:ff:ff:ff:ff:ff
    RX:  bytes packets errors dropped  missed   mcast           
       8594897  135548      0      50       0      91 
    TX:  bytes packets errors dropped carrier collsns           
     384523445  212240      0       0       0       0 
```

This is tracked for some tunnel types at least, _e.g._

```
6: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1360 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 100
    link/none 
    RX:  bytes packets errors dropped  missed   mcast           
      22191579   45173      0       0       0       0 
    TX:  bytes packets errors dropped carrier collsns           
       5577365   50899      0       0       0       0 
```

but perhaps not for the types we use.

**Comment by dfarrell07** [comment]
Seems like we need someone (or a set of folks, on a test day) to check the various types of tunnels we use and see if these metrics are available.
