### ISSUE TITLE
Stale endpoint causing issues setting up tunnels

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1244]
**What happened**:
Imagine two clusters (perf2 and perf8) connected via Submariner. Now if there is a gateway migration on Perf8, the updated endpoint is properly synced on Broker and on Perf2 cluster. However, Perf2 cluster also has the old endpoint associated with Perf8. 

In such a situation when the gateway-pod on perf2 cluster is restarted (for some reason), it was seen that it initially processed the latest endpoint of Perf8 followed by the old endpoint. While processing the old endpoint, it believes that there is already an existing connection to Perf8 and [deletes it](https://github.com/submariner-io/submariner/blob/33d743aa3204c574863386310b2f1d6f2d974555/pkg/cableengine/cableengine.go#L142) and tries to connect to the old endpoint which never succeeds (as expected).

We should identify the reason why the stale endpoint of Perf8 is not deleted on perf2 cluster and also fix the sync issues for related scenarios.

**Environment**:
- Submariner version (use `subctl version`): 0.8.1
- Kubernetes version (use `kubectl version`): OCP 4.7.3
- Cloud provider or hardware configuration: OnPrem/VMWare
- Network plugin and version (if this is a network-related bug): OpenShift SDN

**Comment by sridhargaddam** [comment]
CC: @skitt @mangelajo

**Comment by tpantelis** [comment]
So when the **perf2** GW started, it first gets a **perf8** EP for _.147_:

`I0406 15:40:19.640342       1 tunnel.go:51] Tunnel controller processing added or updated submariner Endpoint object: &v1.Endpoint{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"perf8-submariner-cable-perf8-10-70-56-147", `

Then right after that, it gets _.173_:

`I0406 15:40:19.782204       1 tunnel.go:51] Tunnel controller processing added or updated submariner Endpoint object: &v1.Endpoint{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"perf8-submariner-cable-perf8-10-70-56-173", GenerateName:"", Namespace:"submariner-operator", SelfLink:"/apis/submariner.io/v1/namespaces/submariner-operator/endpoints/perf8-submariner-cable-perf8-10-70-56-173", `

which replaces _.147_:

```
I0406 15:40:19.783415       1 cableengine.go:142] Found a pre-existing cable "submariner-cable-perf8-10-70-56-147" that belongs to this cluster perf8
I0406 15:40:19.783424       1 libreswan.go:357] Deleting connection to {{perf8 submariner-cable-perf8-10-70-56-147 10.12.6.1 perf8-lc8kr-worker-nqvqd 
```

Then over a minute later it gets a remove for _.147_:

`I0406 15:41:41.781880       1 tunnel.go:71] Tunnel controller processing removed submariner Endpoint object: &v1.Endpoint{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"perf8-submariner-cable-perf8-10-70-56-147",`

Then shortly after an add for _.172:_

`I0406 15:41:41.815149       1 tunnel.go:51] Tunnel controller processing added or updated submariner Endpoint object: &v1.Endpoint{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"perf8-submariner-cable-perf8-10-70-56-172",`

which successfully replaces _.173_:

```
I0406 15:41:41.816960       1 cableengine.go:142] Found a pre-existing cable "submariner-cable-perf8-10-70-56-173" that belongs to this cluster perf8
I0406 15:41:41.816970       1 libreswan.go:357] Deleting connection to {{perf8 submariner-cable-perf8-10-70-56-173 10.12.16.1 perf8-lc8kr-worker-8j2qk [10.112.0.0/16 10.12.0.0/16] 10.70.56.173  false libreswan map[]}}
I0406 15:41:42.024071       1 cableengine.go:155] Successfully installed Endpoint cable "submariner-cable-perf8-10-70-56-172" with remote IP 10.70.56.172
```

It never gets a delete for  _.173_, which is puzzling, but shouldn't connectivity still be working with _.172_?

**Comment by sridhargaddam** [comment]
That's correct @tpantelis. The above log from where you made the observations is `--previous` log file for submariner-gateway pod on **Perf2**. I think the connection was successfully established with .172 at "15:41:42.024071" time. However, if we continue to analyze the same log file further, we can see that K8s API Server in the local cluster was down (at 19:41:44) for some reason and leadership could not be renewed, so submariner-gateway pod gets restarted.

```
W0407 19:41:44.370611       1 reflector.go:340] github.com/submariner-io/admiral/pkg/syncer/resource_syncer.go:189: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 10.6.16.1:58568->10.16.0.1:443: read: no route to host") has prevented the request from succeeding
W0407 19:41:44.370654       1 reflector.go:340] github.com/submariner-io/admiral/pkg/syncer/resource_syncer.go:189: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 10.6.16.1:58568->10.16.0.1:443: read: no route to host") has prevented the request from succeeding
E0407 19:41:44.370641       1 syncer.go:247] Error while trying to delete own Gateway "perf2-fqldq-worker-k47z8" : Delete "https://10.16.0.1:443/apis/submariner.io/v1/namespaces/submariner-operator/gateways/perf2-fqldq-worker-k47z8": read tcp 10.6.16.1:58568->10.16.0.1:443: read: no route to host
E0407 19:41:44.370675       1 syncer.go:98] Error getting existing Gateway: Get "https://10.16.0.1:443/apis/submariner.io/v1/namespaces/submariner-operator/gateways/perf2-fqldq-worker-k47z8": read tcp 10.6.16.1:58568->10.16.0.1:443: read: no route to host
F0407 19:41:44.370687       1 main.go:189] Leader election lost, shutting down
```

Now after submariner-gateway pod gets restarted, as you know, we have two endpoints that point to Perf8.
 
```
[sgaddam@localhost 8th]$ kubectl get endpoint -n submariner-operator # On Perf2 Cluster
NAME                                        AGE
perf2-submariner-cable-perf2-10-70-56-190   7d11h
perf8-submariner-cable-perf8-10-70-56-172   42h     --> Correct and latest endpoint
perf8-submariner-cable-perf8-10-70-56-173   35d     --> Stale/Old endpoint
[sgaddam@localhost 8th]$ # 
```

From the submariner-gateway pod logs (after it is restarted), we can see an add for _.172_ first

```
I0407 19:42:21.591061       1 tunnel.go:51] Tunnel controller processing added or updated submariner Endpoint object: &v1.Endpoint{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"perf8-submariner-cable-perf8-10-70-56-172", GenerateName:"", Namespace:"submariner-operator", SelfLink:"/apis/submariner.io/v1/namespaces/submariner-operator/endpoints/perf8-submariner-cable-perf8-10-70-56-172", UID:"7bb36e79-830c-4366-9669-30ad920094e2", ResourceVersion:"25213710", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63753320501, loc:(*time.Location)(0x2087320)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"submariner-io/clusterID":"perf8"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"submariner-engine", Operation:"Update", APIVersion:"submariner.io/v1", Time:(*v1.Time)(0xc0011fd2a0), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc0011fd2e0)}}}, Spec:v1.EndpointSpec{ClusterID:"perf8", CableName:"submariner-cable-perf8-10-70-56-172", HealthCheckIP:"10.12.14.1", Hostname:"perf8-lc8kr-worker-mq26q", Subnets:[]string{"10.112.0.0/16", "10.12.0.0/16"}, PrivateIP:"10.70.56.172", PublicIP:"", NATEnabled:false, Backend:"libreswan", BackendConfig:map[string]string(nil)}}
I0407 19:42:21.591121       1 cableengine.go:101] Installing Endpoint cable "submariner-cable-perf8-10-70-56-172"
```

After few seconds it gets add notification for _.173_
```
I0407 19:42:21.756263       1 tunnel.go:51] Tunnel controller processing added or updated submariner Endpoint object: &v1.Endpoint{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"perf8-submariner-cable-perf8-10-70-56-173", GenerateName:"", Namespace:"submariner-operator", SelfLink:"/apis/submariner.io/v1/namespaces/submariner-operator/endpoints/perf8-submariner-cable-perf8-10-70-56-173", UID:"655e46a0-ceb1-44b3-ae73-64f092c90ce1", ResourceVersion:"982000", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63750413613, loc:(*time.Location)(0x2087320)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"submariner-io/clusterID":"perf8"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"submariner-engine", Operation:"Update", APIVersion:"submariner.io/v1", Time:(*v1.Time)(0xc000f84de0), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc000f84e20)}}}, Spec:v1.EndpointSpec{ClusterID:"perf8", CableName:"submariner-cable-perf8-10-70-56-173", HealthCheckIP:"10.12.16.1", Hostname:"perf8-lc8kr-worker-8j2qk", Subnets:[]string{"10.112.0.0/16", "10.12.0.0/16"}, PrivateIP:"10.70.56.173", PublicIP:"", NATEnabled:false, Backend:"libreswan", BackendConfig:map[string]string(nil)}}
I0407 19:42:21.756339       1 cableengine.go:101] Installing Endpoint cable "submariner-cable-perf8-10-70-56-173"
```

So, it deletes the previous one (.172) and assumes that .173 is the latest/correct endpoint to Perf8. Since there is no submariner-gateway pod on .173 node of Perf8 cluster, the tunnels could not be established. 

```
I0407 19:42:21.757583       1 cableengine.go:142] Found a pre-existing cable "submariner-cable-perf8-10-70-56-172" that belongs to this cluster perf8
I0407 19:42:21.757595       1 libreswan.go:357] Deleting connection to {{perf8 submariner-cable-perf8-10-70-56-172 10.12.14.1 perf8-lc8kr-worker-mq26q [10.112.0.0/16 10.12.0.0/16] 10.70.56.172  false libreswan map[]}}
I0407 19:42:21.757611       1 libreswan.go:369] Whacking with [--delete --name submariner-cable-perf8-10-70-56-172-0-0]
```

So the issues are
1. Why there is no delete notification for .173 on submariner-gateway pod of Perf2 cluster when the endpoint was deleted on Broker?
2. In case there are multiple endpoints (which actually is a bug) to a remote cluster (like .172 and .173 to Perf8), how can we ensure that we process the correct endpoint irrespective of the order in which the notification is received when submariner-gateway pod gets restarted. 
3. As I mentioned on the slack channel, if I manually delete an endpoint from the local cluster, it's not getting synced from the Broker. So, we probably need a mechanism to keep the local endpoints and endpoints on the Broker cluster always in sync. I think this will fix 2 above in an indirect way.

**Comment by tpantelis** [comment]
> So the issues are
> 
> 1. Why there is no delete notification for .173 on submariner-gateway pod of Perf2 cluster when the endpoint was deleted on Broker?

I suspect the same reason that caused the pod to lose the leader election and shut down - it lost connection to the broker API server and never got the delete notification.

> 2. In case there are multiple endpoints (which actually is a bug) to a remote cluster (like .172 and .173 to Perf8), how can we ensure that we process the correct endpoint irrespective of the order in which the notification is received when submariner-gateway pod gets restarted.

I suppose we could inspect the creation time stamps and favor the latest. However the crux of the problem is that .173 should not exist. If a resource is deleted while the process is down or while it's lost connection to the server, on restart it will not learn of the deleted resource from the informer b/c that information is ephemeral - the informer only fetches and notifies of what currently exists on the server. This is kind of a hole with using informers. In our case, we can correct it by reconciling the local resources with the broker resources, ie delete any local resource that doesn't exist on the broker. I have an [issue](https://github.com/submariner-io/admiral/issues/85) for this. 

> 3. As I mentioned on the slack channel, if I manually delete an endpoint from the local cluster, it's not getting synced from the Broker. So, we probably need a mechanism to keep the local endpoints and endpoints on the Broker cluster always in sync. I think this will fix 2 above in an indirect way.

That scenario is an out-of-band local delete which could be easily handled via a resync period. However, for this issue, an endpoint was deleted on the broker and the notification was missed so adding a resync period wouldn't fix this issue as that just fetches the current data. You need a full reconciliation as described above. I believe this is only necessary on startup to handle missed delete notifications while the process was down. If the informer loses connection to the server and misses a delete notification, on reconnect, I believe it will reconcile its cache with the current data on the server and issue a delete notification. At least I would think it would handle this - needs to be verified.

**Comment by tpantelis** [comment]
So I verified the behavior when an informer reconnects to the server.  On reconnect, it re-lists the resources, re-establishes the watch and reconciles the cache with the current list received from the server. If a deletion event was missed during the disconnect period, it will detect that the cached resource is stale and issue a delete event with `DeletedFinalStateUnknown`.

**Comment by tpantelis** [comment]
@sridhargaddam Looking at the creation timestamps for EPs **.173**, **.147**, **.172**:

```
173:  time.Time{wall:0x0, ext:63750413613, loc:(*time.Location)(0x2087320)}   2021-03-04T00:13:33Z
147:  time.Time{wall:0x0, ext:63753018421, loc:(*time.Location)(0x2087320)}   
172:  time.Time{wall:0x0, ext:63753320501, loc:(*time.Location)(0x2087320)}   2021-04-06T15:41:41Z
```

**.173** is far older (over a month ago in Mar).  So it's been stale for quite some time. Given that, the Per2 log prior to restart makes sense: **.147** was the current EP on Perf8 and was replaced by **.172** around _I0406 15:41:41_.  The add for **.173** was extraneous and it shouldn't have replaced **.147**. This also explains why we don't see a delete event for **.173** in that log as the delete happened a while ago prior to the start of that Per2 pod instance. Unfortunately we don't have logs from that prior time period to determine exactly how **.173** became stale but I suspect the delete occurred while no Per2 gateway pod was running and thus the event was missed.

So I think checking the EP timestamps when deciding to replace makes sense, ie take the newer one.  That would protect against a stale EP.  Also the syncer needs to reconcile resources on startup to handle missed delete events.  I'll work on these this week.

**Comment by sridhargaddam** [comment]
> So I think checking the EP timestamps when deciding to replace makes sense, ie take the newer one. That would protect against a stale EP. Also the syncer needs to reconcile resources on startup to handle missed delete events. I'll work on these this week.

Yes, it makes sense @tpantelis. Thanks.
