### ISSUE TITLE
Move to fieldalignment linter from deprecated maligned linter

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1252]
**What would you like to be added**:

Move from the deprecated maligned linter to the new fieldalignment linter.

**Why is this needed**:

Upgrading to golangci-lint 1.39.0 in https://github.com/submariner-io/shipyard/pull/519:

> Deprecated linters:
> * maligned, replaced by fieldalignment

**Comment by dfarrell07** [comment]
This is also reported as a warning in Go linting:

> The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'."

**Comment by skitt** [comment]
The switch itself is implemented in #1306, however it shows that `fieldalignment` flags more issues than `maligned`: it checks struct size, and “pointer size”, _i.e._ how much of the struct needs to be scanned for GC. This is really a minor optimisation (see https://github.com/golang/go/issues/44877 for details) but it can’t be disabled.

Further, golangci-lint can use `maligned`’s suggestions, at least to present them to the user; `fieldalignment` is also capable of producing suggestions, but golangci-lint can’t use them yet (see https://github.com/golangci/golangci-lint/issues/1779). Until that happens, switching to `fieldalignment` seems counter-productive to me: it is liable to find issues in structs without being able to explain how to fix them, and it _does_ find lots of issues related to pointer coverage which are hard to fix.

**Comment by dfarrell07** [comment]
Okay, thanks for digging in and summarizing so clearly @skitt.

Can we add [golangci-lint ignores](https://github.com/submariner-io/submariner/blob/devel/.golangci.yml#L57) for this linter matching text "pointer size" (or similar) to turn `fieldalignment` more into a drop-in replacement for `maligned`?

> Further, golangci-lint can use maligned’s suggestions, at least to present them to the user; fieldalignment is also capable of producing suggestions, but golangci-lint can’t use them yet

I don't see either `fieldalignment` or `maligned` mentioned in the supported linters there, but I do think I remember `maligned`'s suggestions.

So maybe the plan could be something like:

1. Wait until `fieldalignment` and `maligned` have suggestion parity.
2. Use ignore rules for "pointer size" if possible, otherwise wait on ability to disable that check, and then phase in the struct scanning optimizations if we want later.

**Comment by skitt** [comment]
> Can we add [golangci-lint ignores](https://github.com/submariner-io/submariner/blob/devel/.golangci.yml#L57) for this linter matching text "pointer size" (or similar) to turn `fieldalignment` more into a drop-in replacement for `maligned`?

Ah yes, I’d forgotten we could do that! I’ve added the relevant configuration in the updated PR. If it passes everything here I’ll mark it as ready for review.
