### ISSUE TITLE
deploy success but failure in test, no communication between pods 

### ISSUE THREAD

**Issue by chris93111** [submariner-io/submariner#1258]
Hi i try to connect two cluster k3s ( one in my home 192.168 and other in aws 10.210)

deployment is success , the subctl show connected gateway but pods can't connect to another

if i try ping pod in node gateway is work

node is connected with wireguard site 2 site

k3s version v1.19.9+k3s1 (bead080d)

Showing information for cluster "default":
Showing Network details
    No network details discovered

Showing Endpoint details
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
home                          192.168.0.41                    libreswan           local           
aws                           10.210.34.100                   libreswan           remote          

Showing Connection details
GATEWAY                         CLUSTER                 REMOTE IP       CABLE DRIVER        SUBNETS                                 STATUS          
ip-10-210-34-100.eu-west-3.comp aws                     10.210.34.100   libreswan           10.145.0.0/16, 10.144.0.0/16            connected       

Showing Gateway details
NODE                            HA STATUS       SUMMARY                         
debian01                        active          All connections (1) are established

Showing version details
COMPONENT                       REPOSITORY                                            VERSION         
submariner                      quay.io/submariner                                    0.8.1           
submariner-operator             quay.io/submariner                                    0.8.1           
service-discovery               quay.io/submariner                                    0.8.1           

----------------
Showing Network details
    No network details discovered

Showing Endpoint details
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
aws                           10.210.34.100                   libreswan           local           
home                          192.168.0.41                    libreswan           remote          

Showing Connection details
GATEWAY                         CLUSTER                 REMOTE IP       CABLE DRIVER        SUBNETS                                 STATUS          
debian01                        home                    192.168.0.41    libreswan           10.43.0.0/16, 10.42.0.0/16              connected       

Showing Gateway details
NODE                            HA STATUS       SUMMARY                         
ip-10-210-34-100.eu-west-3.comp active          All connections (1) are established

Showing version details
COMPONENT                       REPOSITORY                                            VERSION         
submariner                      quay.io/submariner                                    0.8.1           
submariner-operator             quay.io/submariner                                    0.8.1           
service-discovery               quay.io/submariner                                    0.8.1        
----------------------------------------

test diag : 

Summarizing 8 Failures:

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/tcp/connectivity.go:61

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is not on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/tcp/connectivity.go:61

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/tcp/connectivity.go:61

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

Ran 23 of 34 Specs in 1549.909 seconds
FAIL! -- 15 Passed | 8 Failed | 0 Pending | 11 Skipped

**Comment by nyechiel** [comment]
Hi @chris93111 - thanks for trying Submariner and reporting this!

When you open a bug, can you please follow the Bug Report template? The issue lacks information on what environments you are using, what commands you issued exactly, and any logs that can assist us to figure our what's going on.
