### ISSUE TITLE
make e2e / ci section should be noted to be used only within KIND

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#126]
In Readme - make e2e section should be noted to be used only for KIND tests (local or CI), but not on AWS (or other clouds), as it will corrupt the AWS cluster.

**Comment by mangelajo** [comment]
I don't know what you mean, how can you use make e2e with AWS? :? :?

**Comment by manosnoam** [comment]
This is an old issue, before having the option to run e2e with subctl, not only inside KIND env.
Let's close it for now.
