### ISSUE TITLE
Gateway stuck in connecting and benchmark test fails

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/submariner#1274]

**Comment by pinikomarov** [comment]
This was hit by deploying on a personal laptop with a kind env on F33:

[r@r20 submariner-operator]$ ./bin/subctl validate all
[...]
 ✗ Validating connections in cluster "cluster1"
 ✗ Connection to cluster "cluster2" is in progress
[..]
 ✗ Validating connections in cluster "cluster2"
 ✗ Connection to cluster "cluster1" is in progress

*all other checks were ok

**Comment by pinikomarov** [comment]
*here we can see libreswan gateway agent stuck in connecting state:

r@r20 submariner-operator]$ ./bin/subctl show all

Showing information for cluster "cluster1":
Showing Network details
    Discovered network details:
        Network plugin:  weave-net
        Service CIDRs:   [100.1.0.0/16]
        Cluster CIDRs:   [10.1.0.0/16]


Showing Endpoint details
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
cluster1                      172.19.0.7      46.116.45.94    libreswan           local           
cluster2                      172.19.0.8      46.116.45.94    libreswan           remote          

Showing Connection details
GATEWAY          CLUSTER   REMOTE IP   NAT  CABLE DRIVER  SUBNETS                    STATUS      RTT avg.  
cluster2-worker  cluster2  172.19.0.8  no   libreswan     100.2.0.0/16, 10.2.0.0/16  connecting  0s        

Showing Gateway details
NODE                            HA STATUS       SUMMARY                         
cluster1-worker                 active          0 connections out of 1 are established

Showing version details
COMPONENT                       REPOSITORY                                            VERSION         
submariner                      localhost:5000                                        local           
submariner-operator             localhost:5000                                        local           
service-discovery               localhost:5000                                        local           

Showing information for cluster "cluster2":
Showing Network details
    Discovered network details:
        Network plugin:  weave-net
        Service CIDRs:   [100.2.0.0/16]
        Cluster CIDRs:   [10.2.0.0/16]


Showing Endpoint details
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
cluster2                      172.19.0.8      46.116.45.94    libreswan           local           
cluster1                      172.19.0.7      46.116.45.94    libreswan           remote          

Showing Connection details
GATEWAY          CLUSTER   REMOTE IP   NAT  CABLE DRIVER  SUBNETS                    STATUS      RTT avg.  
cluster1-worker  cluster1  172.19.0.7  no   libreswan     100.1.0.0/16, 10.1.0.0/16  connecting  0s        

Showing Gateway details
NODE                            HA STATUS       SUMMARY                         
cluster2-worker                 active          0 connections out of 1 are established

Showing version details
COMPONENT                       REPOSITORY                                            VERSION         
submariner                      localhost:5000                                        local           
submariner-operator             localhost:5000                                        local           
service-discovery               localhost:5000                                        local

**Comment by pinikomarov** [comment]
attaching subctl gather logs :


[submariner-20210420093104.zip](https://github.com/submariner-io/submariner/files/6342830/submariner-20210420093104.zip)

**Comment by nyechiel** [comment]
Hi @pinikomarov - thanks for reporting this. When you open a bug, can you please follow the Bug Report template? The issue lack information on what version of Submariner/`subctl` is used here, and what commands you issued exactly. The latter part is not available in any of the logs.

From the logs it looks like the IPsec tunnel is not coming up. The `subctl validate` output is accurate, and I wouldn't expect any `benchmark` to run.

**Comment by pinikomarov** [comment]
Thanks @nyechiel 
For some reason submariner versions is not working for me : 

[r@r20 submariner-operator]$ sudo ./bin/subctl show versions
[sudo] password for r: 
Error obtaining the Submariner resource: Get "http://localhost:8080/apis/submariner.io/v1alpha1/namespaces/submariner-operator/submariners/submariner": dial tcp [::1]:8080: connect: connection refused

subctl version: devel-10be09e-dev

So this is the latest git commit with which I ran the deployment:
[r@r20 submariner-operator]$ git show
commit 10be09ec1a8f8bde89c0b6106bbe10fa11cdcde5 (HEAD -> devel, origin/devel, origin/HEAD)
Date:   Fri Apr 16 17:46:48 2021 +0530
Support validate all command (#1256)

**Comment by pinikomarov** [comment]
I think we can close this , since this does not reproduce on a dedicated BM env : 
on seal15.qa.lab.tlv.redhat.com this all works ok, so i'm closing this issue.

test details below :


#versions : 
[root@f0e4c3a5820a submariner-operator]# subctl  version
subctl version: devel-98d505e
[root@f0e4c3a5820a submariner-operator]# git show
commit 98d505e10f05f1b7c5121ac5eee2e42849f88e70 (HEAD -> devel, tag: subctl-devel, origin/devel, origin/HEAD)
Author: Vishal Thapar <5137689+vthapar@users.noreply.github.com>
Date:   Thu Apr 22 17:49:46 2021 +0530

    Remove misleading OVN CNI not supported msg


#validations all check out :

[root@f0e4c3a5820a submariner-operator]# subctl validate  all
 ✓ Validating Submariner support for the Kubernetes version used in cluster "cluster1"
 ✓ The Kubernetes version meets Submariner's requirements

 ✓ Retrieving Submariner resource from "cluster1"

 ✓ Validating Submariner support for the CNI network plugin in cluster "cluster1"
 ✓ The detected CNI network plugin ("weave-net") is supported by Submariner.

 ✓ Validating connections in cluster "cluster1"
 ✓ All connections are established

 ✓ Validating submariner pods in "cluster1"
 ✓ All Submariner pods are up and running

 ✓ Non-Globalnet deployment detected, checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs

 ✓ Validating Submariner support for the kube-proxy mode used in cluster "cluster1"
 ✓ Cluster is not deployed with kube-proxy ipvs mode.

 ✓ Validating the firewall configuration to check if metrics port (8080) is allowed in cluster "cluster1"
 ✓ Prometheus metrics can be retrieved from gateway nodes.

 ✓ Validating the firewall configuration to check if VxLAN traffic is allowed in cluster "cluster1"
 ✓ The firewall configuration for vx-submariner is working fine.

Skipping tunnel firewall validation as it requires two kubeconfigs. Please run "subctl validate firewall tunnel" command manually.

 ✓ Validating Submariner support for the Kubernetes version used in cluster "cluster2"
 ✓ The Kubernetes version meets Submariner's requirements

 ✓ Retrieving Submariner resource from "cluster2"

 ✓ Validating Submariner support for the CNI network plugin in cluster "cluster2"
 ✓ The detected CNI network plugin ("weave-net") is supported by Submariner.

 ✓ Validating connections in cluster "cluster2"
 ✓ All connections are established

 ✓ Validating submariner pods in "cluster2"
 ✓ All Submariner pods are up and running

 ✓ Non-Globalnet deployment detected, checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs

 ✓ Validating Submariner support for the kube-proxy mode used in cluster "cluster2"
 ✓ Cluster is not deployed with kube-proxy ipvs mode.

 ✓ Validating the firewall configuration to check if metrics port (8080) is allowed in cluster "cluster2"
 ✓ Prometheus metrics can be retrieved from gateway nodes.

 ✓ Validating the firewall configuration to check if VxLAN traffic is allowed in cluster "cluster2"
 ✓ The firewall configuration for vx-submariner is working fine.


#overall status seems ok too...

[root@f0e4c3a5820a submariner-operator]# subctl show all

Showing information for cluster "cluster1":
Showing Network details
    Discovered network details:
        Network plugin:  weave-net
        Service CIDRs:   [100.1.0.0/16]
        Cluster CIDRs:   [10.1.0.0/16]


Showing Endpoint details
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE
cluster1                      172.18.0.8      82.81.161.50    libreswan           local
cluster2                      172.18.0.7      82.81.161.50    libreswan           remote

Showing Connection details
GATEWAY          CLUSTER   REMOTE IP   NAT  CABLE DRIVER  SUBNETS                    STATUS     RTT avg.
cluster2-worker  cluster2  172.18.0.7  no   libreswan     100.2.0.0/16, 10.2.0.0/16  connected  295.505µs

Showing Gateway details
NODE                            HA STATUS       SUMMARY
cluster1-worker                 active          All connections (1) are established

Showing version details
COMPONENT                       REPOSITORY                                            VERSION
submariner                      localhost:5000                                        local
submariner-operator             localhost:5000                                        local
service-discovery               localhost:5000                                        local

Showing information for cluster "cluster2":
Showing Network details
    Discovered network details:
        Network plugin:  weave-net
        Service CIDRs:   [100.2.0.0/16]
        Cluster CIDRs:   [10.2.0.0/16]


Showing Endpoint details
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE
cluster2                      172.18.0.7      82.81.161.50    libreswan           local
cluster1                      172.18.0.8      82.81.161.50    libreswan           remote

Showing Connection details
GATEWAY          CLUSTER   REMOTE IP   NAT  CABLE DRIVER  SUBNETS                    STATUS     RTT avg.
cluster1-worker  cluster1  172.18.0.8  no   libreswan     100.1.0.0/16, 10.1.0.0/16  connected  270.421µs

Showing Gateway details
NODE                            HA STATUS       SUMMARY
cluster2-worker                 active          All connections (1) are established

Showing version details
COMPONENT                       REPOSITORY                                            VERSION
submariner                      localhost:5000                                        local
submariner-operator             localhost:5000                                        local
