### ISSUE TITLE
e2e fails after GW failover when global net is enabled

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner#1277]
**What happened**:
e2e fails after GW failover when global net is enabled
Summarizing 2 Failures:

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.9.0-rc0/test/e2e/framework/network_pods.go:184

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.9.0-rc0/test/e2e/framework/network_pods.go:184

Ran 12 of 36 Specs in 686.229 seconds
FAIL! -- 10 Passed | 2 Failed | 0 Pending | 24 Skipped

**What you expected to happen**:
Tests should pass after a g/w failover.

**How to reproduce it (as minimally and precisely as possible)**:

In an HA setup, block the traffic using subnet acl to the active g/w subnet and wait for the passive to take over. Run e2e.

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):0.9.0rc0
- Kubernetes version (use `kubectl version`):  Openshift 4.6.25 ( Kubernetes Version: v1.19.0+a5a0987) 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dfarrell07** [comment]
FYI, I suspect this is the reason we're seeing pretty frequent (>50%) GN failures in the Flake Finder here but not in other repos. Here (the main repo) is the only place we run these failover tests, as I understand it.

https://github.com/submariner-io/submariner/runs/2434102253?check_suite_focus=true

**Comment by sridhargaddam** [comment]
@aswinsuryan the following PR in Shipyard hopefully will fix this issue - https://github.com/submariner-io/shipyard/pull/530

**Comment by aswinsuryan** [comment]
> @aswinsuryan the following PR in Shipyard hopefully will fix this issue - [submariner-io/shipyard#530](https://github.com/submariner-io/shipyard/pull/530)

Thanks, I will test this again after the patch is merged.

**Comment by nyechiel** [comment]
Closing for now. Let's reopen if this happen again.
