### ISSUE TITLE
ovn: the load balancers (ClusterIP) don't forward need-frag ICMPs down to pods.

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1279]
This was work-arounded in https://github.com/submariner-io/submariner/issues/1022, and the
workaround is still working, but it's performance sensitive, and does not work with UDP.

Items:
* [ ] Handle this with the ovn/ovn-kubernetes teams
* [ ] Remove the workaround

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tpantelis** [comment]
bump
