### ISSUE TITLE
Routeagent found error ,and the at this node not access cross cluster pod

### ISSUE THREAD

**Issue by buhe** [submariner-io/submariner#128]
hi ,

Routeagent found error ,and the at this node not access cross cluster pod , but another node can access 

```
E0818 12:41:46.281467       1 route.go:385] error while adding route {Ifindex: 2 Dst: 10.72.0.0/16 Src: <nil> Gw: 172.31.2.255 Flags: [] Table: 0}: network is unreachable
│ E0818 12:41:46.281521       1 route.go:385] error while adding route {Ifindex: 2 Dst: 10.73.0.0/16 Src: <nil> Gw: 172.31.2.255 Flags: [] Table: 0}: network is unreachable
```

thanks 

buhe

**Comment by buhe** [comment]
ssh error node , enter 
ip route add 10.72.0.0/16 table 220 via 172.31.0.1 dev eth0 src 10.62.1.0
return :
RTNETLINK answers: Network is unreachable

Reason is we use aws multi zone , node A at A zone , Node B at B zone , A can access B , A can't access B's Gateway (172.31.0.1)

**Comment by Oats87** [comment]
Yes, this is a current limitation of Submariner (hosts within a cluster need to be on the same L2)

**Comment by buhe** [comment]
thank your reply

**Comment by buhe** [comment]
@Oats87 
close this issue or keep opened ?
