### ISSUE TITLE
REQUEST: New committer rights request for mkolesnik

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner#1280]
### GitHub Username
mkolesnik

### Code you are requesting Committer rights for
submariner-website/Makefile
submariner-website/scripts/*
submariner-website/src/content/development/*

### Requirements
- [x] I have reviewed the contributor roles guidelines (https://submariner.io/community/contributor-roles/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have been actively contributing to Submariner for at least 3 months
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mangelajo 
- @skitt

### List of required reviews to Submariner project PRs
- At least 20 PRs to the relevant codebase that you reviewed: https://github.com/submariner-io/submariner-website/pulls?q=is%3Apr+involves%3Amkolesnik+-author%3Amkolesnik
- At least 5 PRs to the relevant codebase for which you were the primary reviewer

**Comment by mangelajo** [comment]
@tpantelis @skitt can you sponsor mike for those parts ^ :-)
