### ISSUE TITLE
Gateway pod crashes in KIND with wireguard setup

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner#1281]
**What happened**:
Gateway pod is in CrashLoopBackOff status

**What you expected to happen**:
Gateway pod to be running successfully running

**How to reproduce it (as minimally and precisely as possible)**:
Deploy KIND with wireguard as a cable driver
```
make clusters using=prometheus
export KUBECONFIG=$(find $(git rev-parse --show-toplevel)/output/kubeconfigs/ -type f -printf %p:)
subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1
subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2 broker-info.subm --clusterid cluster2 --natt=false --cable-driver=wireguard
subctl join --kubeconfig output/kubeconfigs/kind-config-cluster3 broker-info.subm --clusterid cluster3 --natt=false --cable-driver=wireguard
```

**Environment**:
- Submariner version (use `subctl version`): 0.9-rc0

subctl gather --modules=connectivity --type=logs returns the attached logs for gw pod.

subctl validate reports gw pod restarts but with a delay
[cluster2_submariner-gateway-z7bjl.log](https://github.com/submariner-io/submariner/files/6357773/cluster2_submariner-gateway-z7bjl.log)
[cluster3_submariner-gateway-x92th.log](https://github.com/submariner-io/submariner/files/6357774/cluster3_submariner-gateway-x92th.log)

**Comment by mangelajo** [comment]
@Jaanki did you have the wireguard modules enabled in your system?, this is working on CI, but we install & load the wireguard modules.
