### ISSUE TITLE
Run full E2E matrix only when "ready-for-testing"

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner#1289]
**What would you like to be added**:
E2E test jobs take a long time to complete while the CI has a limited capacity to run concurrent jobs (currently 20 jobs across the entire *@submariner-io* organization.

As such, it would be better to run a default `make e2e` smoke test on each PR sync, and the full test matrix that we have today only when a "ready-for-testing" label is added to the PR.

In order to prevent accidental merging of unlabelled PRs, we can have the PR labelled automatically once it has approval(s).
One possible way to do it is: https://github.com/marketplace/actions/label-approved-pull-requests

**Why is this needed**:
To have faster feedback from small jobs, while still maintaining coverage of E2E.

**Comment by nyechiel** [comment]
@mkolesnik @dfarrell07 can you please document this as part of the dev/PR guide?

**Comment by nyechiel** [comment]
> @mkolesnik @dfarrell07 can you please document this as part of the dev/PR guide?

https://github.com/submariner-io/submariner-website/pull/524
