### ISSUE TITLE
E2E gateway check fails if healthchecks are disabled

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1295]
**What happened**:
When installing with healthcheck disabled on the gateways E2E times out waiting for the gateways to report Latency.

**What you expected to happen**:

E2E discovers that we are not using health checks, and doesn't wait on that.

**How to reproduce it (as minimally and precisely as possible)**:
subctl join broker_info.subm **--health-check=false**

then run verify.

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): 0.9.0-devel
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sridhargaddam** [comment]
@aswinsuryan I think we can close this as its fixed as part of the following PRs
https://github.com/submariner-io/submariner/issues/1519
https://github.com/submariner-io/submariner/pull/1499

What do you say?

**Comment by aswinsuryan** [comment]
> @aswinsuryan I think we can close this as its fixed as part of the following PRs
> #1519
> #1499
> 
> What do you say?

Yes we can close this one. The changes linked should fix this.
