### ISSUE TITLE
Create 18 SubM logos versions for cncf/artwork

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1311]
**What would you like to be added**:

Send 18 versions of our log to the cncf/artwork project.

For example:

https://github.com/cncf/artwork/blob/master/examples/sandbox.md

**Why is this needed**:

CNCF Sandbox onboarding process (https://github.com/submariner-io/submariner/issues/1297).

**Comment by dfarrell07** [comment]
This is the basis we can work from: https://submariner.io/images/logo-submariner.svg

**Comment by dfarrell07** [comment]
![subm_logo](https://user-images.githubusercontent.com/880273/119397123-b3f80880-bca3-11eb-9375-9486e924a3a4.jpg)

Samping this logo I had on my laptop from back in the day, I get color code `2bdfc4` for our green and `3a4747` for the text color.

**Comment by dfarrell07** [comment]
The CNCF is going to help us with this: https://github.com/cncf/sandbox/issues/244

**Comment by nyechiel** [comment]
I think this is done now, see https://github.com/cncf/artwork/blob/master/examples/sandbox.md#submariner-logos
