### ISSUE TITLE
If ipify.org is down, submariner-gateway is unable to start

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1317]
**What happened**:

We use `ipify.org` API to discover the gateway public IP, but if this service is not responding the submariner-gateway will not start.

**What you expected to happen**:

I would expect additional services resolving the external IP if this one fails,
if all fail, use a fallback to the last known PublicIP

**Anything else we need to know?**:

We could provide 'publicip.submariner.io' also as a first resolver, this would allow us to collect anonymous statistics on submariner usage (may be country + version, or just version). But that's a separate topic.

**Environment**:
- Submariner version (use `subctl version`): 0.10.0 & devel

**Comment by mkolesnik** [comment]
Theres a few of these services - https://stackoverflow.com/questions/3097589/getting-my-public-ip-via-api

**Comment by mangelajo** [comment]
A list of fallback resolvers should be good.

**Comment by skitt** [comment]
In addition to this, `go-ipify`’s license isn’t approved by the CNCF; see #1326 for details.

**Comment by dfarrell07** [comment]
There's some related user feedback/question on Slack: https://kubernetes.slack.com/archives/C010RJV694M/p1620934901178400

**Comment by asanderson** [comment]
So, the implication is that currently ipify.com connectivity is another Submariner pre-requisite, no?
