### ISSUE TITLE
Alternatives for  class E range ips VXLAN 

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner#1321]
**What would you like to be added**:
The  class E range ips VXLAN. This could be risky in some setups where the IP is already used. An alternative is use to IPv6 address.

**Why is this needed**:
https://github.com/submariner-io/enhancements/pull/29#discussion_r629103168

**Comment by dfarrell07** [comment]
Talking with the Scrub, this seems like something we'd only want to prioritize if we run into an actual issue. Currently, it's all speculative. We can re-visit if there's actually a conflict.
