### ISSUE TITLE
Change Copyright Notices to CNCF-recommended format

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1322]
**What would you like to be added**:

Follow the CNCF's Copyright Notices recommendations. Namly, change all notices that mention specific companies to one of:

```
Copyright The XYZ Authors.
Copyright The XYZ Contributors.
Copyright Contributors to the XYZ project.
```

My inclination is "Contributors to the Submariner project", but I'm open to any of the options.

https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices

**Why is this needed**:

As part of the CNCF Sandbox onboarding process (https://github.com/submariner-io/submariner/issues/1297).

**Comment by tpantelis** [comment]
> 
> My inclination is "Contributors to the Submariner project", but I'm open to any of the options.
> 

👍

**Comment by dfarrell07** [comment]
I think we should also be more strict in the linting to require this copyright notice exactly, not accept any other.

**Comment by skitt** [comment]
And while we’re at it, add SPDX headers.

**Comment by skitt** [comment]
#1335 shows that we can’t use `.legal.json` to enforce this, we’d have to add something else (or use two enforcements with different configurations, one to check that the license statement is present _everywhere_, the other to check that the copyright statement is the one we expect on all non-generated files).

**Comment by dfarrell07** [comment]
This is done in the main repo via https://github.com/submariner-io/submariner/pull/1335 but we need to do it for the other Go-hosting repos.

**Comment by dfarrell07** [comment]
This is now done for all of our Go code. Thanks @skitt!
