### ISSUE TITLE
Make the PublicIP field of Endpoints compatible with DNS entries

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1369]
As part of: https://github.com/submariner-io/submariner/issues/1071

We can publish Load balancer DNS endpoints, or DNS endpoints. So if the DNS entry changes we don't need
to publish the endpoint again.

Also DNS entries can hold multiple IP endpoints.

**Comment by aswinsuryan** [comment]
Making DNS entry would make it unresolvable for some of the on-prem clusters. So a solution would be to check the public IP behind the load balance periodically and update it as discussed in https://github.com/submariner-io/submariner/issues/1410
