### ISSUE TITLE
Route agent interface setup should be moved to an initcontainer

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#1385]
Route agent pods need to be privileged so they can write to `/proc/sys`. If we handled that in an initcontainer we could reduce the route agent pod privileges.

**Comment by sridhargaddam** [comment]
@skitt do we need this?

**Comment by skitt** [comment]
> @skitt do we need this?

Yes, I think it would be useful and I believe I have a patch in progress somewhere for this.

**Comment by skitt** [comment]
The initial reasoning behind this issue was that the route agent needs to be able to write to `/proc/sys`, and that moving that to an init container would allow the privileges for the main container to be reduced. However the agent also needs to be able to set tunnels up, so this wouldn’t be sufficient to reduce privileges.
