### ISSUE TITLE
Create a common library for route-agent vxlan driver and vxlan cable driver

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner#1393]
**What would you like to be added**:
Create a common library for routeagent vxlan driver and vxlan cable driver.
**Why is this needed**:

**Comment by sridhargaddam** [comment]
This is more like a code refactoring and is good to have if new cable drivers (like IPIP) require this driver.

**Comment by astoycos** [comment]
Sorry never got to this either :(
