### ISSUE TITLE
LoadBalancer support for AWS NLB doesn't sync properly

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1410]
**What happened**:

The load balancer we create or the gateway doesn't sync properly to AWS:

```
  Warning  SyncLoadBalancerFailed  43s                 service-controller  Error syncing load balancer: failed to ensure load balancer: error creating load balancer target group: "DuplicateTargetGroupName: A target group with the same name 'k8s-submarin-submarin-081853df64' exists, but with different settings\n\tstatus code: 400, request id: 564d9c37-e939-46e5-9399-c774281f70a5"
  Warning  SyncLoadBalancerFailed  43s                 service-controller  Error syncing load balancer: failed to ensure load balancer: error adding tags for targetGroup arn:aws:elasticloadbalancing:us-east-2:269733383066:targetgroup/k8s-submarin-submarin-4aef34b009/84e95f12ba7d44e5 due to "TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:us-east-2:269733383066:targetgroup/k8s-submarin-submarin-4aef34b009/84e95f12ba7d44e5' not found\n\tstatus code: 400, request id: e6bf0782-22bc-42fc-a74c-95d867a573a5"
  Warning  SyncLoadBalancerFailed  34s                 service-controller  Error syncing load balancer: failed to ensure load balancer: error adding tags for targetGroup arn:aws:elasticloadbalancing:us-east-2:269733383066:targetgroup/k8s-submarin-submarin-55367631ea/4bb4b59590445989 due to "TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:us-east-2:269733383066:targetgroup/k8s-submarin-submarin-55367631ea/4bb4b59590445989' not found\n\tstatus code: 400, request id: 1556f319-6012-4291-9b6c-7a5c58b893c6"
```
I'm working on a reproducer here https://github.com/mangelajo/k8s-udp-lb-test/blob/main/reproducer.yaml still not ready

One of the issues being found is that most of the time the 2nd port (NATT discovery port) won't work or will take a long time to work. I'm thinking of a workaround for this.

**Comment by sridhargaddam** [comment]
Is this a problem with AWS NLB itself or the controller wrongly configuring the AWS NLB when a Service of type Loadbalancer is created?

**Comment by mangelajo** [comment]
> Is this a problem with AWS NLB itself or the controller wrongly configuring the AWS NLB when a Service of type Loadbalancer is created?

I haven't fully identified what's the underlying problem. I suspect it has to do with https://github.com/submariner-io/submariner/pull/1423 too... if the Endpoint comes and goes (pod going down and up while waiting for the loadbalancer to be ready) we may end up hitting the rate-limiting of the AWS API. I've seen errors of that type in the logs.

**Comment by aswinsuryan** [comment]
The public IP associated with a domain name of a LoadBalancer in AWS seems to be changing and the submariner fails to update the public IP field in the endpoint.

To fix this we need to have a periodic task which checks if the public IP is still valid and update it in the endpoint in case of any changes.

**Comment by nyechiel** [comment]
@sridhargaddam is this one still relevant?

**Comment by maayanf24** [comment]
this is already done
