### ISSUE TITLE
Test NAT combinations with VXLAN Cable driver

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner#1426]
The VXLAN cable driver may not work with all possible NAT Combinations.
 This bug is to track the results for each of them.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g `uname -a`):
- Install tools:
- Others:

**Comment by sridhargaddam** [comment]
This issue is still relevant but low on priority.

**Comment by nyechiel** [comment]
We haven't seen major issues on this space. Let's re-open if there is a concrete bug/user feedback.
