### ISSUE TITLE
Suggestion for Architecture diagram

### ISSUE THREAD

**Issue by alexellis** [submariner-io/submariner#143]
Hi :wave:

Your project looks very cool and it reminds me a bit of [inlets.dev](https://inlets.dev) which also bridges networks, but in a bit more of a rudimentary way. 

Given that the primary example in the repo uses 3 clusters (east, west and broker), and the diagram shows two clusters I found this a bit misleading.

Would you consider updating the image or putting together a new one to match the example?

https://raw.githubusercontent.com/rancher/submariner/master/docs/img/architecture.png

**Comment by Oats87** [comment]
Hi Alex,

Yeah, we're going to be updating the architecture diagram as we make a push to release a new version of Submariner, hopefully this will help to illustrate the way things work.

I've been toying with the idea of using https://github.com/rancher/remotedialer and tunneling the the traffic through the broker cluster which would put it in the data path, but that's down the line and probably not to smart to do in the end.

**Comment by alexellis** [comment]
@Oats87 since this issue got closed out, I wondered if you'd updated the diagram already? Thanks, Alex

**Comment by dfarrell07** [comment]
Hello @alexellis, thanks for following up! The CI was made to support two clusters via https://github.com/submariner-io/shipyard/pull/169, and we are moving jobs to use only two clusters (https://github.com/submariner-io/submariner-operator/pull/409).
