### ISSUE TITLE
subclt should support kube context

### ISSUE THREAD

**Issue by raffaelespazzoli** [submariner-io/submariner#1447]
**What would you like to be added**:

I'd like the `subctl` cli tool to support the concept of kubernetes context besides the concept of standalone kubeconfig file as it already does.
Some `subctl` sub-commands used to do it (like `show`), but it looks like this has been removed.

**Why is this needed**:

In many situation people login to all the clusters at the same time creating different context with in default kubeconfig. This way of working is not supported by `subctl`

**Comment by maayanf24** [comment]
@raffaelespazzoli Can you specify the `subctl` version you're using?
And also which `subctl` commands you find not supporting kubecontext

**Comment by raffaelespazzoli** [comment]
I was working with subct version 0.8.1 and devel
| sub command   |   kubecontext supported    0.8.1    |       devel   |
|----                      |  -------------                                      |        ----      |
| show                 |                                           yes       |       no        |
| benchmark        |                                            no       |        no       |

**Comment by skitt** [comment]
This is tracked as https://github.com/submariner-io/submariner-operator/issues/1326 for `benchmark`.

**Comment by nyechiel** [comment]
Addressed by https://github.com/submariner-io/submariner-operator/pull/1480
