### ISSUE TITLE
iptables is not present in GKE nodes

### ISSUE THREAD

**Issue by cyriltovena** [submariner-io/submariner#146]
Hello,

Even after mounting host / to the pod, /usr/sbin/iptables is not available on GKE nodes.

```
main.go:87] Error running route controller: createIPTableChains returned error. Unable to create SUBMARINER-POSTROUTING chain in iptables: running [/usr/sbin/iptables -t nat -S]: exit status 127: chroot: failed to run command '/usr/sbin/iptables': No such file or directory
```

For now I've moved the agent Dockerfile to alpine.

Not sure if you want to address this.

Thank you

**Comment by Oats87** [comment]
Are you using the published version of Submariner or are you using what is based off of master? We are in the process of making some changes in the way we handle `iptables` on the nodes

/cc @sridhargaddam

**Comment by sridhargaddam** [comment]
Is iptables itself missing (i.e., not installed) on the host or its installed but is present on some other path (i.e., something other than /usr/sbin/iptables)?

**Comment by cyriltovena** [comment]
No I could no find it anywhere else. I'm based off master I wanted to try the VXLAN PR. Which doesn't seems to work on GKE.

**Comment by mangelajo** [comment]
Are you using the updated helm charts that mount /host to the host to access the worker node iptables binaries?

 helm repo add submariner-latest https://submariner-io.github.io/submariner-charts/chart

I guess that we need to document that ^

If after that you're still finding the issue, I guess one option would be... installing iptables on the image, and use the "host" iptables only if it exists, otherwise use the image iptables.

**Comment by mangelajo** [comment]
@cyriltovena thanks for giving it a try!!! :)

**Comment by mangelajo** [comment]
@cyriltovena what's your timezone? could we e-meet in some slack/IRC and try to arrange a debug session if you're able to deploy it live on GKE?

We're working to cut a release ASAP, but it'd be great if we get compatibility with GKE, please feel free to ping me on majopela@redhat.com or kubernetes/rancher slack (mangelajo)

**Comment by cyriltovena** [comment]
Exactly no iptable on GKE, nodes are on a one IP subnet.

I don’t think we can sort this out quickly but yes I’ll reach out to you on slack.

**Comment by cyriltovena** [comment]
@Oats87 I did update your submariner docker image to include an iptables. The result is the same you can't add a route when the destination is not part of you local network.

In GKE nodes are in a single IP space network. using their own IP as subnet mask.

**Comment by sridhargaddam** [comment]
Thanks for giving it a try and sharing your observations @cyriltovena :+1: 

Recently we fixed a similar issue on AWS where programming the routing rules gives a "network unreachable" error. This is fixed via the following PR - https://github.com/submariner-io/submariner/commit/12cb4dc62f8808f1b875f97c2fd365486782ce71

Along with this, you will also require the following fix - https://github.com/submariner-io/submariner/commit/b58259b4f542bdf1ed9882467df4a3d9d6e39cc1

Can you please check if you have the above two fixes in your build for the "route issue"?

On a related note, @mangelajo fixed the issue to use iptables from the Docker image if the iptables utility is not available on the Host - https://github.com/submariner-io/submariner/commit/1521b9799011238d2e568f4125d8aa6dbb46ae3e

**Comment by mangelajo** [comment]
This has been fixed, and I have tested it works now :) Just remember to open your firewall ports to 4500 / 500 UDP on your gateway nodes.
