### ISSUE TITLE
Support metrics in Globalnet 2.0

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1471]
**What would you like to be added**:
In Globalnet 1.0, we used to have the following metrics. This issue is to support metrics with Globalnet 2.0 code introducing new metrics as necessary.

```
submariner_global_IP_availability | cidr | Count of available global IPs per CIDR
submariner_global_IP_allocated   | cidr | Count of global IPs allocated for Pods/Services per CIDR
```

**Comment by nyechiel** [comment]
@sridhargaddam I assume that this one needs docs to be updated? https://submariner.io/operations/monitoring/

**Comment by sridhargaddam** [comment]
@nyechiel the two metrics that @maayanf24 added are existing metrics which we used to support earlier with GN 1.0 implementation and I see that our website already has the associated documentation - https://submariner.io/operations/monitoring/#globalnet

@maayanf24 will be looking at new metrics which are only applicable for GN 2.0 implementation and once that is implemented, we can update the documentation. Thanks for reminding us.

**Comment by maayanf24** [comment]
@sridhargaddam - more metrics that can be added:
submariner_allocated_global_egress_ip
submariner_allocated_cluster_global_egress_ip
submariner_allocated_global_ingress_ip

**Comment by sridhargaddam** [comment]
> @sridhargaddam - more metrics that can be added: submariner_allocated_global_egress_ip submariner_allocated_cluster_global_egress_ip submariner_allocated_global_ingress_ip

Looks fine @maayanf24. Within global_egress_ip category, if required, we can go even further and capture global_egress_ips at namespace and pod levels, but i think its okay if we group them into submariner_allocated_global_egress_ip

Thanks for looking into it.

**Comment by nyechiel** [comment]
@maayanf24 @sridhargaddam anything else planned for 0.12 here or can we close this issue?

**Comment by maayanf24** [comment]
> @maayanf24 @sridhargaddam anything else planned for 0.12 here or can we close this issue?

This PR is in progressL https://github.com/submariner-io/submariner/pull/1687#pullrequestreview-885888241
