### ISSUE TITLE
e2e is failing with VXLAN cable driver in OpenShift

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner#1486]
**What happened**:

[dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is on a gateway and the remote pod is not on a gateway 
  should have sent the expected data from the pod to the other pod
  github.com/submariner-io/submariner@v0.10.0-rc0/test/e2e/dataplane/tcp_pod_connectivity.go:32
STEP: Creating namespace objects with basename "dataplane-conn-nd"
STEP: Generated namespace "e2e-tests-dataplane-conn-nd-h2578" in cluster "asuryana-pre-release-2" to execute the tests in
STEP: Creating namespace "e2e-tests-dataplane-conn-nd-h2578" in cluster "asuryana-pre-release-1"
STEP: Creating a listener pod in cluster "asuryana-pre-release-1", which will wait for a handshake over TCP
Jul 15 17:16:37.334: INFO: Will send traffic to IP: 10.150.0.52
STEP: Creating a connector pod in cluster "asuryana-pre-release-2", which will attempt the specific UUID handshake over TCP
STEP: Waiting for the connector pod "tcp-check-podz88bn" on node "" to exit, returning what connector sent
Jul 15 17:19:43.375: INFO: Pod "tcp-check-podz88bn" output:
nc: 10.150.0.52 (10.150.0.52:1234): Operation timed out
nc: 10.150.0.52 (10.150.0.52:1234): Operation timed out

STEP: Waiting for the listener pod "tcp-check-listenersqgmk" on node "ip-10-0-163-182.us-east-2.compute.internal" to exit, returning what listener sent
Jul 15 17:19:44.421: INFO: Pod "tcp-check-listenersqgmk" output:
listening on 0.0.0.0:1234 ...
nc: timeout

Jul 15 17:19:44.421: INFO: Connector pod has IP: 10.0.26.195
STEP: Deleting namespace "e2e-tests-dataplane-conn-nd-h2578" on cluster "asuryana-pre-release-2"
STEP: Deleting namespace "e2e-tests-dataplane-conn-nd-h2578" on cluster "asuryana-pre-release-1"

• Failure [194.846 seconds]
[dataplane] Basic TCP connectivity tests across clusters without discovery
github.com/submariner-io/submariner@v0.10.0-rc0/test/e2e/dataplane/tcp_pod_connectivity.go:26
  when a pod with HostNetworking connects via TCP to a remote pod
  github.com/submariner-io/submariner@v0.10.0-rc0/test/e2e/dataplane/tcp_pod_connectivity.go:95
    when the pod is on a gateway and the remote pod is not on a gateway
    github.com/submariner-io/submariner@v0.10.0-rc0/test/e2e/dataplane/tcp_pod_connectivity.go:105
      should have sent the expected data from the pod to the other pod [It]
      github.com/submariner-io/submariner@v0.10.0-rc0/test/e2e/dataplane/tcp_pod_connectivity.go:32

      Expected
          <int32>: 1
      to equal
          <int32>: 0

      github.com/submariner-io/shipyard@v0.10.0-rc0/test/e2e/framework/network_pods.go:185

**What you expected to happen**:
All tests should pass, but one failed.
**How to reproduce it (as minimally and precisely as possible)**:
Run e2e in a AWS VXLAN setup.
**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): v0.10.0-rc0
- Kubernetes version (use `kubectl version`): 1.21
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g `uname -a`):
- Install tools:
- Others:

**Comment by nyechiel** [comment]
Update: according to @aswinsuryan, the same issue is seen with both 4.8 and 4.7 - so more likely related to all OpenShiftSDN-based clusters
