### ISSUE TITLE
Benchmark throughput with various cable drivers

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1509]
**What would you like to be added**:
Perform some benchmark tests with various cable drivers on the same platform and capture the observations. In this process, the CPU/Memory usage on the Gateway node should also be monitored.

Interested cable drivers:
1. Libreswan
2. Wireguard
3. VxLAN

**Comment by mangelajo** [comment]
Comparing IPSEC/libreswan to wireguard, we have detected issues with both which will need more investigation, @sridhargaddam has more details

1) ipsec with AES/GCM is limited to one CPU core per remote SA (~ connection)
2) wireguard uses x2.1 CPU for driving sightly less bandwidth under the same architecture (Broadwell Server, model 79)

While ipsec was performing around 1Gbps (n1-standard-8 on GCP), wireguard was performing around 0.8Gbps on the same type of machine.


We should test again with newer architectures (>skylake) which have proven to work better with IPSEC and AES/GCM at least
