### ISSUE TITLE
Only one CPU seems to be used for encryption with Libreswan Cabledriver

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1510]
**What would you like to be added**:
While running some benchmark tests with Libreswan Cable driver on Submariner release-0.8, it was seen that even though the Gateway nodes have 4 CPUs, only one of the CPUs seems to be used for encryption, and it maxed out while the other CPUs are nearly idle. Naturally, this is causing a drop in the throughput even though the network supports higher bandwidth.

```
Mem: 4209248K used, 11168576K free, 45396K shrd, 1080K buff, 2880280K cached
CPU0:   0% usr   0% sys   0% nic   0% idle   0% io   1% irq  98% sirq  <-- CPU 100% used.
CPU1:   2% usr   4% sys   0% nic  90% idle   0% io   0% irq   1% sirq
CPU2:   3% usr   5% sys   0% nic  90% idle   0% io   0% irq   0% sirq
CPU3:   2% usr   4% sys   0% nic  91% idle   0% io   0% irq   0% sirq
Load average: 0.34 0.16 0.11 4/562 9
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    1     0 root     S     2576   0%   0   0% /bin/bash
    9     1 root     R     1600   0%   3   0% top
```

For the above tests, the client and server pods were scheduled on the Gateway nodes.

Analyze if there is any possibility to optimize the platform so that other CPUs can be used and throughput can be improved.
Note: Without encryption (aka IPsec tunnels) iperf3 seems to properly utilize the CPUs, so the issue seems to be with libreswan process not able to use all the available CPUs.

**Comment by skitt** [comment]
The fact that this appears as 98% sirq is surprising, but I think that encryption overhead would be kernel-related, not involving Libreswan, so this could be a kernel configuration issue.

**Comment by dfarrell07** [comment]
Some folks with Axon are looking at this, it will need to be fixed in the kernel.

**Comment by kot-begemot-uk** [comment]
This is expected and unsolvable as long encryption uses tunnel mode and there is no offload.
The hashing of flows for IPSEC is usually done by SRC+DST or SRC+DST+SPI. These are identical for a tunnel. If there is no crypto offload in the adapter (cloud, low end cards, etc), this puts all processing of traffic for one link onto the same CPU every time. This results in the same softirq thread handling crypto as well as everything after that. This thread almost immediately shoots up to 100% and limits the throughput for the link.
The solution here is to either use supported crypto offloads (requires changes to the cable data model) and/or if that is not sufficient or not applicable (f.e. on cloud) - to use different VPN technology which allows load balancing across multiple tunnels.

**Comment by dfarrell07** [comment]
I think there isn't much we can do about the Libreswan implementation, and we are tracking the work-around to do a transport-mode tunnel for GRE-encapsulated traffic here: https://github.com/submariner-io/enhancements/pull/103. This would help with scale and observability. So https://github.com/submariner-io/submariner/issues/1669 tracks what we want to work on here.
