### ISSUE TITLE
Clusters with IPv6 for cluster/service CIDR propagate the endpoints correctly, but libreswan can't make the connections

### ISSUE THREAD

**Issue by oguzdag** [submariner-io/submariner#1546]
**What happened**:

Installed submariner with '--load-balancer' option onto 2 kubernetes cluster running on AWS using kubespray, but i don't see a connection on gateway, i can see load balancer up and running, it accepts connection from ports 4500 and 4490

**What you expected to happen**:

Gateway to have connection on it

**How to reproduce it (as minimally and precisely as possible)**:

deploy kubernetes cluster using kubespray onto AWS, and subctl join using load-balancer option

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
```
Cluster "cluster1"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.20.7" is supported

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("calico") is supported
 ✓ Calico CNI detected, checking if the Submariner IPPool pre-requisites are configured.

 ✗ Checking gateway connections
 ✗ There are no active connections on gateway "xxxxxxxxx"

 ✓ Checking Submariner pods
 ✓ All Submariner pods are up and running

 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs

 ✓ Checking Submariner support for the kube-proxy mode
 ✓ The kube-proxy mode is supported
```

```
subctl show connections                                            
Cluster "cluster1"
 ✗ Showing Connections
 ✗ No connections found
```
- Gather information (use `subctl gather`): Attaching the gather logs for cluster1 and cluster2
- Cloud provider or hardware configuration: AWS
- Install tools: subctl
- Others:

[cluster1.zip](https://github.com/submariner-io/submariner/files/7114869/cluster1.zip)
[cluster2.zip](https://github.com/submariner-io/submariner/files/7114871/cluster2.zip)

**Comment by mangelajo** [comment]
From the operator:

```
I0905 22:52:44.641752       1 network.go:56] controller_submariner "msg"="Discovered K8s network details"  "clusterCIDRs"=["10.234.64.0/18,fd85:ee78:d8a6:8607::2:0000/112"] "plugin"="calico" "serviceCIDRs"=["10.234.0.0/18,fd85:ee78:d8a6:8607::2000/116"]
I0905 22:52:44.641772       1 submariner_networkdiscovery.go:77] controller_submariner "msg"="Using detected CIDR"  "CIDR"="10.234.64.0/18,fd85:ee78:d8a6:8607::2:0000/112" "type"="Cluster"
I0905 22:52:44.641789       1 submariner_networkdiscovery.go:77] controller_submariner "msg"="Using detected CIDR"  "CIDR"="10.234.0.0/18,fd85:ee78:d8a6:8607::2000/116" "type"="Service"
```

gateway with libreswan
```
whack error: "submariner-cable-aws-dev03-10-129-10-49-0-1" IPv4 address may not contain `:' "fd85:ee78:d8a6:8607::3000/116"
W0905 22:56:50.560508       1 libreswan.go:277] error exit status 33 whacking with args: [--psk --encrypt --forceencaps --name submariner-cable-aws-dev03-10-129-10-49-0-1 --id @10.128.16.254-0-1 --host 10.128.16.254 --client 10.234.0.0/18 --to --id @10.129.10.49-1-0 --host 18.132.173.156 --client fd85:ee78:d8a6:8607::3000/116 --ikeport 4500]
whack error: "submariner-cable-aws-dev03-10-129-10-49-0-1" IPv4 address may not contain `:' "fd85:ee78:d8a6:8607::3000/116"
```

**Comment by weizhoublue** [comment]
On my dual-stack cluster , I encounter  similar  ipv6 issue , 
does  submariner support ipv6 ?

on gateway pod
> I0915 09:17:24.143445       1 libreswan.go:370] Executing whack with args: [--psk --encrypt --name submariner-cable-cluster1-172-110-185-45-0-1 --id 172.111.185.50 --host 172.111.185.50 --client 172.51.0.0/16 --ikeport 4500 --to --id 172.110.185.45 --host 172.110.185.45 --client fc02::/108 --ikeport 4500]
> whack error: "submariner-cable-cluster1-172-110-185-45-0-1" IPv4 address may not contain `:' "fc02::/108

on router agent pod

> E0915 09:49:37.265455       1 endpoint_created.go:40] Error handling created endpoint: LocalEndpointCreated failed: "MTU handler" returned error: error adding entry "fc06::/108" to set "SUBMARINER-LOCALCIDRS": exit status 1 (ipset v7.6: Syntax error: '108' is out of range 0-32

**Comment by sridhargaddam** [comment]
> On my dual-stack cluster , I encounter similar ipv6 issue ,
> does submariner support ipv6 ?

Currently, Submariner does not support IPv6. It is on the roadmap, but not on the priority list of items.

**Comment by unixfox** [comment]
bump

**Comment by sridhargaddam** [comment]
This is still relevant, but its on roadmap.

**Comment by dfarrell07** [comment]
We're planning on working on IPv6 this release, tracked by https://github.com/submariner-io/submariner/issues/1739.

**Comment by sridhargaddam** [comment]
This is now fixed as part of https://github.com/submariner-io/submariner/issues/1739
