### ISSUE TITLE
NodeLocal DNS breaks clusterset.local DNS resolution

### ISSUE THREAD

**Issue by hudec** [submariner-io/submariner#1549]
**What would you like to be added**:
Dynamic config init change for the nodelocaldns, simmilar ro coredns
The example:
    #lighthouse-start AUTO-GENERATED SECTION. DO NOT EDIT
    clusterset.local:53 {
        forward . 10.234.25.42
    }
    #lighthouse-end

then for nodelocaldns Configmap
    clusterset.local:53 {
        errors
        log
        cache 30
        reload
        loop
        bind 169.254.23.10
        forward . 10.234.25.42
        prometheus :9253
    }

**Why is this needed**:
In the standard Kubernetes cluster the nodelocaldns daemonset is established.
Int this case the clusterset.local DNS doesn't work

**Comment by aswinsuryan** [comment]
@hudec Is this a case were Lighhouse configuration repalces nodelocal DNS or viceversa?  or Does nodelocal DNS use the same domain name as lighthouse?

**Comment by hudec** [comment]
Typical coredns cm changes
  Corefile: |+
    #lighthouse-start AUTO-GENERATED SECTION. DO NOT EDIT
    clusterset.local:53 {
        forward . 10.237.12.126
    }
    #lighthouse-end
 
The next changes are required for the nodelocaldns cm
  Corefile: |
    cluster.local:53 {
        errors
        cache {
            success 9984 30
            denial 9984 5
        }
        reload
        loop
        bind 169.254.23.10
        forward . 10.237.0.3 {
            force_tcp
        }
        prometheus :9253
        health 169.254.23.10:9254
    }
    clusterset.local:53 {
        errors
        log
        cache 30
        reload
        loop
        bind 169.254.23.10
        forward . 10.237.12.126
        prometheus :9253
    }
    in-addr.arpa:53 {
        errors
...

The should be clusterset.local:53 configuration
vh

**Comment by dfarrell07** [comment]
Talking about this on the PR scrub today and we're not really sure what you did to get here, could use some more clearly reproducible steps and/or data.

**Comment by dfarrell07** [comment]
Adding @aswinsuryan to take a look, triage.

**Comment by chaunceyjiang** [comment]
I have a similar problem.

**Comment by chaunceyjiang** [comment]
I have a temporary solution,replace the `__PILLAR__UPSTREAM__SERVERS__ ` variable of [nodelocaldns.yaml](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml) with the IP address of `coredns`

**Comment by aswinsuryan** [comment]
Currently [nodelocal DNS](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/) is not supported by lighthouse , we need to explore if this can be done in lighthouse as we don't use kube-proxy.

**Comment by dfarrell07** [comment]
We aren't sure if this is still an issue, and if it is we're not sure if this type of deployment is a priority for us to support. As always, we'd welcome feedback or contributions.
