### ISSUE TITLE
Lighthouse partly-deployed when not requested

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1550]
**What happened**:

In the submariner-io/submariner repo, on devel, running a default deployment results in failing Lighthouse pods.

```
$ make deploy
$ kubectl get pods --all-namespaces=true
NAMESPACE             NAME                                             READY   STATUS             RESTARTS   AGE
<snip irrelevant>
submariner-operator   submariner-gateway-92w4c                         1/1     Running            0          67m
submariner-operator   submariner-lighthouse-agent-db6589849-z8475      0/1     ImagePullBackOff   0          67m
submariner-operator   submariner-lighthouse-coredns-68766559c4-4dm4s   0/1     ErrImagePull       0          67m
submariner-operator   submariner-lighthouse-coredns-68766559c4-c4n6z   0/1     ErrImagePull       0          67m
submariner-operator   submariner-operator-5bfdb87494-jnk7t             1/1     Running            1          67m
submariner-operator   submariner-routeagent-8n4lx                      1/1     Running            0          67m
submariner-operator   submariner-routeagent-l75k5                      1/1     Running            0          67m
```

**What you expected to happen**:

No Lighthouse components should be deployed if not requested with the `using=lighthouse` flag.

The defaults in Shipyard should be in effect, as they aren't overridden in submariner-io/submariner's `Makefile`.

Shipyard's `Makefile.inc`:

```
ifneq (,$(filter lighthouse,$(_using)))
override DEPLOY_ARGS += --service_discovery
endif
```

Shipyard's `scripts/shared/deploy.sh`:

```
DEFINE_boolean 'service_discovery' false "Enable multicluster service discovery (set to 'true' to enable)"
```

Shipyard's `scripts/shared/lib/deploy_operator`:

```
    [[ $service_discovery != true ]] || sd="--components service-discovery,connectivity"
```

**How to reproduce it (as minimally and precisely as possible)**:

`make deploy`

**Anything else we need to know?**:

A user originally reported this on Slack.

**Environment**:
- Diagnose information (use `subctl diagnose all`):

```
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.20.7" is supported

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("weave-net") is supported

 ✓ Checking gateway connections
 ✓ All connections are established

 ✗ Checking Submariner pods
 ✗ The desired number of replicas for Deployment "submariner-lighthouse-agent" (1) does not match the actual number running (0)
 ✗ The desired number of replicas for Deployment "submariner-lighthouse-coredns" (2) does not match the actual number running (0)
 ✗ Pod "submariner-lighthouse-agent-97cb87759-cbdq8" is not running. (current state is Pending)
 ✗ Pod "submariner-lighthouse-coredns-7869cfcc87-jjwt9" is not running. (current state is Pending)
 ✗ Pod "submariner-lighthouse-coredns-7869cfcc87-qgsbn" is not running. (current state is Pending)

 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs

 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
```

- Gather information (use `subctl gather`)

Attached: 

[submariner-20210911160644.tar.gz](https://github.com/submariner-io/submariner/files/7148147/submariner-20210911160644.tar.gz)

**Comment by donaldh** [comment]
This addition to the makefile will preload the lighthouse images.
```
PRELOAD_IMAGES :=  lighthouse-agent lighthouse-coredns $(IMAGES)
```
If you don't want lighthouse to be run, I guess that's an operator launch issue?

**Comment by mkolesnik** [comment]
A good solution should be to deploy with specific image overrides so that each project only tests the images that it builds and not random stuff that might (or not) have been built locally previously.

**Comment by skitt** [comment]
We could change `make deploy` in Submariner to specify `--components connectivity` on the `subctl` invocation, which would ensure that Submariner is only deployed with its own components (without having to know what other components to disable).

**Comment by dfarrell07** [comment]
I'm still seeing the `service-discovery` component passed in `make deploy` in the main repo:

```
[output]$ [cluster1] subctl deploy-broker --kubeconfig /go/src/github.com/submariner-io/submariner/output/kubeconfigs/kind-config-cluster1 --repository localhost:5000 --version local --components service-discovery,connectivity
```

Which results in the same errors:

```
submariner-operator   submariner-lighthouse-agent-56467798c6-2j8d8     0/1     ImagePullBackOff   0          103s
submariner-operator   submariner-lighthouse-coredns-68766559c4-bh2bv   0/1     ImagePullBackOff   0          103s
submariner-operator   submariner-lighthouse-coredns-68766559c4-hkq6s   0/1     ErrImagePull       0          103s
```

I verified my local Shipyard image has the expected-fix by running `make shell` and checking `/opt/shipyard/scripts/lib/deploy_operator`.

**Comment by dfarrell07** [comment]
https://github.com/submariner-io/shipyard/pull/645 should have fixed this. :heavy_check_mark:
