### ISSUE TITLE
The cluster is deployed with kube-proxy ipvs mode which Submariner does not support

### ISSUE THREAD

**Issue by 13567436138** [submariner-io/submariner#1559]
✗ Checking Submariner support for the kube-proxy mode 
 ✗ The cluster is deployed with kube-proxy ipvs mode which Submariner does not support

**Comment by jinglina** [comment]
same question with you

**Comment by dfarrell07** [comment]
It seems to me like this is a duplicate of https://github.com/submariner-io/submariner/issues/1611. Can we handle discussion there?
