### ISSUE TITLE
[Question] Does Submariner support connect clusters with Calico CNI and overlapping CIDRs?

### ISSUE THREAD

**Issue by SataQiu** [submariner-io/submariner#1599]
Does Submariner support connect clusters with Calico CNI and overlapping CIDRs?
I have two clusters with the Calico network plugin installed, and their Pod CIDR and Service CIDR are the same.
I want to use Submariner to communicate across these two clusters. 
I can only find the guidance for No overlapping CIDRs [here](https://www.tigera.io/blog/calico-and-submariner-integration-a-hands-on-walkthrough/).
Where can I find guidance more about this?

```sh
# kubectl get ippool default-ipv4-ippool -oyaml
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"362115f5-4449-11ec-9f72-00163e020210","creationTimestamp":"2021-11-13T06:16:17Z"}'
  creationTimestamp: "2021-11-13T06:16:17Z"
  generation: 3
  name: default-ipv4-ippool
  resourceVersion: "41113988"
  selfLink: /apis/crd.projectcalico.org/v1/ippools/default-ipv4-ippool
  uid: 3260f988-cf50-4b22-8a75-0c005d7b672a
spec:
  blockSize: 26
  cidr: 100.64.0.0/16
  ipipMode: Always
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never
```
Kubernetes Version: v1.20.4
Calico Version: v3.8.2

**Comment by sridhargaddam** [comment]
> Does Submariner support connect clusters with Calico CNI and overlapping CIDRs?

Yes, it does. You just have to install Submariner with Globalnet enabled.

Sample commands:
```
subctl deploy-broker  --kubeconfig cluster-a/auth/kubeconfig --globalnet --globalnet-cidr-range <some non-overlapping CIDR>
subctl join --kubeconfig cluster-a/auth/kubeconfig broker-info.subm --clusterid cluster-a
subctl join --kubeconfig cluster-b/auth/kubeconfig broker-info.subm --clusterid cluster-b
```

Also, ensure that you create the necessary IPPools as documented here - https://submariner.io/operations/deployment/calico/
Please see the note in the above page about default globalnet-cidr.
