### ISSUE TITLE
Submariner in different AZs?

### ISSUE THREAD

**Issue by m4ce** [submariner-io/submariner#16]
We tried running submariner in our cluster which spans three different AZs on AWS. It looks like the route agents fail to add the route to the destination cluster CIDRs when using as a default gateway a local node that sits in a different AZ. This is to be expected since you cannot route from one AZ via another in AWS since they are not directly attached. How to solve this?

**Comment by Oats87** [comment]
We are looking at a solution to fix this, like using VXLAN to pass local cluster traffic instead of using ip routing.

**Comment by m4ce** [comment]
Eventually, we decided to run a submariner per AZ and a broker per AZ. So the cluster becomes the AZ. As we had to run the submariner agents in different namespaces, we had to patch the code as the namespace was hard-coded. We now have it working.

**Comment by dimaunx** [comment]
#154
