### ISSUE TITLE
Failure running make reload-images in submariner

### ISSUE THREAD

**Issue by elevran** [submariner-io/submariner#1600]
**What happened**:
Make failed with an error:
```
./scripts/reload-images: line 19: /opt/shipyard/scripts/lib/cluster_settings: No such file or directory
```

**What you expected to happen**:
Images rebuilt

**How to reproduce it (as minimally and precisely as possible)**:
`make reload-images`

**Anything else we need to know?**:
See below for command output.
Running on Ubuntu LTS.

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

```
...
./scripts/reload-images --restart all
Running with: restart=all
[submariner]$ source /opt/shipyard/scripts/lib/deploy_funcs
[submariner]$ . /opt/shipyard/scripts/lib/source_only
[submariner]$ script_name=deploy_funcs
[submariner]$ exec_name=reload-images
[submariner]$ source /opt/shipyard/scripts/lib/utils
[submariner]$ . /opt/shipyard/scripts/lib/source_only
[submariner]$ script_name=utils
[submariner]$ exec_name=reload-images
[submariner]$ source /opt/shipyard/scripts/lib/cluster_settings
./scripts/reload-images: line 19: /opt/shipyard/scripts/lib/cluster_settings: No such file or directory
make: *** [Makefile:62: reload-images] Error 1
[submariner]$ make --debug=b reload-images
make: *** [Makefile.dapper:25: reload-images] Error 2
```

**Comment by nyechiel** [comment]
FWIW, this is what I get now out of the `submariner-operator` repo using Fedora 34:

```
[nyechiel@nyechiel-workstation submariner-operator]$ make reload-images
docker network create -d bridge kind
Error response from daemon: network with name kind already exists
make: [Makefile.dapper:24: reload-images] Error 1 (ignored)
./.dapper  -S z -- make --debug=b reload-images
Sending build context to Docker daemon  391.3MB
Step 1/8 : ARG BASE_BRANCH
Step 2/8 : FROM quay.io/submariner/shipyard-dapper-base:${BASE_BRANCH}
 ---> f851c57e11d4
Step 3/8 : ARG PROJECT
 ---> Using cache
 ---> 34b0fc8d4399
Step 4/8 : ENV DAPPER_ENV="QUAY_USERNAME QUAY_PASSWORD CLUSTERS_ARGS DEPLOY_ARGS CLEANUP_ARGS E2E_ARGS RELEASE_ARGS MAKEFLAGS FOCUS SKIP PLUGIN E2E_TESTDIR GITHUB_USER GITHUB_TOKEN"     DAPPER_SOURCE=/go/src/github.com/submariner-io/${PROJECT} DAPPER_DOCKER_SOCKET=true
 ---> Using cache
 ---> 2ecdcaaf2c20
Step 5/8 : ENV DAPPER_OUTPUT=${DAPPER_SOURCE}/output
 ---> Using cache
 ---> 7d038dbc0e95
Step 6/8 : WORKDIR ${DAPPER_SOURCE}
 ---> Using cache
 ---> ede09efd1ada
Step 7/8 : ENTRYPOINT ["/opt/shipyard/scripts/entry"]
 ---> Using cache
 ---> 87ea1c276368
Step 8/8 : CMD ["sh"]
 ---> Using cache
 ---> 9a3b1a060704
Successfully built 9a3b1a060704
Successfully tagged submariner-operator:heads_devel
[submariner-operator]$ trap chown -R 1000:1000 . exit
[submariner-operator]$ mkdir -p bin dist output
[submariner-operator]$ make --debug=b reload-images
GNU Make 4.3
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Makefile:143: warning: overriding recipe for target 'e2e'
/opt/shipyard/Makefile.inc:129: warning: ignoring old recipe for target 'e2e'
Updating makefiles....
Updating goal targets....
 File 'reload-images' does not exist.
Must remake target 'reload-images'.
make: *** No rule to make target 'reload-images'.  Stop.
[submariner-operator]$ make --debug=b reload-images
make: *** [Makefile.dapper:25: reload-images] Error 2
[nyechiel@nyechiel-workstation submariner-operator]$ 

```

**Comment by nyechiel** [comment]
@mkolesnik are you planning to look at this?

**Comment by mkolesnik** [comment]
> FWIW, this is what I get now out of the `submariner-operator` repo using Fedora 34:
> 

It has never been a capability on operator, but I can add it if desired.

**Comment by nyechiel** [comment]
> > FWIW, this is what I get now out of the `submariner-operator` repo using Fedora 34:
> 
> It has never been a capability on operator, but I can add it if desired.

I don't have a strong need for that, I was just expecting it to work across all repos as a shared script. Speaking of which, I see that we don't have this capability documented anywhere in the website. Should probably go under https://submariner.io/development/building-testing/?

**Comment by mkolesnik** [comment]
> I don't have a strong need for that, I was just expecting it to work across all repos as a shared script. Speaking of which, I see that we don't have this capability documented anywhere in the website. Should probably go under https://submariner.io/development/building-testing/?

This script was only available in `submariner` and `lighthouse` but as a shared script it is possible to make it work across other repos, they just need a small tweak each (how cluster settings are loaded, and images to preload). I feel this would mostly be useful in those repos that generate the images though.

I can add documentation but the script was added a long time ago so it's not really related to this bug, but sure.

**Comment by nyechiel** [comment]
> > I don't have a strong need for that, I was just expecting it to work across all repos as a shared script. Speaking of which, I see that we don't have this capability documented anywhere in the website. Should probably go under https://submariner.io/development/building-testing/?
> 
> This script was only available in `submariner` and `lighthouse` but as a shared script it is possible to make it work across other repos, they just need a small tweak each (how cluster settings are loaded, and images to preload). I feel this would mostly be useful in those repos that generate the images though.
> 
> I can add documentation but the script was added a long time ago so it's not really related to this bug, but sure.

Yes, I raised this separate docs issue: https://github.com/submariner-io/submariner-website/issues/677

**Comment by mkolesnik** [comment]
Added support for operator as well https://github.com/submariner-io/submariner-operator/pull/1874
