### ISSUE TITLE
Submariner VXLAN cable mtu

### ISSUE THREAD

**Issue by m4ce** [submariner-io/submariner#1610]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/network_mtu.html

We use submariner to inter-connect kubernetes clusters running in different AWS regions. Internally, within the region, we do use Jumbo frames. However, on the inter-region vpc peering, the MTU is capped at 1500 due to AWS limitations (see link above).

By default, submariner defaults the vxlan-tunnel's mtu to the default host's interface, which is 9001-50=8951. However, we should really set it to 1500-50=1450.

I did some iperf tests and the performance is quite horrible with the default mtu of 8951. On a specific link where the we should be able to drive throughput as high as 300mbit/s, we can only get up to 150-160mbit/s.

iperf through vxlan-tunnel interface with MTU 8951 (on both side)
```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-300.00 sec  5.25 GBytes   150 Mbits/sec  191             sender
[  4]   0.00-300.00 sec  5.25 GBytes   150 Mbits/sec                  receiver
```

iperf through vxlan-tunnel interface with MTU 1450 (on both side)
```
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-300.00 sec  8.95 GBytes   256 Mbits/sec  3115             sender
[  4]   0.00-300.00 sec  8.95 GBytes   256 Mbits/sec                  receiver
```

Is there any way for us to override the MTU on the vxlan cable driver? Or would you suggest changing the default's interface MTU to 1500 and let path mtu discovery do the rest internally?

Thank you.

**Comment by sridhargaddam** [comment]
Thanks for validating and reporting the observations @m4ce.

> By default, submariner defaults the vxlan-tunnel's mtu to the default host's interface, which is 9001-50=8951. 

That's correct. Currently, Submariner relies on the default host interface to calculate the tunnel interface MTU

> Is there any way for us to override the MTU on the vxlan cable driver? 

Currently, this is not supported but on the long-term roadmap, we have plans within Submariner to auto-discovery the MTU and configure it on the interfaces.

>Or would you suggest changing the default's interface MTU to 1500 and let path mtu discovery do the rest internally?

For now, please take this approach as we do not have other options.

**Comment by dfarrell07** [comment]
> we have plans within Submariner to auto-discovery the MTU and configure it on the interfaces

Do we have an issue to track this? If not, should we open one and close this?

**Comment by sridhargaddam** [comment]
> Do we have an issue to track this? If not, should we open one and close this?

@dfarrell07 I opened a new issue to track this - https://github.com/submariner-io/submariner/issues/1641
So, we can close this one.
