### ISSUE TITLE
Update submariner-security Google Group and submariner-io GH Org Owners

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1615]
**What would you like to be added**:

- [ ] Make [submariner-security Google Group](https://groups.google.com/g/submariner-security/about) publicly visible and group members visible
- [ ] Add @sridhargaddam to submariner-security Google Group
- [ ] Add @skitt to submariner-security Google Group
- [ ] Make sure all/only the Submariner Owners are admins of the submariner-security Google Group
- [ ] Remove @mangelajo from submariner-security Google Group

We need an admin to do this.

**Why is this needed**:

Keep our configuration consistent with [our Contributor Role policies](https://submariner.io/community/contributor-roles/).

**Comment by dfarrell07** [comment]
Can you wield your admin powers to help with this @skitt or @tpantelis?

**Comment by skitt** [comment]
> Can you wield your admin powers to help with this @skitt or @tpantelis?

I can’t, I’ve apparently been removed from the group and was never an admin anyway AFAIK. I think we need @mangelajo for this one...

**Comment by dfarrell07** [comment]
I talked with Miguel on Slack, he was on PTO today (sorry!:skull:) but will take a look at this. Thanks Miguel!

**Comment by mangelajo** [comment]
Hey, @skitt and @tpantelis you were both admins. I also added @sridhargaddam .

Can you verify, and then feel free to drop miguelangel <at> ajo.es and majopela <at> redhat.com ? :)

cheers, and take care

**Comment by skitt** [comment]
Thanks for checking @mangelajo. I suspect the problem I have is that Google Groups for groups outside Red Hat isn’t accessible with our Red Hat accounts — so we can’t manage them with out Red Hat accounts... Could you add my personal account? I’ll email you the details.

**Comment by mangelajo** [comment]
Let me try, I was using my RH account I believe, but it's worth trying.

**Comment by mangelajo** [comment]
It's done, let me know how it goes.

**Comment by dfarrell07** [comment]
@skitt Do you have access to the submariner-security Google Group via your personal account now? Can you make the group public and make sure all the correct folks are added/removed?

**Comment by dfarrell07** [comment]
When we think we have everything set up, I can send a test.

**Comment by skitt** [comment]
> @skitt Do you have access to the submariner-security Google Group via your personal account now? Can you make the group public and make sure all the correct folks are added/removed?

Yes, I can access the group’s administration and add/remove people as appropriate. I’ll remove Miguel.

**Comment by skitt** [comment]
@tpantelis and @sridhargaddam, can you check whether you can access [the group’s administration](https://groups.google.com/g/submariner-security)? We need to ensure we’re not locked out if something happens to me...

**Comment by sridhargaddam** [comment]
> @tpantelis and @sridhargaddam, can you check whether you can access [the group’s administration](https://groups.google.com/g/submariner-security)? We need to ensure we’re not locked out if something happens to me...

Yes, I can @skitt :+1:

**Comment by skitt** [comment]
OK, this is complete.
