### ISSUE TITLE
REQUEST: New committer rights request for dfarrell07

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1622]
### GitHub Username
@dfarrell07

### Code you are requesting Committer rights for
```
submariner-io/submariner-website/*
submariner-io/*/*.md
```

### Requirements
- [x] I have reviewed the contributor roles guidelines (https://submariner.io/community/contributor-roles/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have been actively contributing to Submariner for at least 3 months
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @skitt
- @tpantelis

### List of required reviews to Submariner project PRs
- At least 20 PRs to the relevant codebase that you reviewed, and at least 5 for which you were the primary reviewer
  - https://github.com/submariner-io/submariner-website/pulls?q=is%3Apr+reviewed-by%3Adfarrell07+-author%3Adfarrell07

**Comment by skitt** [comment]
I think this is now complete.

**Comment by dfarrell07** [comment]
> I think this is now complete.

Thanks for all the PRs, @skitt!
