### ISSUE TITLE
pinger_test is flaky

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#1628]
**Which jobs are flaking**: unit tests

**Which test(s) are flaking**: pinger_test

**Testgrid link**: https://github.com/submariner-io/submariner/runs/4562958089?check_suite_focus=true

**Reason for failure**:

```
Pinger when the pinger is stopped 
  should no longer update the statistics
  /go/src/github.com/submariner-io/submariner/pkg/cableengine/healthchecker/pinger_test.go:151
I1217 16:43:42.823708    5966 pinger.go:104] Starting pinger for IP "127.0.0.1"

• Failure [0.207 seconds]
Pinger
/go/src/github.com/submariner-io/submariner/pkg/cableengine/healthchecker/pinger_test.go:39
  when the pinger is stopped
  /go/src/github.com/submariner-io/submariner/pkg/cableengine/healthchecker/pinger_test.go:146
    should no longer update the statistics [It]
    /go/src/github.com/submariner-io/submariner/pkg/cableengine/healthchecker/pinger_test.go:151

    Timed out after 0.202s.
    Expected
        <*healthchecker.LatencyInfo | 0xc000196b40>: {
            ConnectionError: "",
            ConnectionStatus: "",
            Spec: {Last: "0s", Min: "0s", Average: "0s", Max: "0s", StdDev: "0s"},
        }
    not to equal
        <*healthchecker.LatencyInfo | 0xc0004e6930>: {
            ConnectionError: "",
            ConnectionStatus: "",
            Spec: {Last: "0s", Min: "0s", Average: "0s", Max: "0s", StdDev: "0s"},
        }

    /go/src/github.com/submariner-io/submariner/pkg/cableengine/healthchecker/pinger_test.go:110

    Full Stack Trace
    github.com/submariner-io/submariner/pkg/cableengine/healthchecker_test.glob..func2.5(0x3)
    	/go/src/github.com/submariner-io/submariner/pkg/cableengine/healthchecker/pinger_test.go:110 +0xfb
    github.com/submariner-io/submariner/pkg/cableengine/healthchecker_test.glob..func2.9.2()
    	/go/src/github.com/submariner-io/submariner/pkg/cableengine/healthchecker/pinger_test.go:152 +0x70
    github.com/submariner-io/submariner/pkg/cableengine/healthchecker_test.TestHealthChecker(0xc0002e5e00)
    	/go/src/github.com/submariner-io/submariner/pkg/cableengine/healthchecker/healthchecker_suite_test.go:35 +0xa5
    testing.tRunner(0xc0002e5e00, 0x1fbcac0)
    	/usr/lib/golang/src/testing/testing.go:1193 +0x203
    created by testing.(*T).Run
    	/usr/lib/golang/src/testing/testing.go:1238 +0x5d8
```

**Anything else we need to know**: this has been seen on a number of PRs.

**Comment by tpantelis** [comment]
I ran this locally with `-untilFails` many hundreds of times w/o failure. What's strange is that it fails in the initial `verifyPingStats` before it even stops it but the "the IP is reachable" test that also calls `verifyPingStats` doesn't fail.  The only difference is that the `pingInterval` is shorter (100 ms) than the other test (300 ms) so perhaps the actual ping itself sometimes takes a bit longer. I'll take a look at that.

**Comment by skitt** [comment]
In all the failures I’ve seen, the output was all 0s; does that mean that the ping was too fast to be measured, or that none had been measured at all? It might be worth logging the number of received pings.

**Comment by tpantelis** [comment]
> In all the failures I’ve seen, the output was all 0s; does that mean that the ping was too fast to be measured, or that none had been measured at all? It might be worth logging the number of received pings.

I was thinking the first ping hadn't happened yet but perhaps 100ms interval is sometimes too small to produce a measurable difference. Either way, with this test case, we just want to make sure the pinger has started so we can verify that it stopped so we just need to ensure one ping occurred and not measure a difference - I'll change the test accordingly.
