### ISSUE TITLE
infinite creation of submariner-networkplugin-syncer-XXX pods

### ISSUE THREAD

**Issue by luis5tb** [submariner-io/submariner#1631]
In deployment on top of AWS, the gateway node is simply using the local filesystem as there is no option to, for instance, point to EBS volumes in "prepare aws" (https://submariner.io/operations/deployment/subctl/#prepare-aws)

In long living environments this is a problem as the node will soon reach the disk pressure status and will start evicting pods. This triggers the recreation of the submariner-networkplugin-syncer pod, without removing the previous one, and without having an exponential back-off or the like to not create them that frequently. This in turns lead to having tons of submariner-networking-syncer pods consuming IPs but in evicted mode, which blocks the creation of new pods.

In an environment running for 10 days I had more than 12k submariner-networkplugin-syncer pods in the submariner-operator namespace.

So, an option for supporting EBS (for instance) could be added, but at least the evicted pods on submariner-operator namespace should be cleaned up before creating new replicas of them

**Comment by sridhargaddam** [comment]
Thanks, @luis5tb for reporting the issue. I think currently there is no easy way to inform K8s to auto-clean up the evicted pods. There seems to be some limit that can be lowered but it's a cluster-wide configuration.

I have the following questions
1. Does configuring EBS for the Submariner gateway nodes solve the issue?
2. In case its yes for the above, can we do this unconditionally in `subctl cloud prepare aws ...` or should Submariner look at the worker node configuration in the clusters and apply the EBS only if the other workers are using that config?

**Comment by nyechiel** [comment]
@luis5tb can you review the questions from Sridhar, please?

**Comment by luis5tb** [comment]
Sorry I missed the reply here. 
For 1, yes, configuring EBS solved the problem for us.
For 2, I think having EBS unconditionally could not be the right option always. Either this needs to be "a prompt question" or as you suggest, copying the same as the other worker nodes. In fact, related to that, what must be added to is a note on the "subctl cloud prepare aws" to ACK that a new node/VM is going to be created.

**Comment by dfarrell07** [comment]
Discussed on the scrub today, we're not sure if this is still an issue. Is it still showing up in the most recent versions? We think we've reduced the number of errors and amount of logging.

I wonder if this should be subsumed by a longevity testing exercise.

**Comment by astoycos** [comment]
Let's close for now If this isn't an issue
