### ISSUE TITLE
Support configuring the MTU of VxLAN interface

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1641]
Currently, Submariner configures the VxLAN interface MTU which is derived from the default host interface MTU. However, this approach may not be suitable for all deployments, one such example is discussed in the following issue - https://github.com/submariner-io/submariner/issues/1610

In order to support such deployments, it would be great if Submariner can do one/both of the following.

1. Support overriding the MTU information in a cluster
2. Auto-discover the MTU and configure the appropriate one.

PS: Although this issue talks about VxLAN interface, the solution should take into consideration the other cable drivers as well and find a generic mechanism.

**Comment by sridhargaddam** [comment]
still relevant

**Comment by dfarrell07** [comment]
This is still nice-to-have but no one has asked for it so it' low priority currently.
