### ISSUE TITLE
Configurable encryption settings in the cable driver

### ISSUE THREAD

**Issue by kot-begemot-uk** [submariner-io/submariner#1668]
**What would you like to be added**:
Configurable encryption settings in the cable driver

**Why is this needed**:
To enable the choice of cipher (and authentication) which has hardware offload support.
1. This allows throughput from 1-2Gbits to increase to higher rates. On some configurations - up to line rate.
2. On some adapters it also allows further processing (TCP, etc) to be correctly load-balanced across multiple queues.
3. While it is not essential, it is better if the encryption settings are per connection and not global. F.E. some destinations will perform best with AES-GCM, some with AES-CBC, etc.

**Comment by kot-begemot-uk** [comment]
This will resolve https://github.com/submariner-io/submariner/issues/1510 on some configurations where it is possible to use crypto offload.

**Comment by maayanf24** [comment]
Talked on the scrub call and agreed to close. You can re-open if needed
