### ISSUE TITLE
Add a new cable driver to use GRE tunnel with optional IPSEC transport "security wrap"

### ISSUE THREAD

**Issue by kot-begemot-uk** [submariner-io/submariner#1669]
**What would you like to be added**:
GRE tunnel driver with optional per connection "use IPSEC if required".

**Why is this needed**:
The performance is significantly higher than VXLAN or Tunnel mode for site-to-site traffic and on some hardware it is capable of achieving line rate with IPSEC (up to 40GBit), because of both IPSEC and TCP offloads can work simultaneously.

**Comment by kot-begemot-uk** [comment]
In the longer term, this will allow working around https://github.com/submariner-io/submariner/issues/1510 on all configurations.

**Comment by dfarrell07** [comment]
Is this related? https://github.com/submariner-io/enhancements/pull/103

**Comment by dfarrell07** [comment]
Confirmed this is still nice to have but we don't currently have bandwidth - scrub

**Comment by maayanf24** [comment]
Talked on the scrub call and agreed to close. You can re-open if needed

**Comment by maayanf24** [comment]
Closing now
