### ISSUE TITLE
Issue with submariner and ROKS (IBM Cloud)

### ISSUE THREAD

**Issue by dberg1** [submariner-io/submariner#1670]
Here is my issue with submariner + ROKS.
Cluster B is using Calico.
A pod running on node 2 in cluster B tries to connect to a service exported by cluster A.
The SYN packet is sent to the submariner gateway node through the submariner VXLAN tunnel.
The submariner gateway node forwards the SYN packet through the IPsec tunnel established with remote cluster A.
Cluster A sends the SYN+ACK response through the IPsec tunnel.
The submariner gateway node on cluster B forwards the SYN+ACK response to node 2 through the eth0 network interface.
Node 2 never receives the SYN+ACK response packet (tcpdump shows nothing).
It looks like the SYN+ACK packet is discarded by some sort of firewall between the submariner gateway node and node 2.

```
  Cluster A                           Cluster B                   
+-----------+        IPsec          +-----------+
|  GW node  |=======================|  GW node  |
|           |<--------SYN-----------|           |
|           |-------SYN+ACK-------->|           |
+-----------+                       +-----------+
                                        ^   |
                                    SYN |   | SYN+ACK
                        (vx-submariner) |   v (eth0)
                                        |   X
                                        |
                                    +-----------+
                                    |   node2   |
                                    |           |
                                    |           |
                                    +-----------+
```

_Originally posted by @dberg1 in submariner-io/submariner-operator#1852

**Comment by dberg1** [comment]
> My guess would be that SYN+ACK packet from ClusterB GW node has sourceIP as ClusterIP Svc in Node A. Since the sourceIP does not match any of the interface IPs on ClusterB GW node, the underlying infrastructure might be dropping the packets (leaving the GW node) silently as part of Anti-spoofing rules (i.e., it might only allow traffic that has the original IP and MAC assigned to the ClusterB Gw node). Please check if this is the case.

@sridhargaddam Yes, that is my understanding too.
The source IP address is the one of the svc in cluster A. The source MAC address is the one of the submariner GW node in cluster B. I checked the VPC subnet in IBM Cloud, and all IP traffic is allowed between the cluster nodes. But there could be some underlying security rules that block the SYN+ACK.

**Comment by dberg1** [comment]
In IBM Cloud VPC, there is an option named "Allow IP spoofing" that you can enable on a per-VSI basis.
This option is not available for OpenShift VSIs though.
But at least, it seems to indicate that this anti-spoofing is enabled by default which could explain why the SYN+ACK is blocked.
![image](https://user-images.githubusercontent.com/48122102/152758764-7d89ac58-ec92-47f4-9d4d-4b1f97d76a7d.png)

**Comment by dberg1** [comment]
> If you are using the instance as a "next hop", the instance's network interfaces must allow IP spoofing.

https://cloud.ibm.com/docs/vpc?topic=vpc-ip-spoofing-about

This would mean that the anti-spoofing must be disabled on the submariner gateway node.
Will check with IBM support if this is doable.

**Comment by dberg1** [comment]
I may have found a possible workaround.
Setting `ipipMode: Always` (instead of `CrossSubnet`) in IPPool `default-ipv4-ippool` seems to work around the issue by encapsulating all the traffic from the submariner gateway node in Cluster B to node2 (including the SYN+ACK) in an IP-in-IP tunnel such that it is not dropped by IBM Cloud VPC.
This is a bit of an overkill though as it impacts all the communications between the cluster nodes.

**Comment by dberg1** [comment]
With `ipipMode: Always` we can circumvent IBM Cloud VPC security checks on `eth0`:

```
  Cluster A                           Cluster B
+-----------+        IPsec          +-----------+
|  GW node  |=======================|  GW node  |
|           |<--------SYN-----------|           |
|           |-------SYN+ACK-------->|           |
+-----------+                       +-----------+
                                        ^   |
                                    SYN |   | SYN+ACK
                        (vx-submariner) |   | (tunl0)
                                        |   |
                                        |   v
                                    +-----------+
                                    |   node2   |
                                    |           |
                                    |           |
                                    +-----------+
```

**Comment by dfarrell07** [comment]
@dberg1 Is this still an issue?

**Comment by dberg1** [comment]
Yes, it is still an issue. I don't think submariner can do anything about it though.
The SYN+ACK is discarded by IBM Cloud's anti-spoofing filter because SYN and SYN+ACK do not go through the same network interface.
The only workaround so far is to use Calico to encapsulate the SYN+ACK in an IP-in-IP tunnel so that it is not detected by IBM Cloud's anti-spoofing filter.

**Comment by dfarrell07** [comment]
Okay, sounds like we need to dig into this. Maybe we can make this UX easier with cloud-prepare.

**Comment by yboaron** [comment]
@dberg1 ,
Also investigated SM deployment on ROKS clusters,
- ROKS cluster comes with default infra SG (named kube-< clusterID >) that allows intra-cluster traffic only when both src and dest IPs are from clutser's pod CIDR
- As you mentioned, in case calico default IPPool overlay is configured  to ipipMode: CrossSubnet and nodes IPs are from the same subnet, intra-cluster traffic will not be encapsulated in IPinIP tunnel by Calico.
- So, in this case the syn-ack packet sent from gw-node@clusterB to node2@clusterB, won't be encapsulated in IPinIP by Calico, which means that packet's srcIP= < someIP from clusterA pod CIDR > and destIP < someIP from clusterB CIDR > 
- This packet will be dropped by cluster INFRA SG. 


Currently, we have two possible workarounds here:
1. As you mentioned, setting ipipMode: Always  on both clusters, 
- with this change, the packet from gw-node@clusterB to node2@clusterB will be encapsulated in IPIP,  and INFRA SG will allow this packet
- Submarinr route-agent will allow the asymmetric traffic by updating rp_filter for loose mode for the CNI interface (node's network interface with IP address from cluster's POD CIDR)
 
2.  On each cluster:  update infra SG to allow traffic from remote clusters CIDRS and allow asymmetric traffic on the interface with node IP
 -  You need to update cluster SG to allow traffic from remote clusters, check [A]
 -  Update rp_filter to loose mode for network interface with node IP address


BTW, starting from submariner 0.16.0 , submariner automatically create Calico IPPools needed for inter-cluster connectivity. 

[A]
ibmcloud is security-group-rule-add kube-xxxx inbound all --remote <remote_cluster_cidr>

**Comment by yboaron** [comment]
@dberg1 any update on this issue ?

**Comment by jaywcarman** [comment]
Hi @yboaron! @dberg1 is no longer working on this. (👋🏻 dberg1 if you've receiving this notification 😃 !)

Lately @bkhadars has been working with Submariner on Power, though I'm not sure if ROKs has been in the mix at all. Any thoughts Basheer?

(fyi @vijay-vin, who's leading the RHACM on Power related work now)

**Comment by yboaron** [comment]
I'm going to close this issue, feel free to reopen it if it's still relevant
