### ISSUE TITLE
Globalnet does not work for services without selector

### ISSUE THREAD

**Issue by anfredette** [submariner-io/submariner#1693]
**What happened**:
Created a service without selector and it was not reachable from another cluster in the clusterset.

**What you expected to happen**:
That the service be reachable from anywhere in the clusterset

**How to reproduce it (as minimally and precisely as possible)**:
- Create a service w/o selector
- Manually create a pod endpoint for the service
- Confirm that it is accessible on the local cluster
- Export the service
- Attempt to access the global IP address from nettest on another cluster in the clusterset
- Note that it is not accessible

Note: The actual global IP address must be used instead of the domain name until https://github.com/submariner-io/lighthouse/issues/603 is resolved.

**Anything else we need to know?**:
It is believed that this issues was introduced by https://github.com/submariner-io/submariner/pull/1643

A work-around is to manually create an endpoint for the internal service created by the export. For example, execute the following script (assuming service and pod names are as defined below)
```
SVC_NAME=nginx-svc
SVC_POD_NAME=nginx-pod
SVC_PORT=80
INTERNAL_SVC_NAME=$(kubectl get services -l submariner.io/exportedServiceRef=$SVC_NAME | grep submariner | awk '{print $1}')
SVC_POD_IP=$(kubectl get pods -n default $SVC_POD_NAME -o wide | grep $SVC_POD_NAME | awk '{print $6}')

cat << EOF | kubectl apply -f -
apiVersion: v1
kind: Endpoints
metadata:
  name: $INTERNAL_SVC_NAME
subsets:
  - addresses:
      - ip: $SVC_POD_IP
    ports:
      - port: $SVC_PORT
EOF
```

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by sridhargaddam** [comment]
This is still relevant. The PR from @anfredette addresses the LH/ServiceDiscovery use-cases.

**Comment by anfredette** [comment]
I didn't intend to close this issue per comment from @sridhargaddam.  I am reopening it again.

**Comment by anfredette** [comment]
This was fixed by the following two PRs:
https://github.com/submariner-io/submariner/pull/1695
https://github.com/submariner-io/submariner-operator/pull/1845
