### ISSUE TITLE
Enhance subctl gather to collect Globalnet objects

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1700]
**What would you like to be added**:
As part of `subctl gather ...` command, we can collect the necessary globalnet objects like clusterGlobalEgressIPs, globalEgressIPs, globalIngressIPs etc.

Also, for every exported service, globalnet now creates an internal service with external_ip configured with the corresponding globalIP assigned to the exported service. Capturing the details of `internal services` as part of `subctl gather` helps while troubleshooting issues.

**Comment by nerdalert** [comment]
@sridhargaddam  Happy to run with this one if it helps

**Comment by sridhargaddam** [comment]
> @sridhargaddam Happy to run with this one if it helps

That would be awesome @nerdalert, thank you. If you need any inputs related to this task, please let me know. Feel free to assign this issue when you start looking into it.

**Comment by nerdalert** [comment]
Hi @sridhargaddam, going through the gather code and it looks like it is already implemented in the [subctl gather](https://github.com/submariner-io/submariner-operator/blob/06c4fd8b19a8da241fdf31f1595889656049b860/pkg/subctl/cmd/gather/gather.go#L198-L200).

I double checked it in the gather output as well:

![gather-ingress](https://user-images.githubusercontent.com/1711674/155259478-8c69b826-eb05-4c74-bb0e-fe132c560633.png)

Lemme know if I'm missing something here. Thanks!

**Comment by sridhargaddam** [comment]
Thank you @nerdalert for looking into it. Yes, you are right we are capturing these objects as part of gather. The following alone is missing.

For every exported service, globalnet now creates an `internal service` with `external_ip` configured with the corresponding `globalIP` assigned to the exported service. Can you please add code to capture the internal services for every exported service.

Sample output:
---------------------
```
[sgaddam@localhost submariner]$ kubectl get svc nginx -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-02-23T08:21:26Z"
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "18712"
  uid: cf50fc6c-242c-4fda-ac73-8039ff2179a9
spec:
  clusterIP: 100.0.210.4
  clusterIPs:
  - 100.0.210.4
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

```
[sgaddam@localhost submariner]$ kubectl get giip -o yaml
apiVersion: v1
items:
- apiVersion: submariner.io/v1
  kind: GlobalIngressIP
  metadata:
    creationTimestamp: "2022-02-23T08:21:26Z"
    generation: 2
    labels:
      submariner-io/originatingNamespace: default
    name: nginx
    namespace: default
    resourceVersion: "18723"
    uid: dda423d2-f48c-4406-b6e9-a06409ae5d3e
  spec:
    serviceRef:
      name: nginx
    target: ClusterIPService
  status:
    allocatedIP: 242.254.1.253
    conditions:
    - lastTransitionTime: "2022-02-23T08:21:26Z"
      message: Allocated global IP
      reason: Success
      status: "True"
      type: Allocated
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

```

```
[sgaddam@localhost submariner]$ kubectl get svc submariner-lpq6zr4tl4o5qvrv2t7o3l3gawkagast -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-02-23T08:21:26Z"
  finalizers:
  - submariner.io/globalnet-internal-service
  labels:
    submariner.io/exportedServiceRef: nginx
  name: submariner-lpq6zr4tl4o5qvrv2t7o3l3gawkagast
  namespace: default
  resourceVersion: "18720"
  uid: 926bb167-2c06-49bd-874d-d8aaacbbabd8
spec:
  clusterIP: 100.0.168.115
  clusterIPs:
  - 100.0.168.115
  externalIPs:
  - 242.254.1.253
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
