### ISSUE TITLE
The logical for selecting vxlan interface needs to be optimised

### ISSUE THREAD

**Issue by lut777** [submariner-io/submariner#1715]
**What would you like to be added**:

I'm trying to deploy submarine into my K8s system, which is built based on [Kube-OVN](https://github.com/kubeovn/kube-ovn). 
However, there is a logical problem which needs to be optimized.
Currently in this [function](https://github.com/submariner-io/submariner/blob/f40880e523d3201c5dcd3648079b798134ef52cc/pkg/routeagent_driver/cni/cni_iface.go#L50) , the way to determine whether a interface is connected to the pod is to see if the ip in that interface is included in the podCIDR of ClusterNetwork.
While in Kube-OVN, an interface, which is named as ovn0, is set to receive all data streams to the pods. However, the IP of this interface ovn0 is completely unrelated to the PodCIDR.
The reason to get the interface is to lead the data stream from VXLAN to the pods as I find in this [func](https://github.com/submariner-io/submariner/blob/f40880e523d3201c5dcd3648079b798134ef52cc/pkg/cable/vxlan/vxlan.go#L322).

So here my suggestion is: Is it possible for users to just specify this interface by themselves?

**Comment by dfarrell07** [comment]
@aswinsuryan agreed to take a look, give feedback

**Comment by dfarrell07** [comment]
We support OVN-Kubernetes, but not Kube-OVN. I don't think there's interest to work on adding it currently.
