### ISSUE TITLE
Relevant postrouting iptables rules on cluster1 not being deleted after subctl uninstall cluster2

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#1720]
**What happened**:
Postrouting iptables rules on cluster1 allowing traffic to cluster2 subnets not removed 
 after running  'subctl uninstall Cluster2'

**What you expected to happen**:
Relevant iptables rules should be deleted

**How to reproduce it (as minimally and precisely as possible)**:
1. Run Kind deployment (https://submariner.io/getting-started/quickstart/kind/), where cluster1 is also the broker
2. Run 'subctl uninstall cluster2'
3. Verify that cluster2 EP removed from cluster1

>> $ kubectl get endpoints.submariner.io -A 
>>NAMESPACE               NAME                                            AGE
submariner-k8s-broker   cluster1-submariner-cable-cluster1-172-20-0-4   20m
submariner-operator     cluster1-submariner-cable-cluster1-172-20-0-4   20m

4. check iptables (nat  table) on cluster1 GW node, we can still see rules that accept traffic from cluster2 subnets (100.2.0.0/16 and 10.2.0.0/16)

>> $iptables -t nat -L SUBMARINER-POSTROUTING
>> Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain SUBMARINER-POSTROUTING (1 references)
target     prot opt source               destination         
SNAT       all  --  240.0.0.0/8          anywhere             to:10.1.128.0
ACCEPT     all  --  10.1.0.0/16          100.2.0.0/16        
ACCEPT     all  --  100.2.0.0/16         10.1.0.0/16         
ACCEPT     all  --  10.1.0.0/16          10.2.0.0/16         
ACCEPT     all  --  10.2.0.0/16          10.1.0.0/16         

[subcatl_gather.gz](https://github.com/submariner-io/submariner/files/8198844/subcatl_gather.gz)

**Comment by sridhargaddam** [comment]
Thanks @yboaron for reporting the issue and capturing the logs. I will take a look at it.
