### ISSUE TITLE
GlobalNet- exported service isn't reachable after service re creation

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#1734]
**What happened**:
1. I followed the service export instructions from [A],
a.  I created a service (default/nginx) on cluster1 and export it
b.  I was able to access the service from cluster2.
2.  I re create the service on cluster1 by
 a.  delete the (default/nginx)  service from cluster1 
 b.  create a new service with the same name 

Though both service and the corresponding serviceexport exist on cluster1, I wasn't able to access default/nginx service from cluster2.

I think that the root cause is that GN controller removed the Global Ingress IP CR on step 2.a and didn't create it after 2.b

[A]
https://submariner.io/getting-started/quickstart/kind/#verify-manually

**What you expected to happen**:
Remote service should be reachable
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Kind , reswan + GlobalNet

**Comment by sridhargaddam** [comment]
Currently Globlanet controller does not process Service creation/updation events and it only processes delete events. In order to handle this use-case we will have to enhance the code to process create events for Services.

**Comment by dfarrell07** [comment]
This might be fixed by https://github.com/submariner-io/enhancements/pull/111.

**Comment by dfarrell07** [comment]
@sridhargaddam says there is a work-around for this, lowering prio.

**Comment by tpantelis** [comment]
This will also fix https://github.com/submariner-io/lighthouse/issues/693.
