### ISSUE TITLE
PodSecurityPolicy: unable to admit pod: []

### ISSUE THREAD

**Issue by mikekuzak** [submariner-io/submariner#1736]
Rancher v2.5.12
K8s: v1.20

Hi
When trying to install the submariner operator I'm getting the following error:

```
-bash-4.2$ subctl deploy-broker --kubeconfig .kube/config-cluster
 ✓ Setting up broker RBAC 
 ✗ Deploying the Submariner operator 
 ✓ Created operator CRDs
 ✓ Created operator namespace: submariner-operator
 ✓ Created operator service account and role
 ✓ Created lighthouse service account and role
 ✓ Created Lighthouse service accounts and roles
Error deploying the operator: timed out waiting for the condition
```

Error creating: pods "submariner-operator-57fdbfdb78-" is forbidden: PodSecurityPolicy: unable to admit pod: []

![image](https://user-images.githubusercontent.com/18675587/158665305-24516ffb-586e-40e7-beb0-b57223c7340e.png)

Didn't have any issues deploying anything else before. 
Thanks for any advice.

**Comment by dfarrell07** [comment]
I'm wondering if K8s moving away from this and to https://github.com/submariner-io/subctl/pull/105 would have resolve any issue?

**Comment by dfarrell07** [comment]
We've made quite a few fixes for PodSecurityPolicy (but focused on OCP, not K3s), is this still an issue @mikekuzak?

Also that was a fairly old version of K8s, I'm wondering if it's still relevant.

**Comment by dfarrell07** [comment]
If this is still an issue we can re-open, but closing for now as we think this has likely been resolved.
