### ISSUE TITLE
GlobalNet - exported service isn't reachable using desired port after service port edit

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#1738]
**What happened**:
This issue is similar to https://github.com/submariner-io/submariner/issues/1734  

1. I followed the service export instructions from [A],
a. I created a service (default/nginx) on cluster2 and export it
b. I was able to access the service from cluster1.
2. I changed the frontend port# of  service default/nginx from 80 to 8080 using 'kubectl edit'
3. While I can successfully connect the service with port 8080  using the local DNS name from cluster2 [B] I can't connect to exported service from cluster1 with port 8080 [C]

I think that root cause is that the service created by GN controller to handle ingress traffic towards service pods not being updated with the desired port

[A]
>>
https://submariner.io/getting-started/quickstart/kind/#verify-manually

[B]
>>
bash-5.0# curl nginx.default.svc.cluster2.local:8080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
bash-5.0# curl nginx.default.svc.cluster2.local:80
curl: (28) Failed to connect to nginx.default.svc.cluster2.local port 80: Operation timed out
bash-5.0# 

[C]

>>
bash-5.0# curl   nginx.default.svc.clusterset.local:8080
curl: (28) Failed to connect to nginx.default.svc.clusterset.local port 8080: Operation timed out
bash-5.0# curl   nginx.default.svc.clusterset.local:80
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
bash-5.0#

**Comment by sridhargaddam** [comment]
Currently Globlanet controller does not process Service creation/updation events and it only processes delete events. In order to handle this use-case we will have to enhance the code to process update events for Services.

**Comment by dfarrell07** [comment]
CC @vthapar might take this up if/when he has time.

It was discussed if these are related:
https://github.com/submariner-io/lighthouse/pull/899
https://github.com/submariner-io/lighthouse/pull/879

**Comment by sridhargaddam** [comment]
**Some additional notes:**

Submariner Globalnet controller internally creates an additional service with globalIP configured as external_ip. When the original service is updated, the Globalnet controller does not listen on the service updates, so it will not update the internal service, because of this, port update is not propagated to the internal service as we can see below. 

```
[sgaddam@localhost submariner]$ kubectl get svc
NAME                                          TYPE        CLUSTER-IP       EXTERNAL-IP     PORT(S)    AGE
kubernetes                                    ClusterIP   100.65.0.1       <none>          443/TCP    10m
nginx                                         ClusterIP   100.65.37.138    <none>          8081/TCP   7m41s
submariner-lpq6zr4tl4o5qvrv2t7o3l3gawkagast   ClusterIP   100.65.225.203   242.254.1.253   8080/TCP   7m18s
```
