### ISSUE TITLE
Use minimum GITHUB_TOKEN permissions for each job

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1740]
The `GITHUB_TOKEN` used by some GitHub Actions can be configured to [`permissive` or `restricted`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token). We currently use `permissive` as a GitHub Organizational default. We should instead use `restricted` as the GitHub Organizational default and explicitly grant the minimum required permissions to each job/workflow.

> You can use the permissions key in your workflow file to modify permissions for the GITHUB_TOKEN for an entire workflow or for individual jobs. This allows you to configure the minimum required permissions for a workflow or job. When the permissions key is used, all unspecified permissions are set to no access, with the exception of the metadata scope, which always gets read access.

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

Example per-workflow: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-1-passing-the-github_token-as-an-input

Example per-job: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api

Depends on https://github.com/submariner-io/submariner/pull/2042
Depends on https://github.com/submariner-io/submariner/pull/2054
Depends on https://github.com/submariner-io/submariner/issues/1799
Depends on https://github.com/submariner-io/admiral/pull/438
Depends on https://github.com/submariner-io/cloud-prepare/pull/424
Depends on https://github.com/submariner-io/lighthouse/pull/913
Depends on https://github.com/submariner-io/releases/pull/515
Depends on https://github.com/submariner-io/shipyard/pull/994
Depends on https://github.com/submariner-io/subctl/pull/310
Depends on https://github.com/submariner-io/submariner-charts/pull/284
Depends on https://github.com/submariner-io/submariner-operator/pull/2292
Depends on https://github.com/submariner-io/submariner-website/pull/839
Depends on https://github.com/submariner-io/enhancements/pull/140

**Comment by dfarrell07** [comment]
Better docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by dfarrell07** [comment]
It's weird this doesn't fail: https://github.com/submariner-io/lighthouse/pull/821

Maybe the permissions changes don't take effect on PRs to prevent some attacks? Maybe they have to be merged?

**Comment by dfarrell07** [comment]
* https://github.com/submariner-io/lighthouse/pull/821
* https://github.com/submariner-io/lighthouse/pull/858
* https://github.com/submariner-io/lighthouse/pull/861
* https://github.com/submariner-io/submariner/pull/1980
* https://github.com/submariner-io/admiral/pull/405
* https://github.com/submariner-io/cloud-prepare/pull/366
* https://github.com/submariner-io/coastguard/pull/77
* https://github.com/submariner-io/enhancements/pull/131
* https://github.com/submariner-io/get.submariner.io/pull/34
* https://github.com/submariner-io/releases/pull/470
* https://github.com/submariner-io/shipyard/pull/926
* https://github.com/submariner-io/subctl/pull/236
* https://github.com/submariner-io/submariner-charts/pull/261
* https://github.com/submariner-io/submariner-operator/pull/2201
* https://github.com/submariner-io/submariner-website/pull/818

**Comment by nyechiel** [comment]
@dfarrell07 is there anything left for review here?

**Comment by dfarrell07** [comment]
> @dfarrell07 is there anything left for review here?

The periodic markdown link check job's permissions still need tweaking, I'll use `Depends on` to track.

**Comment by dfarrell07** [comment]
Broken link job permissions are sorted out: https://github.com/submariner-io/submariner/issues/2063

**Comment by skitt** [comment]
This has been completed.
