### ISSUE TITLE
In an OCP setup on AWS, the following logs are seen in Gateway pod

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1747]
The tunnels are properly setup, but gateway pod was restarted couple of times (3 times to be more precise) and the logs of previous instance have the following lines.

```
<SNIP>
2022/03/22 11:27:27 FATAL: sending packet: write ip4 0.0.0.0->242.1.255.254: sendto: object is remote
2022/03/22 11:27:28 FATAL: sending packet: write ip4 0.0.0.0->242.1.255.254: sendto: object is remote
2022/03/22 11:27:29 FATAL: sending packet: write ip4 0.0.0.0->242.1.255.254: sendto: object is remote
2022/03/22 11:27:30 FATAL: sending packet: write ip4 0.0.0.0->242.1.255.254: sendto: object is remote
2022/03/22 11:27:31 FATAL: sending packet: write ip4 0.0.0.0->242.1.255.254: sendto: object is remote
F0322 11:27:32.004953       1 libreswan.go:588] Pluto exited: signal: aborted (core dumped)
```

The pod eventually recovers, so its not a blocker/major-issue, but it would be good to understand why the pod is getting restarted couple of times.

subctl version: | v0.12.0-rc1
Submariner version: | v0.12.0
Kubernetes Server version: | v1.23.3+e419edf
Globalnet is enabled in the setup.

[GWlogs-previous.log](https://github.com/submariner-io/submariner/files/8327225/GWlogs-previous.log)

[GWLogs.log](https://github.com/submariner-io/submariner/files/8327233/GWLogs.log)

**Comment by dfarrell07** [comment]
@yboaron was saying on the sync call this may have been fixed as a part of work with the health checker.

**Comment by yboaron** [comment]
I think this issue was addressed by [1] ,
@sridhargaddam , do you think we can close this one?


[1] 
https://github.com/submariner-io/submariner/pull/1908

**Comment by sridhargaddam** [comment]
Yes, we can close it.
