### ISSUE TITLE
Connection shows error when the cluster joins with option "--cable-driver vxlan" in Calico

### ISSUE THREAD

**Issue by lut777** [submariner-io/submariner#1776]
First I tried the connections based on default method, which is IPsec as I was told. In this scenario, everything works well.
But when I tried to use VxLAN mode, the connections is always in "error" status, which is like following:

```
[root@localhost bin]# ./subctl show connections
Cluster "kubernetes"
 ✓ Showing Connections
GATEWAY  CLUSTER   REMOTE IP      NAT  CABLE DRIVER  SUBNETS                       STATUS  RTT avg.
slave    cluster1  192.168.50.99  no   vxlan         12.96.0.0/12, 162.168.0.0/16  error   0s
```

What I have changed is just adding a extra parameter "--cable-driver vxlan" when joining clusters to the broker.

So is it a bug? How could I debug it?

**Comment by sridhargaddam** [comment]
@lut777 please attach the output of `subctl gather ...` from your clusters. Without this info, its hard to understand/debug the problem.

**Comment by lut777** [comment]
Ok. I attach the gather information from two clusters.
[cluster0gather.zip](https://github.com/submariner-io/submariner/files/8458909/cluster0gather.zip)
[cluster1gather.zip](https://github.com/submariner-io/submariner/files/8458910/cluster1gather.zip)

**Comment by nyechiel** [comment]
@sridhargaddam @aswinsuryan did we learn anything from the logs? is this bug still relevant?

**Comment by sridhargaddam** [comment]
From a quick look at the logs I do not see anything obvious apart from the following.

```
E0404 16:02:53.860750       1 vxlan.go:191] Got error: file exists, &{{0 1450 0 vxlan-tunnel  up 0 0 0 <nil>  <nil> 0 <nil>  <nil> unknown 0 0 0 0 0 [] 0 <nil>} 1000 0 <nil> <nil> 0 0 false false false false false false false false false false false 0 0 4500 0 0}
I0404 16:02:53.860922       1 vxlan.go:199] VxLAN interface already exists with same configuration.
I0404 16:02:53.861026       1 vxlan.go:153] Successfully configured rp_filter to loose mode(2) on vxlan-tunnel
```

Which suggests that the node already has a vxlan-tunnel interface with the same configuration (which can happen if the gateway pod is restarted or if there was a previous deployment with the same cable-driver). Apart from this, I dont see any other error from the logs. @aswinsuryan did you find anything?

**Comment by aswinsuryan** [comment]
@sridhargaddam I did not find either. I think it would be better to try a different cable driver after doing a uninstall than trying it in existing setup.

**Comment by dfarrell07** [comment]
It seems like we have some issues with Calico, which isn't something the current devs depoy with often. We're collecting the issues to better see the picture, and are looking for folks to help in better supporting it.

**Comment by sridhargaddam** [comment]
> @sridhargaddam I did not find either. I think it would be better to try a different cable driver after doing a uninstall than trying it in existing setup.

@lut777 can you let us know if you tried this sequence and have any updates?
