### ISSUE TITLE
Stale entries seen in SUBMARINER-LOCALCIDRS ipset

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1778]
Even after running `subctl uninstall ...` and then redeploying the Submariner on the cluster, it was seen that MTU handler IPset chains include some stale entries in SUBMARINER-LOCALCIDRS

```
[root@edge-2 submariner]# ipset list
Name: SUBMARINER-REMOTECIDRS
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 504
References: 2
Number of entries: 2
Members:
242.1.0.0/16
242.0.0.0/16

Name: SUBMARINER-LOCALCIDRS
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 504
References: 2
Number of entries: 2
Members:
242.2.0.0/16
242.1.0.0/16
[root@edge-2 submariner]#
```

The globalCIDR allocated to the cluster was 242.2.0.0/16, but the `SUBMARINER-LOCALCIDRS` chain includes the previous deployment GlobalCIDR which is `242.1.0.0/16`.

Platform:
Microshift with flannel CNI
K8s: v1.21.1
iptables v1.8.7 (nf_tables)
ipset v7.11, protocol version: 7
Submariner: 0.12.0

**Comment by sridhargaddam** [comment]
Output of subctl gather from the cluster: [cluster2-logs.zip](https://github.com/submariner-io/submariner/files/8450776/cluster2-logs.zip)

**Comment by sridhargaddam** [comment]
The above rules are used for tcp-mss-clamping and the stale entry will not create any issue, so its good to fix this issue, but its not a blocker/critical issue.

**Comment by yboaron** [comment]
I managed to reproduce it, seems that we get an error when deleting the first ipset (SUBMARINER-LOCALCIDRS)on uninstall flow [1],  a similar error is reported also in weave project [2]

[1]
`I0426 11:37:58.467787       1 routes_iface.go:265] On GWNode, in updateRoutingRulesForInterClusterSupport ignoring
I0426 11:37:58.474429       1 iptables_iface.go:116] Deleting iptables rule for outgoing traffic: -s 10.1.0.0/16 -d 242.41.0.0/16 -j ACCEPT
I0426 11:37:58.479062       1 iptables_iface.go:122] Deleting iptables rule for incoming traffic: -s 242.41.0.0/16 -d 10.1.0.0/16 -j ACCEPT
I0426 11:37:58.481725       1 mtuhandler.go:185] Flushing iptable entries in "SUBMARINER-POSTROUTING" chain of "mangle" table
I0426 11:37:58.486225       1 mtuhandler.go:192] Deleting iptable entry in "POSTROUTING" chain of "mangle" table
I0426 11:37:58.488275       1 mtuhandler.go:199] Deleting iptable "SUBMARINER-POSTROUTING" chain of "mangle" table
I0426 11:37:58.490568       1 ipset.go:349] Running ipset [destroy SUBMARINER-LOCALCIDRS]
E0426 11:37:58.501197       1 mtuhandler.go:207] Error deleting ipset "SUBMARINER-LOCALCIDRS": error destroying set "SUBMARINER-LOCALCIDRS": exit status 1 (ipset v7.11: Set cannot be destroyed: it is in use by a kernel component
)
I0426 11:37:58.501246       1 ipset.go:349] Running ipset [destroy SUBMARINER-REMOTECIDRS]
`

[2] 

https://github.com/weaveworks/weave/issues/3816
