### ISSUE TITLE
Test Istio Multi-Cluster with Submariner

### ISSUE THREAD

**Issue by srampal** [submariner-io/submariner#1791]
Tracking issue to test and verify whether Istio Multi-Cluster works correctly with Submariner .. specifically whether Istio can work with Multi-Cluster Services implemented using Submariner.  This issue is in addition to and separate from [issue 1685](https://github.com/submariner-io/submariner/issues/1685) which tests Multi-Cluster Ingress with Submariner using Istio's implementation of the K8s Gateway APi.

**Comment by maayanf24** [comment]
Talked on the scrub call and agreed to close. You can re-open if needed
