### ISSUE TITLE
submariner v0.12.0 pod 'submariner-operator' report error 'error building an authorize d RestConfig for the broker'

### ISSUE THREAD

**Issue by wangjun1974** [submariner-io/submariner#1800]
3 clusters
* edge-1 (broker, gateway)
* edge-2 (gateway)
* edge-3 (gateway)

**What happened**:
$ subctl deploy-broker --kubeconfig /root/kubeconfig/edge/edge-1/kubeconfig 
$ subctl join --kubeconfig /root/kubeconfig/edge/edge-1/kubeconfig broker-info.subm --clusterid cluster1 --natt=false
$ subctl join --kubeconfig /root/kubeconfig/edge/edge-2/kubeconfig broker-info.subm --clusterid cluster2 --natt=false

error in pod 'submariner-operator'
```
2022-04-18T01:15:35.001Z ERR ..oller/controller.go:267 ..mariner-controller Reconciler error error="error building an authorize
d RestConfig for the broker: Get \"https://10.66.208.162:6443/api/v1/namespaces/submariner-k8s-broker/secrets/any\": dial tcp 10.66.208.162:6443: i/o timeout"
 name=submariner namespace=submariner-operator reconciler group=submariner.io reconciler kind=Submariner
```

subctl version is 'v0.12.0'
test subctl version 'release-0.10' without this issue.

**What you expected to happen**:
subctl version is 'v0.12.0'
test subctl version 'release-0.10' without this issue.

**How to reproduce it (as minimally and precisely as possible)**:
$ subctl deploy-broker --kubeconfig /root/kubeconfig/edge/edge-1/kubeconfig 
$ subctl join --kubeconfig /root/kubeconfig/edge/edge-1/kubeconfig broker-info.subm --clusterid cluster1 --natt=false
$ subctl join --kubeconfig /root/kubeconfig/edge/edge-2/kubeconfig broker-info.subm --clusterid cluster2 --natt=false

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by skitt** [comment]
Just to be clear: on the same setup, Submariner 0.10 works, but Submariner 0.12 doesn’t; is that right?

“dial tcp 10.66.208.162:6443: i/o timeout” suggests a connectivity problem but if 0.10 works, that suggests something else is failing.

**Comment by wangjun1974** [comment]
> Just to be clear: on the same setup, Submariner 0.10 works, but Submariner 0.12 doesn’t; is that right?
Yes.

**Comment by dfarrell07** [comment]
This seems like it's related to edge-2 not being able to connect to the broker. Could this be a setup issue?
