### ISSUE TITLE
Submariner installation from git

### ISSUE THREAD

**Issue by dirajag1** [submariner-io/submariner#1808]
**What would you like to be added**:
Can you add the steps to deploy submariner on 2 OCP clusters without using subctl ? 
 For example, is there a way to clone the code from git and run some commands to install submariner ?

**Why is this needed**:
As part of our product certification , it is required to keep all images in a private registry . `subctl` is pulling all related images like submariner-route-agent , submariner-gateway  etc from quay.io .
Is there some way to build the images and push them to a private registry and use them  from there ?

**Comment by dfarrell07** [comment]
Sorry we missed this! It sounds to me like the main thing there is being able to override the images you deploy. That should be possible today, see the subctl `--image-override` flag: https://submariner.io/operations/deployment/subctl/#join-flags-images-and-repositories

Note that if this is also an air-gapped deployment, we think that works now but are adding CI. Tracking that here: https://github.com/submariner-io/submariner/issues/1790

**Comment by dfarrell07** [comment]
I think we have all the requested features here, closing. Feel free to open another issue if there's still something you're looking for @dirajag1. Thanks!
