### ISSUE TITLE
Expand e2e datapath testing to cover both client and server directions

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#1841]
**What would you like to be added**:

The current DP e2e testing covers TCP connections validation where in all tests cluster1 acts as a client and cluster 2 as a server.

It makes sense to extend the tests to also check TCP connection with cluster2 as client and cluster1 as server.

**Why is this needed**:
Since SM client/server datapath flows aren't symmetric

**Comment by MaxBab** [comment]
Hi @yboaron 

I can take it.

Do you think all DP tests should be modified to test datapath flows both directions?

**Comment by yboaron** [comment]
> Hi @yboaron
> 
> I can take it.
> 
> Do you think all DP tests should be modified to test datapath flows both directions?

@MaxBab Ideally, we would prefer to run all DP tests in both client/server directions, but I assume we should also take into account the time it takes to run the tests, I guess we should run some of the tests

**Comment by MaxBab** [comment]
@yboaron 
Yes, agree.

Could we choose some tests as a candidate for the change?
Maybe we have some that more critical to get the change?

**Comment by yboaron** [comment]
I assume the DP test from a pod runs on non GW node to a remote pod that runs on non GW node 

@sridhargaddam WDYT ?

**Comment by sridhargaddam** [comment]
Couple of weeks back I pushed a PR to validate the test in the reverse direction and its merged - https://github.com/submariner-io/submariner/pull/2033

**Comment by MaxBab** [comment]
@yboaron  ^^^

**Comment by sridhargaddam** [comment]
@yboaron @MaxBab I think we can mark this issue as closed.

**Comment by yboaron** [comment]
After Sridhar's PR ^^ got merged, we can close this issue
