### ISSUE TITLE
First time deploy - crd not cleaned-up

### ISSUE THREAD

**Issue by eranra** [submariner-io/submariner#185]
What I did 
initial install (1):
"helm install submariner-latest/submariner-k8s-broker --name "submariner-k8s-broker" --namespace "submariner-k8s-broker"
than (2):
`helm delete --purge submariner-k8s-broker`
and again (3):
"helm install submariner-latest/submariner-k8s-broker --name "submariner-k8s-broker" --namespace "submariner-k8s-broker"

and got::

Error: customresourcedefinitions.apiextensions.k8s.io "clusters.submariner.io" already exists

**Comment by dimaunx** [comment]
You need to remove the created CRDs with kubectl delete crd clusters.submariner.io endpoints.submariner.io before reinstalling the  broker or pass the --set crd.create=false to helm installation command.

**Comment by mangelajo** [comment]
thanks for the report @eranra I'm not an expert in helm myself, do you know how to fix that?

**Comment by mangelajo** [comment]
@eranra we are focusing on providing an operator to deploy submariner, and in that case the CRD creation/deletion is handled by the operator lifecycle manager.
