### ISSUE TITLE
Cleanup OVN resources during uninstall

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner#1868]
**What would you like to be added**:
Cleanup all OVN resources during uninstall if OVNKubernetes is the CNI

**Why is this needed**:
During install, networkplugin-syncer and route-agent add some resources to OVN. Need to make sure these are all cleaned up properly during an uninstall.

**Comment by nyechiel** [comment]
Users are going to expect this to be working so this is really something we should try and fix for 0.13 if possible. In any case, we need to provide guidance/docs on how to cleanup an OVN cluster, so if we have this info handy, automating it should not be too complicated.

**Comment by nyechiel** [comment]
This would require a backport to `release-0.13`.

**Comment by nyechiel** [comment]
Verified with 0.13.0-rc1 using `subctl` devel:

```
[nyechiel@nyechiel-workstation openshift-install-linux]$ subctl uninstall
? This will completely uninstall Submariner from the cluster "nyechiel-ovn-a". Are you sure you want to continue? Yes
 ✓ Checking if the connectivity component is installed on cluster "nyechiel-ovn-a" 
 ✓ The connectivity component is installed on cluster "nyechiel-ovn-a"
 ✓ Deleting the Submariner resource - this may take some time 
 ✓ Checking if the broker component is installed on cluster "nyechiel-ovn-a" 
 ✓ The broker component is installed in namespace "submariner-k8s-broker"
 ⚠ Verifying broker namespace "submariner-k8s-broker" is not in use 
 ⚠ Broker namespace "submariner-k8s-broker" appears to be in use by other clusters ([cluster-b]) - keeping the broker components.
 ✓ Deleting the Submariner cluster roles and bindings on cluster "nyechiel-ovn-a" 
 ✓ Deleted the "submariner-diagnose" cluster role and binding
 ✓ Deleted the "submariner-gateway" cluster role and binding
 ✓ Deleted the "submariner-globalnet" cluster role and binding
 ✓ Deleted the "submariner-lighthouse-agent" cluster role and binding
 ✓ Deleted the "submariner-lighthouse-coredns" cluster role and binding
 ✓ Deleted the "submariner-networkplugin-syncer" cluster role and binding
 ✓ Deleted the "submariner-routeagent" cluster role and binding
 ✓ Unlabeling gateway nodes on cluster "nyechiel-ovn-a" 
```

Thanks @aswinsuryan!

**Comment by aswinsuryan** [comment]
These were cleaned up (for future reference)

In RouteAgent
1)Delete all the ports created as a part of ovn submariner -integration
2)Delete the bridges created for submainer
3) Flush the iptable rules added in non-g/w node which routes for intra-cluster traffic
4) Flush the iptable rules in g/w node which includes the clamping rules and the routes for intra-cluster traffic

In N/W plugin syncer

1) Remove submariner-logical router flows
2) Remove submariner-logical ports and router
3)Remove the ports in ovn-router created for submariner and the associated flows
4)Remove the submariner_gateway switch and its ports
5)Remove the  submariner_join switch and its ports

**Comment by sridhargaddam** [comment]
I noticed some stale routes and iptable rules from OVN-RouteAgent handler after running uninstall. Re-opening this issue and will push the corresponding PRs.
