### ISSUE TITLE
First time deploy - permissions 

### ISSUE THREAD

**Issue by eranra** [submariner-io/submariner#187]
I see in the replicaset the following::
(when deployed on minishift as user system:admin)

Events:
  Type     Reason        Age                From                   Message
  ----     ------        ----               ----                   -------
  Warning  FailedCreate  2m (x20 over 21m)  replicaset-controller  Error creating: pods "submariner-6b65665876-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: "ALL": capability may not be added spec.containers[0].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used]

**Comment by eranra** [comment]
(after some google work ... I was able to progress when I executed `oc adm policy add-scc-to-user privileged -n submariner -z submariner-engine`

**Comment by mangelajo** [comment]
Oh, right, for openshift you need to do that.

**Comment by eranra** [comment]
@roytman correct ... closing.
