### ISSUE TITLE
Sometimes gateway object is not updated when using LB mode

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1871]
**What happened**:
When using Loadbalancer mode of Submariner on AWS Cluster (where the public-ip associated with the LB Service changes), it was seen that local endpoint is properly updated with the correct public-ip, however the public-ip in the Gateway object is not updated. Because of this, `subctl show ...` command displays wrong public-ip to the users.

From gateway object:

```
    haStatus: active
    localEndpoint:
      backend: libreswan
      backend_config:
        natt-discovery-port: "4490"
        preferred-server: "true"
        preferred-server-timestamp: "1654881267"
        udp-port: "4500"
        using-loadbalancer: "true"
      cable_name: submariner-cable-sgaddam-aws-spoke1-10-0-129-37
      cluster_id: sgaddam-aws-spoke1
      healthCheckIP: 10.135.0.1
      hostname: ip-10-0-129-37
      nat_enabled: true
      private_ip: 10.0.129.37
      public_ip: 3.128.47.166                          <--- Old public-ip
      subnets:
      - 172.32.0.0/16
      - 10.132.0.0/14
    statusFailure: ""
    version: devel-f55a4d1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
[sgaddam@localhost aws-ocp]$

```
**What you expected to happen**:
Although there is no issue for the actual connection because the local endpoint is properly updated and sync'ed to the Broker, the information displayed to the user as part of gateway object (and subctl show command) could be misleading to the end users.

**Comment by nyechiel** [comment]
As per discussion with Sridhar, this is not affecting the data plane (as local information in the cluster is correct). This is a rare control plane sync race that is probably only relevant for AWS.

**Comment by dfarrell07** [comment]
CC @yboaron @sridhargaddam
