### ISSUE TITLE
Will submariner provide multi arch images for other release version (such as release-0.12) officially?

### ISSUE THREAD

**Issue by jinglina** [submariner-io/submariner#1873]
I need multi arch images for submariner. It can be found only in images tagged devel . I want to known if multi-arch images related submariner (such as gateway, lighthoue-coredns) will be provided in quay.io .

**Comment by skitt** [comment]
We aren’t planning on providing multi-arch images in 0.12; 0.13 is planned for mid-July, and we’ll be releasing 0.13.0-rc0 images today.

**Comment by jinglina** [comment]
Got it. Thanks.
