### ISSUE TITLE
Label node as 'submariner.io/gateway=true' failed on ROSA 

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#1896]
To enable Submariner GW deployment we need to label one or more nodes as 'submariner.io/gateway=true' , 

Label node using [1] command failed on ROSA platform.

To work around this issue I created new node/nodes using 'rosa create machinepool' API [2] .

[1]

$ oc label --overwrite node ip-10-0-171-134.ec2.internal   submariner.io/gateway=true
Error from server (Prevented from accessing Red Hat managed resources. This is an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at[ https://access.redhat.com/support](https://access.redhat.com/support).

To modify node labels or taints, use OCM or the ROSA cli to edit the MachinePool.): admission webhook "regular-user-validation.managed.openshift.io" denied the request: Prevented from accessing Red Hat managed resources. This is an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at[ https://access.redhat.com/support](https://access.redhat.com/support).

To modify node labels or taints, use OCM or the ROSA cli to edit the MachinePool.

[2]
rosa create machinepool --cluster=yb-rosa  --name=sm-gw-mp --replicas=2 --labels='submariner.io/gateway=true'

**Comment by nyechiel** [comment]
I think it would be good to understand how ARO behaves as well.

**Comment by yboaron** [comment]
According to feedback from ARO experts, adding new labels to nodes is possible with CLI [1]  using the 'oc label node ' command 

[1] 
https://docs.microsoft.com/en-us/azure/openshift/tutorial-connect-cluster#connect-using-the-openshift-cli

**Comment by yboaron** [comment]
@nyechiel @sridhargaddam Well, since this is the expected behavior (labeling node isn't allowed ) for ROSA clusters, I think we shouldn't treat it as Submariner bug. Do you think we can close this one (and just document the workaround ) ?

**Comment by sridhargaddam** [comment]
> @nyechiel @sridhargaddam Well, since this is the expected behavior (labeling node isn't allowed ) for ROSA clusters, I think we shouldn't treat it as Submariner bug. Do you think we can close this one (and just document the workaround ) ?

Fine with me.

**Comment by yboaron** [comment]
This is not a Submariner bug (labeling and annotating nodes is blocked on ROSA), in order to allow Submariner gateway deployment a new machinepool (see [1]) should be created.

We should document this step and close this bug.
[1]
rosa create machinepool --cluster=<cluster-name> --name=sm-gw-mp --replicas=2 --labels='submariner.io/gateway=true'
