### ISSUE TITLE
Build with go 1.18, use glangci-lint in 1.17 mode

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1902]
Go 1.17 will become End of Life in August. There's a push in ACM to get all projects building with 1.18. However, some golangci-lint linters don't work with 1.18 yet and would need to be disabled, causing a gap in coverage (see https://github.com/stolostron/backlog/issues/22428). Instead, figure out how to run golangci-lint in 1.17 mode. 

This will also require an update to Prow, see https://github.com/stolostron/backlog/issues/22428.

It seems that both ACM 2.4 and 2.5+ want this, so this will need to be backported to the release-0.12 and release-0.13 branches.

**Comment by skitt** [comment]
To run golangci-lint in 1.17 mode, set `go` to `1.17` in the `run` section; see https://golangci-lint.run/usage/configuration/#run-configuration

**Comment by skitt** [comment]
Note that we’re already building with Go 1.18 upstream, but we’re listing 1.17 at most as our minimal version in `go.mod`, which causes golangci-lint to run in 1.17 mode anyway.

**Comment by dfarrell07** [comment]
Nice, thanks for the details @skitt!

**Comment by dfarrell07** [comment]
I don't think there's actually anything to be done in submariner-io repos for this, closing.
