### ISSUE TITLE
Switch to our Zoom account for upstream calls we want to share on YouTube

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#1927]
Now that we have a CNCF-provided Zoom account for the project, we should use that for upstream calls.

I have the account details, I’ll communicate them in private to whoever takes care of this.

**Comment by nyechiel** [comment]
@dfarrell07 do we still want to do this?

**Comment by dfarrell07** [comment]
This seems to only really provide value for the automation we can set up to post some widely-interesting calls to YouTube, like the tech exchange.

**Comment by dfarrell07** [comment]
Discussing with folks, this seems to have limited potential for reward. If we want to put a tech exchange call on YT we can always do that manually, but they don't happen often.
