### ISSUE TITLE
Log Warning when VxLAN cable-driver is used with NAT

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1928]
**What happened**:
When using VxLAN cable-driver with NAT enabled, we can run into issues in certain environments. Currently Submariner supports VxLAN cable-driver in a no-NAT deployments. 

So, as discussed in the [original issue](https://github.com/submariner-io/submariner/issues/1417#issuecomment-862928685), lets log a warning in the gateway pod (and diagnose?)

**Comment by sridhargaddam** [comment]
CC: @aswinsuryan

**Comment by nyechiel** [comment]
@sridhargaddam @aswinsuryan this seems like an easy change with high value?

**Comment by sridhargaddam** [comment]
> @sridhargaddam @aswinsuryan this seems like an easy change with high value?

Yes, we can add a warning message both in Submariner as well as in diagnose.

**Comment by aswinsuryan** [comment]
I can work on it

**Comment by cyclinder** [comment]
Is anyone working on this? I'm interested in it.

**Comment by nyechiel** [comment]
> Is anyone working on this? I'm interested in it.

Not at the moment. Contribution is welcome! :)
