### ISSUE TITLE
SM deployment (using LB) fails on OCP/AWS when number of gateways set in cloud prepare is > 0 

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#1943]
**What happened**:
A. I deployed OCP on AWS, check [1] for version details
B. Run subctl prepare using [2] command
C. Deploy SM with LoadBalancer service using subctl (0.13) CLI 

SM deployment failed and the root cause was K8S service-controller failed to ensure the SM gateway LB service, with [3] error.

Running 'subctl prepare' with --gateways 0 solved the problem, but we need to find a way how to label more than one node with 'submariner.io/gateway=true' to enable GW HA.

[1] 
$ oc version 
Client Version: 4.8.11
Server Version: 4.10.10
Kubernetes Version: v1.23.5+9ce5071
$ 

[2] 
subctl cloud prepare aws  --ocp-metadata aws-cluster-b/metadata.json

[3] 
```
$ oc describe  svc -n submariner-operator  submariner-gateway 
Name:                     submariner-gateway
Namespace:                submariner-operator
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/aws-load-balancer-type: nlb
Selector:                 app=submariner-gateway,gateway.submariner.io/status=active
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       172.30.25.145
IPs:                      172.30.25.145
Port:                     cable-encaps  4500/UDP
TargetPort:               4500/UDP
NodePort:                 cable-encaps  30531/UDP
Endpoints:                <none>
Port:                     natt-discovery  4490/UDP
TargetPort:               4490/UDP
NodePort:                 natt-discovery  30766/UDP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     31484
Events:
  Type     Reason                  Age                   From                Message
  ----     ------                  ----                  ----                -------
  Normal   EnsuringLoadBalancer    2m11s (x12 over 32m)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  2m10s (x12 over 32m)  service-controller  Error syncing load balancer: failed to ensure load balancer: Multiple tagged security groups found for instance i-0acd2ff8a57ea9b85; ensure only the k8s security group is tagged; the tagged groups were sg-00e5ee55f67f27562(terraform-20220727163351506400000002) sg-0208130199687d637(yboaron-cluster-b-mqv58-submariner-gw-sg)
$
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by mkolesnik** [comment]
Your server is very old, better use later OCP installer. Your `oc` is even older but I don't think that causes any issues here.

As for cloud prepare, it would be useful if you attached the run output so we know what it did.

**Comment by yboaron** [comment]
> Your server is very old, better use later OCP installer. Your `oc` is even older but I don't think that causes any issues here.
> 
> As for cloud prepare, it would be useful if you attached the run output so we know what it did.


OK, just to clarify, deployment fails only when SM is deployed using LoadBalancer.
I don't have the setup available, I'll reproduce it and attach the relevant logs when I have running env.

**Comment by nyechiel** [comment]
@yboaron is this still relevant?

**Comment by yboaron** [comment]
> @yboaron is this still relevant?

Yep, [1] should address this one.
But it isn't in 0.14 scope, right? 

[1] 
https://github.com/submariner-io/cloud-prepare/pull/385

**Comment by yboaron** [comment]
@skitt Does [your PR that updates AWS prepare not to tag Submariner SG as cluster-owned ](https://github.com/submariner-io/cloud-prepare/commit/754d7968acb8c5d6188ca145ba54dd407e765156) addresses also this bug? 

I think it is
