### ISSUE TITLE
exec command: subctl join broker-info.subm got an error message. [No worker node available to label as the gateway]

### ISSUE THREAD

**Issue by Sword-zhj** [submariner-io/submariner#1959]

**Comment by Sword-zhj** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/32220271/184293258-90e965bd-d14f-4d5a-9d51-16006ea5e81e.png">
how can i fix this warning？

**Comment by tpantelis** [comment]
There must be at least [Gateway Engine](https://submariner.io/getting-started/architecture/gateway-engine/) instance running in the cluster. The `Gateway Engine` will run on any node labeled with `submariner.io/gateway=true`. `subctl` tries to find a non-master node (ie one not labeled with `node-role.kubernetes.io/master`). So it seems you only have master nodes in your cluster in which case you can manually label one with `submariner.io/gateway=true`.

**Comment by Sword-zhj** [comment]
> There must be at least [Gateway Engine](https://submariner.io/getting-started/architecture/gateway-engine/) instance running in the cluster. The `Gateway Engine` will run on any node labeled with `submariner.io/gateway=true`. `subctl` tries to find a non-master node (ie one not labeled with `node-role.kubernetes.io/master`). So it seems you only have master nodes in your cluster in which case you can manually label one with `submariner.io/gateway=true`.

thinks very much.

**Comment by Sword-zhj** [comment]
> There must be at least [Gateway Engine](https://submariner.io/getting-started/architecture/gateway-engine/) instance running in the cluster. The `Gateway Engine` will run on any node labeled with `submariner.io/gateway=true`. `subctl` tries to find a non-master node (ie one not labeled with `node-role.kubernetes.io/master`). So it seems you only have master nodes in your cluster in which case you can manually label one with `submariner.io/gateway=true`.

thanks very much.

**Comment by Sword-zhj** [comment]
> There must be at least [Gateway Engine](https://submariner.io/getting-started/architecture/gateway-engine/) instance running in the cluster. The `Gateway Engine` will run on any node labeled with `submariner.io/gateway=true`. `subctl` tries to find a non-master node (ie one not labeled with `node-role.kubernetes.io/master`). So it seems you only have master nodes in your cluster in which case you can manually label one with `submariner.io/gateway=true`.

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/32220271/184371719-024ce32d-2b81-4c41-8271-0d8ee05f3f27.png">
What causes above error？ when i exec the command [subctl show all]. @tpantelis

**Comment by tpantelis** [comment]
> What causes above error？ when i exec the command [subctl show all]. @tpantelis

That means the cluster wasn't joined, specifically the [Submariner](https://github.com/submariner-io/submariner-operator/blob/9bf9b0ba4eb131c2ad8c4c7b9005150cc46d662d/pkg/embeddedyamls/yamls.go#L103) CR doesn't exist.

**Comment by Sword-zhj** [comment]
> > What causes above error？ when i exec the command [subctl show all]. @tpantelis
> 
> That means the cluster wasn't joined, specifically the [Submariner](https://github.com/submariner-io/submariner-operator/blob/9bf9b0ba4eb131c2ad8c4c7b9005150cc46d662d/pkg/embeddedyamls/yamls.go#L103) CR doesn't exist.

thank you very much
