### ISSUE TITLE
use command [subctl diagnose all] to diagnose issues with, each cluster. I got an error

### ISSUE THREAD

**Issue by Sword-zhj** [submariner-io/submariner#1960]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I have two clusters named cluster-001 and cluter-002, two cluster with overlapping CIDRs, and deploy-broker with flag --globalnet in cluster-001.
Show overview of, and diagnose issues in  cluster-001:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/32220271/184603156-06dcfdbc-bf7b-4696-982d-578368c14731.png">
<img width="707" alt="image" src="https://user-images.githubusercontent.com/32220271/184603263-a857311f-e142-4a6a-9753-33e46cafa6c3.png">
<img width="498" alt="image" src="https://user-images.githubusercontent.com/32220271/184603313-27bf2761-85db-42ae-b4f3-d6a2597cf6a9.png">
Show overview of, and diagnose issues in cluster-002:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/32220271/184607321-cd6ecdb7-d717-488a-b008-36b524777155.png">
<img width="836" alt="image" src="https://user-images.githubusercontent.com/32220271/184607630-a586840f-b97a-4784-aaab-46f8156d4380.png">

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by Sword-zhj** [comment]
The cluster is deployed with kube-proxy ipvs mode which Submariner does not support. This means kube-proxy iptable mode is supported？

**Comment by Sword-zhj** [comment]
Why connection to cluster "cluster-002" is not established.

**Comment by sridhargaddam** [comment]
> The cluster is deployed with kube-proxy ipvs mode which Submariner does not support. This means kube-proxy iptable mode is supported？

Yes

**Comment by sridhargaddam** [comment]
> Why connection to cluster "cluster-002" is not established.

Since there are no logs (i.e., output of `subctl gather`) its hard to tell from the limited information. However, one potential reason could be IPVS mode, so you can try with kubeproxy iptables mode and if you still see the issue attach the relevant logs as per the template.

**Comment by Sword-zhj** [comment]
> > The cluster is deployed with kube-proxy ipvs mode which Submariner does not support. This means kube-proxy iptable mode is supported？
> 
> Yes

Does Submariner has plans to support kube-proxy ipvs mode. Kube-proxy ipvs mode is commonly used from Kubernetes v1.11.

**Comment by sridhargaddam** [comment]
> Does Submariner has plans to support kube-proxy ipvs mode. Kube-proxy ipvs mode is commonly used from Kubernetes v1.11.

It on the road-map, but not on the immediate priority list. If you have any links about the adoption of IPVS mode in kube-proxy, please share it.
