### ISSUE TITLE
Can't deploy broker when offline

### ISSUE THREAD

**Issue by 631068264** [submariner-io/submariner#1962]
**What happened**:

subctl deploy-broker --kubeconfig karmada-config --repository private-repo/submariner --version 0.13.0

 ✓ Setting up broker RBAC 
 ✗ Deploying the Submariner operator 
 ✓ Created operator namespace: submariner-operator
 ✓ Created operator service account and role
 ✓ Created submariner service account and role
 ✓ Created lighthouse service account and role
 ✗ Error deploying Submariner operator: error deploying Submariner operator: error awaiting Deployment ready: timed out waiting for the condition

subctl version: v0.13.0

I has pushed all the images to my private repo following https://github.com/submariner-io/submariner/issues/1790

I even don't know how to get more detail log

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
```
Cluster "default"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.19.5+k3s2" is supported

 ⚠ Submariner is not installed

```
- Gather information (use `subctl gather`):
```
Cluster "default"
Gathering information from cluster "default"
 ⚠ Gathering connectivity logs
 ⚠ The Submariner connectivity components are not installed
 ⚠ Gathering connectivity resources
 ⚠ The Submariner connectivity components are not installed
 ⚠ Gathering service-discovery logs
 ⚠ The Submariner service discovery components are not installed
 ⚠ Gathering service-discovery resources
 ⚠ The Submariner service discovery components are not installed
 ✓ Gathering broker logs
 ✓ Gathering broker resources
 ✓ Gathering operator logs
 ✓ Found 0 pods matching label selector "name=submariner-operator"
 ✗ Gathering operator resources
 ✗ Failed to gather submariners: error listing "submariners": the server could not find the requested resource
 ✗ Failed to gather servicediscoveries: error listing "servicediscoveries": the server could not find the requested resource
 ✓ Found 0 deployments by field selector "metadata.name=submariner-operator" in namespace "submariner-operator"
 ✓ Found 0 daemonsets by label selector "app=submariner-gateway" in namespace "submariner-operator"
 ✓ Found 0 daemonsets by label selector "app=submariner-routeagent" in namespace "submariner-operator"
 ✓ Found 0 daemonsets by label selector "app=submariner-globalnet" in namespace "submariner-operator"
 ✓ Found 0 deployments by label selector "app=submariner-networkplugin-syncer" in namespace "submariner-operator"
 ✓ Found 0 deployments by label selector "app=submariner-lighthouse-agent" in namespace "submariner-operator"
 ✓ Found 0 deployments by label selector "app=submariner-lighthouse-coredns" in namespace "submariner-operator"
Files are stored under directory "submariner-20220816014327"
```
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
This is tracked by https://github.com/submariner-io/submariner/issues/1790

**Comment by sridhargaddam** [comment]
@631068264, we would need the logs of submariner-operator to understand the issue. You have attached the output of `subctl gather ...` but if you look at the last line, it stores all the logs in a folder `submariner-20220816014327`. Please tar this folder and attach it for us to analyse the exact error.

**Comment by 631068264** [comment]
@sridhargaddam   I have solved this.   It was my fault .  I mistakenly thought  that  the broker would run a pod  on k8s.  So closed it
