### ISSUE TITLE
can only access the pod on the gateway node

### ISSUE THREAD

**Issue by pengbinbin1** [submariner-io/submariner#1966]
**What happened**:
I have deploy the submariner on my 3 ckuster by subctl ,the version is 0.13.0 . I have export the service on cluster1 ,but when i want to access the export service on cluster2 or cluster3 by the  global IP , I only access it  when the endpoint is round robin to one that is on the gateway node ,otherwise it will fail.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
I think we'd need more information, like the info requested in the issue template, to be able to do much with this.

```
Diagnose information (use subctl diagnose all):
Gather information (use subctl gather):
Cloud provider or hardware configuration:
Install tools:
Others:
```

**Comment by dfarrell07** [comment]
@pengbinbin1 Closing due to lack of feedback, feel free to provide details an re-open.
