### ISSUE TITLE
two on-premises clusters connectivity in clusterset

### ISSUE THREAD

**Issue by jinglina** [submariner-io/submariner#1977]
in a clusterset with on-premises and public clusters included, is it necessary to guarantee they are IP reachable (two on-premises clusters) with public or private ips?  If they are not ip reachable, is it possible to establish connections between clusters across broker cluster?

**Comment by jinglina** [comment]
For example, in clusterset, there are four clusters: broker-cluster, public cluster and two  on-premises(they are not ip reachable using public ip or private ip)。 How the two on-premises clusters can be conencted with each other? If ip reachable is necessary with public or private ip, how to solve this kind of cluster combination? is it necessary doing something using broker cluster ?

**Comment by sridhargaddam** [comment]
You can find various typologies and what is supported and what is not in the following link - https://submariner.io/operations/nat-traversal/

If the two onPrem clusters are not reachable using publicIP or privateIPs, then connections cannot be established between these two clusters. Currently Submariner uses Broker only for exchanging the metadata and not as a transit router, so we cannot do anything via the Broker.
