### ISSUE TITLE
[Question] Comparison with K8s Federation

### ISSUE THREAD

**Issue by ablekh** [submariner-io/submariner#2]
Interesting and certainly useful project. However, I'm wondering about how it compares with related K8s Federation project: https://github.com/kubernetes/federation. Please use this issue to clarify. Thank you!

**Comment by Oats87** [comment]
Submariner can provide the interconnectivity between clusters that are managed/federated using the Federation project.

Federation has support for the concept of using a `FederatedService` that utilizes external IP's, with Submariner you would be able to use the internal cluster IP's to connect your applications together.

Currently, Submariner itself doesn't have any functionality for cross cluster service discovery but this is on the roadmap; it's already possible to get these features by using other service discovery mechanisms (Consul, KubeFed, etc.)

**Comment by ablekh** [comment]
@Oats87 Thank you very much for prompt reply. I look forward to learning more about and trying this project. I suggest that you include a chapter on comparison/integration with K8s Federation in the future documentation. Good luck! BTW, I cannot find an issue I have opened on rancher/rancher repo approx. 1-3 weeks ago (and haven't had any feedback on) - do you, guys, simply delete issues that you don't like?

**Comment by Oats87** [comment]
@ablekh absolutely, thank you for the question!

I can definitely add an entry to the list of "things-to-do" for the integration. I think it may be even better if we can show an example federated application that is run between two clusters connected with Submariner, in addition to the Istio example we are working on.

As for your issue on rancher/rancher, we don't delete any issues; you should be able to trace back your issue via GitHub (especially if you filter by author).

**Comment by ablekh** [comment]
@Oats87 My pleasure. Yes, providing detailed example(s) in docs would be great.

Re: my "lost issue" - Thank you, I definitely tried search/filtering. It turns out that it was not an issue but rather my comment on someone's issue (now Closed), reporting the problem surfaced in my environment. Apologies for the issue-vs.-comment confusion. Unfortunately, I haven't heard from Rancher team on this (even though I have tagged your lead engineer). I would appreciate if you could take a look my "issue" (https://github.com/rancher/rancher/issues/15986#issuecomment-469015564) and help resolve it (directly or routing to appropriate people).

**Comment by mangelajo** [comment]
I added this to the doc sprint, may be something that we can clarify and document on the website.

**Comment by ablekh** [comment]
@mangelajo Have you had a chance to clarify and document this?
