### ISSUE TITLE
REQUEST: New membership request for maxbab

### ISSUE THREAD

**Issue by MaxBab** [submariner-io/submariner#2030]
### GitHub Username
@maxbab

### Requirements
- [x] I have reviewed the contributor roles guidelines (https://submariner.io/community/contributor-roles/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have multiple contributions to Submariner that meet the requirements listed in the community membership guidelines
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dfarrell07 
- @skitt 

### List of contributions to the Submariner project
- https://github.com/submariner-io/subctl/pull/186
- https://github.com/submariner-io/shipyard/pull/755
- https://github.com/submariner-io/shipyard/pull/837

Working on refactoring redundancy tests:
https://github.com/submariner-io/submariner/issues/2013

- https://github.com/submariner-io/shipyard/pull/945
- https://github.com/submariner-io/shipyard/pull/947
- https://github.com/submariner-io/shipyard/pull/946
- https://github.com/submariner-io/shipyard/pull/948
- https://github.com/submariner-io/shipyard/pull/944
- https://github.com/submariner-io/submariner/pull/2014
- https://github.com/submariner-io/submariner/pull/2017
- https://github.com/submariner-io/submariner/pull/2018

**Comment by dfarrell07** [comment]
Looks great!:heavy_check_mark:  Thank you for your contributions @MaxBab!

**Comment by skitt** [comment]
Likewise, I heartily endorse this request.

**Comment by sridhargaddam** [comment]
+1 from me.

**Comment by tpantelis** [comment]
> +1 from me.

and me

**Comment by skitt** [comment]
I’ve invited Maxim to join the Submariner organisation on GH.
