### ISSUE TITLE
Unable to get connectivity between services on a two-cluster scenario in both directions using Calico

### ISSUE THREAD

**Issue by goncalopcarvalho** [submariner-io/submariner#2035]
**What happened**:
I'm unable to get connectivity between services on a two-cluster scenario in both directions. One direction works but not the other.
The tested scenario includes a three-node kubeadm cluster (cluster A) with a public IP using Calico, and a single-node kubeadm cluster (cluster B) with a private IP using Flannel. The submariner broker is running in the three-node cluster and globalnet was enabled. I followed Calico-specific configuration steps by creating an IPPool (243.1.0.0/16) in Cluster A that represents cluster B.

**What you expected to happen**:
Bidirectional connectivity between services running in the two clusters.

After some testing, I was able to reach a service running in cluster B from a service running in cluster A. But I couldn't reach services on cluster A from cluster B. Furthermore, I also noticed that I could only get connectivity in the first scenario (reach cluster B services from A) if the nettest image used for verifications is deployed in the same node of Cluster A where the submariner gateway is. Not sure this is related.
subctl show all that both clusters are connected successfully.
subctl diagnose output in cluster B shows everything works as intended. Nevertheless, in cluster A, the following subctl diagnose test fails (all the others pass):
```
✗ Checking the firewall configuration to determine if VXLAN traffic is allowed
✗ The tcpdump output from the sniffer pod does not contain the expected remote endpoint IP 243.1.0.0. Please check that your firewall configuration allows UDP/4800 traffic.
```
I double-checked that there are no firewall restrictions between clusters A and B nor between the nodes in the three-node cluster (cluster A) as suggested by the subctl diagnose output.

**How to reproduce it (as minimally and precisely as possible)**:

- Two kubeadm clusters using default setup [instructions](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/). Cluster A with three nodes. Cluster B Single Node.
- For cluster A, a default calico setup via [manifests](https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml).
- For cluster B, a default setup via [manifests](https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml).
- Setup of a calico IPPool with for global IP range.
```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: cluster-b
spec:
  cidr: 243.1.0.0/16
  disabled: true
  vxlanMode: Always
```
- Deploy of submariner broker in the cluster A with GlobalNet.
- Join the cluster A to the broker followed by cluster B.
- Check whether cluster A can access a service exported from cluster B, and if cluster B can access a service exported from cluster A.

@sridhargaddam any ideas on what could be the issue?

**Comment by dfarrell07** [comment]
@sridhargaddam is working with this user via Slack, has an understanding of the issue but needs to either access the cluster or make a new one to reproduce and dig more.

**Comment by zcz-1020** [comment]
Hello, is this problem solved?

**Comment by sridhargaddam** [comment]
> Hello, is this problem solved?

Currently I'm a bit busy with some deliverables and could not look into it. If you want to investigate with some pointers, please reach out on slack.

**Comment by nyechiel** [comment]
https://github.com/submariner-io/submariner/issues/2121#issuecomment-1320850903 might be related.

**Comment by ardenwick** [comment]
> Currently I'm a bit busy with some deliverables and could not look into it. If you want to investigate with some pointers, please reach out on slack.

How can I join in Slack?

**Comment by skitt** [comment]
@cangyin https://kubernetes.slack.com/archives/C010RJV694M

**Comment by ardenwick** [comment]
@skitt thks!
