### ISSUE TITLE
e2e test failed between ROSA and AWS 

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#2043]
I deployed Submariner on AWS and ROSA as follows:

AWS - deployed using subctl (v0.13.1), standard deployment (non LB)
ROSA - deployed using subctl (devel , including the SCC fix), with LoadBalancer service
SM deployed successfully on ROSA using only [1] workaround

ROSA cluster details: OC version: 4.11.5  SDN : OVNKubernetes
AWS cluster details :  OC version: 4.11.5  SDN: OpenShiftSDN

One of the TCP connectivity tests across clusters tests failed [2]

The root cause seems to be MTU,  after applying  the mss-clamp iptables rules to fixed size on GW node in ROSA cluster all the tests passed successfully.

[1]
https://github.com/submariner-io/submariner/issues/1896
[2]
[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is not on a
 gateway [It] should have sent the expected data from the pod to the other pod                                                                                                                
github.com/submariner-io/shipyard@v0.13.1/test/e2e/tcp/connectivity.go:71 
 
Ran 24 of 42 Specs in 714.001 seconds 
FAIL! -- 23 Passed | 1 Failed | 0 Pending | 18 Skipped 
[] E2E failed

**Comment by yboaron** [comment]
A similar issue is seen also with GlobalNet , after applying mss clamping [2]  WA on GW node at ROSA cluster all tests are green

[1] 
Summarizing 11 Failures:

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod matching an egress IP namespace selector connects via TCP to the globalIP of a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod matching an egress IP namespace selector connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod matching an egress IP pod selector connects via TCP to the globalIP of a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod matching an egress IP pod selector connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod with HostNetworking connects via TCP to the globalIP of a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod with HostNetworking connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote headless service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote headless service when the pod is on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.13.1/test/e2e/framework/network_pods.go:183

Ran 25 of 42 Specs in 3353.513 seconds
FAIL! -- 14 Passed | 11 Failed | 0 Pending | 17 Skipped
[] E2E failed

subctl version: v0.13.1 


[2]
4# iptables -t mangle -I SUBMARINER-POSTROUTING -m set --match-set SUBMARINER-REMOTECIDRS src -m set --match-set SUBMARINER-LOCALCIDRS  dst -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1200
sh-4.4# iptables -t mangle -I SUBMARINER-POSTROUTING -m set --match-set SUBMARINER-LOCALCIDRS  src -m set --match-set SUBMARINER-REMOTECIDRS  dst -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1200

**Comment by nyechiel** [comment]
@yboaron can you please update this one?

**Comment by yboaron** [comment]
> @yboaron can you please update this one?

-  Seems to be related to MTU (happens in both GN and non GN deployments)
-  Further investigation is needed 
-  Need also to check how to allow mss-clamping workaround based on node's annotation for ROSA clusters (as nodes annotation is blocked in ROSA)

**Comment by yboaron** [comment]
- e2e tests (non GN) between ARO and ROSA seem to be OK (in both directions).
- As per ROSA and AWS case ,  I can see on tcpdump(on ROSA GW node) the ICMP fragmentation needed msg, it's an MTU issue.

**Comment by yboaron** [comment]
After [allow setting particular MSS clamping for non-GN PR](https://github.com/submariner-io/submariner/pull/2087) got merged. 
Annotating the GW  node (submariner.io/tcp-clamp-mss=<desired MSS value>)  on AWS cluster should solve the issue.
