### ISSUE TITLE
NAT discovery always active?

### ISSUE THREAD

**Issue by jeinwag** [submariner-io/submariner#2076]
I've managed to successfully deploy submariner (0.14.0-m2) on two Kubernetes clusters in a private network (clusters joined with -natt=false)

However, when doing failover tests with multiple deployed gateways, the speed of the failover operation seems kind of slow. I noticed that the gateway is still trying to do NAT discovery. Once the the operation has timed out ("NAT discovery for endpoint ... has timed out" in the log), the connection is established immediately. I'm not sure why a) submariner still tries to do NAT discovery and b) why the operation does run into a timeout - UDP packets on port 4490 can flow freely between the nodes.

Any hints?

**Comment by nyechiel** [comment]
@aswinsuryan can you take a look at this issue?

**Comment by sridhargaddam** [comment]
I'll let @aswinsuryan to debug/comment on this issue.

Just thought of sharing one small observation: The NAT discovery might be timing out when trying to connect to the `public_ip` listed in the endpoints (which will fail as both the clusters are behind the same router). If your cluster is only reachable on the private-ips and/or if its in an air-gapped deployment, you can try passing the following flag while joining the cluster to the Broker and this should help.

`--air-gapped` (for more details - https://submariner.io/operations/deployment/subctl/#join)

**Comment by jeinwag** [comment]
Thanks, I'll have a look at the --air-gapped option. Can I just redo the join without having to uninstall first?

I also tried explicitly setting the public address to the same address as the private one via annotations. I can see the NATT packets passing between the servers, but submariner doesn't seem to register them - I always end up running into a timeout.

**Comment by aswinsuryan** [comment]
@jeinwag it is better to do a subctl unistall and do a deploy-broker and join.

**Comment by dfarrell07** [comment]
Closing for now as the conversation seems to have resolved, but feel free to re-open.
