### ISSUE TITLE
Add e2e test to validate FIPS configuration with submariner

### ISSUE THREAD

**Issue by MaxBab** [submariner-io/submariner#2107]
**What would you like to be added**:
When FIPS is enabled on the cluster and submariner deployed with ipsec, the ipsec tunnel should work in FIPS Mode.

**Why is this needed**:
We would like to make sure that submariner detects and uses FIPS configuration.

**Comment by MaxBab** [comment]
Hi @skitt @sridhargaddam @tpantelis 

Do you think anything beside verification of the fips mode in submariner gateway pod ipsec configuration should be tested?

**Comment by MaxBab** [comment]
The way to test that gateway pod is running in FIPS mode.
- Execute the following on the gateway pod:
ipsec pluto --selftest

Look for the "FIPS Mode: YES"

**Comment by skitt** [comment]
I can’t think of anything apart from checking that Libreswan is running in FIPS mode. I wonder if there’s an equivalent for WireGuard...

**Comment by MaxBab** [comment]
I will check that.
Ok, I have something to start working on.
Thanks.

**Comment by MaxBab** [comment]
@skitt 
I found this [link](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_and_managing_networking/assembly_setting-up-a-wireguard-vpn_configuring-and-managing-networking) talking about setting wireguard in rhel and it has the following worning message:

`You can use WireGuard only if the Federal Information Processing Standard (FIPS) mode in RHEL is disabled. `

I'm not sure it's the same in openshift, but my guess, it is.

**Comment by skitt** [comment]
From an upstream perspective that doesn’t matter.

**Comment by MaxBab** [comment]
https://github.com/submariner-io/submariner/pull/2232
https://github.com/submariner-io/submariner/pull/2252

Implemented.
