### ISSUE TITLE
Decide support status of K3s

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#2108]
We have had a number of issues reported for K3s that we don't have devs with the resources or setups to properly investigate. We should decide if we really can support K3s, and if not remove it from our docs to not confuse users.

**Comment by sridhargaddam** [comment]
Related issues:
https://github.com/submariner-io/subctl/issues/444
https://github.com/submariner-io/submariner/issues/1926

**Comment by dfarrell07** [comment]
@skitt pointed out that it would make sense to delete the K3s quickstart guide, as we seem to be misleading people into thinking it's supported when it's currently not.

**Comment by dfarrell07** [comment]
Per discussions with the team, I think we don't have folks with the infra or cycles to support K3s currently. We'd very much like someone from Rancher or who otherwise wants K3s support to adopt that part of the project.

We've already remove K3s docs from the website to not mislead folks.
