### ISSUE TITLE
Submariner for development team

### ISSUE THREAD

**Issue by marciodel** [submariner-io/submariner#211]
Is it possible to use Submariner as a development tool? The idea would be to have local development nodes for developer accessing services the main shared cluster.

Thanks!

**Comment by mangelajo** [comment]
That would be possible, yes. Ideally you would like to setup a public cluster as the broker. And that'd be it.

You also need connectivity via UDP ports 4500 and 500, (or any other set of ports, you can tune that) 

Tell us if you give it a try.
