### ISSUE TITLE
Submariner doesn't work with Calico CNI

### ISSUE THREAD

**Issue by zcz-1020** [submariner-io/submariner#2121]
Recently, I used **calico CNI** to build a k8s cluster on multiple virtual machines and encountered the same problem 【 **https://github.com/submariner-io/submariner/issues/407** 】. In cross-cluster scenarios, only pods on the gateway can communicate with each other. The data plane on non-gateway nodes cannot communicate with each other. I also followed the instructions in **https://submariner.io/operations/deployment/calico/** to create IPPool, but it didn't work, everything is correct when using subctl diagnose command.Traffic can be transmitted from the vx-submariner of other nodes in the cluster to the vx-submariner of the gateway node, but the packet is not sent to the vxlan-tunnel of the gateway node. As a result, a tunnel cannot be established with the remote cluster.

The environment version is as follows:
  k8s: 1.21.0
  calico: 3.21
  submariner: 0.13.0

**Comment by zcz-1020** [comment]
Recently, we spent some time trying to locate the problem. It is found that packet loss occurs on the FORWARD chain of the filter table. The default policy of the FORWARD chain is DROP. Because the request packet does not match any of the rules, the packet is discarded. After the default policy of the Forward chain is changed to ACCEPT or the rules that can be matched by data packets are added, the access is normal.

**Comment by sridhargaddam** [comment]
@zcz-1020 we recently validated Calico with Submariner and noticed that there are some issues when Calico is deployed with IPIP overlay tunnels. But when we changed the Calico configuration to VxLAN overlay tunnels and configured the required Submariner IPPools as documented [here](Calico supports different types of overlay networking. Currently, Submariner is validated only when Calico is deployed with VXLAN encapsulation.), we noticed that everything works fine. Did you deploy Calico with IPIP tunnels or VxLAN tunnels?

**Comment by ii2day** [comment]
> @zcz-1020 we recently validated Calico with Submariner and noticed that there are some issues when Calico is deployed with IPIP overlay tunnels. But when we changed the Calico configuration to VxLAN overlay tunnels and configured the required Submariner IPPools as documented [here](Calico supports different types of overlay networking. Currently, Submariner is validated only when Calico is deployed with VXLAN encapsulation.), we noticed that everything works fine. Did you deploy Calico with IPIP tunnels or VxLAN tunnels?
> 
> @ zcz-1020我们最近使用 Submariner 验证了 Calico，并注意到当 Calico 使用 IPIP 覆盖隧道部署时存在一些问题。但是当我们将 Calico 的配置改为 VxLAN 覆盖隧道并配置所需的 Submariner IPPools 时(Calico 支持不同类型的覆盖网络)。目前，Submariner 只有在 Calico 部署 VXLAN 封装时才能验证。)我们注意到一切都很正常。你是用 IPIP 隧道还是 VxLAN 隧道部署了 Calico？

Hi I have the same problem, I determined that my calico is in vxlan mode, my calico version 3.24.0

**Comment by ii2day** [comment]
> @zcz-1020 we recently validated Calico with Submariner and noticed that there are some issues when Calico is deployed with IPIP overlay tunnels. But when we changed the Calico configuration to VxLAN overlay tunnels and configured the required Submariner IPPools as documented [here](Calico supports different types of overlay networking. Currently, Submariner is validated only when Calico is deployed with VXLAN encapsulation.), we noticed that everything works fine. Did you deploy Calico with IPIP tunnels or VxLAN tunnels?

Hi I have the same problem, I determined that my calico is in vxlan mode, my calico version 3.24.0
my submariner cableDriver is vxlan

**Comment by sridhargaddam** [comment]
> > @zcz-1020 we recently validated Calico with Submariner and noticed that there are some issues when Calico is deployed with IPIP overlay tunnels. But when we changed the Calico configuration to VxLAN overlay tunnels and configured the required Submariner IPPools as documented [here](Calico supports different types of overlay networking. Currently, Submariner is validated only when Calico is deployed with VXLAN encapsulation.), we noticed that everything works fine. Did you deploy Calico with IPIP tunnels or VxLAN tunnels?
> 
> Hi I have the same problem, I determined that my calico is in vxlan mode, my calico version 3.24.0 my submariner cableDriver is vxlan

We enhanced subctl recently to validate the Calico Overlay mode and also the IPPools that Submariner requires. Can you try running `subctl diagnose cni` using the latest devel which you can download as shown below.

```
curl -Ls https://get.submariner.io | VERSION=devel bash
```

**Comment by zcz-1020** [comment]
> 
@sridhargaddam I'm using IPIP mode deployment, but I understand that this has nothing to do with IPIP or VXLAN mode. You can focus on the question I said above.
_**It is found that packet loss occurs on the FORWARD chain of the filter table. The default policy of the FORWARD chain is DROP. Because the request packet does not match any of the rules, the packet is discarded. After the default policy of the Forward chain is changed to ACCEPT or the rules that can be matched by data packets are added, the access is normal.**_

**Comment by zcz-1020** [comment]
@sridhargaddam I have another question. Recently, we are testing the calico BGP mode. We find that the data plane of pods in different clusters is also unreachable. Have you verified this before?

**Comment by sridhargaddam** [comment]
> > 
> 
> @sridhargaddam I'm using IPIP mode deployment, but I understand that this has nothing to do with IPIP or VXLAN mode. You can focus on the question I said above. _**It is found that packet loss occurs on the FORWARD chain of the filter table. The default policy of the FORWARD chain is DROP. Because the request packet does not match any of the rules, the packet is discarded. After the default policy of the Forward chain is changed to ACCEPT or the rules that can be matched by data packets are added, the access is normal.**_

Not sure if the above observation applies to Gateway node or non-Gateway node, but either way when we configure the IPPools for the remote clusters (as documented [here](https://submariner.io/operations/deployment/calico/)), the remote cluster  packets should not be dropped AFAICT. Anyways, currently we do not validate Calico in our CI pipeline and this needs some investigation.

CC: @yboaron JFYI

**Comment by sridhargaddam** [comment]
> @sridhargaddam I have another question. Recently, we are testing the calico BGP mode. We find that the data plane of pods in different clusters is also unreachable. Have you verified this before?

We verified Calico with VxLAN overlay in which BGP is disabled.

**Comment by yboaron** [comment]
@zcz-1020 Can you share the content of Calico's default ippool from your environment?

**Comment by zcz-1020** [comment]
@yboaron Sorry, the environment is gone. My IPPool is configured according to [this](https://submariner.io/operations/deployment/calico/) .  The cidr in the spec in the IPPool is set to the pod_cidr and the service_cidr of the remote cluster.

**Comment by yboaron** [comment]
> @yboaron Sorry, the environment is gone. My IPPool is configured according to [this](https://submariner.io/operations/deployment/calico/) . The cidr in the spec in the IPPool is set to the pod_cidr and the service_cidr of the remote cluster.

I meant to the content of the default ippool (named 'default-ipv4-ippool')  and not the ippools created to allow Submariner functionality with Calico CNI.

In case you have an environment please run (on both clusters):
A.  Update default ippool spec to one of [1] or [2]  
B.  Restart all Submariner submariner-routeagent pods by running [3] command

And then run Submariner connectivity test.

Let us know if you still have issues.

[1]
  ipipMode: Always
  vxlanMode: Never
[2] 
  ipipMode: Never
  vxlanMode: Always
[3]
kubectl delete pod -n submariner-operator -l app=submariner-routeagent

**Comment by leberknecht** [comment]
Maybe a little bit off-topic, but maybe also a little bit on-topic: i have an old gke cluster (i think we started it with 1.13) and im pretty sure we once installed calico manually back then to use `NetworkPolicy` resources. Now its been upgraded over time to 1.24, and the gcloud console UI shows `Calico Kubernetes Network policy | Enabled`

But `subctl diagnose cni` gives
```
 ⚠ Checking Submariner support for the CNI network plugin
 ⚠ Submariner could not detect the CNI network plugin and is using ("generic") plugin. It may or may not work.
 ✓ Trying to detect the Calico ConfigMap 
```
It seems odd that it does find a config-map but cant detect the plugin.. just out of curiosity, what config-map does it look for here?

**Comment by sridhargaddam** [comment]
@leberknecht the Network Plugin discovery code looks for configMap named "calico-config".

For more details, you can see the corresponding code here 
https://github.com/submariner-io/submariner-operator/blob/0a98c9c95d5bfb10d3a7fcb0507f741397160c23/pkg/discovery/network/calico.go#L43

**Comment by sridhargaddam** [comment]
> @leberknecht the Network Plugin discovery code looks for configMap named "calico-config".
> 
> For more details, you can see the corresponding code here https://github.com/submariner-io/submariner-operator/blob/0a98c9c95d5bfb10d3a7fcb0507f741397160c23/pkg/discovery/network/calico.go#L43

Also, we recently enhanced the discovery code for Calico CNI - https://github.com/submariner-io/submariner-operator/pull/2769

**Comment by sridhargaddam** [comment]
@leberknecht did you get a chance to try out the suggestion from @yboaron here - https://github.com/submariner-io/submariner/issues/2121#issuecomment-1455065582

**Comment by ardenwick** [comment]
I encountered the same problem, where cross cluster communication only works on gateway nodes, while non-gateway nodes not.

**Comment by ardenwick** [comment]
> Recently, we spent some time trying to locate the problem. It is found that packet loss occurs on the FORWARD chain of the filter table. The default policy of the FORWARD chain is DROP. Because the request packet does not match any of the rules, the packet is discarded. After the default policy of the Forward chain is changed to ACCEPT or the rules that can be matched by data packets are added, the access is normal.

How do you fixed the iptables rules? Could you detail the operations, thanks !

**Comment by yboaron** [comment]
Starting from release V0.16.0 Submariner automatically creates the necessary Calico IPPools for remote cluster connectivity when the Calico API Server is installed in the cluster and Calico CNI detection also includes searching for calico-node CNI pods when the calico-config map is not detected.

Please try to install Submariner with Calico [1] again using the latest version of Submariner and let us know if you encounter any problem.

I'm going to close this issue.


[1]
https://submariner.io/operations/deployment/calico/

**Comment by lgy1027** [comment]
I encountered the same problem using the latest subctl. How to avoid this?

**Comment by yboaron** [comment]
@lgy1027 ,
A. Did you try the steps described [here](https://github.com/submariner-io/submariner/issues/2121#issuecomment-1455065582) ?
B. Also please share the output of [1] and [2] 


[1] 
**subctl --kubeconfig <kubeconfig_path> diagnose all**

[2] 
**subctl gather --kubeconfig <kubeconfig_path> --dir <directory_to_store_logs>**

**Comment by yboaron** [comment]
I'm going to close this one, @lgy1027's issue tracked in https://github.com/submariner-io/submariner/issues/3110
