### ISSUE TITLE
Some network access is abnormal

### ISSUE THREAD

**Issue by hackersean** [submariner-io/submariner#2128]
**What happened**:
I have a k3s cluster, the first vm vm158 ran the gateway. vm151 is the k3s master.
pod in vm151 can access accross other cluster. but pod in vm158 can't.

**What you expected to happen**:
my cluster_cidr and service_cidr alse  mask 16 ，but in subctl cluster_cidr becomes 24。
```
	'--cluster-cidr' \
	'10.44.0.0/16' \
	'--service-cidr' \
	'10.45.0.0/16' \
```
```
    Discovered network details via Submariner:
        Network plugin:  generic
        Service CIDRs:   [10.45.0.0/16]
        Cluster CIDRs:   [10.44.0.0/24]
```

E1115 08:11:00.806767       1 main.go:115] Error while annotating the node: error annotating node with CNI interface IP: Error retrieving the CNI interface for 10.42.0.0/24: unable to find CNI Interface on the host which has IP from "10.42.0.0/24"

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
@hackersean Thanks for the report, we've seen a lot of K3s bugs recently and are looking for help in better supporting it.

**Comment by dfarrell07** [comment]
We need to decide if K3s is supported, maybe find some folks to contribute to it. https://github.com/submariner-io/submariner/issues/2108
