### ISSUE TITLE
Run the MCS API conformance suite and report results

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#2130]
As part of its progress towards graduating to beta, the MCS API is refining its conformance suite. We should run it against Submariner and report discrepancies, either as issues with Submariner’s conformance itself, or with the conformance tests.

To run the tests, clone https://github.com/kubernetes-sigs/mcs-api/, export `KUBECONFIG1` and `KUBECONFIG2` pointing to two clusters connected using Submariner, and run

    go test e2etest

See https://docs.google.com/document/d/18mk62nOXE_MCSSnb4yJD_8UadtzJrYyJxFwbrgabHe8/edit

**Comment by skitt** [comment]
I’ve looked into this, and opened https://github.com/kubernetes-sigs/mcs-api/issues/23 and https://github.com/kubernetes-sigs/mcs-api/pull/24 upstream, and https://github.com/submariner-io/lighthouse/issues/980 for us, as a result.

**Comment by nyechiel** [comment]
@tpantelis I believe you wanted to take this one?

**Comment by tpantelis** [comment]
> @tpantelis I believe you wanted to take this one?

@skitt already did it a while ago and reported issues. But it looks like there's been [updates](https://github.com/kubernetes-sigs/mcs-api/pull/36/) since then.

**Comment by skitt** [comment]
Yes, there are updates in-progress in the SIG.

**Comment by nyechiel** [comment]
bump
