### ISSUE TITLE
Increase Submariner unit test coverage

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#2174]
We now have easy insight into unit test coverage via SonarCloud. The current UT coverage for the submariner-io/submariner repo is 47.2%. We should strive to improve UT coverage, ideally initially up to at least 70%.

https://sonarcloud.io/summary/overall?id=submariner-io_submariner
https://sonarcloud.io/component_measures?id=submariner-io_submariner&metric=coverage&view=list

**Comment by tpantelis** [comment]
Code coverage is now up to [70%](https://sonarcloud.io/component_measures?metric=coverage&view=list&id=submariner-io_submariner).
