### ISSUE TITLE
Check infrastructure prerequisites as part of `join` operation

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner#2176]
Currently, we check a few things when joining a cluster:

* Minimal K8s version.
* Valid customCoreDNSConfig.
* Overlapping GlobalnetCIDRs when the user explicitly supplies a globalCIDR

Expand `subctl join` to check additional prerequisites from the infrastructure itself, and make sure it supports installing Submariner:

- [ ] Gateway nodes are set-up -  Kube proxy, if there, doesn't run in IPVS mode - as it's currently not supported.
- [ ] The broker is reachable from the cluster.
- [ ] Check if CNI as detected by us is supported (from a list of plugins).
Warn that Submariner might not work if the CNI not detected (but don't fail the operation).
- [ ] Extra checks for:
  - [ ] OVN-K -  Version of nothbound database is supported.
  - [ ] Calico - IP Pools are configured in the cluster to instruct Calico not to perform NAT on the subnets associated with the Pod and Service CIDRs of the remote clusters.
- [ ] Conflicts with existing clusters in the clusterset.
  - [ ] CIDRs should be distinct, unless the clusterset is using globalnet.
- [ ] The necessary ports are open.
  - [ ] On the gateway, when not using Load Balancer, the cable driver port(s).
  - [ ] On the nodes, when not using OVN, the vxlan port.

Optionally add a `--dry-run` flag in order to allow running just the validations, without installing Submariner on the cluster.

To see proposed implementation details, check out https://github.com/submariner-io/enhancements/pull/134/

**Comment by tpantelis** [comment]
Shouldn't this be in the **enhancements** or **subctl** repo?
