### ISSUE TITLE
A PodSecurity violate error is reported in subctl verify (Submariner v0.15.0-m1)

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#2233]
I deployed Submariner on two OCP clusters (4.11.5) on GCP  using subctl (v0.15.0-m1), check [1] for version details,
the PodSecurity violate error [2] is reported when running subctl verify.

Attached below [3] the subctl gather file.

[1] 

$ oc version 
Client Version: 4.12.0-ec.5
Kustomize Version: v4.5.7
Server Version: 4.11.5
Kubernetes Version: v1.24.0+3882f8f
$ subctl version 
subctl version: v0.15.0-m1
$

[2]

` subctl verify --context cluster-a --tocontext cluster-b --only service-discovery,connectivity
Performing the following verifications: service-discovery, connectivity
Running Suite: Submariner E2E suite
===================================
Random Seed: 1672904600
Will run 40 of 44 specs

W0105 09:43:31.042769  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx-demo" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx-demo" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx-demo" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx-demo" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0105 09:43:42.255890  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "netshoot" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "netshoot" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "netshoot" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "netshoot" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
•W0105 09:44:01.714758  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx-demo" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx-demo" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx-demo" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx-demo" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0105 09:44:07.399297  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx-demo" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx-demo" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx-demo" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx-demo" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0105 09:44:18.660389  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "netshoot" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "netshoot" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "netshoot" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "netshoot" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
•W0105 09:44:32.279914  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx-demo" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx-demo" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx-demo" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx-demo" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0105 09:44:38.015424  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "netshoot" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "netshoot" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "netshoot" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "netshoot" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
•W0105 09:44:58.699433  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx-demo" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx-demo" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx-demo" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx-demo" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0105 09:45:09.913430  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "netshoot" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "netshoot" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "netshoot" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "netshoot" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0105 09:45:19.740307  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx-demo" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx-demo" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx-demo" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx-demo" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0105 09:45:29.777402  732594 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx-demo" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx-demo" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx-demo" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx-d
emo" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`

[3]

[submariner-20230105075616.zip](https://github.com/submariner-io/submariner/files/10350377/submariner-20230105075616.zip)

**Comment by nyechiel** [comment]
@tpantelis can you take a look at this?

**Comment by tpantelis** [comment]
@yboaron Do you still have a setup that reproduces the issue?

**Comment by skitt** [comment]
> @yboaron Do you still have a setup that reproduces the issue?

I’ve got one, I can send you the kubeconfigs.

**Comment by tpantelis** [comment]
These warnings are emanating from the service discovery tests where we create various `nginx` and `netshoot` deployments/pods.  These are created in the generated E2E test namespace where we set the `pod-security.kubernetes.io/enforce=privileged` label which **should** avoid these warnings in OCP 4.11.x.

A little background...

Originally we saw these warnings with OCP 4.11 and was addressed by [this PR](https://github.com/submariner-io/subctl/issues/118) which added the `pod-security.kubernetes.io/enforce=privileged` label. 

Then OCP 4.12 came along which added default functionality to attempt to figure out what the `pod-security` mode should be for a namespace (from SCC's etc) and override/ignore an explicit setting. It defaulted to `restricted` whereas in 4.11 it defaulted to `warn`.  [This PR](https://github.com/submariner-io/submariner-operator/issues/2317) addressed that  by specifically setting the `SecurityContext` for nettest pod images.

We then saw another issue with OCP 4.12 which was addressed by [this PR](https://github.com/submariner-io/shipyard/pull/1024) to disable the pod-security label syncing via another label (`security.openshift.io/scc.podSecurityLabelSync`).  

So the question is why is this now popping up again with 4.11... Perhaps something changed in a later 4.11 release such that now it's now ignoring our `pod-security` label setting, doing the label syncing and setting it to `warn`. Note that we don't see the warning with the connectivity tests b/c those pods set a `SecurityContext`.  Similarly setting the `SecurityContext` for the service discovery test pods alleviates the warnings.

**Comment by skitt** [comment]
Note that @yboaron’s tests ran on 4.11, but my environment was running 4.12.

**Comment by nyechiel** [comment]
@manosnoam @MaxBab are you seeing any of this in your recent downstream testing with OCP 4.11/4.12?

**Comment by tpantelis** [comment]
> Note that @yboaron’s tests ran on 4.11, but my environment was running 4.12.

Hmm... I thought yours was 4.11 as well.  With 4.12 the `security.openshift.io/scc.podSecurityLabelSync` label disables the syncing so it keeps our `privileged` setting. But by emitting the warning it's acting as though the level is `warn`, at least according to how it's documented.  Either way they're only warnings and doesn't affect functionality. And as I mentioned setting the `SecurityContext` for the service discovery test pods does alleviate the warnings although, based on the OCP docs and what we're currently doing, we **shouldn't** need to do that even though it's good to reduce privileges if we don't need them.

**Comment by manosnoam** [comment]
> @manosnoam @MaxBab are you seeing any of this in your recent downstream testing with OCP 4.11/4.12?

With Submariner 0.14 on OCP 4.11 and 4.12 we haven't seen podSecurity issues recently, but we did not test Submariner **0.15** yet...

**Comment by tpantelis** [comment]
> With Submariner 0.14 on OCP 4.11 and 4.12 we haven't seen podSecurity issues recently, but we did not test Submariner **0.15** yet...

We've only had one sprint with 0.15 and there weren't any changes in this area.

**Comment by manosnoam** [comment]
Correction on 0.14 d/s tests - I do see podSecurity issue, but just a warning when creating the klusterlet for ACM managed cluster - I don't see it when running subctl E2E.

```
$ oc  apply -f "./acm-osp-nmanos-b2-import.yaml"
namespace/open-cluster-management-agent created
serviceaccount/klusterlet created
clusterrole.rbac.authorization.k8s.io/klusterlet unchanged
clusterrole.rbac.authorization.k8s.io/klusterlet-bootstrap-kubeconfig unchanged
clusterrole.rbac.authorization.k8s.io/open-cluster-management:klusterlet-admin-aggregate-clusterrole unchanged
clusterrolebinding.rbac.authorization.k8s.io/klusterlet unchanged
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false 
(container "klusterlet" must set securityContext.allowPrivilegeEscalation=false), 
unrestricted capabilities 
(container "klusterlet" must set securityContext.capabilities.drop=["ALL"]), 
runAsNonRoot != true (pod or container "klusterlet" must set securityContext.runAsNonRoot=true), seccompProfile 
(pod or container "klusterlet" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

deployment.apps/klusterlet created
secret/bootstrap-hub-kubeconfig created
klusterlet.operator.open-cluster-management.io/klusterlet created
```

**Comment by tpantelis** [comment]
I tried it with subctl 0.14 and I don't see the warnings. The only relevant thing I can think that's changed is the K8s version - we're now building against 1.26.

**Comment by tpantelis** [comment]
The warning is emitted by the [client-go rest](https://github.com/kubernetes/client-go/blob/3e0d99053357a2c37e68b65adbf16437803b1f64/rest/warnings.go#L108) code from data extracted from the HTTP response. 

The warning is also mysteriously popping up with the `subctl diagnose kube-proxy-mode` command and also (at least) one of the connectivity tests. The important thing though is that our pod security settings are working correctly with OCP.  Since we configure the namespaces we create and consequently the contained pods to be privileged, the warnings are extraneous and appear to actually be bogus. We can hook in our own warning handler via [SetDefaultWarningHandler](https://github.com/kubernetes/client-go/blob/3e0d99053357a2c37e68b65adbf16437803b1f64/rest/warnings.go#L46). I propose we use that to suppress the pod security warnings for all `subctl` commands.

**Comment by dfarrell07** [comment]
@tpantelis noted that we don't see this error on 0.14.0, so removed the backport label.
