### ISSUE TITLE
Add a “manual” cable driver

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#2281]
**What would you like to be added**:

A “manual” cable driver, which tracks desired connections but doesn’t do anything to set them up. This could be file-based, _e.g._ in the gateway pod, the desired connections would be written to a file, and established connections would be read from another file.

**Why is this needed**:

This would simplify exploration of new connectivity options between Submariner gateways: it would be possible to manage connections manually from the gateway pods without fighting with the gateway agent.

**Comment by dfarrell07** [comment]
This seems like a good idea for a development tool for creating new cable drivers, but I'm not sure we have plans for creating new cable drivers at the moment. If that changes, this would be a good thing to revisit.
