### ISSUE TITLE
0.12.1 subctl uninstall can not pull pause image,I am in china,can submariner give a parameter to indicate pause image

### ISSUE THREAD

**Issue by 13567436138** [submariner-io/submariner#2286]
**What happened**:
![image](https://user-images.githubusercontent.com/31508490/218958965-1c307731-f84e-4954-8590-2ce777b4d554.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by skitt** [comment]
Since version 0.13.2, `subctl` uses the `nettest` image instead of the `pause` image. Later versions of `subctl` can uninstall earlier Submariner setups, please use 0.13.2 or 0.13.3 instead.
