### ISSUE TITLE
network plugin can not be detected,my netowrk plugin is flannel

### ISSUE THREAD

**Issue by 13567436138** [submariner-io/submariner#2287]
⚠ Checking Submariner support for the CNI network plugin
 ⚠ Submariner could not detect the CNI network plugin and is using ("generic") plugin. It may or may not work.

# Network plugins supported: calico, flannel, kube-router, cilium, kube-ovn
CLUSTER_NETWORK="flannel"
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
```
[root@localhost ~]# subctl diagnose all
Cluster "cluster1"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.23.1" is supported

 ⚠ Checking Submariner support for the CNI network plugin
 ⚠ Submariner could not detect the CNI network plugin and is using ("generic") plugin. It may or may not work.

 ✗ Checking gateway connections
 ✗ There are no gateways detected

 ✓ Checking Submariner pods
 ✓ All Submariner pods are up and running

 ✓ Globalnet deployment detected - checking if globalnet CIDRs overlap
 ✓ Clusters do not have overlapping globalnet CIDRs

 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported

 ✗ Checking the firewall configuration to determine if the metrics port (8080) is allowed 
 ✗ The tcpdump output from the sniffer pod does not contain the client pod HostIP. Please check that your firewall configuration allows TCP/8080 traffic on the "192.168.229.154" node.

 ✗ Checking the firewall configuration to determine if VXLAN traffic is allowed
 ✗ Could not find the local Endpoint in cluster "cluster1"

 ✗ Checking Globalnet configuration
 ✗ Found [0 %!d(string=cluster-egress.submariner.io)] ClusterGlobalEgressIP resources but only the default instance (%!q(MISSING)) is supported
 ✗ Couldn't find the default ClusterGlobalEgressIP resource(["cluster-egress.submariner.io"])

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.
```
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others: subctl 0.12.1

**Comment by yboaron** [comment]
Several fixes [1] related to CNI flannel detection were pushed in recent releases of Subctl (you used Subctl 0.12.1). Could you please test this using the latest Subctl [2]?



[1] 
https://github.com/submariner-io/submariner-operator/pull/2451
https://github.com/submariner-io/submariner-operator/pull/1850

[2] 

https://submariner.io/operations/deployment/subctl/#installing-specific-versions

**Comment by dfarrell07** [comment]
This may have been fixed, as described above. Closing for now, feel free to re-open @13567436138 if this is still an issue with latest subctl.
