### ISSUE TITLE
ci failing to access cluster2

### ISSUE THREAD

**Issue by hunchback** [submariner-io/submariner#229]
@dimaunx kindly assist

Error occurred while ci tests run on PR:
https://github.com/submariner-io/submariner/pull/221

Error log can be found:
https://travis-ci.com/submariner-io/submariner/builds/136954091

**Comment by dimaunx** [comment]
This fails because without kubefed the required kubeconfig files are not set. They are only set if kubefed=true, according to the changes proposed. This means that cluster2 and cluster3 kubectl based commands will fail if kubefed is not used.

**Comment by hunchback** [comment]
Thanks!
