### ISSUE TITLE
gateway can curl resource from another cluster's svc,but pod in hthe cluster can not visit another cluster's svc

### ISSUE THREAD

**Issue by 13567436138** [submariner-io/submariner#2290]
gateway can curl resource from another cluster's svc,but pod in hthe cluster can not visit another cluster's svc

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by skitt** [comment]
Please provide the diagnostic information requested in the bug template; please also provide more details of the behaviour you’re seeing:

* how did you set the clusters up?
* what command(s) did you try running?
* what did you expect to happen?
* what happened instead?

**Comment by 13567436138** [comment]
solved by setting node's hostname
