### ISSUE TITLE
gateway hostport 8080 conflict with node-local-dns hostport 8080

### ISSUE THREAD

**Issue by 13567436138** [submariner-io/submariner#2291]
gateway hostport 8080 conflict with node-local-dns hostport 8080

**What happened**:
gateway hostport 8080 conflict with node-local-dns hostport 8080
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by skitt** [comment]
What version of Submariner are you using?

**Comment by 13567436138** [comment]
0.12.1

**Comment by sridhargaddam** [comment]
Port 8080/8081 are used for metrics and is a known issue with Submariner releases prior to 0.14.
It is addressed in 0.14 release.

Release notes: https://submariner.io/community/releases/#v0140
