### ISSUE TITLE
helm install : remove unused  "broker.globalnet"

### ISSUE THREAD

**Issue by cyclinder** [submariner-io/submariner#2293]
**What happened**:

[docs](https://submariner.io/operations/deployment/helm/) says: If your clusters have overlapping IPs (Cluster/Service CIDRs),   please set:

```shell
        --set broker.globalnet="${GLOBALNET}" \ 
        --set submariner.globalCidr="${GLOBAL_CIDR}" \
```

But I noticed there is no [template file](https://github.com/submariner-io/submariner-charts/blob/devel/submariner-operator/templates/submariner.yaml) that uses this [configurations](https://github.com/submariner-io/submariner-charts/blob/72c6f180ba43ad5684f17a169d889416dedf60d7/submariner-operator/values.yaml#L25). Is the typo or bug here?

**What you expected to happen**:

remove `broker.globalnet` in docs and values.yaml or use it in template files.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
I think this is necessary for Globalnet RBAC. It's used here:

https://github.com/submariner-io/submariner-charts/blob/devel/submariner-operator/templates/rbac.yaml#L293

Global CIDR is used here:

https://github.com/submariner-io/submariner-charts/blob/devel/submariner-k8s-broker/crds/crd.yaml#L42

Feel free to re-open if that's wrong!
