### ISSUE TITLE
Run security analyses periodically on all supported branches

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#2303]
**What would you like to be added**:

We should run security analyses on our dependencies periodically on all supported branches.

**Why is this needed**:

We have good coverage of security issues in our dependencies through dependabot on our main branch, and direct dependency updates on our supported branches. We also have good coverage through CodeQL and Grype on PRs. There’s a step missing in between: because we don’t have periodic analyses on branches other than the main branch, we only find out about issues in our release branches when a PR is opened against them; at worst that happens during the release process, but that’s bad for two reasons — we don’t want to have to handle security bump PRs during a release process, and we don’t want to have to wait for a planned release to handle security issues.

**Comment by skitt** [comment]
I’m opening this in the Submariner project but it applies to all repositories.

**Comment by dfarrell07** [comment]
Cool, so time-triggers for CodeQL and Grype and maybe a step to raise issues if there are failures so we're sure to notice.

**Comment by dfarrell07** [comment]
It's not possible to run GHAs using periodic triggers on non-default branches. We could use a work-around to check out a different branch's code, but that wouldn't allow us to report security issues to the correct branch.

**Comment by dfarrell07** [comment]
https://github.com/orgs/community/discussions/16107
