### ISSUE TITLE
Add CI gate for validating IPV4 Submariner on dual-stack K8S

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#2308]
After adding support for Submariner (IPv4)  on dual-stack networks  [1], it makes sense to cover this case on CI.

[1] 
https://github.com/submariner-io/submariner/pull/2294

**Comment by sridhargaddam** [comment]
Fixed via 
CI job: https://github.com/submariner-io/shipyard/pull/1174
Shipyard support: https://github.com/submariner-io/shipyard/pull/1173
