### ISSUE TITLE
endpoints submariner-cable-subm not found

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#234]
Please see attached log

**Comment by manosnoam** [comment]
[endpoints submariner-cable-subm not found.txt](https://github.com/submariner-io/submariner/files/3908386/endpoints.submariner-cable-subm.not.found.txt)

**Comment by Oats87** [comment]
@manosnoam What is your expected output in this case? Are you sure that you're not trying the connection too quickly? It can take a little bit for the cable to actually be installed, but in this case, it looks like subm-cluster-a never actually pushed it's cluster/endpoint into the broker

**Comment by manosnoam** [comment]
I tried for 30 seconds as well, still no response:

kubconf_a oc exec ${netshoot_pod} -- curl --output /dev/null -m 30
--progress-bar --verbose --head --fail ${nginx_svc_ip_clusterB}
*   Trying 100.96.179.149:80...
* TCP_NODELAY set
* Connection timed out after 30001 milliseconds  #     #    #
#
* Closing connection 0                             #     #    #
#

curl: (28) Connection timed out after 30001 milliseconds
command terminated with exit code 28

It might be related to our NAT or firewall, but this is why I chose to open
ikeport 501 and nattport 4501.

**Comment by Oats87** [comment]
@manosnoam could you provide the logs from the subm-cluster-a submariner-engine?

**Comment by manosnoam** [comment]
Please see the attached log above. 

- submariner-engine pod status on Public cluster A (AWS) shows error from server (BadRequest): 
  "pod  submariner does not have a host assigned"
  Pod does not have any log output.

- submariner-engine pod status on Private cluster B (Openstack) shows:
 "Security Associations (0 up, 0 connecting): none. command terminated with exit code 3"
 Pod log shows: clusters.submariner.io "subm-cluster-b" not found

**Comment by mangelajo** [comment]
@manosnoam  Do you have any node marked as submariner gateway in AWS?

"pod submariner does not have a host assigned"

It could also be that you marked as gateway a master node, instead of a worker node (we have a subctl bug about that offering of master nodes )

**Comment by manosnoam** [comment]
Yes:

kubconf_a  oc get nodes -l "submariner.io/gateway=true"
    NAME                           STATUS   ROLES    AGE   VERSION
    ip-10-0-138-118.ec2.internal   Ready    worker   28h   v1.14.6+c07e432da

**Comment by mangelajo** [comment]
By looking at the logs, it seems like you labeled a node that was master (and not worker) to assign the gateway, that's why the engine does not go up. A later patch was introduced in subctl which prevents this from happening.
