### ISSUE TITLE
Upgrade tests not running on release-0.12 and release-0.13

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#2368]
**What happened**:

Upgrade jobs are not being triggered on the release-0.12 and release-0.13 branches. Examples:

https://github.com/submariner-io/submariner/pull/2367
https://github.com/submariner-io/submariner/pull/2366

They are running on release-0.14 and devel:

https://github.com/submariner-io/submariner/pull/2365
https://github.com/submariner-io/submariner/pull/2349

They are configured to run:

https://github.com/submariner-io/submariner/blob/release-0.13/.github/workflows/upgrade-e2e.yml#L20

The versioned GHA exists:

https://github.com/submariner-io/shipyard/tree/release-0.13/gh-actions/upgrade-e2e

**What you expected to happen**:

Upgrade jobs should be required to pass on all supported branches.

**Comment by skitt** [comment]
We disabled these jobs because the upgrade job doesn’t handle tests to non-devel: https://github.com/submariner-io/submariner/pull/1935

**Comment by dfarrell07** [comment]
Ah well that's obvious in retrospect, thanks.
