### ISSUE TITLE
prep_for_subm.sh to allow user input of security ports

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#240]
(mangelajo note: we could even look into doing this from the operator if possible -if we can get the cloud credentials from openshift., otherwise at least subctl) 
Currently the SubM ports are hard coded (4500 and 500):

https://github.com/submariner-io/submariner/blob/02e8a4fbece5ae88c9cdcf9ad33c27168b591a6e/tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/ec2-resources.tf#L33

https://github.com/submariner-io/submariner/blob/02e8a4fbece5ae88c9cdcf9ad33c27168b591a6e/tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/ec2-resources.tf#L40

**Comment by sridhargaddam** [comment]
This issue is referred to in the Quickstart VSphere/AWS guide on website. Once this issue is resolved, the corresponding section has to be updated accordingly.

**Comment by manosnoam** [comment]
Still relevant (at least as long as we use this script to configure AWS ports, etc.).
