### ISSUE TITLE
Restart of GW pod cause to short DP failure (libreswan cable driver)

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#2529]
- I deployed Submariner (Submariner 0.15, cable driver - libreswan) on two Kind clusters 
- run  pod with nettest image on cluster1 (p1, on non_GW node) and cluster2 (p2, on non_GW node)
- Retrieve the IP address of pod p2
- Kubectl exec into p1 pod on cluster1
-  run 'ping -i .1 <  p2 IP address >'
- Restart GW pod on cluster1 by running the next steps:
   kubectl exec -it  -n submariner-operator  <gw pod name> /bin/sh
   run 'ps -aux ' , the output should be something like [1]
   Kill the pluto process
- Checking the ping output, I can see that connectivity to remote cluster wad down for ~2 seconds , check [2]

[1]
$  ps -aux 
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.4  0.1 742112 49836 ?        Ssl  Jun04   3:31 submariner-gateway -v=2 -alsologtostderr
root          31  0.0  0.0 843036 17304 ?        Sl   Jun04   0:01 /usr/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --nofork
root       10090  0.0  0.0   4464  3604 pts/0    Ss   11:44   0:00 /bin/sh
root       10099  0.0  0.0   7012  1496 pts/0    R+   11:44   0:00 ps -aux

[2]
64 bytes from 10.131.1.16: icmp_seq=147 ttl=60 time=0.231 ms
64 bytes from 10.131.1.16: icmp_seq=148 ttl=60 time=0.229 ms
64 bytes from 10.131.1.16: icmp_seq=149 ttl=60 time=0.264 ms
64 bytes from 10.131.1.16: icmp_seq=150 ttl=60 time=0.221 ms
64 bytes from 10.131.1.16: icmp_seq=151 ttl=60 time=0.293 ms
64 bytes from 10.131.1.16: icmp_seq=171 ttl=60 time=0.238 ms
64 bytes from 10.131.1.16: icmp_seq=172 ttl=60 time=0.244 ms
64 bytes from 10.131.1.16: icmp_seq=173 ttl=60 time=0.327 ms
64 bytes from 10.131.1.16: icmp_seq=174 ttl=60 time=0.234 ms

**Comment by maayanf24** [comment]
@yboaron - can you link the PR here?

**Comment by yboaron** [comment]
> @yboaron - can you link the PR here?

I didn't link the PR because I'm not sure it will completely solve this issue

**Comment by yboaron** [comment]
I will close this issue, with [1] PR datapath downtime in case of GW pod restart was shortened.

[1]
#2543
