### ISSUE TITLE
Submariner components should log their version on startup

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#2548]
**What would you like to be added**:

Each component (each `main.go` file) should log its version on startup, [in the same way as the operator](https://github.com/submariner-io/submariner-operator/blob/8fb881cb70d8ffe7eb04545c7a4071af895e7bb5/main.go#L69) (with a version defined at build-time).

**Why is this needed**:

This will allow deployed versions to be determined precisely.

**Comment by cyclinder** [comment]
I'd like working this, can I have this?

**Comment by skitt** [comment]
You can indeed, thanks @cyclinder!
