### ISSUE TITLE
Refactoring E2E sh to use armada and separate helm/subctl

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#256]
1) Use armada to deploy kind clusters
2) Separate helm and subctl logic to different "sh" libs that we can import from e2e.sh, the functions to setup stuff would have the same name in the helm and subctl versions... 
3) Remove all the conditionals: we can now call setup_broker, install_subm, setup_xxx_gateway  ....

**Comment by dfarrell07** [comment]
Done:

> 1. Separate helm and subctl logic to different "sh" libs that we can import from e2e.sh, the functions to setup stuff would have the same name in the helm and subctl versions...
> 2. Remove all the conditionals: we can now call setup_broker, install_subm, setup_xxx_gateway ....

https://github.com/submariner-io/submariner/pull/273

Broke this out into a different issue:

> 1. Use armada to deploy kind clusters

https://github.com/submariner-io/submariner/issues/291
