### ISSUE TITLE
Initial connection fails randomly, including when we add a cluster

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#257]
There is some "warm up" or "caching" that needs to happen somewhere on the
stack that will make the first connection very slow or fail.

By warming up with test_connection which retries, we force that "caching" to happen
before "E2E", we should investigate the root cause and fix it.

**Comment by sridhargaddam** [comment]
@mangelajo can you share the steps to reproduce this issue. You mentioned that we can simulate it using e2e tests by commenting out something.

**Comment by mangelajo** [comment]
I'm not being able to reproduce with those changes, I wonder if installing with kindnet and not weave-net will trigger it.

**Comment by sridhargaddam** [comment]
I tried reproducing this issue both in KIND based deployment as well as between a Rancher and AWS(OCP) clusters. Sadly, in both the setups, I was not able to reproduce the issue.

For the rancher+AWS(OCP) clusters, I've used subctl commands for connecting the clusters as shown below.
rm ./broker-info.subm
./subctl deploy-broker --kubeconfig auth/kubeconfig --no-dataplane
./subctl join --kubeconfig auth/kubeconfig ./broker-info.subm
./subctl join --kubeconfig auth/rancher-cluster-kubeconfig ./broker-info.subm

Observations1:
1. Let's say that we have two (aka Rancher and AWS) Clusters deployed and running. 
2. The clusters are not connected.
3. We have two PODs, POD1 on Rancher Cluster and POD2 on AWS Cluster.
4. If we try connecting from POD1 to POD2, connectivity fails as expected.
5. Now deploy Submariner on both the Clusters to connect them.
6. Monitor the amount of time it takes for POD1 to talk to POD2. 

I've seen that it usually takes around 8 to 12 secs which IMO is a reasonable time for establishing connectivity between the clusters (a lot of things happen behind the scenes like - a leader is chosen in the cluster, endpoint/cluster CRDs are updated on the Broker, CRDs are then sync'ed on the local clusters from Broker, IPSEC connectivity and routing rules are configured, etc)

Observations2:
1. Let's say that we have two (aka Rancher and AWS) Clusters deployed and running. 
2. We deploy Submariner on both the Clusters to connect them.
3. Deploy POD1 (on Rancher Cluster) and POD2 (on AWS Cluster)
4. Monitor the amount of time it takes for POD1 to talk to POD2. 

I've seen that it takes somewhere between 20 secs to 40 secs for POD1 to talk to POD2. During this period, I've seen that most of the time was spent on downloading and bringing up the POD images.

**Comment by mangelajo** [comment]
@sridhargaddam thanks for looking at the problem close. This is something which was happening to me always at kubecon most of the time. Sometimes thos 8-12 seconds became a timeout. I wonder what's exactly happening during those 8-12 seconds.

May be to validate/investigate we can change the netshoot/nginx test with a "IPSEC ready" test which does not exercise any traffic.

And then let the E2E tests run normally, but without forcing any discoveries on the datapath. Does that change sound ok to verify stability and that "discovery" whatever it is?

@Oats87 , @sridhargaddam  ^ ?

**Comment by sridhargaddam** [comment]
An old issue which AFAIU is no longer reproduced, closing it.
