### ISSUE TITLE
Submariner connectivity lost for 15-20 minutes 

### ISSUE THREAD

**Issue by dirajag1** [submariner-io/submariner#2572]
We have our OCP cluster connected to 2 switches in an MLAG pair .
We upgraded one of the switches and observed that when the switch went for a reboot , submariner connectivity went  down and was degraded for 15-20 minutes . The connectivity was restored after that without any manual intervention. 
Also observed several of the submariner pods had restarted couple of times.
Attaching subctl gather logs for reference  
[must-gather.zip](https://github.com/submariner-io/submariner/files/11851066/must-gather.zip)

**Comment by skitt** [comment]
Which version of Submariner are you running? Your `subctl gather` output says 0.12.0 — is that accurate?

**Comment by dirajag1** [comment]
Yes, 0.12 is the submariner version

**Comment by skitt** [comment]
Are you staying on 0.12.0 for any specific reason?

**Comment by dirajag1** [comment]
We are still on OCP 4.10 , and moving to newer versions of submariner would mean we also upgrade our OCP version .
We will go there , but it may be few months down the line

**Comment by sridhargaddam** [comment]
@dirajag1 It looks like you are using OCP 4.10 with OVN-K CNI. Please note that Submariner is supported with OVNK CNI starting from OCP 4.11+ version as documented here - https://submariner.io/getting-started/architecture/networkplugin-syncer/ovn-kubernetes/

You have two choices.
1. Change the CNI from OVN-K to OpenShift SDN while continuing to use OCP 4.10
2. Move to a newer version of OCP and a more recent version of Submariner.

Personally, I would suggest option 2.

**Comment by dfarrell07** [comment]
Closing because incompatible versions
