### ISSUE TITLE
Error deploying Submariner on a baremetal multi-cloud k8s setup

### ISSUE THREAD

**Issue by Pl4tiNuM** [submariner-io/submariner#2613]
**What happened**:
Hello everyone, I am currently facing some issues while deploying Submariner on my clusters. Specifically, I have set up two baremetal K8S clusters on top some VMs and deployed the Karmada (https://github.com/karmada-io/karmada) multi-cloud system to enable orchestration across the 2 clusters. In order to enable inter-cluster service discovery, I have to also deploy Submariner to connect the networks between the clusters. My clusters are as follows (all nodes only have IPv4 enabled and I use Flannel as CNI in both clusters):
```
# karmada-cp
$ KUBECONFIG=~/.kube/karmada_cp_config kubectl get nodes
NAME                 STATUS   ROLES           AGE   VERSION
nephele-karmada-cp   Ready    control-plane   46d   v1.27.2

# nephele-cloud
$ KUBECONFIG=~/.kube/nephele_cloud_config kubectl get nodes
NAME                   STATUS   ROLES           AGE   VERSION
nephele-cloud-master   Ready    control-plane   48d   v1.27.2
nephele-cloud-w01      Ready    <none>          48d   v1.27.2
nephele-cloud-w02      Ready    <none>          48d   v1.27.2
```

I have deployed the Submariner broker on the `nephele-karmada-cp` node and joined both clusters to it:
```
$ subctl deploy-broker --kubeconfig ~/.kube/karmada_cp_config
$ subctl join --kubeconfig ~/.kube/karmada_cp_config broker-info.subm --clusterid karmada-cp --natt=false
$ subctl join --kubeconfig ~/.kube/nephele_cloud_config broker-info.subm --clusterid nephele-cloud --natt=false
```

After that, all pods are up and running in both clusters:
```
$ KUBECONFIG=~/.kube/karmada_cp_config kubectl get pods -n submariner-operator 
NAME                                             READY   STATUS    RESTARTS       AGE
submariner-gateway-47g8l                         1/1     Running   2 (114s ago)   179m
submariner-lighthouse-agent-657f98676b-bn6vz     1/1     Running   0              179m
submariner-lighthouse-coredns-5c786466dc-886lc   1/1     Running   0              179m
submariner-lighthouse-coredns-5c786466dc-z5rq8   1/1     Running   0              179m
submariner-metrics-proxy-lzft4                   1/1     Running   0              179m
submariner-operator-6bd479d489-lmjc6             1/1     Running   0              3h1m
submariner-routeagent-t5s5d                      1/1     Running   0              179m

$ KUBECONFIG=~/.kube/nephele_cloud_config kubectl get pods -n submariner-operator 
NAME                                            READY   STATUS    RESTARTS        AGE
submariner-gateway-xxs6z                        1/1     Running   3 (2m31s ago)   179m
submariner-lighthouse-agent-89cdc9498-rp42f     1/1     Running   0               179m
submariner-lighthouse-coredns-7c9c99fd7-9v5sf   1/1     Running   0               179m
submariner-lighthouse-coredns-7c9c99fd7-zr8ck   1/1     Running   0               179m
submariner-metrics-proxy-rpbth                  1/1     Running   0               179m
submariner-operator-6bd479d489-5k269            1/1     Running   0               179m
submariner-routeagent-k9dp7                     1/1     Running   0               179m
submariner-routeagent-qgxv2                     1/1     Running   0               179m
submariner-routeagent-x69qn                     1/1     Running   0               179m
```

However, when I run the `nginx` example found here (https://submariner.io/getting-started/quickstart/k3s/#verify-manually) the service is not discovered from the one cluster to another. Also when I check the logs of the gateway pod I get the following error:
```
2023-07-18T10:47:25.705Z ERR ..ne/syncer/syncer.go:234 GWSyncer             Error retrieving driver connections: error waiting for whack to complete: exit status 33
```

**What you expected to happen**:
The inter-cluster service discovery should be working properly.

**How to reproduce it (as minimally and precisely as possible)**:
The steps followed are described above.

**Anything else we need to know?**:
I also have Liqo (https://github.com/liqotech/liqo) deployed on the `nephele-cloud` cluster.

**Environment**:
- Diagnose information (use `subctl diagnose all`):
```
$ KUBECONFIG=~/.kube/karmada_cp_config subctl diagnose all
Cluster "kubernetes"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.27.2" is supported

 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking if gateway metrics are accessible from non-gateway nodes
 ✓ Skipping this check as it's a single node cluster

 ⚠ Checking Submariner support for the CNI network plugin
 ⚠ Submariner could not detect the CNI network plugin and is using ("generic") plugin. It may or may not work.
 ✗ Checking gateway connections
 ✗ There are no active connections on gateway "nephele-karmada-cp"
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
 ✓ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed
 ✓ Skipping this check as it's a single node cluster
 ✓ Globalnet is not installed - skipping

 ✓ Checking if services have been exported properly
 ✓ All services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: v0.15.2


$ KUBECONFIG=~/.kube/nephele_cloud_config subctl diagnose all
Cluster "kubernetes"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.27.2" is supported

 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking if gateway metrics are accessible from non-gateway nodes 
 ✓ The gateway metrics are accessible

 ⚠ Checking Submariner support for the CNI network plugin
 ⚠ Submariner could not detect the CNI network plugin and is using ("generic") plugin. It may or may not work.
 ✗ Checking gateway connections
 ✗ There are no active connections on gateway "nephele-cloud-master"
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
 ✗ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed
 ✗ Unable to obtain a remote endpoint: endpoints.submariner.io "remote Endpoint" not found
 ✓ Globalnet is not installed - skipping

 ✓ Checking if services have been exported properly
 ✓ All services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: v0.15.2
- Gather information (use `subctl gather`):
Outputs attached
[submariner-20230718135329.zip](https://github.com/submariner-io/submariner/files/12081254/submariner-20230718135329.zip)

- Cloud provider or hardware configuration:
Baremetal installation as described above.

**Comment by yboaron** [comment]
From a quick look at the log files, it seems that subnets of Submariner endpoints are overlapping (check [1] , from GW log you attached ), as a result of that Submariner doesn't create the connections between the clusters.

The [2] error in GW pod logs is just a side effect of ^^ .

Can you share the commands (subctl) you used to install Submariner?  did you specify the pod,svc subnets in subctl join command ? 

Also please attach the output of 'subctl show all' from both clusters and subctl gather also from the other cluster.


[1] 
[90m2023-07-18T13:44:47.818Z[0m [1m[31mERR[0m[0m ../datastoresyncer.go:232 DSSyncer             Skip processing the remote endpoint &v1.Endpoint{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"nephele-cloud-submariner-cable-nephele-cloud-147-102-37-180", GenerateName:"", Namespace:"submariner-k8s-broker", SelfLink:"", UID:"78eb3daf-fcae-4585-97a2-4194491bb46b", ResourceVersion:"4599528", Generation:1, CreationTimestamp:time.Date(2023, time.July, 18, 10, 48, 14, 0, time.Local), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"submariner-io/clusterID":"nephele-cloud"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"submariner-gateway", Operation:"Update", APIVersion:"submariner.io/v1", Time:time.Date(2023, time.July, 18, 10, 48, 14, 0, time.Local), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc000939668), Subresource:""}}}, Spec:v1.EndpointSpec{ClusterID:"nephele-cloud", CableName:"submariner-cable-nephele-cloud-147-102-37-180", HealthCheckIP:"10.244.0.0", Hostname:"nephele-cloud-master", Subnets:[]string{"10.96.0.0/12", "10.244.0.0/16"}, PrivateIP:"147.102.37.180", PublicIP:"147.102.37.180", NATEnabled:false, Backend:"libreswan", BackendConfig:map[string]string{"natt-discovery-port":"4490", "preferred-server":"false", "udp-port":"4500"}}} as subnets are overlapping
[90m2023-07-18T13:44:47.819Z[0m [32mINF[0m ../datastoresyncer.go:333 DSSyncer             Creating local submariner Endpoint: types.SubmarinerEndpoint{Spec:v1.EndpointSpec{ClusterID:"karmada-cp", CableName:"submariner-cable-karmada-cp-147-102-37-185", HealthCheckIP:"10.244.0.0", Hostname:"nephele-karmada-cp", Subnets:[]string{"10.96.0.0/12", "10.244.0.0/16"}, PrivateIP:"147.102.37.185", PublicIP:"147.102.37.185", NATEnabled:false, Backend:"libreswan", BackendConfig:map[string]string{"natt-discovery-port":"4490", "preferred-server":"false", "udp-port":"4500"}}} 
[90m2023-07-18T13:44:47.825Z[0m [32mINF[0m ../datastoresyncer.go:105 DSSyncer             Datastore syncer started

[2] 
 Error retrieving driver connections: error waiting for whack to complete: exit status 33

**Comment by Pl4tiNuM** [comment]
Hello and many thanks for your answer :)

> it seems that subnets of Submariner endpoints are overlapping

Yes, I have seen the error you are mentioning about the subnets, about I am not sure how I am supposed to resolve it. By default Flannel uses `10.244.0.0/16` as the `podCIDR`, so, do I have to change this manually on each of my clusters?

> Can you share the commands (subctl) you used to install Submariner?

To deploy Submariner I used the commands mentioned above:
```
$ subctl deploy-broker --kubeconfig ~/.kube/karmada_cp_config
$ subctl join --kubeconfig ~/.kube/karmada_cp_config broker-info.subm --clusterid karmada-cp --natt=false
$ subctl join --kubeconfig ~/.kube/nephele_cloud_config broker-info.subm --clusterid nephele-cloud --natt=false
```

> did you specify the pod,svc subnets in subctl join command ?

I don't think I've met something like this in the docs, so I guess not... Could you redirect me to the relevant instructions?

> Also please attach the output of 'subctl show all' from both clusters

```
# Karmada CP
$ KUBECONFIG=~/.kube/karmada-cp_config subctl show all
Cluster "kubernetes"
 ✓ Detecting broker(s)
NAMESPACE               NAME                COMPONENTS                        GLOBALNET   GLOBALNET CIDR   DEFAULT GLOBALNET SIZE   DEFAULT DOMAINS   
submariner-k8s-broker   submariner-broker   service-discovery, connectivity   no          242.0.0.0/8      65536                                      

 ✗ Showing Connections
 ✗ No connections found

 ✓ Showing Endpoints
CLUSTER      ENDPOINT IP      PUBLIC IP        CABLE DRIVER   TYPE    
karmada-cp   147.102.37.185   147.102.37.185   libreswan      local   

 ✓ Showing Gateways
NODE                 HA STATUS   SUMMARY                                                                                    
nephele-karmada-cp   active      Error retrieving driver connections: error waiting for whack to complete: exit status 33   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  generic
        Service CIDRs:   [10.96.0.0/12]
        Cluster CIDRs:   [10.244.0.0/16]

 ✓ Showing versions
COMPONENT                       REPOSITORY           VERSION   
submariner-gateway              quay.io/submariner   0.15.2    
submariner-routeagent           quay.io/submariner   0.15.2    
submariner-metrics-proxy        quay.io/submariner   0.15.2    
submariner-operator             quay.io/submariner   0.15.2    
submariner-lighthouse-agent     quay.io/submariner   0.15.2    
submariner-lighthouse-coredns   quay.io/submariner   0.15.2    

subctl version: v0.15.2

# Nephele Cloud
KUBECONFIG=~/.kube/nephele_cloud_config subctl show all
Cluster "kubernetes"
 ✓ Detecting broker(s)
 ✓ No brokers found

 ✗ Showing Connections
 ✗ No connections found

 ✓ Showing Endpoints
CLUSTER         ENDPOINT IP      PUBLIC IP        CABLE DRIVER   TYPE    
nephele-cloud   147.102.37.180   147.102.37.180   libreswan      local   

 ✓ Showing Gateways
NODE                   HA STATUS   SUMMARY                                                                                    
nephele-cloud-master   active      Error retrieving driver connections: error waiting for whack to complete: exit status 33   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  generic
        Service CIDRs:   [10.96.0.0/12]
        Cluster CIDRs:   [10.244.0.0/16]

 ✓ Showing versions
COMPONENT                       REPOSITORY           VERSION   
submariner-gateway              quay.io/submariner   0.15.2    
submariner-routeagent           quay.io/submariner   0.15.2    
submariner-metrics-proxy        quay.io/submariner   0.15.2    
submariner-operator             quay.io/submariner   0.15.2    
submariner-lighthouse-agent     quay.io/submariner   0.15.2    
submariner-lighthouse-coredns   quay.io/submariner   0.15.2    

subctl version: v0.15.2

```

> and subctl gather also from the other cluster.

I attach the `gather` results again for both clusters this time

[submariner_gather_karmada-cp.zip](https://github.com/submariner-io/submariner/files/12093215/submariner_gather_karmada-cp.zip)
[submariner_gather_nephele-cloud.zip](https://github.com/submariner-io/submariner/files/12093216/submariner_gather_nephele-cloud.zip)

Thank you!

**Comment by yboaron** [comment]
> so, do I have to change this manually on each of my clusters?


Well, you have two options here, 

- redeploy one of the clusters with non overlapping service and pod CIDRs 
- deploy submariner with GlobalNet [1] , all you need to do to enable GlobalNet is to add '--globalnet'
to **subctl deploy-broker** command, so you should run 

  subctl deploy-broker --kubeconfig ~/.kube/karmada_cp_config  --globalnet


Let me know how it goes 


[1] 
https://submariner.io/getting-started/architecture/globalnet/

**Comment by Pl4tiNuM** [comment]
The GlobalNet option worked perfectly. Thanks for your help :) You may close this issue.
