### ISSUE TITLE
Fail to run submariner with OCP 4.13.9 on AWS 

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/submariner#2673]
**What happened**:
Using `subctl` version 0.16.0-m4
submariner-route-agent are not running - no connection to other cluster.
From logs:
 `Error registering the handlers: Event handler "ovn-hostroutes-handler" failed to initialize: error getting connection handler to connect to OvnDB: error creating NBDB connection: error connecting to ovsdb: failed to connect to unix:/var/run/ovn-ic/ovnnb_db.sock: failed to open connection: dial unix /var/run/ovn-ic/ovnnb_db.sock: connect: connection refused
`
**What you expected to happen**:
all pods will run

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:
[submariner-gather.tar.gz](https://github.com/submariner-io/submariner/files/12537220/submariner-gather.tar.gz)

**Comment by yboaron** [comment]
Hit same issue also on OCP 4.12.28
