### ISSUE TITLE
SUBMARINER-POSTROUTING chain slipped its position in POSTROUTING chain

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#272]
Submariner programs certain IPTable rules to preserve the source-IP of the PODs for cross-cluster communication.
Generally, the local cluster CNI also programs iptable rules and when the destination-IP does not belong to the local cluster, it usually performs MASQ/SNAT.
So, Submariner requires that the iptable rules that its programming has higher precedence over the iptable rules that are programmed by the local Cluster CNI.
In order to do this, Submariner inserts a rule with the target as the SUBMARINER-POSTROUTING chain at the beginning of the POSTROUTING chain as shown below (sample output with Weavenet). 
The necessary iptable rules for cross-cluster communication would now be added to the SUBMARINER-POSTROUTING chain.

Chain POSTROUTING (policy ACCEPT 10 packets, 600 bytes)
num   pkts bytes target     prot opt in     out             source   destination         
**1     5360  329K SUBMARINER-POSTROUTING  all  --  *      * 0.0.0.0/0 0.0.0.0/0**           
2     5513  342K KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0 0.0.0.0/0      
3     5464  339K WEAVE      all  --  *      *              0.0.0.0/0 0.0.0.0/0 

So far we have not seen an issue with this, but on a cluster that uses Calico, the CNI seems to update(/monitor?) the POSTROUTING chain and reinsert (after a certain interval?) its own chain (aka cali-POSTROUTING) at the beginning of the POSTROUTING chain moving the SUBMARINER-POSTROUTING rule lower as shown below. 
Because of this, cross-cluster communication is failing.

Chain POSTROUTING (policy ACCEPT 2 packets, 120 bytes)
num   pkts bytes target     prot opt in     out              source  destination         
1    16254 1039K cali-POSTROUTING  all  --  *      *       0.0.0.0/0 0.0.0.0/0
**2     8537  576K SUBMARINER-POSTROUTING  all  --  *      * 0.0.0.0/0 0.0.0.0/0**           
3    1685K  110M KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0 0.0.0.0/0

We need to identify the reason why SUBMARINER-POSTROUTING rule slipped its position (is it because the local CNI was restarted for some reason or if its because the CNI was monitoring iptable rules and updating them when necessary?) and handle such scenarios in Submariner.

**Comment by sridhargaddam** [comment]
@Oats87 , do you have any idea about the issue?

**Comment by mangelajo** [comment]
We want to figure out how often does this happen. If it's not very often we can just monitor and re-insert our rules. If it happens due to specific events then we may need to look for other solutions.

**Comment by nyechiel** [comment]
@sridhargaddam @mangelajo what are your thoughts about this one? If it's important, let's prioritize to v0.7.

**Comment by sridhargaddam** [comment]
This is a duplicate of https://github.com/submariner-io/submariner/issues/407 and its addressed by creating IPPools in Calico Cluster as documented here - https://github.com/submariner-io/submariner-website/pull/258
