### ISSUE TITLE
Issue while deploying Submariner while connecting clusters

### ISSUE THREAD

**Issue by choudham** [submariner-io/submariner#2745]
**What happened**:
1) Deployed submariner using subctl commands:
2) Deployed broker which created broker-info.subm
3) Used subctl join command to join the cluster A.
4) Copied the same broker-info.subm onto cluster B and executed the subctl join command

**What you expected to happen**:
submariner should be deployed and connectivity should be established between two clusters.

**How to reproduce it (as minimally and precisely as possible)**:
Follows steps 1-4

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- ClusterA
Cluster "cluster-f1qa257"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.22.6" is supported

 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ⚠ Checking the status of all Submariner pods
 ⚠ Pod "submariner-gateway-5q6qw" has restarted 16 times
 ✓ Checking if gateway metrics are accessible from non-gateway nodes 
 ✓ The gateway metrics are accessible

 ✗ Checking Submariner support for the CNI network plugin
 ✗ The detected CNI plugin ("flannel") is not supported by Submariner. Supported plugins: [generic canal-flannel weave-net OpenShiftSDN OVNKubernetes calico kindnet]
 ✗ Checking gateway connections
 ✗ Connection to cluster "ccpcnx" is in progress
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
 ✓ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed 
 ✓ The firewall configuration allows intra-cluster VXLAN traffic
 ✓ Globalnet is not installed - skipping

 ✓ Checking if services have been exported properly
 ✓ All services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: v0.15.2
- Cluster B:
  Cluster "arn:aws:eks:us-west-2:478147420456:cluster/ccpcnx-gravity-default-eks"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.23.17-eks-2d98532" is supported

 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking if gateway metrics are accessible from non-gateway nodes 
 ✓ The gateway metrics are accessible

 ⚠ Checking Submariner support for the CNI network plugin
 ⚠ Submariner could not detect the CNI network plugin and is using ("generic") plugin. It may or may not work.
 ✗ Checking gateway connections
 ✗ Connection to cluster "cluster-f1qa257" is in progress
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
 ✓ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed 
 ✓ The firewall configuration allows intra-cluster VXLAN traffic
 ✓ Globalnet is not installed - skipping

 ✓ Checking if services have been exported properly
 ✓ All services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: v0.15.2
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration: Both clusters are AWS in same AWS account connected via VPC peering.
- Install tools:
- Others:

**Comment by sridhargaddam** [comment]
Thanks for reporting the issue @choudham. Please attach the output directory of `subctl gather...` so that someone from the Submariner team can take a look.

**Comment by choudham** [comment]
[submariner-20231010210117.tar.gz](https://github.com/submariner-io/submariner/files/12871915/submariner-20231010210117.tar.gz) --> Cluster A aka cluster-f1qa257
@sridhargaddam : Please find above the attached output of subctl gather from clusterA .

Cluster B subctl gather output:
[submariner-20231011161346.tar.gz](https://github.com/submariner-io/submariner/files/12872276/submariner-20231011161346.tar.gz) -> Cluster B aka ccpcnx-gravity-default-eks"

**Comment by choudham** [comment]
> Thanks for reporting the issue @choudham. Please attach the output directory of `subctl gather...` so that someone from the Submariner team can take a look.

@sridhargaddam : I have attached the requested output

**Comment by yboaron** [comment]
Hi @choudham , 

Could you please retry deploying Submariner with the latest version (0.16.0) ?

1.  First uninstall Submariner from both clusters , use **subctl uninstall --kubeconfig <kubeconfig_path>** ,  
2. Get latest (0.16.0) subctl version , check [A] for more details  
3. Deploy Submariner using subctl 0.16.0 



[A]
curl -Ls https://get.submariner.io | VERSION=0.16.0 bash
export PATH=~/.local/bin:$PATH

**Comment by dfarrell07** [comment]
This was fixed in 0.16 and it looks like the discussion has stalled, so closing for now (feel free to re-open).
