### ISSUE TITLE
Extend the scope of submariner to cluster-to-non-cluster

### ISSUE THREAD

**Issue by mkimuram** [submariner-io/submariner#275]
Currently, scope of submariner is to achieve connectivity of cluster-to-cluster. This issue is to extend its scope to cluster-to-non-cluster.

Background of this issue is that k8s doesn't provide a fixed egress source IP from a pod when a pod access to outside k8s cluster, in a common way (Please see discussion in https://github.com/kubernetes/enhancements/pull/1105.) So, this could be a problem to achieve the connectivity of cluster-to-non-cluster.
I'm not sure that submariner is the right component to handle this, but as I commented in https://github.com/kubernetes/enhancements/pull/1105#issuecomment-571694606, submariner will help achieve this goal. Therefore, I would like to get submariner community's attentions to it. (At least to consider whether this could also be a submariner's scope or this should be handled in a different project that submariner can collaborate with, etc ..)

**Comment by mangelajo** [comment]
@mkimuram can you explain further or join bit.ly/submariner-dev to share the usecase with us, may be join our periodic meeting on Tuesdays?.

Do you mean that you would be interested in connecting one cluster with a legacy network, or ... a subnet on a cloud VPC to a submariner connected cluster?

**Comment by mkimuram** [comment]
> Do you mean that you would be interested in connecting one cluster with a legacy network, or ... a subnet on a cloud VPC to a submariner connected cluster?

Yes. Both subnets on a cloud VPC and subnets in on-premise are my scope.

> can you explain further or join bit.ly/submariner-dev to share the usecase with us, may be join our periodic meeting on Tuesdays?.

Thank you for your suggestion.
I will join the next meeting to explain more in details.

**Comment by mkimuram** [comment]
I will explain with these slides [k8s-to-non-k8s.pdf](https://github.com/submariner-io/submariner/files/4150527/k8s-to-non-k8s.pdf) .

**Comment by mangelajo** [comment]
Ping @Oats87 this makes sense to me for connecting legacy cloud workloads to submariner / k8s workloads. I propose we model it in terms of submariner.

**Comment by mkimuram** [comment]
@mangelajo @Oats87

Sorry for late update.
I've implemented operator version of this feature as a separated component from submariner itself, [here](https://github.com/mkimuram/k8s-ext-connector).

It is completely rewritten with go and it now has unit tests and e2e tests, so it should be ready for starting discussion on moving it to subproject of submariner. 

Could you check it?
I would like to resume discussions on what will be the next step.

**Comment by Oats87** [comment]
This looks great @mkimuram and @mangelajo there is definitely merit here for this use case, especially given a Submariner-enabled cluster is really just an IPsec (or wireguard) endpoint

**Comment by mangelajo** [comment]
@mkimuram following the upstream conversation, please send a kep-like, updated for submariner into https://groups.google.com/forum/#!topic/submariner-dev/EEyaG5iDg6M so we can discuss and see how to make this possible in submariner.

**Comment by mangelajo** [comment]
@mkimuram do you want to dedicate a big part of next meeting to this? I think we need to help you model things in a way they are more compatible with the submariner design but still you achieve the same functionality.

**Comment by mangelajo** [comment]
@mkimuram we can also setup a one time meeting on a different time if it works better for you

**Comment by mkimuram** [comment]
@mangelajo

> do you want to dedicate a big part of next meeting to this? I think we need to help you model things in a way they are more compatible with the submariner design but still you achieve the same functionality.

Thank you for taking care of this issue.

Actually, the enhancement proposal below is still a draft, but I would appreciate it if you could take time to give me a feedback in the next meeting. 

https://github.com/mkimuram/enhancements-1/blob/non-cluster/20200602-cluster-to-noncluster-connection.md

**Comment by mkimuram** [comment]
Still discussing online.
