### ISSUE TITLE
Gateway fail-over tests: should not fail if more than one labels exist

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#280]
Gateway label is a mandatory step for Submariner, and adding another label is not wrong (can be done by user on existing environment) - so the test should not fail if more than 1 one label exists. It should **only fail if 0 label exists**.

In general, Gateway fail-over tests (like any other test scenario) should not rely on a certain environment setup (in our case, assumes only one gateway label exists), unless it initially takes care of creating that environment before the test (i.e. adding setup and teardown functions to the test scenario).

I suggest to fix this:
https://github.com/submariner-io/submariner/blob/03cb609214c0ee60feb18b05b60b70a70e3ae5a0/test/e2e/redundancy/gateway_failover.go#L16

And add a **BeforeEach** step to list the current number of gateway labels on each cluster
```
clusterAName := framework.TestContext.KubeContexts[framework.ClusterA]
clusterBName := framework.TestContext.KubeContexts[framework.ClusterB]

gatewayNodesClusterA := f.FindNodesByGatewayLabel(framework.ClusterA, true)
gatewayNodesClusterB := f.FindNodesByGatewayLabel(framework.ClusterA, true)
```

In addition, remove this check, as this should be a condition state (Ginkgo _When_ state), not a condition to assert and fail upon:
`Expect(gatewayNodes).To(HaveLen(1), fmt.Sprintf("Expected only one gateway node on %q", clusterName))`

**Comment by tpantelis** [comment]
I think it may make sense to have tests tailored to the persona running the tests. 

For an end-user wanting to verify gateway fail-over in their environment, we could have a test that doesn't assume a specific config and doesn't change the config but adapts to the existing config, ie basically finds and kills the active subm engine pod and verifies connectivity to/from another cluster.

The current tests are really intended for devs/CI to verify gateway fail-over works properly in all possible config scenarios using a test/temporary cluster setup. Each test scenario attempts to modify the config appropriately. In this case I think it makes sense to assume and start with the simplest/default config of one gateway node and one engine replica on entry.

@mangelajo @skitt

**Comment by mangelajo** [comment]
I agree that could be beneficial, but (as we discussed on the last team meeting), we must keep the existing tests too, to make sure all scenarios are always verified on CI, and enhance the documentation so it's well known how to run E2E, and what's expected to be present to do it right.

Also, another thing we may want to do, is add a "diagnostic" tag to all the tests that are safe to be run by operators on their submariner clusters to validate connectivity with diagnostics.

**Comment by mangelajo** [comment]
I'm closing this one in favor of those issues:

https://github.com/submariner-io/submariner/issues/303
https://github.com/submariner-io/submariner/issues/302
