### ISSUE TITLE
submariner-operator crash on re-installation

### ISSUE THREAD

**Issue by ardenwick** [submariner-io/submariner#2872]
**What happened**:
If an existing submariner cluster is re-joined, the submariner-operator crashes

**What you expected to happen**:
No crash.

**How to reproduce it (as minimally and precisely as possible)**:
1. create 2 cluster
2. join them
3. delete the submariner-k8s-broker namespace
4. join them again
5. the 2 submariner-operator's in 2 cluster both crashes, with stack trace followed

**Anything else we need to know?**:
Stack trace:
https://pastebin.com/JwvktdS8

**Environment**:
- Diagnose information (use `subctl diagnose all`):
  - All green
- Gather information (use `subctl gather`):
  isolated network
- Cloud provider or hardware configuration:
  self hosted k8s cluster with Calico CNI
- Others:
  version: 0.16.2

**Comment by tpantelis** [comment]
There was a concurrent map write in `logIfChanged`. We can see that the `ServiceDiscovery` and `Submariner` resources were being deleted concurrently. Those are 2 separate controllers and threads so the timing was just right with both threads writing to the map. The map needs to be synchronized.
