### ISSUE TITLE
Network performance bottleneck

### ISSUE THREAD

**Issue by ardenwick** [submariner-io/submariner#2890]
**What happened**:

There is an **intra** -cluster tunnel `vx-submariner` carrying intra-cluster traffic. While the **inter** -cluster tunnel is used for transmitting data between clusters.

I measured performance of both intra-cluster and inter-cluster tunnels, and found a weird problem for inter-cluster VXLAN tunnels:
1. comparing with the underlying network, the intra-cluster tunnel almost appears to have no performance drop.
2. comparing with the underlying network, the inter-cluster tunnel almost appears to have no performance drop.
3. but network performance between pods running on non-gateway nodes of respective clusters can drop significantly.

Where is the bottleneck?

Inter-Cluster Tunnel | iperf3 Client Pod Runs On | iperf3 Server Pod Runs On | Performance Ratio To Underlying NIC
-- | -- | -- | --
IPsec | non-gateway | non-gateway | 26%
IPsec | gateway | gateway | 36%
IPsec | gateway | non-gateway | 29%
VXLAN | non-gateway | non-gateway | 44%
VXLAN | gateway | gateway | 100%
VXLAN | gateway | non-gateway | 75%

**What you expected to happen**:
No performance drop between pods running on non-gateways nodes, for VXLAN inter-cluster tunnels.

**How to reproduce it (as minimally and precisely as possible)**:
deploy 2 cluster as normal, and test the network performance with iperf3 between pods running on different nodes.

**Comment by ardenwick** [comment]
The network bottleneck between pods running on non-gateway nodes can be vital for DBMS clusters with large volume of daily incremental data.

Suppose the gateway node has a 10Gbit/s NIC, for DBMS servers running on non-gateway nodes, they only **share**  560 MByte/s. This means the whole cluster is only able to transfer 46TB of data per day, which is unacceptable for productional clusters (JFYI, a small to median sized productional ClickHouse cluster can receive more than 40TB of data per day).

Also, submariner is not able to choose an alternative network interface for data exchange, when there're multiple NIC's attached to a node each carrying different type of traffic (e.g. customer data ingestion/query, backup/restore, administrative)

**Comment by yboaron** [comment]
Do you use pod that run on podnetworking or hostnetworking ? 

Submariner inter-cluster traffic is assymetric, egress handled by Submariner and ingress by the CNI.

 So the datapath for pod@non_gwnode_cluster1 to  pod@non_gwnode_cluster2 comprise of the following segments:

A. pod@non_gwnode_cluster1 to GWnode@cluster1 using Submariner intra-cluster VxLAN tunnel
B. Inter-cluster VxLAN/IPSec tunnel
C. CNI handles RX from GWnode@cluster2 to pod@nonGWnode_cluster2

Did you check the network performance between two pods (on different nodes) on the same cluster?

**Comment by ardenwick** [comment]
> Do you use pod that run on podnetworking or hostnetworking ?

No. They all run on POD network.

> egress handled by Submariner and ingress by the CNI.

Is it by the SNAT rule [here](https://github.com/submariner-io/submariner/pull/316/files#diff-67610d80b7a5df309398c299f3e3f4b0d183c040e9a03b55aff7e4a43cb78aa6R55) ?

> Did you check the network performance between two pods (on different nodes) on the same cluster?

I will recheck that and feed back here.

**Comment by yboaron** [comment]
> Is it by the SNAT rule [here](https://github.com/submariner-io/submariner/pull/316/files#diff-67610d80b7a5df309398c299f3e3f4b0d183c040e9a03b55aff7e4a43cb78aa6R55) ?
> 

No, this rule handled egress traffic for hostNetworking to remote clusters case.
You can find more details about submariner datapath arch: [here](https://github.com/submariner-io/submariner/issues/2541#issuecomment-1584438003)

**Comment by ardenwick** [comment]
The network performance between two pods on non-gateways nodes in the same cluster is reported as:

```
tmp-shell11:/app# iperf3 -c 10.244.61.199
Connecting to host 10.244.61.199, port 5201
[  5] local 10.244.137.211 port 57432 connected to 10.244.61.199 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  85.3 MBytes   715 Mbits/sec   20    337 KBytes
[  5]   1.00-2.00   sec   105 MBytes   881 Mbits/sec   28    452 KBytes
[  5]   2.00-3.01   sec   104 MBytes   862 Mbits/sec    2    530 KBytes
[  5]   3.01-4.00   sec   101 MBytes   863 Mbits/sec    0    609 KBytes
[  5]   4.00-5.00   sec   105 MBytes   881 Mbits/sec  166    284 KBytes
[  5]   5.00-6.00   sec   105 MBytes   881 Mbits/sec    2    380 KBytes
[  5]   6.00-7.01   sec  99.4 MBytes   823 Mbits/sec   11    523 KBytes
[  5]   7.01-8.00   sec  99.0 MBytes   841 Mbits/sec    0    588 KBytes
[  5]   8.00-9.00   sec   100 MBytes   841 Mbits/sec    0    609 KBytes
[  5]   9.00-10.00  sec   104 MBytes   875 Mbits/sec  147    486 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1009 MBytes   846 Mbits/sec  376             sender
[  5]   0.00-10.00  sec  1007 MBytes   845 Mbits/sec                  receiver
```
Which gives about 82% of the underlying 1Gbit/s NIC's capability. PODs on gateway nodes or non-gateway nodes behaves the same.

**Comment by ardenwick** [comment]
> > Is it by the SNAT rule [here](https://github.com/submariner-io/submariner/pull/316/files#diff-67610d80b7a5df309398c299f3e3f4b0d183c040e9a03b55aff7e4a43cb78aa6R55) ?
> 
> No, this rule handled egress traffic for hostNetworking to remote clusters case. You can find more details about submariner datapath arch: [here](https://github.com/submariner-io/submariner/issues/2541#issuecomment-1584438003)

A bit off topic. Why the vx-submariner interface of gateway node responds to `ping` requests from non-gateway nodes, e.g. from non-gateway nodes (host machine network) run `ping 240.x.x.x`, where `240.x.x.x` is the IP of `vx-submariner` interface on gateway.

But vx-submariner interface of non-gateway nodes do not respond to `ping` requests from gateway nodes. Which I would mistakenly think it be kind of 'assymetric'. Can you explain a bit for me, thanks!

**Comment by yboaron** [comment]
> A bit off topic. Why the vx-submariner interface of gateway node responds to `ping` requests from non-gateway nodes, e.g. from non-gateway nodes (host machine network) run `ping 240.x.x.x`, where `240.x.x.x` is the IP of `vx-submariner` interface on gateway.

Could it be that some infra SG is blocking the traffic?

**Comment by ardenwick** [comment]
> Could it be that some infra SG is blocking the traffic?

What is SG ?

**Comment by yboaron** [comment]
> What is SG ?

hoo, sorry. I meant to Security Group

**Comment by dfarrell07** [comment]
Just wanted to update, we've been doing quite a lot of performance testing and making improvements.

We'll have to figure out the best way to share results when they are done.
