### ISSUE TITLE
REQUEST: New committer rights request for dfarrell07

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#2900]
### GitHub Username
@dfarrell07

### Code you are requesting Committer rights for
All the files required to make a release.

releases/releases/*
admiral/go.mod
admiral/go.sum
cloud-prepare/go.mod
cloud-prepare/go.sum
lighthouse/go.mod
lighthouse/go.sum
lighthouse/coredns/go.mod
lighthouse/coredns/go.sum
submariner/go.mod
submariner/go.sum
submariner-operator/api/v1alpha1/versions.go
submariner-operator/go.mod
submariner-operator/go.sum
subctl/scripts/test/system.sh
subctl/go.mod
subctl/go.sum
submariner-charts/Makefile

### Requirements
- [x] I have reviewed the contributor roles guidelines (https://submariner.io/community/contributor-roles/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have been actively contributing to Submariner for at least 3 months
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tpantelis
- @skitt

### List of required reviews to Submariner project PRs
- At least 20 PRs to the relevant codebase that you reviewed, and at least 5 for which you were the primary reviewer
  - https://github.com/submariner-io/releases/pulls?q=is%3Apr+reviewed-by%3Adfarrell07+-author%3Adfarrell07

**Comment by tpantelis** [comment]
+1

Let's use this to also add @aswinsuryan and @maayanf24. I pushed https://github.com/submariner-io/submariner/pull/2899 to start it off.

First we need to get the "_Add vthapar as code owner_" PRs merged in each repo to avoid conflicts. Just need another approver.

**Comment by skitt** [comment]
+1 from me too, for all three.

**Comment by dfarrell07** [comment]
We could add @yboaron too?

**Comment by tpantelis** [comment]
> We could add @yboaron too?

+1

**Comment by skitt** [comment]
+1 for @yboaron too!

**Comment by dfarrell07** [comment]
I think all the PRs and backports have been merged. Thanks all!
