### ISSUE TITLE
OKD onpremise cluster stuck on 'Conecting'

### ISSUE THREAD

**Issue by mathgonzlez** [submariner-io/submariner#2901]
**What happened**:
I deploy submariner in a 2 private cloud cluster in my home, i use this command for join to broker
subctl join --kubeconfig #CONFIG broker-info.subm --clusterid NAME --natt=false --force-udp-encaps --air-gapped

the --air-gapped is used only in the last attempt because i read that is for use only private IP (my clusters have the same public and i dont open ports)

I try with this join commands too:
subctl join --kubeconfig #CONFIG broker-info.subm --clusterid NAME --natt=false
subctl join --kubeconfig #CONFIG broker-info.subm --clusterid NAME --natt=false --force-udp-encaps

But everytime i deploy the conections stuck on 'conecting'. Could you please tell me if something wrong with my join command for my particular environment? or maybe i forgot something?. 
The others day i deployed sumbariner in a mixed env with azure and RHV and works flawessly out of the box, but in my environment i cant reach the conected status.

Thanks

**What you expected to happen**:
My 2 clusters reach conected status

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy 2 OKD clusters on premise (behing the same public IP)
- try to connect with submariner

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
subctl diagnose all
Cluster "okd-osp"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.27.1-3351+b49f9d1356bca4-dirty" is supported

 ✓ Non-Globalnet deployment detected - checking that cluster CIDRs do not overlap
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking that gateway metrics are accessible from non-gateway nodes

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("OpenShiftSDN") is supported
 ✗ Checking gateway connections
 ✗ Connection to cluster "ovirt" is in progress
 ✓ Checking Submariner support for the kube-proxy mode
 ✓ The kube-proxy mode is supported
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic

 ✓ Checking that services have been exported properly

Cluster "osp"
 ✗ Error building the cluster.Info for the default configuration: error retrieving Submariner: failed to get API group resources: unable to retrieve the complete list of server APIs: submariner.io/v1alpha1: Get "http://localhost:8080/apis/submariner.io/v1alpha1": dial tcp [::1]:8080: connect: connection refused
Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: v0.16.3

- Gather information (use `subctl gather`):
[submariner-20240206032036.tar.gz](https://github.com/submariner-io/submariner/files/14174370/submariner-20240206032036.tar.gz)
[submariner-20240206130615.tar.gz](https://github.com/submariner-io/submariner/files/14179933/submariner-20240206130615.tar.gz)

- Cloud provider or hardware configuration:
okd 4.13 on RHV 4.4
okd4.14 on Openstack Bobcat

- Install tools:
subctl

- Others:
I run the cloud config for openstack environment that create and assign security group for GW node. I have a fortinet with all ports open for this clusters

**Comment by yboaron** [comment]
Hi @mathgonzlez , thanks for reaching out.

Could you please upload subctl gather (subctl gather --kubeconfig <kubeconfig_file>) logs for both clusters?

**Comment by mathgonzlez** [comment]
> Hi @mathgonzlez , thanks for reaching out.
> 
> Could you please upload subctl gather (subctl gather --kubeconfig <kubeconfig_file>) logs for both clusters?

Hi yboaron, thanks for reply!

i recently added to the original post.

Thanks

**Comment by yboaron** [comment]
From gw pod (private IP= 192.168.30.16) logs [1]  at okd-ovirt , it seems that GW pod can't communicate with other gw using private IP (192.168.60.83) and public IP  (181.117.10.119) on udp port 4490,
while the other GW can connect using private IP on this port.

Could it be that ports needed for Submariner inter-cluster traffic (like udp port 4500) are blocked on okd-osp?




[1]
`[REQUEST_NUMBER: 0x467e3fb7e6f929eb, SENDER: "submariner-cable-ovirt-192-168-30-16", RECEIVER: "submariner-cable-osp-192-168-60-83", USING_SRC: 192.168.30.16:4490, USING_DST: 192.168.60.83:4490
[90m2024-02-06T03:17:22.689Z[0m [33mDBG[0m ..ery/request_send.go:115 NAT                  Sending request - REQUEST_NUMBER: 0x467e3fb7e6f929ec, SENDER: "submariner-cable-ovirt-192-168-30-16", RECEIVER: "submariner-cable-osp-192-168-60-83", USING_SRC: 192.168.30.16:4490, USING_DST: 181.117.10.119:4490
[90m2024-02-06T03:17:24.690Z[0m [31mWRN[0m ..ery/natdiscovery.go:184 NAT                  NAT discovery for endpoint "submariner-cable-osp-192-168-60-83" has timed out
[90m2024-02-06T03:17:24.690Z[0m [33mDBG[0m ../remote_endpoint.go:128 NAT                  using NAT legacy settings for endpoint "submariner-cable-osp-192-168-60-83", using private IP "192.168.60.83"
`

[2]
`NAT                  Sending request - REQUEST_NUMBER: 0x781f8e5fceff55be, SENDER: "submariner-cable-osp-192-168-60-83", RECEIVER: "submariner-cable-ovirt-192-168-30-16", USING_SRC: 192.168.60.83:4490, USING_DST: 192.168.30.16:4490
[90m2024-02-06T03:18:29.184Z[0m [33mDBG[0m ..y/response_handle.go:31 NAT                  Received response from 192.168.30.16:4490 - REQUEST_NUMBER: 0x781f8e5fceff55be, RESPONSE: NAT_DETECTED, SENDER: "submariner-cable-ovirt-192-168-30-16", RECEIVER: "submariner-cable-osp-192-168-60-83"`

**Comment by mathgonzlez** [comment]
> From gw pod (private IP= 192.168.30.16) logs [1] at okd-ovirt , it seems that GW pod can't communicate with other gw using private IP (192.168.60.83) and public IP (181.117.10.119) on udp port 4490, while the other GW can connect using private IP on this port.
> 
> Could it be that ports needed for Submariner inter-cluster traffic (like udp port 4500) are blocked on okd-osp?
> 
> [1] `�[REQUEST_NUMBER: 0x467e3fb7e6f929eb, SENDER: "submariner-cable-ovirt-192-168-30-16", RECEIVER: "submariner-cable-osp-192-168-60-83", USING_SRC: 192.168.30.16:4490, USING_DST: 192.168.60.83:4490 �[90m2024-02-06T03:17:22.689Z�[0m �[33mDBG�[0m ..ery/request_send.go:115 NAT Sending request - REQUEST_NUMBER: 0x467e3fb7e6f929ec, SENDER: "submariner-cable-ovirt-192-168-30-16", RECEIVER: "submariner-cable-osp-192-168-60-83", USING_SRC: 192.168.30.16:4490, USING_DST: 181.117.10.119:4490 �[90m2024-02-06T03:17:24.690Z�[0m �[31mWRN�[0m ..ery/natdiscovery.go:184 NAT NAT discovery for endpoint "submariner-cable-osp-192-168-60-83" has timed out �[90m2024-02-06T03:17:24.690Z�[0m �[33mDBG�[0m ../remote_endpoint.go:128 NAT using NAT legacy settings for endpoint "submariner-cable-osp-192-168-60-83", using private IP "192.168.60.83" `
> 
> [2] `NAT Sending request - REQUEST_NUMBER: 0x781f8e5fceff55be, SENDER: "submariner-cable-osp-192-168-60-83", RECEIVER: "submariner-cable-ovirt-192-168-30-16", USING_SRC: 192.168.60.83:4490, USING_DST: 192.168.30.16:4490 �[90m2024-02-06T03:18:29.184Z�[0m �[33mDBG�[0m ..y/response_handle.go:31 NAT Received response from 192.168.30.16:4490 - REQUEST_NUMBER: 0x781f8e5fceff55be, RESPONSE: NAT_DETECTED, SENDER: "submariner-cable-ovirt-192-168-30-16", RECEIVER: "submariner-cable-osp-192-168-60-83"`


Thank you for your answer. I solved the issue by creating a new security group that allows all UDP ports and removing the ones generated by 'subctl cloud prepare rhos', as they seemed to have been created incorrectly. I'll reconfigure them accordingly.

Thanks again.

**Comment by yboaron** [comment]
>I solved the issue by creating a new security group that allows all UDP ports and removing the ones generated by 'subctl cloud prepare rhos', as they seemed to have been created incorrectly. I'll reconfigure them accordingly.

Cool, does connection state is up after this change?

**Comment by yboaron** [comment]
@mathgonzlez ,  any update ?

**Comment by dfarrell07** [comment]
Closing for now, please re-open if there's more discussion to be had.
