### ISSUE TITLE
Support PROXY vars on Gateway Pod

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner#2913]
**What would you like to be added**:
Support configuring Submariner GW pods for proxy access. this includes setting Proxy env vars in gw pods and using those envs to use proxy for gw connections.

**Why is this needed**:
In a OCP4 cluster behind a proxy with a global proxy configured the submariner operator pod gets NO_PROXY, HTTP_PROXY, and HTTPS_PROXY env vars set. The gateway pod does not. There doesn't seem to be a set environment vars in the operator`kind: Submariner` yaml either.

As the gateway pod isn't configured for proxy access or you can't configure it we get a bunch of time out errors.

**Comment by adibrastegarnia** [comment]
How did you set the enviroment variable in the gateway pod? do we have that option when we join clusters?
