### ISSUE TITLE
Can not curl exported service 

### ISSUE THREAD

**Issue by trhthang** [submariner-io/submariner#2921]
![image](https://github.com/submariner-io/submariner/assets/71713264/d5524cdb-16ca-40de-9040-2766cb600bbf)

I am trying to deploy Submariner on 2 kubeadm clusters (same network)... the problem I see is that I have installed exactly the same as in the instructions but my cluster1 cannot resolve the svc of cluster2. Here is how I deployed 2 clusters

**cluster1**
pod-cidr: 10.241.0.0/16
service-cidr: 10.111.0.0/16

// Calico CNI:

kubectl create -f - <<EOF
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  registry: quay.io/
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
    ipPools:
     - cidr: 10.241.0.0/16
       encapsulation: VXLAN

apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
   name: default
spec: {}
EOF

kubectl create -f - <<EOF
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: svc-c2
spec:
 cidr: 10.112.0.0/16
 natOutgoing: false
 disabled: true

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: pod-c2
spec:
 cidr: 10.242.0.0/16
 natOutgoing: false
 disabled: true
EOF

// deploy broker on cluster1

curl -Ls https://get.submariner.io | bash
export PATH=$PATH:~/.local/bin
echo export PATH=\$PATH:~/.local/bin >> ~/.profile
****

**cluster2:**
pod-cidr: 10.242.0.0/16
service-cidr: 10.112.0.0/16

//Calico CNI:

kubectl create -f - <<EOF
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  registry: quay.io/
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
    ipPools:
     - cidr: 10.242.0.0/16
       encapsulation: VXLAN

apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
   name: default
spec: {}
EOF

kubectl create -f - <<EOF
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: svc-c1
spec:
 cidr: 10.111.0.0/16
 natOutgoing: false
 disabled: true

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: pod-c1
spec:
 cidr: 10.241.0.0/16
 natOutgoing: false
 disabled: true
EOF

// Deploy broker
subctl deploy-broker --kubeconfig ./config-cluster1

// Join cluster1 and cluster2 to the Broker

subctl join --kubeconfig ~/.kube/config-cluster1 broker-info.subm --clusterid cluster1 --natt=false
subctl join --kubeconfig ~/.kube/config-cluster2 broker-info.subm --clusterid cluster2 --natt=false

**What you expected to happen**:
I have deployed and tested on KinD, after joining 2 clusters, when checking connections, it will look like this:
![image](https://github.com/submariner-io/submariner/assets/71713264/b9a0bfb0-65ba-4f25-ae5b-5857103e453b)

But currently I check and only display only one as follows:
![image](https://github.com/submariner-io/submariner/assets/71713264/270154b4-5a8a-4396-b82e-3c07b0e67acb)
I tried again many times and the results were the same

**Environment**:
- AWS EC2 instance (same VPC)
- Kubeadm
- Submariner
- Calico CNI

**Comment by trhthang** [comment]
![image](https://github.com/submariner-io/submariner/assets/71713264/25161725-51ec-4d94-800a-ce46b26d1fad)

![image](https://github.com/submariner-io/submariner/assets/71713264/7d46ef0b-b39d-4466-97a3-50f9e54cb870)

**cluster1:**

![image](https://github.com/submariner-io/submariner/assets/71713264/811d4ed8-01dc-4bcb-9505-af15b6749202)

![image](https://github.com/submariner-io/submariner/assets/71713264/bf7f80ee-7e27-4a1c-96f7-1045e7aaec77)

**cluster2:**
![image](https://github.com/submariner-io/submariner/assets/71713264/a2a504d5-9637-4149-94bc-c9c8e59dbc20)

![image](https://github.com/submariner-io/submariner/assets/71713264/9109e20c-2096-4ff2-bb39-652e771423bb)

**Comment by ardenwick** [comment]
Check that service is actually imported in each cluster with:
```
kubectl -n default get serviceimport
```
Please check the installation following the [User Guide](https://submariner.io/operations/usage/)

BTW, use tool command `subctl gather` to provide logs and other information instead of screen snapshots, if possible.

**Comment by trhthang** [comment]
![image](https://github.com/submariner-io/submariner/assets/71713264/81141021-17ad-45f7-8548-9a2cb18abb73)


As far as I can see only cluster1 is collected
![image](https://github.com/submariner-io/submariner/assets/71713264/b860c8ec-2466-48c7-aa59-10edce6106c6)

**Comment by yboaron** [comment]
Thanks for reporting this issue @trhthang , 

A. So IPSec connections are up on both clusters, we need to check submariner components logs, could you please run subctl gather [1]  on both clusters and attach the files.

B. Also you can run Submariner service-discovery and connectivity tests using **subctl verify** command,   please run [2] and attach the output.




[1] 
$ subctl gather --kubeconfig  <kubeconfig_file>
or
$ subctl gather --context <cluster_context>

[2] 
$subctl verify --context <kubeContext1> --tocontext <kubeContext2> --only connectivity,service-discovery

**Comment by trhthang** [comment]
A.
**cluster1**
![image](https://github.com/submariner-io/submariner/assets/71713264/a30de93f-38ac-42cb-8eab-0b221098353b)

**cluster2**
![image](https://github.com/submariner-io/submariner/assets/71713264/28e5415a-dbb8-4f3c-b956-7a63a4e1e9b4)

B. 
![image](https://github.com/submariner-io/submariner/assets/71713264/c4975b0f-2b93-4508-954e-ee0416696029)
![image](https://github.com/submariner-io/submariner/assets/71713264/c4f4c0ce-dbfc-40a5-8485-a8a73e5ddcb0)

**Comment by trhthang** [comment]
@yboaron **A. output of submariner components logs**

**Comment by trhthang** [comment]
@yboaron  A. output of  submariner components logs,

[submariner-20240221080342.zip](https://github.com/submariner-io/submariner/files/14356916/submariner-20240221080342.zip)
[submariner-20240221080414.zip](https://github.com/submariner-io/submariner/files/14356921/submariner-20240221080414.zip)

**Comment by trhthang** [comment]
why this ticket closed?

**Comment by yboaron** [comment]
Please share the output of **$subctl verify --context < context1 > --tocontext < context2 > --only connectivity** command
and the content of Calico IPPools resources from both pools

**Comment by trhthang** [comment]
@yboaron   **the output of $subctl verify --context < context1 > --tocontext < context2 > --only connectivity command**
![image](https://github.com/submariner-io/submariner/assets/71713264/bf2774b2-4737-41e6-91c6-58b6aaa78f34)


**Calico IPPools:** 

cluster1:

![image](https://github.com/submariner-io/submariner/assets/71713264/a4cecb87-8a6d-4b6d-b7b1-9c7aaea72d0b)

cluster2:
![image](https://github.com/submariner-io/submariner/assets/71713264/8477a639-c408-4b65-b890-ec7b8b7d7017)

**Comment by trhthang** [comment]
**The output of `subctl diagnose all --kubeconfig 153config`  command**

![image](https://github.com/submariner-io/submariner/assets/71713264/95399631-94be-4628-9024-9a338fcfb19c)
![image](https://github.com/submariner-io/submariner/assets/71713264/3b2437c4-bc90-45fd-be78-1255efdc5f2d)

**Comment by trhthang** [comment]
![image](https://github.com/submariner-io/submariner/assets/71713264/c8949874-5b8c-4e4a-a6a6-6659683c7219)

![image](https://github.com/submariner-io/submariner/assets/71713264/2a874317-af3e-44d3-817b-ea07c7dff8e9)

**Comment by trhthang** [comment]
As far as I can see after exporting the service by `subctl`, it did not create a resource

![image](https://github.com/submariner-io/submariner/assets/71713264/0b4749fc-2329-445b-8edb-31efea07e8e2)

**Comment by trhthang** [comment]
The logs in the Submariner Operator:

![image](https://github.com/submariner-io/submariner/assets/71713264/451ae1e5-985f-450f-85d6-db5bd7f7f602)

**Comment by trhthang** [comment]
@yboaron I used Globalnet, it works well...

**Comment by yboaron** [comment]
> I used Globalnet, it works well...

It is great that you were able to get inter-cluster connectivity and multi-cluster service discovery functionality with Submariner on your env.

[GlobalNet](https://submariner.io/getting-started/architecture/globalnet/) is mandatory only if clusters pod/service CIDRs overlap and that's not the case here, so I wonder why it didn't work with non GlobalNet Submariner.


If you still have the env handy, it would be useful if you could redeploy non GlobalNet Submariner and share (**as text files**) the output of 
**$subctl verify --context < context1 > --tocontext < context2 > --only connectivity  --verbose** 
and the content of Calico IPPools (including default-ippool) resources from both pools

**Comment by trhthang** [comment]
yes, I understand that I don't need to use Globalnet when I have deployed non-overlap CIDR.
I will redeploy and share you @yboaron

**Comment by dfarrell07** [comment]
@trhthang Any update?

**Comment by trhthang** [comment]
@dfarrell07  @yboaron 
Sorry for the late response... I'm testing submariner on-premis and cloud... I think we can close this issue and I will open another issue if there are problems when re-deploy
