### ISSUE TITLE
Cannot create ippools due different resource name (ippools.crd.projectcalico.org)

### ISSUE THREAD

**Issue by adibrastegarnia** [submariner-io/submariner#2952]
In my enviroment, the CR for Calico ip has a different name and I noticed in route agent logs, it cannot create the IPPool because it tries to find ippools.projectcalico.org. Is it a well known issue? Is this configurable to look for a different resource name?

```bash
rver could not find the requested resource (post ippools.projectcalico.org), error creating Calico IPPool for ClusterID \"cluster-2\" subnet \"10.44.0.0/24\" (is Calico API server running?): the server could not find the requested resource (post ippools.projectcalico.org)]"
```

**Comment by adibrastegarnia** [comment]
@tpantelis  @skitt  Would be great if you can share your insights on this. Thanks.

**Comment by adibrastegarnia** [comment]
I found this issue https://github.com/projectcalico/calico/issues/7845 but still not clear to me what is the best way to solve this issue.

**Comment by yboaron** [comment]
@adibrastegarnia , 
Yep, we create IPPools needed for inter-clusters traffic using CRs processed by Calico API server as [Calico folks recommended](https://github.com/projectcalico/calico/issues/7845). 

So, if you want Submariner to create IPPools for you, you need to deploy [Calico API Server](https://docs.tigera.io/calico/latest/operations/install-apiserver#install-the-api-server) on your cluster.

You can find more details [here](https://submariner.io/operations/deployment/calico/)

**Comment by adibrastegarnia** [comment]
I used rke2 config to enable deploying calico ip server so no need for manual deployment. 
ipserver:
  enabled: true
