### ISSUE TITLE
subctl diagnose all passes all checks but service discovery does not work

### ISSUE THREAD

**Issue by adibrastegarnia** [submariner-io/submariner#2953]
I have with the following ip ranges: 

```bash
cluster 1: 
    "cluster-cidr": "10.46.0.0/16",
     "service-cidr": "10.45.0.0/16"

cluster 2:
 "cluster-cidr": "10.42.0.0/16", 
   "service-cidr": "10.43.0.0/16"
```

I joined the clusters using a command like this
```bash
subctl join --kubeconfig cluster1.yaml broker-info.subm --clusterid cluster-1 --context cluster-4f50834d  --natt=false --air-gapped   --health-check=false --force-udp-encaps
```

subctl show all for each cluster shows the connections and endpoints properly  and all connected. 

The nginx service exported successfully 

```bash
kubectl --kubeconfig cluster2.yaml get serviceexports.multicluster.x-k8s.io nginx -o json
{
    "apiVersion": "multicluster.x-k8s.io/v1alpha1",
    "kind": "ServiceExport",
    "metadata": {
        "creationTimestamp": "2024-03-29T01:10:07Z",
        "generation": 1,
        "name": "nginx",
        "namespace": "default",
        "resourceVersion": "24281",
        "uid": "8cf288b4-5484-4288-96aa-96ad4dc6cac9"
    },
    "status": {
        "conditions": [
            {
                "lastTransitionTime": "2024-03-29T01:43:35Z",
                "message": "",
                "reason": "",
                "status": "True",
                "type": "Valid"
            },
            {
                "lastTransitionTime": "2024-03-29T01:10:08Z",
                "message": "Service was successfully exported to the broker",
                "reason": "",
                "status": "True",
                "type": "Ready"
            }
        ]
    }
}

```

the service import looks normal:
```bash
kubectl --kubeconfig cluster1.yaml get serviceimports.multicluster.x-k8s.io nginx -o json
{
    "apiVersion": "multicluster.x-k8s.io/v1alpha1",
    "kind": "ServiceImport",
    "metadata": {
        "creationTimestamp": "2024-03-29T01:44:09Z",
        "generation": 1,
        "name": "nginx",
        "namespace": "default",
        "resourceVersion": "25296",
        "uid": "be999abd-1326-4585-9e9f-946940113ba1"
    },
    "spec": {
        "ports": [
            {
                "port": 80,
                "protocol": "TCP"
            }
        ],
        "type": "ClusterSetIP"
    },
    "status": {
        "clusters": [
            {
                "cluster": "cluster-2"
            }
        ]
    }
}

```

The result of dig shows the DNS is working fine. 
```bash
dig nginx.default.svc.clusterset.local

; <<>> DiG 9.16.6 <<>> nginx.default.svc.clusterset.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29308
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 106f10ae4159f478 (echoed)
;; QUESTION SECTION:
;nginx.default.svc.clusterset.local. IN A

;; ANSWER SECTION:
nginx.default.svc.clusterset.local. 5 IN A      10.43.51.67

;; Query time: 0 msec
;; SERVER: 10.45.0.10#53(10.45.0.10)
;; WHEN: Fri Mar 29 05:10:41 UTC 2024
;; MSG SIZE  rcvd: 125
```

the subctl diagnose pass all checks
```bash
subctl diagnose all --kubeconfig cluster1.yaml
Cluster "cluster-4f50834d"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.27.9+rke2r1" is supported

 ✓ Non-Globalnet deployment detected - checking that cluster CIDRs do not overlap 
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking that gateway metrics are accessible from non-gateway nodes
 ✓ Skipping this check as it's a single node cluster

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("calico") is supported
 ✓ Calico CNI detected, checking if the Submariner IPPool pre-requisites are configured
 ✓ Checking gateway connections
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic
 ✓ Skipping this check as it's a single node cluster

 ✓ Checking that services have been exported properly

```

The endpointslice in the broker does exist 

```bash
kubectl get endpointslices.discovery.k8s.io -n submariner-k8s-broker -o json
{
    "apiVersion": "v1",
    "items": [
        {
            "addressType": "IPv4",
            "apiVersion": "discovery.k8s.io/v1",
            "endpoints": [
                {
                    "addresses": [
                        "10.43.51.67"
                    ],
                    "conditions": {
                        "ready": true
                    }
                }
            ],
            "kind": "EndpointSlice",
            "metadata": {
                "annotations": {
                    "lighthouse.submariner.io/globalnet-enabled": "false",
                    "lighthouse.submariner.io/publish-not-ready-addresses": "false"
                },
                "creationTimestamp": "2024-03-29T01:43:38Z",
                "generateName": "nginx-",
                "generation": 1,
                "labels": {
                    "app": "nginx",
                    "endpointslice.kubernetes.io/managed-by": "lighthouse-agent.submariner.io",
                    "lighthouse.submariner.io/is-headless": "false",
                    "lighthouse.submariner.io/sourceNamespace": "default",
                    "multicluster.kubernetes.io/service-name": "nginx",
                    "multicluster.kubernetes.io/source-cluster": "cluster-2",
                    "submariner-io/clusterID": "cluster-2",
                    "submariner-io/originatingNamespace": "default"
                },
                "name": "nginx-ppdwn",
                "namespace": "submariner-k8s-broker",
                "resourceVersion": "394372",
                "uid": "e7afd998-5f98-4e8a-8935-068c16ddcf11"
            },
            "ports": [
                {
                    "name": "",
                    "port": 80,
                    "protocol": "TCP"
                }
            ]
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}

```

But curl does not return any response back. Anything else I am missing? 
I followed all the steps in this document as well https://submariner.io/operations/troubleshooting/ and everything seems normal and healthy. 
How can I debug from now on? 
any help would be great.

**Comment by adibrastegarnia** [comment]
cc @tpantelis any insights on this issue?

**Comment by skitt** [comment]
@adibrastegarnia please stop pinging individual contributors — you don’t know who the best person to take care of your issue is, and we triage bugs regularly so your issue will get attention even without pings.

**Comment by adibrastegarnia** [comment]
We found out connectivity tests fail. we are behind proxy in our enviroment. We noticed there is PR here https://github.com/submariner-io/submariner/pull/2947 that tries to address the issue but I don't think it is working. We ended up building a custom image to set those env variables inside the gateway docker image but still no luck

**Comment by adibrastegarnia** [comment]
```bash
Summarizing 2 Failures:
  [FAIL] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is on a gateway and the remote pod is on a gateway [It] should have sent the expected data from the pod to the other pod [dataplane, basic]
  github.com/submariner-io/shipyard@v0.17.0/test/e2e/framework/network_pods.go:196
  [FAIL] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod [dataplane, basic]
  github.com/submariner-io/shipyard@v0.17.0/test/e2e/framework/network_pods.go:196

```

**Comment by yboaron** [comment]
A.  Can you elaborate on your env?
B. Please attach **subctl gather  --kubeconfig <path_to_kubeconfig>** from both clusters
C. Also attach the output of **subctl verify --context  <from_context> --tocontext <to_context> --only connectivity,service-discovery --verbose**

**Comment by adibrastegarnia** [comment]
@yboaron  thanks for getting back to me. 
Regarding your questions: 
A. Can you elaborate on your env?
> my clusters are running on VMs where rancher is creating clusters and calico API server is enabled. Here is the k8s version v1.27.9+rke2r1 with calico API server: mirrored-calico-apiserver:v3.26.3. One major difference is that my enviroment is behind proxy. My guess is that proxy is causing problem and I was trying this PR https://github.com/submariner-io/submariner/pull/2947 by creating a custom image based on submariner-gateway:devel for submariner-gateway to set proxy env variables in the new docker image but still no luck with passing connectivity tests. 

B) unfortunately I cannot run subctl gather in my enviroment due to limitation for gathering logs but I can provide them manually as soon as I can. If you are looking for the logs of a specific subsystem, I can provide them to the point. 

C) Attached
[verify_results.txt](https://github.com/submariner-io/submariner/files/14816979/verify_results.txt)
 the results of the verify. Two tests that are failing are connectivity ones. the rest are passing.

**Comment by yboaron** [comment]
Although the GW2GW connectivity is up, the connectivity tests between pod on gwnode in cluster1 and pod (or service's backend pod) on gwnode in cluster2 fail.

Can you create two pods (non HostNetworking) one on each GW node and see if you are able to ping between them? 

This looks like a data path issue, we need more information here (preferably subctl gather), if you can't run subctl gather try collecting at least GW and Routeagent pod logs from both clusters.

**Comment by adibrastegarnia** [comment]
Here are the logs for GW and router agent attached. I am going to do the experiment and let you know more. 
[gateway-cluster-1.txt](https://github.com/submariner-io/submariner/files/14826625/gateway-cluster-1.txt)
[gateway-cluster-2.txt](https://github.com/submariner-io/submariner/files/14826627/gateway-cluster-2.txt)
[router-agent-cluster-1.txt](https://github.com/submariner-io/submariner/files/14826628/router-agent-cluster-1.txt)
[router-agent-cluster-2.txt](https://github.com/submariner-io/submariner/files/14826629/router-agent-cluster-2.txt)

**Comment by adibrastegarnia** [comment]
I created two netstat pod in cluster 1 and cluster 2. From cluster 2, I cannot ping pod IP in cluster 1 (i.e. ip range 10.46.X.X) and from cluster 1, I cannot ping pod IP in cluster 2 (range 10.42.X.X)
From cluster 1 to cluster 2 I am getting 
ing 10.42.232.5
PING 10.42.232.5 (10.42.232.5) 56(84) bytes of data.
From 10.128.11.126 icmp_seq=1 Destination Host Unreachable
From 10.128.11.126 icmp_seq=2 Destination Host Unreachable
From 10.128.11.126 icmp_seq=3 Destination Host Unreachable
From 10.128.11.126 icmp_seq=4 Destination Host Unreachable
From 10.128.11.126 icmp_seq=5 Destination Host Unreachable

but from cluster 2 to cluster 1 I am not getting any response back. 

however, I can ping endpoints of each clusters (i.e subctl show endpoints) from other cluster

**Comment by yboaron** [comment]
>I cannot ping pod IP in cluster 1 (i.e. ip range 10.46.X.X) and from cluster 1, I cannot ping pod IP in cluster 2 (range 10.42.X.X)
From cluster 1 to cluster 2 I am getting
ing 10.42.232.5


Ok, I wanted to make sure if this is a L3 connectivity issue or something specific for TCP, that's the first.

I checked the logs, found [1] error, Submariner sets reverse path filter to loose mode for CNI interface (== interface with IP address from pods CIDR), to allow inter-cluster traffic, you can find more details  [here](https://github.com/submariner-io/submariner/issues/2541#issuecomment-1584438003).

Some datapath use cases may not work if the CNI interface's rp_filter is not set to loose mode and this could explain your problem.

A. Any idea why on your environment interface "vxlan.calico" IP is "10.46.104.192" and not some IP from pods CIDR range?
B. You can manually set rp_filter to loose mode for the CNI interface and see if that helps

[1] 
https://github.com/submariner-io/submariner/blob/devel/pkg/routeagent_driver/handlers/kubeproxy/kp_packetfilter.go#L120

**Comment by adibrastegarnia** [comment]
A. Any idea why on your environment interface "vxlan.calico" IP is "10.46.104.192" and not some IP from pods CIDR range?
No idea but it is coming from cluster CIDR range looks like. if It should come from other ranges and what would be? The pods that I created has the same cluster IP range as you can see from the ping. I also looked at the code you sent me, and it uses cluster CIDR range IP to find CNI interface. I also checked node description and Pod CIDR is in the same range as cluster CIDR. 
B. You can manually set rp_filter to loose mode for the CNI interface and see if that helps
It seems vxlan.calico interface is already on loose mode (i.e. 2). Any other interface you meant? However, all of the interfaces are set to 2 for this rp_filter anyway. 
```bash
sudo cat  /proc/sys/net/ipv4/conf/vxlan.calico/rp_filter 
2
```

**Comment by adibrastegarnia** [comment]
This error in the route agent 
```bash
Error while annotating the node error="error annotating node with CNI interface IP: Error retrieving the CNI interface for 10.46.0.0/24: unable to find CNI Interface on the host which has IP from \"10.46.0.0/24\""
```
Is this what you were referring to?

**Comment by adibrastegarnia** [comment]
Here also ippools created by submariner in cluster 1 and cluster 2 if it helps to verify things. 
```bash
 kubectl --kubeconfig cluster1.yaml get ippools.projectcalico.org submariner-cluster-2-10.42.0.0-24 -o json
{
    "apiVersion": "projectcalico.org/v3",
    "kind": "IPPool",
    "metadata": {
        "creationTimestamp": "2024-04-03T18:45:26Z",
        "labels": {
            "submariner.io/ippool": "true"
        },
        "name": "submariner-cluster-2-10.42.0.0-24",
        "resourceVersion": "2429482",
        "uid": "cbf3693b-38a5-4fd2-994f-94360820c5bf"
    },
    "spec": {
        "allowedUses": [
            "Workload",
            "Tunnel"
        ],
        "blockSize": 26,
        "cidr": "10.42.0.0/24",
        "disabled": true,
        "ipipMode": "Never",
        "nodeSelector": "all()",
        "vxlanMode": "Never"
    }
}
```

```bash
kubectl --kubeconfig cluster1.yaml get ippools.projectcalico.org submariner-cluster-2-10.43.0.0-16 -o json
{
    "apiVersion": "projectcalico.org/v3",
    "kind": "IPPool",
    "metadata": {
        "creationTimestamp": "2024-04-03T18:45:22Z",
        "labels": {
            "submariner.io/ippool": "true"
        },
        "name": "submariner-cluster-2-10.43.0.0-16",
        "resourceVersion": "2429448",
        "uid": "af0405e3-4898-4bbb-b133-82f97ff93a4c"
    },
    "spec": {
        "allowedUses": [
            "Workload",
            "Tunnel"
        ],
        "blockSize": 26,
        "cidr": "10.43.0.0/16",
        "disabled": true,
        "ipipMode": "Never",
        "nodeSelector": "all()",
        "vxlanMode": "Never"
    }
}

```


```bash
kubectl --kubeconfig cluster2.yaml get ippools.projectcalico.org submariner-cluster-1-10.45.0.0-16 -o json
{
    "apiVersion": "projectcalico.org/v3",
    "kind": "IPPool",
    "metadata": {
        "creationTimestamp": "2024-04-03T18:45:20Z",
        "labels": {
            "submariner.io/ippool": "true"
        },
        "name": "submariner-cluster-1-10.45.0.0-16",
        "resourceVersion": "2444739",
        "uid": "0fb19533-3d6e-49b2-a81f-1547fbed1ed5"
    },
    "spec": {
        "allowedUses": [
            "Workload",
            "Tunnel"
        ],
        "blockSize": 26,
        "cidr": "10.45.0.0/16",
        "disabled": true,
        "ipipMode": "Never",
        "nodeSelector": "all()",
        "vxlanMode": "Never"
    }
}
```

```bash
kubectl --kubeconfig cluster2.yaml get ippools.projectcalico.org submariner-cluster-1-10.46.0.0-24 -o json 
{
    "apiVersion": "projectcalico.org/v3",
    "kind": "IPPool",
    "metadata": {
        "creationTimestamp": "2024-04-03T18:45:24Z",
        "labels": {
            "submariner.io/ippool": "true"
        },
        "name": "submariner-cluster-1-10.46.0.0-24",
        "resourceVersion": "2444775",
        "uid": "6633e42d-01d2-4fda-9b61-9c35a94dc104"
    },
    "spec": {
        "allowedUses": [
            "Workload",
            "Tunnel"
        ],
        "blockSize": 26,
        "cidr": "10.46.0.0/24",
        "disabled": true,
        "ipipMode": "Never",
        "nodeSelector": "all()",
        "vxlanMode": "Never"
    }
}
```

**Comment by adibrastegarnia** [comment]
@yboaron I think the traffic is not going through  vx-submariner (or  vxlan.calico) as far I can tell if it is supposed to go but it goes through the default interface and from there goes to some place which has 10.128.11.126 ip address which seems not right to me. when I did tcpdump on the node itself, all traffic is received on default interface. Do you think the traffic is not encapsulated properly to go through tunnel? Do you know how can I really verify this part?

**Comment by yboaron** [comment]
A. 
> This error in the route agent

>Error while annotating the node error="error annotating node with CNI interface IP: Error retrieving the CNI interface for 10.46.0.0/24: unable to find CNI Interface on the host which has IP from \"10.46.0.0/24\""
>Is this what you were referring to?

Yep, as cluster CIDR is 10.46.0.0/24 no interface with ip in this range ( vxlan.calico has 10.46.104.192)

B. What overlay do you use for Calico (can you share the default IPPool CR from both clusters )? 

C. 
> I think the traffic is not going through vx-submariner (or vxlan.calico) as far I can tell if it is supposed to go but it goes through the default interface and from there goes to some place which has 10.128.11.126 ip address which seems not right to me. when I did tcpdump on the node itself, all traffic is received on default interface. Do you think the traffic is not encapsulated properly to go through tunnel? Do you know how can I really verify this part?

OK, so we know that connectivity between pods on non GW nodes is OK, but connectivity is down between pods on GW nodes. 

You can tcpdump both GW nodes while running ping between two pods (non HostNetworking) one on each GW node , that may help us narrow down the issue ?  since you set '--force-udp-encaps' in subctl join command ipsec traffic will be encapsulated in udp port 4500

**Comment by adibrastegarnia** [comment]
Here is the IPPools for each cluster including the default one and the one submariner creates. Are they conflicting with each other? What should be default pool look like? 

```bash
kubectl --kubeconfig cluster1.yaml get ippools.projectcalico.org -o json
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "projectcalico.org/v3",
            "kind": "IPPool",
            "metadata": {
                "creationTimestamp": "2024-03-29T01:03:25Z",
                "name": "default-ipv4-ippool",
                "resourceVersion": "1249",
                "uid": "639e6200-3ace-4eaf-a4fe-779a9f1afc64"
            },
            "spec": {
                "allowedUses": [
                    "Workload",
                    "Tunnel"
                ],
                "blockSize": 26,
                "cidr": "10.46.0.0/16",
                "ipipMode": "Never",
                "natOutgoing": true,
                "nodeSelector": "all()",
                "vxlanMode": "Always"
            }
        },
        {
            "apiVersion": "projectcalico.org/v3",
            "kind": "IPPool",
            "metadata": {
                "creationTimestamp": "2024-04-03T20:53:32Z",
                "labels": {
                    "submariner.io/ippool": "true"
                },
                "name": "submariner-cluster-2-10.42.0.0-24",
                "resourceVersion": "2496257",
                "uid": "ba20686d-400e-4c60-9205-a0b2f111ca28"
            },
            "spec": {
                "allowedUses": [
                    "Workload",
                    "Tunnel"
                ],
                "blockSize": 26,
                "cidr": "10.42.0.0/24",
                "disabled": true,
                "ipipMode": "Never",
                "nodeSelector": "all()",
                "vxlanMode": "Never"
            }
        },
        {
            "apiVersion": "projectcalico.org/v3",
            "kind": "IPPool",
            "metadata": {
                "creationTimestamp": "2024-04-03T20:53:28Z",
                "labels": {
                    "submariner.io/ippool": "true"
                },
                "name": "submariner-cluster-2-10.43.0.0-16",
                "resourceVersion": "2496221",
                "uid": "33278dfc-1fb4-4915-9701-1b9be6e3cbc2"
            },
            "spec": {
                "allowedUses": [
                    "Workload",
                    "Tunnel"
                ],
                "blockSize": 26,
                "cidr": "10.43.0.0/16",
                "disabled": true,
                "ipipMode": "Never",
                "nodeSelector": "all()",
                "vxlanMode": "Never"
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}

```

```bash
 kubectl --kubeconfig cluster2.yaml get ippools.projectcalico.org -o json
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "projectcalico.org/v3",
            "kind": "IPPool",
            "metadata": {
                "creationTimestamp": "2024-03-29T01:04:24Z",
                "name": "default-ipv4-ippool",
                "resourceVersion": "1436",
                "uid": "2f335e8f-5176-4392-866a-8e1e74371375"
            },
            "spec": {
                "allowedUses": [
                    "Workload",
                    "Tunnel"
                ],
                "blockSize": 26,
                "cidr": "10.42.0.0/16",
                "ipipMode": "Never",
                "natOutgoing": true,
                "nodeSelector": "all()",
                "vxlanMode": "Always"
            }
        },
        {
            "apiVersion": "projectcalico.org/v3",
            "kind": "IPPool",
            "metadata": {
                "creationTimestamp": "2024-04-03T20:53:30Z",
                "labels": {
                    "submariner.io/ippool": "true"
                },
                "name": "submariner-cluster-1-10.45.0.0-16",
                "resourceVersion": "2502616",
                "uid": "ba0a50b9-45ff-4885-80f1-3f5b6c29c698"
            },
            "spec": {
                "allowedUses": [
                    "Workload",
                    "Tunnel"
                ],
                "blockSize": 26,
                "cidr": "10.45.0.0/16",
                "disabled": true,
                "ipipMode": "Never",
                "nodeSelector": "all()",
                "vxlanMode": "Never"
            }
        },
        {
            "apiVersion": "projectcalico.org/v3",
            "kind": "IPPool",
            "metadata": {
                "creationTimestamp": "2024-04-03T20:53:34Z",
                "labels": {
                    "submariner.io/ippool": "true"
                },
                "name": "submariner-cluster-1-10.46.0.0-24",
                "resourceVersion": "2502653",
                "uid": "b7ab7296-f299-4c1c-9576-7edf810ba144"
            },
            "spec": {
                "allowedUses": [
                    "Workload",
                    "Tunnel"
                ],
                "blockSize": 26,
                "cidr": "10.46.0.0/24",
                "disabled": true,
                "ipipMode": "Never",
                "nodeSelector": "all()",
                "vxlanMode": "Never"
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}

```

How do you distinguish GW nodes from non GW nodes. It is a single node cluster where the same node is annotated to be gateway. I am going to run more tests and share some tcpdump results here soon.

**Comment by adibrastegarnia** [comment]
Even I configured my cluster to use /16 range for cluster and service cidrs, submariner detects them differently. The cluster cidrs are /24. not sure relevant but I thought share with you @yboaron 

subctl show networks --kubeconfig cluster1.yaml
Cluster "cluster-4f50834d"
 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  calico
        Service CIDRs:   [10.45.0.0/16]
        Cluster CIDRs:   [10.46.0.0/24]

➜  ~ subctl show networks --kubeconfig cluster2.yaml                         
Cluster "cluster-6a9e8042"
 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  calico
        Service CIDRs:   [10.43.0.0/16]
        Cluster CIDRs:   [10.42.0.0/24]

**Comment by adibrastegarnia** [comment]
I passed --clustercidr to be the one which I configured and the problem solved why submariner detects a different one?

**Comment by yboaron** [comment]
> I passed --clustercidr to be the one which I configured and the problem solved why submariner detects a different one?

Nice! 

Submariner uses [the following code](https://github.com/submariner-io/submariner-operator/blob/devel/pkg/discovery/network/calico.go#L33) for auto-detecting cluster and service CIDRs for calico, as you noticed you can workaround CIDR auto-detection by passing **--clustercidr**  and **--servicecidr** in **subctl join** command.

**Comment by adibrastegarnia** [comment]
Going to close this but I guess we need to look into auto discovery part to see why what is configured as cluster cidr and which is discovered is different.
