### ISSUE TITLE
Submariner EKS connectivity  issue 

### ISSUE THREAD

**Issue by adibrastegarnia** [submariner-io/submariner#2987]
I am trying to join an EKS cluster which I created using rancher to submariner. In the first attempt, it seems everything gets installed using the following flags: --natt=false --air-gapped --health-check=false --version=devel --force-udp-encaps --check-broker-certificate=false.

What I noticed is that the status of connections to my other on-prem clusters is remains in connecting status

```
```bash
subctl show all --kubeconfig c-8qkkw.yaml   
Cluster "c-8qkkw"
 ✓ Detecting broker(s)
 ✓ No brokers found

 ✓ Showing Connections
GATEWAY         CLUSTER       REMOTE IP      NAT   CABLE DRIVER   SUBNETS                      STATUS       RTT avg.   
host-7b116651   cluster-1    10.23.21.156   no    libreswan      10.45.0.0/16, 10.46.0.0/16   connecting              
host-104d640e   cluster-2   10.23.21.161   no    libreswan      10.43.0.0/16, 10.42.0.0/16   connecting              

 ✓ Showing Endpoints
CLUSTER       ENDPOINT IP      PUBLIC IP   CABLE DRIVER   TYPE     
c-8qkkw       10.114.180.179               libreswan      local    
cluster-1    10.23.21.156                 libreswan      remote   
cluster-2   10.23.21.161                 libreswan      remote   

 ✓ Showing Gateways
NODE                             HA STATUS   SUMMARY                                  
ip-10-114-180-179   active      0 connections out of 2 are established   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  calico
        Service CIDRs:   [172.20.0.0/16]
        Cluster CIDRs:   [10.114.180.0/23]

 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING              ARCH    
submariner-gateway              quay.io/submariner   devel        devel-3bcd82c0b3ea   amd64   
submariner-routeagent           quay.io/submariner   devel        devel-3bcd82c0b3ea   amd64   
submariner-metrics-proxy        quay.io/submariner   devel        devel-5a7a7c4547c3   amd64   
submariner-operator             quay.io/submariner   devel        devel-bd61362df6e9   amd64   
submariner-lighthouse-agent     quay.io/submariner   devel        devel-35e7db30dfe3   amd64   
submariner-lighthouse-coredns   quay.io/submariner   devel        devel-35e7db30dfe3   amd64
```

Diagnose also shows that the connection is in progress but I guess something is preventing it to happen. 

```bash
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.26.15-eks-adc7111" is supported

 ✓ Non-Globalnet deployment detected - checking that cluster CIDRs do not overlap
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking that gateway metrics are accessible from non-gateway nodes
 ✓ Skipping this check as it's a single node cluster

 ⚠ Checking Submariner support for the CNI network plugin
 ⚠ Submariner could not detect the CNI network plugin and is using ("generic") plugin. It may or may not work.
 ✗ Checking gateway connections
 ✗ Connection to cluster "cluster-1" is in progress
 ✗ Connection to cluster "cluster-2" is in progress
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic
 ✓ Skipping this check as it's a single node cluster

 ✓ Checking that services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.
```

Any ideas how can I debug further? Do I need NAT for connectivity between a cloud cluster and on prem cluster?

**Comment by adibrastegarnia** [comment]
I also see these logs in the gateway. Even I joined it via natt false not sure why it tries to use nat. 
```bash
, "udp-port":"4500"}}} as subnets are overlapping
2024-04-27T00:00:44.671Z INF ..ery/natdiscovery.go:161 NAT                  Starting NAT discovery for endpoint "submariner-cable-cluster-2-10-23-21-161"
2024-04-27T00:00:44.691Z INF .._update_federator.go:68 Federator            local -> broker: Created Cluster "submariner-k8s-broker/-eks-1" 
2024-04-27T00:00:44.943Z INF .._update_federator.go:68 Federator            broker -> local: Created Endpoint "submariner-operator/eks-1-submariner-cable--eks-1-10-114-18
0-195" 
2024-04-27T00:00:44.943Z INF ../datastoresyncer.go:102 DSSyncer             Datastore syncer started
2024-04-27T00:00:44.972Z INF .._update_federator.go:68 Federator            local -> broker: Created Endpoint "submariner-k8s-broker/eks-1-submariner-cable-eks-1-10-114-
180-195" 
2024-04-27T00:00:45.138Z INF .._update_federator.go:68 Federator            broker -> local: Created Endpoint "submariner-operator/cluster-1-submariner-cable-cluster-1-10-23-21-156" 
2024-04-27T00:00:45.144Z INF ..ery/natdiscovery.go:161 NAT                  Starting NAT discovery for endpoint "submariner-cable-cluster-1-10-23-21-156"
2024-04-27T00:00:45.236Z DBG ..ery/request_send.go:117 NAT                  Sending request - REQUEST_NUMBER: 0xa9f620a50460b436, SENDER: "submariner-cable-eks-1-10-114-180-195", RECE
IVER: "submariner-cable-cluster-2-10-23-21-161", USING_S, "udp-port":"4500"}}} as subnets are overlapping
2024-04-27T00:00:44.671Z INF ..ery/natdiscovery.go:161 NAT                  Starting NAT discovery for endpoint "submariner-cable-cluster-2-10-23-21-161"
2024-04-27T00:00:44.691Z INF .._update_federator.go:68 Federator            local -> broker: Created Cluster "submariner-k8s-broker/eks-1" 
2024-04-27T00:00:44.943Z INF .._update_federator.go:68 Federator            broker -> local: Created Endpoint "submariner-operator/eks-1-submariner-cable-eks-1-10-114-18
0-195" 
2024-04-27T00:00:44.943Z INF ../datastoresyncer.go:102 DSSyncer             Datastore syncer started
2024-04-27T00:00:44.972Z INF .._update_federator.go:68 Federator            local -> broker: Created Endpoint "submariner-k8s-broker/eks-1-submariner-cable-eks-1-10-114-
180-195" 
2024-04-27T00:00:45.138Z INF .._update_federator.go:68 Federator            broker -> local: Created Endpoint "submariner-operator/cluster-1-submariner-cable-cluster-1-10-23-21-156" 
2024-04-27T00:00:45.144Z INF ..ery/natdiscovery.go:161 NAT                  Starting NAT discovery for endpoint "submariner-cable-cluster-1-10-23-21-156"
2024-04-27T00:00:45.236Z DBG ..ery/request_send.go:117 NAT                  Sending request - REQUEST_NUMBER: 0xa9f620a50460b436, SENDER: "submariner-cable-eks-1-10-114-180-195", RECE
IVER: "submariner-cable-cluster-2-10-23-21-161", USING_SRC: 10.114.180.195:4490, USING_DST: 10.23.21.161:4490RC: 10.114.180.195:4490, USING_DST: 10.23.21.161:4490

```

**Comment by adibrastegarnia** [comment]
One error I found in the gateway of other clusters where my EKS is trying to connect is this 

```bash
Error installing cable for &natdiscovery.NATEndpointInfo{Endpoint:v1.Endpoint{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"eks-1-submariner-cable-eks-1-10-114-180-82", GenerateName:"", Namespace:"submariner-operator", SelfLink:"", UID:"e78f62c5-a47e-4b46-abf9-2877326357b3", ResourceVersion:"10501616", Generation:1, CreationTimestamp:time.Date(2024, time.April, 27, 2, 1, 31, 0, time.Local), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"submariner-io/clusterID":"eks-1"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"submariner-gateway", Operation:"Update", APIVersion:"submariner.io/v1", Time:time.Date(2024, time.April, 27, 2, 1, 31, 0, time.Local), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc0000116e0), Subresource:""}}}, Spec:v1.EndpointSpec{ClusterID:"eks-1", CableName:"submariner-cable-eks-1-10-114-180-82", HealthCheckIP:"", Hostname:"ip-10-114-180-82.us-west-2.compute.internal", Subnets:[]string{"172.20.0.0/16", "10.114.180.0/23"}, PrivateIP:"10.114.180.82", PublicIP:"", NATEnabled:false, Backend:"libreswan", BackendConfig:map[string]string{"natt-discovery-port":"4490", "preferred-server":"false", "udp-port":"4500"}}}, UseNAT:false, UseIP:"10.114.180.82"} error="error installing Endpoint cable \"submariner-cable-eks-1-10-114-180-82\": error whacking with args [--psk --encrypt --forceencaps --name submariner-cable-eks-1-10-114-180-82-0-0 --id 10.23.21.156 --host 10.23.21.156 --client 10.45.0.0/16 --ikeport 4500 --to --id 10.114.180.82 --host 10.114.180.82 --client 172.20.0.0/16 --ikeport 4500 --dpdaction=hold --dpddelay 30]: exit status 20"


```

**Comment by adibrastegarnia** [comment]
I don't know why it tries to do NAT discovery when the nat is disabled according to the logs

```bash
2024-04-28T05:37:51.503Z WRN ..ery/natdiscovery.go:183 NAT                  NAT discovery for endpoint "submariner-cable-cluster-1-10-23-21-156" has timed out
2024-04-28T05:40:08.583Z WRN ..ery/natdiscovery.go:183 NAT                  NAT discovery for endpoint "submariner-cable-cluster-2-10-23-21-161" has timed out
```

**Comment by adibrastegarnia** [comment]
I tried with calico plugin and everything in the logs normal but connection stays in connecting status.

**Comment by adibrastegarnia** [comment]
I continued debug this issue what I found out is both sides are sending IKE_SA_INIT request but no response is coming back. One thing I can found is when the cluster gets joined and it tries to establish ipsec tunnel, the ping stops working from on-prem cluster to cloud but cloud to on-prem cluster works fine.

**Comment by yboaron** [comment]
Hi @adibrastegarnia  ,
I can see that you use Calico as CNI, did you follow https://submariner.io/operations/deployment/calico/ ?

**Comment by adibrastegarnia** [comment]
@yboaron  Thanks for getting back to me. Yes. I installed calico api server and I think ippools created properly with submariner as far as I can tell. The reason that I moved from generic to calico because I got it working with on prem clusters.  I observed something which I don't quite understand and perhaps you can help me with that. I have two clusters on prem and one cluster in the cloud. The on prem cluster is in 10.23.X.Y range and cloud is 10.114.X.Y range. on prem clusters can communicate with each other and endpoints get connected and all verify tests pass. The problem is between cloud and an on prem cluster where the ipsec tunnel stays in connecting state. Before joining the cloud cluster to submariner, I can ping cloud to on prem and vice versa but after joining the cloud cluster ping works from cloud to on prem cluster but not from on prem to cloud. What I found out is IKE init packets is not going out from both sides and never reaches the other side which is the source of the issue that connection stays half open. How do you explain this behavior? Why ipsec tunnel affects the ping traffic in one direction but not the other?

**Comment by yboaron** [comment]
>I don't know why it tries to do NAT discovery when the nat is disabled according to the logs

Submariner always runs NAT discovery (if nat discovery port is defined, and it is by default),  nat param is used only if nat discovery failed to determine the IP (timed out) ,  check IP Selection Algorithm - [here](https://submariner.io/operations/nat-traversal/)

IIUC, 10.23.21.156 is on-prem gateway node IP  and 10.114.180.179 is the public cloud gateway IP, both IPs are from private IP range (10.0.0.0/8), packets between onprem and public cloud must undergo NAT to allow connectivity. 
private IPs are not routable in the public internet, they must get routable/public IP (via NAT for example). 

You can find more details [here](https://submariner.io/operations/nat-traversal/)

**Comment by adibrastegarnia** [comment]
> > I don't know why it tries to do NAT discovery when the nat is disabled according to the logs
> 
> Submariner always runs NAT discovery (if nat discovery port is defined, and it is by default), nat param is used only if nat discovery failed to determine the IP (timed out) , check IP Selection Algorithm - [here](https://submariner.io/operations/nat-traversal/)
> 
> IIUC, 10.23.21.156 is on-prem gateway node IP and 10.114.180.179 is the public cloud gateway IP, both IPs are from private IP range (10.0.0.0/8), packets between onprem and public cloud must undergo NAT to allow connectivity. private IPs are not routable in the public internet, they must get routable/public IP (via NAT for example).
> 
> You can find more details [here](https://submariner.io/operations/nat-traversal/)

@yboaron  Thanks for your response. That is true our public cloud is on eks but it is routable in our private network. I was under the impression that we can implement Option 1 where all the networks are reachable via private ips as they are now. I can ping submariner endpoints (from cloud or on prem) without any problems. What else forces NAT in this scenario? Am I missing something?

**Comment by yboaron** [comment]
> public cloud is on eks but it is routable in our private network

How the private network and eks private network connected ?  VPN?


As per Submariner, one of the pre-requisite is IP reachability between the gateway nodes, 
the gateways must have connectivity to each other on their public or private IP address and encapsulation port. This is needed for creating the tunnels between the clusters.
Also Submariner uses default 4500/UDP port for IPSec udp encapsulation and port 4490/UDP for nat-discovery, you need to make sure the firewall allows traffic on these ports.

Since you mentioned that nat-discovery timed out (on gw pod logs), I assume you need to make sure the above requirements are met.

**Comment by yboaron** [comment]
@adibrastegarnia Any update?

**Comment by adibrastegarnia** [comment]
> @adibrastegarnia Any update? 
> 
> 

It could be an issue in our network where some of the ports are closed. We haven't tried it again as we need to fix the issue I can close this for now and I will open it if the issue persists thanks for following up
