### ISSUE TITLE
[Doc] Submariner components requires Go >= 1.13

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#299]
We need to update the READMEs in all Submariner components repos - that in order to compile them - Go 1.13 or above is required.

For example, when running in Go 1.12 [submariner-operator] [./setup_subm.sh] - it fails during compilation of Lighthouse:
```
[submariner-operator]$ CGO_ENABLED=0 go build -ldflags -s -w -X github.com/submariner-io/submariner-operator/pkg/version.Version=dev  -X github.com/submariner-io/submariner-operator/pkg/version.Commit=405f7c9dbf1bda1bc1951a21a67bcd8b9b14d560 -o bin/subctl-dev-linux-amd64 ./pkg/subctl/main.go
# github.com/submariner-io/submariner-operator/pkg/subctl/lighthouse/install/crds
pkg/subctl/lighthouse/install/crds/ensure.go:76:36: undefined: embeddedyamls.Crds_multiclusterservices_crd_yaml
note: module requires Go 1.13
[submariner-operator]$ ./scripts/build onetime false
time="2020-01-26T13:55:25+02:00" level=fatal msg="exit status 2"
make: *** [build] Error 1
```

**Comment by mangelajo** [comment]
We must use the dapper environment for compilation not our bare host. Otherwise we will run into problems like this or many others.

Always use "make" actions to compile or test.

You can also use ./.dapper -s -m bind if you want

**Comment by mangelajo** [comment]
May be we should make sure the readme is clear about the make fact.

**Comment by manosnoam** [comment]
The Readme has to be specifying the exact requirments, and deployment procedure. If workaround is required, just like prepare_for_sumariner.sh script, or an alternative build command (like #146 )
it should be clear to follow.

Regarding Go version, can the customer build Submariner without having Go already installed ?
