### ISSUE TITLE
REQUEST: New Committer rights request for yboaron

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#3001]
### GitHub Username
@yboaron 

### Code you are requesting Committer rights for
submariner/\* 

### Requirements
- [x] I have reviewed the contributor roles guidelines (https://submariner.io/community/contributor-roles/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have been actively contributing to Submariner for at least 3 months
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tpantelis 
- @vthapar 

### List of required reviews to Submariner project PRs
- At least 20 PRs to the relevant codebase that you reviewed, and at least 5 for which you were the primary reviewer:
- https://github.com/submariner-io/submariner/pulls?q=is%3Apr+reviewed-by%3Ayboaron+-author%3Ayboaron

**Comment by tpantelis** [comment]
+1

**Comment by vthapar** [comment]
+1

**Comment by sridhargaddam** [comment]
+1

**Comment by yboaron** [comment]
https://github.com/submariner-io/submariner/pull/3054
