### ISSUE TITLE
Support configuration of HTTP_PROXY, HTTPS_PROXY and NO_PROXY for Gateway DaemonSet

### ISSUE THREAD

**Issue by winkrs** [submariner-io/submariner#3007]
**What would you like to be added**:
To ensure connectivity to the broker, which is exclusively accessible via a proxy, the HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables must be included in the gateway DaemonSet configuration. During the `subctl join` process, can incorporate these configurations into the Submariner Custom Resource (CR), ensuring that the gateway DaemonSet will automatically set the environment variables for the proxy, just as it does for other environment variables.

**Why is this needed**:
The broker, operating within a remote cluster, can only be reached via a proxy. To establish a connection between the gateway and the broker, the specified environment variables must be configured.

**Comment by skitt** [comment]
This will be available in 0.18; see https://github.com/submariner-io/subctl/pull/1103 for the new `subctl` flags. If you’re not using `subctl`, you can set the appropriate environment variables in the operator `Deployment` object, and they will be propagated to the other pods (including the gateway).

**Comment by winkrs** [comment]
Is there a way to setup proxy only for gateway? 

Also after adding the proxy env in operator deployment, I'm getting below error:

```
Failed to get Pod error="failed to get API group resources: unable to retrieve the complete list of server APIs: v1: Get \"
[https://X.X.X.X:443/api/v1\":](https://X.X.X.X/api/v1/%22:)
Service Unavailable"
```

**Comment by skitt** [comment]
Which version of Submariner are you using?

**Comment by winkrs** [comment]
My bad, I was using `0.17`. After using `devel` version its working.
