### ISSUE TITLE
MTU is smaller than necessary for vx-submariner path

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#301]
We use vx-submariner to achieve src-ip preservation of pods.

But vx-submariner MTU is not calculated and uses a fixed 1450. We should identify the outgoing interface, and adapt the interface to use interface.mtu - 50 (Vxlan overhead).

**Comment by mangelajo** [comment]
@sridhargaddam I added you to this one since you were working on the other related fix, and you are very familiar with this part, but let me know if you are busy and wand me to look at it.

**Comment by sridhargaddam** [comment]
> @sridhargaddam I added you to this one since you were working on the other related fix, and you are very familiar with this part, but let me know if you are busy and wand me to look at it.

No problem @mangelajo, I'll work on the necessary changes and push the PR.

**Comment by sridhargaddam** [comment]
The necessary fix is now merged in Submariner repo.
