### ISSUE TITLE
Mark diagnostic E2E tests which can be used outside CI E2E by customers without special requisites.

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#302]
We must organize the subset of E2E tests which can be used to validate connectivity and a submariner install without specific setup of the environment (gateway redundancy, etc.).

This should also include clear documentation on how to use such E2E tests, and what's required to do so.

This is also related to: https://github.com/submariner-io/submariner-operator/issues/103

**Comment by tpantelis** [comment]
Rather than exposing the Go E2E tests to end-users, I would propose we package such validation in a CLI, ie subctl.

**Comment by mangelajo** [comment]
Yes, but my intention is to use these tests directly (at least for now) from subctl, by compiling them in. And then subctl can select specifically the "diagnostic" ones.
