### ISSUE TITLE
The Inter Cluster route shoud be add cniIface address src 

### ISSUE THREAD

**Issue by rayroot** [submariner-io/submariner#3103]
**What would you like to be added**:

https://github.com/submariner-io/submariner/blob/ae618af1be6351bf93755f4764cdb6f9ded3d18d/pkg/routeagent_driver/handlers/kubeproxy/routes_iface.go#L291

this should be add src ( cniIface.IPAddress )  , just as on gateway node; 

**Why is this needed**:

 when from cluster1-node1 ( not  gateway) ->  cluster1-gateways->  cluster2-gateways -> cluster2-pod, 
the request can auto select a pod address as src, and not vx-submariner's address ( using this address as src could not connect to the cluster2-pod)

**Comment by yboaron** [comment]
Thanks for reaching out @rayroot  , 

Could you please elaborate on the use case? 
do you mean connectivity from  host networking/non_GW_node@cluster1 to pod@cluster2 ?

**Comment by rayroot** [comment]
> Thanks for reaching out @rayroot ,
> 
> Could you please elaborate on the use case? do you mean connectivity from host networking/non_GW_node@cluster1 to pod@cluster2 ?

Yes, you are right, i want to from non_GW_node@cluster1 to pod@cluster2

**Comment by yboaron** [comment]
It should work, there's [Iptables rule](https://github.com/submariner-io/submariner/blob/ae618af1be6351bf93755f4764cdb6f9ded3d18d/pkg/routeagent_driver/handlers/kubeproxy/packetfilter_iface.go#L90) for SNATing node's IP to node's cni IP address .


Could you please share more details about your environment and the connectivity issue?

**Comment by rayroot** [comment]
> It should work, there's [Iptables rule](https://github.com/submariner-io/submariner/blob/ae618af1be6351bf93755f4764cdb6f9ded3d18d/pkg/routeagent_driver/handlers/kubeproxy/packetfilter_iface.go#L90) for SNATing node's IP to node's cni IP address .
> 
> Could you please share more details about your environment and the connectivity issue?

Thank you very much. 

When I first checked the environment, I did not find the SNAT iptables rules, and I saw the log message "Error discovering the CNI interface" in the route agent. 

Then, I restarted the route agent, the SNAT rule appeared, and everything worked normally. 

I thought about it and it seems that my environment had a restart previously, which could have caused the route agent to start before Calico, leading to it not finding the CNI interface?  

But now, everything goes well, thanks again !

**Comment by dfarrell07** [comment]
Looks like this is done. Thanks all!
