### ISSUE TITLE
ROKS(Calico): Submariner RA failed to discover CNI interface after node reboot

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#3120]
I deployed Submariner (0.18) on ROKS, after node reboot Submariner RA [failed to discover the CNI interface](https://github.com/submariner-io/submariner/blob/devel/pkg/routeagent_driver/handlers/kubeproxy/kp_packetfilter.go#L117).

Checking the logs it seems that Calico CNI interface (tunl0) doesn't exist when RA pod starts running post-reboot. 

This is the order of events based on logs details:

A. After rebooting the node pods running on it are restarted
B. Node's status changed to  NotReady
C. Submariner RouteAgent pod starts running on node
  -  C.1 RouteAgent **submariner-routeagent-init** waits until node status is READY
  -  C.2 RouteAgent **submariner-routeagent** fails to discover Calico CNI interface on node.

D. Calico-node pod creates Calico CNI interface

**Comment by dfarrell07** [comment]
We think we'd like to have RelNotes for this but we're interested in how https://github.com/submariner-io/submariner/issues/3110 resolves before writing it up.
