### ISSUE TITLE
maybe use a model VPN  like wireguard ?

### ISSUE THREAD

**Issue by joeblew99** [submariner-io/submariner#32]
https://www.wireguard.com/

Its open and in c and golang

**Comment by mangelajo** [comment]
If we make a driver architecture IMHO it could be a driver if somebody has capacity to write it. For some environments wireguard is still not accepted, specially since it's a young project, and the kernel modules aren't upstream yet. But it's promising.

**Comment by nyechiel** [comment]
Wireguard support is in progress. Please see https://github.com/submariner-io/submariner/issues/394
