### ISSUE TITLE
Store sensitive details in secrets

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#326]
Things that can be stored on (ideally separate) secrets:

a) the ipsec-psk (or other cable engine related secrets)
b) the token/cert (just a copy of the service account secret created on the broker)

Secrets won't buy extra security because, with the right permissions can be extracted. But it will make it:

1) Cleaner when showing pods, the secrets won't be dumped on screen
2) Easier to update

**Comment by mangelajo** [comment]
@roytman  ^

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
See also https://github.com/submariner-io/submariner/issues/815

**Comment by skitt** [comment]
This is still relevant.

**Comment by tpantelis** [comment]
bump

**Comment by skitt** [comment]
This is still relevant.

**Comment by dfarrell07** [comment]
@skitt is working on this with PRs like https://github.com/submariner-io/submariner-operator/pull/1687

**Comment by nyechiel** [comment]
@skitt can this be closed now or is there anything else needed?

**Comment by skitt** [comment]
> @skitt can this be closed now or is there anything else needed?

I’m trying to check, but `make deploy` no longer works for me, I need to fix that first.

Ideally we’d _only_ use secrets to close this issue, but that has to wait for 0.13; perhaps we can track that as a separate issue.

**Comment by skitt** [comment]
Everything that should be in a secret is now in a secret; I’ve filed https://github.com/submariner-io/submariner-operator/issues/1869 to ensure we remove the non-secret occurrences in 0.13.

**Comment by nyechiel** [comment]
@skitt anything we should update in our docs to reflect these changes?

**Comment by skitt** [comment]
> @skitt anything we should update in our docs to reflect these changes?

We don’t describe this in the docs currently, I’ve filed https://github.com/submariner-io/submariner-website/issues/678 to make sure we don’t forget to change this situation (but it’s not required for 0.12 IMO, it’s only liable to create problems once we drop support for the non-secret variants).
