### ISSUE TITLE
During a gateway node transitions, route-agent pod PANICs

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#331]
[RA-2] I0207 10:50:19.334650       1 route.go:439] Handling object in handleEndpoint
[RA-2] I0207 10:50:19.334672       1 route.go:440] Processing endpoint object: submariner-operator/cluster-b-submariner-cable-cluster-b-10-0-33-255
[RA-2] E0207 10:50:19.339389       1 route.go:619] Error retrieving link by name vx-submariner: Link not found
[RA-2] I0207 10:50:19.340396       1 vxlan.go:152] Successfully added the bridge fdb entry 10.0.42.39 00:00:00:00:00:00
[RA-2] I0207 10:50:19.340479       1 vxlan.go:152] Successfully added the bridge fdb entry 10.0.159.70 00:00:00:00:00:00
[RA-2] I0207 10:50:19.340530       1 vxlan.go:152] Successfully added the bridge fdb entry 10.0.33.255 00:00:00:00:00:00
[RA-2] I0207 10:50:19.340583       1 vxlan.go:152] Successfully added the bridge fdb entry 10.0.131.68 00:00:00:00:00:00
[RA-2] I0207 10:50:19.340631       1 vxlan.go:152] Successfully added the bridge fdb entry 10.0.175.135 00:00:00:00:00:00
[RA-2] F0207 10:50:19.340698       1 route.go:473] Unable to create VxLAN interface on GatewayNode (ip-10-0-33-255): failed to add FDB entry on the Gateway Node vxlan iface unable to add the bridge fdb entry <nil> 00:00:00:00:00:00, err: address family not supported by protocol
[RA-2] goroutine 94 [running]:
[RA-2] k8s.io/klog.stacks(0xc000210300, 0xc00052e000, 0x110, 0x225)
[RA-2]  /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:828 +0xb1
[RA-2] k8s.io/klog.(*loggingT).output(0x1e58e00, 0xc000000003, 0xc0002f55e0, 0x1de3beb, 0x8, 0x1d9, 0x0)
[RA-2]  /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:779 +0x2d9
[RA-2] k8s.io/klog.(*loggingT).printf(0x1e58e00, 0x3, 0x12d0dc6, 0x38, 0xc000227e08, 0x2, 0x2)
[RA-2]  /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:678 +0x14e
[RA-2] k8s.io/klog.Fatalf(...)
[RA-2]  /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:1207
[RA-2] github.com/submariner-io/submariner/pkg/routeagent/controllers/route.(*Controller).processNextEndpoint.func1(0xc00039c000, 0x10ec5e0, 0xc00032f3b0, 0x0, 0x0)
[RA-2]  /go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/route.go:473 +0xca8
[RA-2] github.com/submariner-io/submariner/pkg/routeagent/controllers/route.(*Controller).processNextEndpoint(0xc00039c000, 0xc0000aed01)
[RA-2]  /go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/route.go:503 +0x4d
[RA-2] github.com/submariner-io/submariner/pkg/routeagent/controllers/route.(*Controller).runEndpointWorker(0xc00039c000)
[RA-2]  /go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/route.go:211 +0x2b
[RA-2] k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00047b800)
[RA-2]  /go/src/github.com/submariner-io/submariner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
[RA-2] k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00047b800, 0x3b9aca00, 0x0, 0x1, 0xc0000886c0)
[RA-2]  /go/src/github.com/submariner-io/submariner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
[RA-2] k8s.io/apimachinery/pkg/util/wait.Until(0xc00047b800, 0x3b9aca00, 0xc0000886c0)
[RA-2]  /go/src/github.com/submariner-io/submariner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
[RA-2] created by github.com/submariner-io/submariner/pkg/routeagent/controllers/route.(*Controller).Run
[RA-2]  /go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/route.go:196 +0xae8
 I0207 10:50:09.349334       1 route.go:439] Handling object in handleEndpoint

Although sometimes it won't panic like in this example, resulting in a missing vx-submariner interface.

**Comment by sridhargaddam** [comment]
@mangelajo I modified the title of this issue to match the logs. Let us create separate issues for any errors seen for HA use-cases. I'm closing this issue as the PANIC is now addressed.
