### ISSUE TITLE
Audit Twitter, Youtube social channels for refactoring

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#379]
Generally review Twitter and Youtube to make sure our social outlets are in good shape. Put together plan for usage, sharing going forward.

**Comment by dfarrell07** [comment]
[Twitter](https://twitter.com/submarinerio) looks good overall, a few minor fixes:
* Change "on prem" to "on-prem" in bio.
* Add link to GitHub in website bio field.
* RT a @mention highlighting the new Lighthouse demo.

[YouTube](https://www.youtube.com/channel/UCZ3brSgl2v4boglZoeChClQ/featured) looks good, no action needed.

[Website](https://submariner.io/) needs work, but that is ongoing in [submariner-io/submariner-website](https://github.com/submariner-io/submariner-website/).

**Comment by nyechiel** [comment]
@dfarrell07  Re: YouTube - how can we improve SEO and overall visibility of our channel? This is the current search experience: https://www.youtube.com/results?search_query=submariner.io

**Comment by dfarrell07** [comment]
@skitt Is there some way you can share editing privileges for the YouTube channel with me?

**Comment by dfarrell07** [comment]
> @skitt Is there some way you can share editing privileges for the YouTube channel with me?

It should be possible from studio.youtuble.com -> Settings -> Permissions.

https://support.google.com/youtube/answer/9481328

**Comment by skitt** [comment]
I’ve added Miguel and you as co-owners of the channel.

**Comment by dfarrell07** [comment]
I now have permissions to edit the YouTube channel. Edited:
* Changed all video categories from People and Blogs to Science and Technology.
* Specified that the video languages are English.
* Added channel-wide keywords:
  * Submariner, Submariner-io, Kubernetes, K8s, Networking, Cross-cluster Networking, Multi-cluster Networking, Open Source, Hybrid Cloud.
* Added tags to video "Connecting hybrid Kubernetes clusters using Submariner"
  * Same channel-wide tags
  * AWS, on-prem
* Added tags to video "Cross-cluster service discovery in Submariner using Lighthouser"
  * Same channel-wide tags
  * Service Discovery, Cross-Cluster Service Discovery, Lighthouse.
* Added tags to video "Deploying Submariner with subctl"
  * Same channel-wide tags
  * Deployment, subctl
