### ISSUE TITLE
Validate Overlapping CIDRs use-case using Globalnet (without DNS)

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#391]
Validate Globalnet Controller use-case by manually deploying two clusters with Overlapping CIDRs and ensuring that POD to Service use-case is working as expected.

**Comment by sridhargaddam** [comment]
@manosnoam the necessary PRs are all in and it's ready for testing. We have not tagged the subctl yet, but you can pick the latest subctl from submariner-operator repo. Just let me or @vthapar once you are ready to test and we will provide more details.

**Comment by manosnoam** [comment]
I'm testing according to e2e script as in:
https://github.com/submariner-io/submariner-operator/pull/254

Do we have Readme for globalnet already ?
If not, there should be a issue to add globalnet info and examples to Readme.

**Comment by sridhargaddam** [comment]
> I'm testing according to e2e script as in:
> [submariner-io/submariner-operator#254](https://github.com/submariner-io/submariner-operator/pull/254)
> 
> Do we have Readme for globalnet already ?
> If not, there should be a issue to add globalnet info and examples to Readme.

Right, you can start with the simple deployment scenario where you specify globalnet is enabled and start expanding on specifying different values. 

We have two Jiras to add the documentation and they are in progress.
@vthapar is looking at - https://github.com/submariner-io/submariner/issues/384
@sridhargaddam -  https://github.com/submariner-io/submariner-website/issues/20

**Comment by manosnoam** [comment]
I'm renaming this issue, as I have validated GlobalNet to be working correctly WITHOUT using DNS (service-discovery). I will Open another issue to validate it with DNS on the next release (see #458)
