### ISSUE TITLE
Refactor CI job structure of testing re-deploys on existing deployments

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#392]
The current Travis jobs attempt to test re-running on existing deployments when the e2e scripting is modified.

```
  - if [[ "${CHANGED_FILES_PR[@]}" =~ "scripts/kind-e2e/e2e.sh" ]]; then
      echo "scripts/kind-e2e/e2e.sh was modified, testing recurring run on already deployed infrastructure.";
      set -o pipefail;
      $CMD 2>&1 |  ts '[%H:%M:%.S]' -s;
    fi;
```

However, the logic no longer really applies because the scripts used in e2e are now many more than just e2e.sh.

Parts:
* Trigger re-runs at correct, useful times. Don't re-run verify jobs, for example.
* Maybe trigger based on periodic timer, vs extending job times for PRs.

**Comment by dfarrell07** [comment]
This check caught a legit bug in https://github.com/submariner-io/submariner/pull/427, so maybe it adds enough value that it should remain when e2e files are modified but the check should be extended to catch all e2e-related file changes.

**Comment by mkolesnik** [comment]
A simple fix could be to trigger on `"${CHANGED_FILES_PR[@]}" =~ "scripts/kind-e2e/"`

Also note that if the script failed at that point it didn't actually fail the job, so the fact it caught a bug in #427 was since I was actually reading the build logs, and would go unnoticed otherwise.
