### ISSUE TITLE
[Tracker] WireGuard support

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#394]
WireGuard is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography. Traffic is encrypted and encapsulated in UDP packets.

The goal of this Issue is to track the work to support it as a cable driver.

**Comment by nyechiel** [comment]
Patches from @roytman and team :)

**Comment by tpantelis** [comment]
https://github.com/submariner-io/submariner/pull/349
https://github.com/submariner-io/submariner-operator/pull/185/

**Comment by nyechiel** [comment]
https://github.com/submariner-io/submariner/pull/441

**Comment by nyechiel** [comment]
@roytman Can you please update this Issue and link all relevant patches? I think we should try and get it in for v0.3.

**Comment by roytman** [comment]
As I know, the flowing WireGuard support related issues should be resolved:

- implement WG driver connection status. 
- update submariner helm based deployment  PR https://github.com/submariner-io/submariner-charts/pull/18 (btw, do we need it?)
- copy the WG e2e tests to shipyard. PR https://github.com/submariner-io/submariner/pull/476, and integrate WG tests into the Submariner automatic test pipeline. (should be done together with the Submariner team).
- In general, WG driver has the [README](https://github.com/submariner-io/submariner/blob/master/pkg/cable/wireguard/README.md), the questions is, if some upper layer documentation files should be updated.

**Comment by nyechiel** [comment]
@mangelajo @skitt @tpantelis can you please provide guidance to Alexey?
