### ISSUE TITLE
ZeroTier as Connection Method?

### ISSUE THREAD

**Issue by meditatus** [submariner-io/submariner#4]
Suggesting this to see if it can be integrated? Might facilitate the connection process, it's free and self-hostable.

https://www.zerotier.com/

**Comment by Oats87** [comment]
Hi @meditatus we will examine ZeroTier's feasibility to see if it would be a suitable cable engine.

**Comment by anjia0532** [comment]
100 nodes is free ,more than is not!

**Comment by meditatus** [comment]
Was there a purpose to that response?

The self hosted version is unlimited.

**Comment by mangelajo** [comment]
@meditatus you can now consider the contribution of a cable driver. We now have wireguard and libreswan on the making.
