### ISSUE TITLE
Support in KIND (via Armada) to deploy clusters with Overlapping CIDRs

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#412]
Currently, KIND clusters are deployed with non-overlapping CIDRs (pod and svc). Inorder to validate Globanetnet Controller, we require clusters with overlapping CIDRs. This issue is to track the necessary enhancements in KIND/Armada for this use-case.

**Comment by dfarrell07** [comment]
We decided not to go with Go-based Armada, so my patch became irrelevant, but @sridhargaddam ended up implementing this logic on the Bash-based path here: https://github.com/submariner-io/submariner/pull/436/files
