### ISSUE TITLE
Submariner failed to pull image

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#416]
After deploying Submariner and joining 2 Clusters (on OSP and AWS), submariner engine pods failed to pull images:

```
$ oc get pods -n submariner-operator
NAME                                   READY   STATUS             RESTARTS   AGE
submariner-gateway-lhg65               0/1     ImagePullBackOff   0          25m
submariner-gateway-q8ghj               0/1     ImagePullBackOff   0          25m
submariner-operator-5f896d567d-jxft6   1/1     Running            0          27m
submariner-routeagent-g54mp            0/1     ImagePullBackOff   0          25m
submariner-routeagent-lrrs5            0/1     ImagePullBackOff   0          25m
```

Full log output attached: 
[Submariner failing to pull image.log](https://github.com/submariner-io/submariner/files/4294537/Submariner.failing.to.pull.image.log)

**Comment by sridhargaddam** [comment]
Submariner 0.1.1 tagged images are missing at https://quay.io/repository/submariner/submariner

CC: @mangelajo @skitt

**Comment by mangelajo** [comment]
Ah, 4 days ago, but it was released 3 days ago :)
