### ISSUE TITLE
StrongSwan connecting to 'default' URI failed

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#426]
After deploying Submariner, all submariner-operator are running, but strongswan status returns exit code 3. Looking at swanctl, I'm seeing that StrongSwan connecting to 'default' URI 'unix:///run/strongswan/charon.vici' failed: No such file or directory.

```
cd /home/nmanos/go/src/github.com/submariner-io/submariner-operator
./bin/subctl info
Discovered network details:
Network plugin:  OpenShift
Service CIDRs: [172.30.0.0/16]
Cluster CIDRs: [10.128.0.0/14]
/home/nmanos/automation/ocp-install/oc get pods -n submariner-operator
NAME                                   READY   STATUS    RESTARTS   AGE
submariner-gateway-fz4rh               1/1     Running   0          12m
submariner-gateway-gclmz               1/1     Running   0          12m
submariner-operator-8446795d99-jk7xt   1/1     Running   0          13m
submariner-routeagent-4tjmm            1/1     Running   0          12m
submariner-routeagent-9m9zx            1/1     Running   0          12m
submariner-routeagent-mzkh4            1/1     Running   0          12m
submariner-routeagent-wtf2w            1/1     Running   0          12m

op_pod=submariner-gateway-fz4rh

/home/nmanos/automation/ocp-install/oc exec submariner-gateway-fz4rh -n submariner-operator -- bash -c "swanctl --list-sas"
connecting to 'unix:///run/strongswan/charon.vici' failed: No such file or directory
Error: connecting to 'default' URI failed: No such file or directory
strongSwan 5.8.2 swanctl
command terminated with exit code 2
```

[StrongSwan connecting to default URI failed.log](https://github.com/submariner-io/submariner/files/4305589/StrongSwan.connecting.to.default.URI.failed.log)

**Comment by sridhargaddam** [comment]
Just for record: When more than one node is labelled as SubmarinerGateway capable node, submariner engine (that runs as a DaemonSet) will run on both the nodes. However, only one of them will be the active gateway node for the cluster. The above logs are seen on the non-Gateway/Backup node where Charon daemon is not running, hence the error.

**Comment by manosnoam** [comment]
Seems to be caused by URI path, this seems to be responding correctly:

```
[nmanos@nmanos ocp-install]$ kubconf_a oc exec submariner-gateway-4tgkx -n submariner-operator -- bash -c "swanctl --list-sas --uri unix:///var/run/charon.vici"
submariner-cable-nmanos-cluster-b-tunnel-10-166-0-13: #1, CONNECTING, IKEv2, 55cb5ae27d7402d7_i* 0000000000000000_r
  local  '%any' @ 10.0.132.20[501]
  remote '%any' @ 66.187.233.202[4501]
  active:  IKE_VENDOR IKE_INIT IKE_NATD IKE_CERT_PRE IKE_AUTH IKE_CERT_POST IKE_CONFIG CHILD_CREATE IKE_AUTH_LIFETIME
```

**Comment by manosnoam** [comment]
On latest Submariner (0.3.0), the URI "unix:///var/run/charon.vici" is not working either:

```
oc exec submariner-gateway-jwk68 -n submariner-operator -- bash -c swanctl --list-sas --uri unix:///var/run/charon.vici
connecting to 'unix:///var/run/charon.vici' failed: No such file or directory
Error: connecting to 'unix:///var/run/charon.vici' URI failed: No such file or directory
```

@sridhargaddam, can you point me to the correct URI to validate StrongSwan status ?

**Comment by manosnoam** [comment]
Attaching pod log:
[charon_check_should_wait_longer.log](https://github.com/submariner-io/submariner/files/4621168/charon_check_should_wait_longer.log)

@mangelajo suggested we should wait some time before reporting connection errors to charon, to avoid missleading logs.

However, according to the log, this error seems to be related to charon.vici path, but not to the IKE charon daemon.

**Comment by sridhargaddam** [comment]
Please use the new Gateway objects with kubectl that @mangelajo implemented recently in Submariner. The Gateway object would abstract the implementation details of driver (like Strongswan, Wireguard etc) and provides a consistent API to consume the status of the connection.

kubectl get Gateway -A -o yaml
