### ISSUE TITLE
Globalnet Controller is not annotating Services without selectors

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#460]
Setup: Overlapping Clusters with Submariner Globalnet deployed. 

Services without selectors i.e no backend pod, are not accessible across clusters if globalnet is enabled. It works when clusters don't have overlapping CIDRs and globalnet is not used.

**Comment by mangelajo** [comment]
But what if the service without selectors is pointing to local cluster pods?

**Comment by mangelajo** [comment]
Ahh sorry I see it was implemented, cool
