### ISSUE TITLE
Automation of the release process as a whole.

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#468]
adding noam and me , since will relate 
to the CI-CD testing effort

**Comment by nyechiel** [comment]
https://github.com/submariner-io/submariner/pull/600

**Comment by manosnoam** [comment]
Please see how to automate release tags and labels, without manually updating them.
For example, the following label and tag should be auto-generated each release:

- "Latest release" (green label):
https://github.com/submariner-io/submariner-operator/releases/latest leads to v0.3.1, and not to the latest one (0.4.0 RC2)

- "latest" tag (found under Tags):
- https://github.com/submariner-io/submariner-operator/releases/tag/latest leads to even older version (from April).

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
@mkolesnik I think that at this point we can go ahead and close this Issue. There are always going to be more improvements, but I think we better track them with concrete Issues/PRs. Wdyt?

**Comment by mkolesnik** [comment]
Created specific issues to track the rest of the work remaining:

https://github.com/submariner-io/releases/issues/75
https://github.com/submariner-io/releases/issues/76
