### ISSUE TITLE
Investigate Chaos Monkey-style tests

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#472]
Explore the options for tests that are of the Chaos Monkey style - ie they "randomly" break parts of the deployment and validate we can recover.

Early discussions with a potential user highlighted this as a type of testing they would need to see before adopting Submariner.

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
Should look into: https://github.com/chaos-mesh/chaos-mesh

**Comment by dfarrell07** [comment]
Bump, I still think we should look into this in the medium-term.
