### ISSUE TITLE
How many clusters can a broker cluster register at most, and how about its performance

### ISSUE THREAD

**Issue by 1093439315** [submariner-io/submariner#517]
### GitHub Username
e.g. (at)1093439315@qq.com

How many clusters can a broker cluster register at most, and how about its performance?

**Comment by dfarrell07** [comment]
Thanks for the question! /cc @mangelajo @sridhargaddam

**Comment by mangelajo** [comment]
Sorry, this question is still valid. We haven't performed scalability testing yet, @1093439315 did you have any target numbers or examples of what you're looking for?

**Comment by mangelajo** [comment]
Please @1093439315, track  https://github.com/submariner-io/submariner/issues/861 for information, I'll post there as soon as we have some numbers available.

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
We have plans to work on simulating scale testing in 0.9.

https://github.com/submariner-io/submariner/issues/861

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by jinglina** [comment]
Any further disscussions?
