### ISSUE TITLE
Network is unreachable error from route agent in GCP

### ISSUE THREAD

**Issue by hyunsun** [submariner-io/submariner#520]
I just deployed Submariner to a K8S cluster on GCP VMs, and found that route-agent cannot add routes to the gateway node because GCP VM get assigned /32 IP.
```
E0423 05:47:28.693920       1 route.go:385] error while adding route {Ifindex: 2 Dst: 10.44.0.0/17 Src: <nil> Gw: 10.168.0.14 Flags: [] Table: 0}: network is unreachable
E0423 05:47:28.694012       1 route.go:385] error while adding route {Ifindex: 2 Dst: 10.44.128.0/17 Src: <nil> Gw: 10.168.0.14 Flags: [] Table: 0}: network is unreachable
```

Does Submariner not support GCP? Or is there a way to work around this error?

**Comment by mangelajo** [comment]
Hey @hyunsun , we can try to help figure this out.

While using GKE, I spent some time on it, and I almost got it, but still something is missing: 
https://github.com/submariner-io/submariner-website/pull/33

Which flavor of K8s and which CNI are you using on top of the GCP VMs?,

 feel free to ping us in the submariner k8s slack #submariner channel: https://kubernetes.slack.com/archives/C010RJV694M you can find me as @Miguel Angel Ajo in there.

**Comment by hyunsun** [comment]
Hi @mangelajo, thanks for your reply.
I'm using k8s 1.15.11 and Calico as CNI.
Will ping you on Slack.

**Comment by mangelajo** [comment]
Hmm, may be it's related to calico, I believe we have tested so far with:
* flannel
* flannel + canal (although we have an existing issue there)
* openshift-sdn
* weave works

I see this one related to calico opened by @roytman https://github.com/submariner-io/submariner/issues/407

**Comment by hyunsun** [comment]
Confirmed it works fine with weave CNI and subctl 0.2.0.
Thanks for your help.
[This link](https://github.com/hyunsun/documentations/wiki/Rancher-Submariner-Test) includes the instructions that I used for the quick test.
Hope this helps :)

**Comment by mangelajo** [comment]
@hyunsun nice, I see you also tried the darwin binary of subctl :-)

I wonder if we could use parts of your link as a section for the website we are building, as a "Quickstart" for rancher

@Oats87  ^  :-)

**Comment by hyunsun** [comment]
@mangelajo Sure.

**Comment by nyechiel** [comment]
@mangelajo @hyunsun is there anything else we need to track in here or we can close this Issue at this point?

**Comment by mangelajo** [comment]
I believe we can close it.
