### ISSUE TITLE
Fix PANIC in Submariner seen on LH builds in CI

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#529]
Lighthouse builds are failing with the following error.

E0430 07:33:06.632456       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/submariner-io/submariner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/submariner-io/submariner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/submariner-io/submariner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/golang/src/runtime/panic.go:679
/usr/lib/golang/src/runtime/panic.go:199
/usr/lib/golang/src/runtime/signal_unix.go:394
/go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/driver.go:75
/go/src/github.com/submariner-io/submariner/vendor/k8s.io/client-go/util/retry/util.go:64
/go/src/github.com/submariner-io/submariner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203
/go/src/github.com/submariner-io/submariner/vendor/k8s.io/client-go/util/retry/util.go:63
/go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/driver.go:66
/go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/route.go:220
/go/src/github.com/submariner-io/submariner/pkg/routeagent/main.go:94
/usr/lib/golang/src/runtime/asm_amd64.s:1357
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf8193c]

goroutine 33 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1137020, 0x1c7e440)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
github.com/submariner-io/submariner/pkg/routeagent/controllers/route.(*Controller).annotateNodeWithCNIInterfaceIP.func1(0xc0003fa000, 0xc0000191f0)
	/go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/driver.go:75 +0x11c
k8s.io/client-go/util/retry.RetryOnConflict.func1(0x98, 0x98, 0xc0000d65a0)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/client-go/util/retry/util.go:64 +0x33
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc0003d3230, 0xa0, 0x11ca9c0)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203 +0xde
k8s.io/client-go/util/retry.RetryOnConflict(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc0000192a8, 0xa, 0xc0000d6628)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/client-go/util/retry/util.go:63 +0xa0
github.com/submariner-io/submariner/pkg/routeagent/controllers/route.(*Controller).annotateNodeWithCNIInterfaceIP(0xc00012a2a0, 0xc000424b70, 0xf, 0x1, 0xc000019510)
	/go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/driver.go:66 +0xb1
github.com/submariner-io/submariner/pkg/routeagent/controllers/route.(*Controller).Run(0xc00012a2a0, 0xc0000a8660, 0x0, 0x0)
	/go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/route.go:220 +0xbb0
main.main.func1(0xc0002e2940, 0xc00012a2a0, 0xc0000a8660, 0xc000209530)
	/go/src/github.com/submariner-io/submariner/pkg/routeagent/main.go:94 +0x84
created by main.main
	/go/src/github.com/submariner-io/submariner/pkg/routeagent/main.go:92 +0x80f

**Comment by mangelajo** [comment]
Fix was merged
