### ISSUE TITLE
Categorize intermittent failures in CI

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#532]
It seems that we have some sporadic failures in CI, and that they are related to non-Submariner parts of the CI deployment. However, to really see the pattern and resole it, we need to document the rare-ish failures. Use this issue collect logs from sporadic CI failures.

For example:

Repo: submariner-io/submariner
Job: `CMD="make e2e" CLUSTERS_ARGS="--globalnet" DEPLOY_ARGS="${CLUSTERS_ARGS} --deploytool helm"`
Failure summary: E2E connection tests timeout
Logs: https://pastebin.com/0AWQt1pp

- [ ] Globalnet sub-issue: https://github.com/submariner-io/submariner/issues/544

**Comment by dfarrell07** [comment]
Repo: submariner-io/submariner
Job: CMD="make e2e" CLUSTERS_ARGS="--globalnet" DEPLOY_ARGS="${CLUSTERS_ARGS} --deploytool helm"
Failure summary: Gateway fail-over test failure
Logs: https://pastebin.com/qxdzusfd

**Comment by dfarrell07** [comment]
Repo: submariner-io/submariner
Job: `CMD="make e2e" RELEASE=true`
Failure summary: Gateway fail-over tests
Logs: https://github.com/submariner-io/submariner/pull/526#issuecomment-621361178

Repo: submariner-io/submariner
Job: `CMD="make e2e" CLUSTERS_ARGS="--globalnet true" DEPLOY_ARGS="${CLUSTERS_ARGS} --deploytool helm"`
Failure summary: Travis timeout at 10m no output
Logs: https://github.com/submariner-io/submariner/pull/526#issuecomment-621361178

**Comment by dfarrell07** [comment]
Repo: Shipyard
Job: Undocumented
Failure summary: Weave deployment failure
Logs: https://github.com/submariner-io/shipyard/pull/122#issuecomment-620573349

**Comment by dfarrell07** [comment]
Repo: Lighthouse
Job: `CMD="make e2e deploytool=helm"`
Failure summary: Timeout after 10m in output, in Weave section of deploy
Logs: https://pastebin.com/A6iBzNGq

Repo: Lighthouse
Job: `CMD="make e2e delpoytool=operator" RELEASE=true`
Failure summary: Failure while running clusters.sh, just after Weave deploy
Logs: https://pastebin.com/7rYT0rPU

**Comment by dfarrell07** [comment]
Repo: Submariner
Job: `CMD="make e2e" CLUSTERS_ARGS="--globalnet" DEPLOY_ARGS="${CLUSTERS_ARGS} --deploytool helm"`
Failure summary: [Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
Logs: https://pastebin.com/zEf5e0ZB

**Comment by mangelajo** [comment]
I see two categories: globalnet, and weave, right?

Thanks @dfarrell07 for tracking this, I think it's very helpful.

**Comment by dfarrell07** [comment]
Repo: Shipyard
Job:  `make deploy`
```
  env:
    CLUSTERS_ARGS:  --timeout 1m
    DEPLOY_ARGS:  --deploytool helm --timeout 2m
```
Failure summary: "Error: EOF" on Helm-based Sumariner install
Logs: https://pastebin.com/wH5RiJDz
https://github.com/submariner-io/shipyard/pull/149/checks?check_run_id=666918597

**Comment by dfarrell07** [comment]
Repo: Submariner
Job: `e2e (--globalnet, operator)`
Failure summary: `[Fail] [redundancy] Gateway fail-over tests when a new node is labeled as a gateway node and the label on the existing gateway node is removed [It] should start a submariner engine on the new gateway node and be able to connect from another cluster`
Logs: https://pastebin.com/TvY8PTWY

**Comment by sridhargaddam** [comment]
> Repo: Submariner
> Job: `e2e (--globalnet, operator)`
> Failure summary: `[Fail] [redundancy] Gateway fail-over tests when a new node is labeled as a gateway node and the label on the existing gateway node is removed [It] should start a submariner engine on the new gateway node and be able to connect from another cluster`
> Logs: https://pastebin.com/TvY8PTWY

The following PR would fix this issue.
https://github.com/submariner-io/submariner/pull/610

**Comment by mangelajo** [comment]
Repo: Submariner-operator
Job: e2e (lighthouse)
Failure summary: failed curl via netshoot.

Logs: https://github.com/submariner-io/submariner-operator/runs/729933188?check_suite_focus=true

Postmortem seems to be ok, we need more info, like gateway status, etc.

**Comment by dfarrell07** [comment]
I think most/all of the sources of instability we have documented here have been resolved. There have been many incremental improvements to stability on many fronts (@sridhargaddam on Globalnet this sprint, @mkolesnik with Shipyard/CI retries last sprint, etc). Maybe I will close this now? We can re-open if we need later, or start a fresh Issue if instability shows up again.
