### ISSUE TITLE
Submariner Gateway POD is being restarted sometimes...

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#540]
On a VSphere environment, it was seen that after leaving the setup for few days (4 in this example), Submariner Gateway POD was restarted a few times.

We have to identify the reasons why Gateway POD is restarted. Incase its done by K8s, then we have to see if we can do something to reduce/optimize it.

![9](https://user-images.githubusercontent.com/6574656/80948444-b7f28780-8e0f-11ea-9a33-9eeffdebcb51.png)

Note: Currently we have a known [issue](https://github.com/submariner-io/submariner/issues/386) where datapath will be disrupted (as IPSEC tunnel is terminated) when GW POD is restarted.

**Comment by mangelajo** [comment]
Did you look at the status of the daemonset?, It should provide a record of the issues?

kubectl describe Daemonset submariner-gateaway -n submariner-operator

**Comment by mangelajo** [comment]
Adding you as assignee as you are the only one with vspheres :D

**Comment by sridhargaddam** [comment]
> kubectl describe Daemonset submariner-gateaway -n submariner-operator

Yes, I had a look, but could not find anything interesting.

[sgaddam@localhost mcm-cluster1]$  kubectl describe Daemonset submariner-gateway -n submariner-operator 
Name:           submariner-gateway
Selector:       app=submariner-engine
Node-Selector:  submariner.io/gateway=true
Labels:         app=submariner-engine
                component=engine
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 1
Current Number of Nodes Scheduled: 1
Number of Nodes Scheduled with Up-to-date Pods: 1
Number of Nodes Scheduled with Available Pods: 1
Number of Nodes Misscheduled: 0
Pods Status:  1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=submariner-engine
  Service Account:  submariner-operator
  Containers:
   submariner:
    Image:      quay.io/submariner/submariner:0.3.0-rc1
    Port:       <none>
    Host Port:  <none>
    Command:
      submariner.sh
    Environment:
      SUBMARINER_NAMESPACE:        submariner-operator
      <SNIP>
      CE_IPSEC_NATTPORT:           4500
    Mounts:                        <none>
  Volumes:                         <none>
Events:                            <none>
[sgaddam@localhost mcm-cluster1]$

**Comment by sridhargaddam** [comment]
Also, output of describe pod.
kubectl describe pod submariner-gateway-sx6h4 -n submariner-operator
Name:               submariner-gateway-sx6h4
Namespace:          submariner-operator
Priority:           0
PriorityClassName:  <none>
Node:               compute-1/10.19.114.246
Start Time:         Thu, 30 Apr 2020 00:08:52 +0530
Labels:             app=submariner-engine
                    controller-revision-hash=86dfb49d74
                    pod-template-generation=1
Annotations:        openshift.io/scc: privileged
Status:             Running
IP:                 10.19.114.246
Controlled By:      DaemonSet/submariner-gateway
Containers:
  submariner:
    Container ID:  cri-o://7fc78174836b1e9a516baae692f212bf1ae3151b76bb5e914954b41d352935ae
    Image:         quay.io/submariner/submariner:0.3.0-rc1
    Image ID:      quay.io/submariner/submariner@sha256:defd471fba09602bda9b5db71b0a3b459cd46d8620f993f30cb7e50b52f0caf2
    Port:          <none>
    Host Port:     <none>
    Command:
      submariner.sh
    State:          Running
      Started:      Sat, 02 May 2020 19:42:32 +0530
    **Last State:     Terminated
      Reason:       Error
      Exit Code:    255**
      Started:      Sat, 02 May 2020 15:39:05 +0530
      Finished:     Sat, 02 May 2020 19:42:31 +0530
    Ready:          True
    **Restart Count:  9**
    Environment:

<SNIP>

Volumes:
  submariner-operator-token-fbrn2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  submariner-operator-token-fbrn2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  submariner.io/gateway=true
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:          <none>
[sgaddam@localhost mcm-cluster1]$ 
[sgaddam@localhost mcm-cluster1]$ 
[sgaddam@localhost mcm-cluster1]$ kubectl describe pod submariner-gateway-sx6h4 ^C
[sgaddam@localhost mcm-cluster1]$ kubectl get events -n submariner-namespace 
No resources found.
[sgaddam@localhost mcm-cluster1]$

**Comment by sridhargaddam** [comment]
> Adding you as assignee as you are the only one with vspheres :D

haha..I wish I had permanent access to VSphere. I'll be losing access to the setup shortly. Also, I **think** this is not specific to VSphere alone but might be applicable to other environments as well. Understanding the possible reasons when a POD would be restarted might give us some pointers.

**Comment by dfarrell07** [comment]
Can you check the logs of the submariner-operator Pod @sridhargaddam?

**Comment by sridhargaddam** [comment]
> Can you check the logs of the submariner-operator Pod @sridhargaddam?

[sgaddam@localhost mcm-cluster1]$ kubectl logs submariner-operator-56dd49d66f-cbbzw -n submariner-operator
{"level":"info","ts":1588185517.2164085,"logger":"cmd","msg":"Go Version: go1.13.9"}
{"level":"info","ts":1588185517.216461,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1588185517.2164693,"logger":"cmd","msg":"Version of operator-sdk: v0.10.0+git"}
{"level":"info","ts":1588185517.2169938,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1588185519.8006594,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1588185519.8084476,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1588185522.3653545,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1588185522.36613,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1588185522.3664217,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"servicediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1588185522.3666048,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"servicediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1588185522.3668058,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"submariner-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1588185522.3669128,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"submariner-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1588185530.0556219,"logger":"metrics","msg":"Metrics Service object created","Service.Name":"submariner-operator-metrics","Service.Namespace":"submariner-operator"}
{"level":"info","ts":1588185532.6902711,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1588185532.6905887,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1588185532.79071,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"servicediscovery-controller"}
{"level":"info","ts":1588185532.7907186,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"submariner-controller"}
{"level":"info","ts":1588185532.8910124,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"submariner-controller","worker count":1}
{"level":"info","ts":1588185532.8910122,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"servicediscovery-controller","worker count":1}
{"level":"info","ts":1588185532.8911874,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588185532.930283,"logger":"controller_submariner","msg":"Created a new DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588185532.9374075,"logger":"controller_submariner","msg":"Created a new DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588185532.9453664,"logger":"controller_submariner","msg":"Created a new DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588185532.9707854,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588185532.9921052,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588185533.020806,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588185533.0457008,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588185533.0592778,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588185533.0769486,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588185533.0827503,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588185533.0871472,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
E0430 04:12:21.481273       1 reflector.go:270] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1alpha1.ServiceDiscovery: Get https://172.30.0.1:443/apis/submariner.io/v1alpha1/namespaces/submariner-operator/servicediscoveries?resourceVersion=5903583&timeoutSeconds=535&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
{"level":"info","ts":1588219943.3942733,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588219943.4174502,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588219943.4368198,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588219943.4559102,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588219943.4719362,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588219943.4914196,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588219943.498263,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588219943.5044224,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588255943.3946571,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588255943.412149,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588255943.4180937,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588255943.4244964,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588291943.3949087,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588291943.4100816,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588291943.415272,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588291943.4199548,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588327943.395159,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588327943.4124048,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588327943.4170442,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588327943.4217668,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588363943.3953574,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588363943.4107661,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588363943.4162712,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588363943.4229584,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588399943.395857,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588399943.4256604,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588399943.4320164,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588399943.4374118,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588435943.4094212,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588435943.5800107,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588435943.5895097,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588435943.5938554,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588471943.396263,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588471943.4244235,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588471943.4308395,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588471943.435298,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588507943.3964207,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588507943.4109676,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588507943.4156296,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588507943.420484,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588543943.3966432,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588543943.411096,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588543943.416015,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588543943.4199765,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
{"level":"info","ts":1588579943.3968146,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
{"level":"info","ts":1588579943.4111168,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-gateway"}
{"level":"info","ts":1588579943.4170272,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-routeagent"}
{"level":"info","ts":1588579943.4219456,"logger":"controller_submariner","msg":"Updated existing DaemonSet","Request.Namespace":"submariner-operator","Request.Name":"submariner","DaemonSet.Namespace":"submariner-operator","DaemonSet.Name":"submariner-globalnet"}
[sgaddam@localhost mcm-cluster1]$

**Comment by dfarrell07** [comment]
Yeah, I think that's the source of the restarting - you can see the multiple reconciling/updating DaemonSet loops.

**Comment by dfarrell07** [comment]
@sridhargaddam can you also include a `get pod` on the submariner-operator? Maybe there is something useful in the status we are reporting.

**Comment by sridhargaddam** [comment]
> @sridhargaddam can you also include a `get pod` on the submariner-operator? Maybe there is something useful in the status we are reporting.

[sgaddam@localhost mcm-cluster1]$ kubectl describe pod submariner-operator-56dd49d66f-cbbzw -n submariner-operator    
Name:               submariner-operator-56dd49d66f-cbbzw
Namespace:          submariner-operator
Priority:           0
PriorityClassName:  <none>
Node:               compute-1/x.x.x.x
Start Time:         Thu, 30 Apr 2020 00:08:34 +0530
Labels:             name=submariner-operator
                    pod-template-hash=56dd49d66f
Annotations:        k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "openshift-sdn",
                          "interface": "eth0",
                          "ips": [
                              "x.x.x.x"
                          ],
                          "dns": {},
                          "default-route": [
                              "x.x.x.x"
                          ]
                      }]
                    openshift.io/scc: restricted
                    submariner.io/globalIp: 169.254.57.89
Status:             Running
IP:                 x.x.x.x
Controlled By:      ReplicaSet/submariner-operator-56dd49d66f
Containers:
  submariner-operator:
    Container ID:  cri-o://8083beb3b4aa3c40ea85c1ff9b55f80df4b557be9d6fa419aaeea8aa5d829da9
    Image:         quay.io/submariner/submariner-operator:0.3.0-rc1
    Image ID:      quay.io/submariner/submariner-operator@sha256:a435511fba8d04e407575c7f6d8bdfeb28e111e3e950494c92cb332686dec5e6
    Port:          <none>
    Host Port:     <none>
    Command:
      submariner-operator
    State:          Running
      Started:      Thu, 30 Apr 2020 00:08:37 +0530
    Ready:          True
    Restart Count:  0
    Environment:
      WATCH_NAMESPACE:  submariner-operator (v1:metadata.namespace)
      POD_NAME:         submariner-operator-56dd49d66f-cbbzw (v1:metadata.name)
      OPERATOR_NAME:    submariner-operator
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from submariner-operator-token-fbrn2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  submariner-operator-token-fbrn2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  submariner-operator-token-fbrn2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
[sgaddam@localhost mcm-cluster1]$

**Comment by sridhargaddam** [comment]
@dfarrell07 as discussed with you over slack, assigning this to you.

**Comment by sridhargaddam** [comment]
I see that we have an option to get the logs of previous POD by supplying "--previous" to "kubectl logs ..." command. When I ran this command on Gateway POD, I found something interesting in the logs.

Basically, it appears like GatewayPOD is not able to renew its lease for the leaderLock, and OnStoppedLeading[*] gets called where we issue "klog.Fatalf" and GW POD terminates (and gets restarted). Currently, the RenewDeadline interval is set to 3 secs in Submariner. Yet to understand why GatewayPOD was not able to renew in the RenewDeadline interval. One possible workaround to this issue is to increase the leaderElection intervals.

[*] https://github.com/submariner-io/submariner/blob/bea7b6d995e069fc14b0fbda0ecf3a43496f5354/main.go#L276

I0502 14:12:06.498611       1 kubernetes.go:355] Endpoint "west-submariner-cable-west-10-19-114-246" matched what we received from datastore - not updating
I0502 14:12:31.290744       1 leaderelection.go:249] failed to renew lease submariner-operator/submariner-engine-lock: failed to tryAcquireOrRenew context deadline exceeded
F0502 14:12:31.290811       1 main.go:271] Leader election lost
goroutine 1 [running]:
k8s.io/klog.stacks(0xc000250600, 0xc000028000, 0x40, 0x1c3)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:828 +0xb8
k8s.io/klog.(*loggingT).output(0x1c6e840, 0xc000000003, 0xc00010e700, 0x1bea0b8, 0x7, 0x10f, 0x0)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:779 +0x351
k8s.io/klog.(*loggingT).printf(0x1c6e840, 0x3, 0x1297d98, 0x14, 0x0, 0x0, 0x0)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:678 +0x14b
k8s.io/klog.Fatalf(...)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:1207
main.startLeaderElection.func1()
        /go/src/github.com/submariner-io/submariner/main.go:271 +0x5b
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc0004b61e0)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:163 +0x40
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0004b61e0, 0x1441620, 0xc00004e780)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:172 +0x15e
k8s.io/client-go/tools/leaderelection.RunOrDie(0x1441660, 0xc0000ba008, 0x144b4c0, 0xc000450a20, 0x12a05f200, 0xb2d05e00, 0x77359400, 0xc00034c8c0, 0x13149f0, 0x0, ...)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:184 +0x96
main.startLeaderElection(0x1473ea0, 0xc00035c240, 0x1441a60, 0xc000454380, 0xc00034c8c0)
        /go/src/github.com/submariner-io/submariner/main.go:263 +0x6e3
main.main()
        /go/src/github.com/submariner-io/submariner/main.go:207 +0xdae

**Comment by dfarrell07** [comment]
As discussed on Slack, per @sridhargaddam's latest info above it doesn't seem to be an Operator problem. Unassigning myself.

**Comment by sridhargaddam** [comment]
Okay, looks like leader election interval alone is not the only reason for the restart scenario. In a fresh deployment, I found that SM Gateway POD got restarted twice and the logs are as shown.

I0504 16:06:47.912358       1 kubernetes.go:355] Endpoint "west-submariner-cable-west-10-19-114-235" matched what we received from datastore - not updating
W0504 16:06:48.903462       1 strongswan.go:534] **Failed to connect to charon - retrying: dial unix /var/run/charon.vici: connect: no such file or directory**
F0504 16:06:49.903660       1 main.go:177] Error starting the cable engine: failed to load connections from charon: dial unix /var/run/charon.vici: connect: no such file or directory
goroutine 84 [running]:
k8s.io/klog.stacks(0xc00025c600, 0xc000166000, 0xb7, 0xea)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:828 +0xb8
k8s.io/klog.(*loggingT).output(0x1c6e840, 0xc000000003, 0xc00010a0e0, 0x1bea0b8, 0x7, 0xb1, 0x0)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:779 +0x351
k8s.io/klog.(*loggingT).printf(0x1c6e840, 0x3, 0x12a7166, 0x23, 0xc0004b3fa0, 0x1, 0x1)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:678 +0x14b
k8s.io/klog.Fatalf(...)
        /go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:1207
main.main.func1.1(0xc000049410, 0x144b100, 0xc00038c8c0, 0xc0002416d0)
        /go/src/github.com/submariner-io/submariner/main.go:177 +0x10c
created by main.main.func1
        /go/src/github.com/submariner-io/submariner/main.go:174 +0x609

After the GW Pod got restarted, it's continuing to run fine (about two hours now).

**Comment by mangelajo** [comment]
> F0504 16:06:49.903660 1 main.go:177] **Error starting the cable engine:** failed to load connections from charon: dial unix /var/run/charon.vici: connect: no such file or directory

> After the GW Pod got restarted, it's continuing to run fine (about two hours now).

Ok, this one seems like a different issue just a startup. I guess we need to allow more time for charon to start, and and add more retries. Finally if it does not start for some reason the right thing is to quit trying, then other gateway node can try to set it up.
