### ISSUE TITLE
Include necessary utilities (or dnf) in Gateway POD

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#541]
As part of reducing the size of Gateway Engine, we have removed dnf. But this is going to make debugging issues a lot more difficult as we do not have necessary utils (like tcpdump, conntrack etc) and cannot install them. For a production environment, it makes sense to strip off everything that is not necessary, but for our day-to-day installations of Submariner, it might be worth to include dnf or the necessary utils.

**Comment by skitt** [comment]
I think most debugging scenarios (checking the networking setup, `iptables` rules etc.) are better addressed by starting a separate network debugging container alongside the engine (_e.g._ based on netshoot). See also [Using sidecars to analyze and debug network traffic in OpenShift and Kubernetes pods](https://developers.redhat.com/blog/2019/02/27/sidecars-analyze-debug-network-traffic-kubernetes-pod/).

In other scenarios, tools such as `oc-inject` can be used to inject arbitrary binaries into a running container; see [Installing debugging tools into a Red Hat OpenShift container with oc-inject](https://developers.redhat.com/blog/2020/01/15/installing-debugging-tools-into-a-red-hat-openshift-container-with-oc-inject/) for details.

Similar approaches are possible in non-OpenShift Kubernetes setups.

**Comment by sridhargaddam** [comment]
Thanks @skitt for your inputs and possible alternatives. 

In the meantime, can someone share how much improvement (in size) we see by removing this from the Gateway Pods?
@mkolesnik @mangelajo @dfarrell07

**Comment by skitt** [comment]
We recently changed the gateway container images to keep `microdnf` installed, so I’m not sure this is still relevant.

**Comment by sridhargaddam** [comment]
> We recently changed the gateway container images to keep `microdnf` installed, so I’m not sure this is still relevant.

Cool. Yeah, I see microdnf in the Gateway/Globalnet pods. Thanks.
