### ISSUE TITLE
Detect overlapping CIDRs in Submariner

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#545]
Currently overlapping global/Pod/Service CIDRs validation for clusters is done in subctl, but when clusters are deployed with helm we do not have any mechanism to alert the user.
We can enhance Submariner to detect this overlap and fail fast with an appropriate error message.

**Comment by mangelajo** [comment]
I think this is more  to go on the operator.

**Comment by sridhargaddam** [comment]
> I think this is more to go on the operator.

No @mangelajo. The idea is to handle this in the Submariner Globalnet Code itself. If GN Controller detects that globalCIDRs of multiple clusters are overlapping, it can return FATAL and fail early.

**Comment by mangelajo** [comment]
Please don’t fail fatal :-) may be we can mark the new overlapping cluster and use some sort of reporting to make it evident.

Let’s think of production clusters . If the admin makes a mistake, let’s try to report and minimize the problems. If we fail fatal we will kill the GN connectivity of new spawning pods. 

I’d try to detect and mark the new cluster that overlaps. The use some mean of reporting this to make it evident.

Enviado desde mi iPhone

**Comment by sridhargaddam** [comment]
> Please don’t fail fatal :-) may be we can mark the new overlapping cluster and use some sort of reporting to make it evident.

Ack. What is the best place to report this issue? Gateway Status?

> Let’s think of production clusters . If the admin makes a mistake, let’s try to report and minimize the problems. If we fail fatal we will kill the GN connectivity of new spawning pods.

This detection happens when the GN Pod (or Submariner Gateway Pod?) is booting up in **a newly joined cluster**. So, what do you mean by "we will kill the GN connectivity of new spawning pods"? We cannot support GN globalIP use-case if the globalCIDRs overlap across the cluster. 

> I’d try to detect and mark the new cluster that overlaps. The use some mean of reporting this to make it evident. 

Sure, if you have any ideas/suggestions on where we can report this, we can do the necessary changes instead of returning FATAL.

Enviado desde mi iPhone
> […](#)
> El 5 may 2020, a las 16:41, Sridhar Gaddam ***@***.***> escribió: ﻿ I think this is more to go on the operator. No @mangelajo. The idea is to handle this in the Submariner Globalnet Code itself. If GN Controller detects that globalCIDRs of multiple clusters are overlapping, it can return FATAL and fail early. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sridhargaddam** [comment]
Addressed via - https://github.com/submariner-io/submariner/pull/570
