### ISSUE TITLE
WireGuard doesn't seem to be working with globalnet

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner#552]
Running in this combination, it seems the E2E tests are failing

See also https://github.com/submariner-io/submariner/pull/551/checks?check_run_id=652184597

The logs are attached as well - 
[logs_13.zip](https://github.com/submariner-io/submariner/files/4591708/logs_13.zip)

**Comment by mangelajo** [comment]
ping @deanlorenz @roytman  ^

**Comment by deanlorenz** [comment]
ACK. Will look into it.
Probably has to do with finding the local interface ip -- with globalnet there is no local interface with a global IP, so no interface with an allowed IP.

**Comment by deanlorenz** [comment]
[c3.3.log](https://github.com/submariner-io/submariner/files/4608701/c3.3.log)
driver is being called with empty public key. 
remove EP called before init

**Comment by deanlorenz** [comment]
[e2e-tcpdump-dp-gn.log](https://github.com/submariner-io/submariner/files/4612279/e2e-tcpdump-dp-gn.log)
[e2e-tests-dp-gn.log](https://github.com/submariner-io/submariner/files/4612280/e2e-tests-dp-gn.log)

- e2e tests with focus=dataplane-globalnet
- 5 of 6 tests pass, WG config and routes look as expected
- Failed test does not get SNAT to GN so gets dropped and times-out -- *seems to be a problem in GN IPT*
- redundancy test also causes GN-DP failures (see log in previous comment) -- engine breaks the cable driver with corrupt endpoint entries

**Comment by mangelajo** [comment]
The issue was fixed by https://github.com/submariner-io/submariner/pull/562
