### ISSUE TITLE
Globalnet Controller should skip annotating master nodes with globalip

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#553]

**Comment by mangelajo** [comment]
I'm not sure if this is necessarily a bug in some cases (where the master nodes are also used as workers?)

**Comment by sridhargaddam** [comment]
> I'm not sure if this is necessarily a bug in some cases (where the master nodes are also used as workers?)

Okay, basically what happens is that submariner-route-agent that runs ONLY on the worker node annotates the respective node with the cniInterfaceIP annotation. Globalnet controller has a listener for nodes and will wait for this annotation before it can program rules for HostNetwork to remoteCluster support. It was seen that since master nodes were constantly getting re-queued as the annotation was missing. The idea is that GN controller can check if the node is capable of scheduling pods (aka worker node) and only then re-queue the node if annotation is missing.

**Comment by sridhargaddam** [comment]
This is addressed
