### ISSUE TITLE
DNS leak on e2e tests

### ISSUE THREAD

**Issue by deanlorenz** [submariner-io/submariner#568]
@sridhargaddam @mangelajo, could be related to #567
External DNS bombarded with PTRs to internal addresses.

Example:
![image](https://user-images.githubusercontent.com/8469923/81968311-e731a180-9624-11ea-97a3-a690849fcb8a.png)

Produced with `sudo tcpdump -i any udp port 53` on host

Could be related to #567 if only after NXDOMAIN there is a fallback to actual destination (just guessing)

**Comment by mangelajo** [comment]
Try using -n on tcpdump, could be tcpdump trying to resolve the inverse of each ip it sees

**Comment by deanlorenz** [comment]
![dns (2)](https://user-images.githubusercontent.com/8469923/82139063-f2a3e900-982d-11ea-8bcf-debc1690586f.png)

no tcpdump running on the kind nodes.

**Comment by deanlorenz** [comment]
@mangelajo I ran another test to verify -- did not run iptables in kind. Used -n flag. No WG. 
Still many PTR for internal addresses.
Plus, lots of DNS traffic -- mostly to docker.io
