### ISSUE TITLE
REQUEST: New Membership request for maayanf24

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/submariner#574]
### GitHub Username
maayanf24

### Requirements
- [x] I have reviewed the community membership guidelines (https://submariner-io.github.io/en/contributing/community-membership/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have multiple contributions to Submariner that meet the requirements listed in the community membership guidelines
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mkolesnik 
- @mangelajo 

### List of contributions to the Submariner project
- Participating on the upstream meetings.
- https://github.com/submariner-io/submariner-operator/pull/395
- https://github.com/submariner-io/admiral/pull/63

**Comment by mangelajo** [comment]
Updated the "v" for "x" on the checkboxes :)

**Comment by mangelajo** [comment]
@dfarrell07 @tpantelis here we have a point holding us back, she didn't have time yet to make contributions, but she's joined most of the last U/S meetings, and she's hired by one of the participating companies. 

I think it'd be beneficial to consider that point optional, otherwise we can't assign issues/PRs to her.

**Comment by mangelajo** [comment]
@maayanf24 if you start having reviews/PRs, please link them here :) (by the end of the description)

**Comment by mangelajo** [comment]
I'm going propose back this Tuesday on upstream meeting :)

**Comment by mangelajo** [comment]
Welcome @maayanf24 you should have an invite to submariner-contributors.
