### ISSUE TITLE
REQUEST: New committer rights request for mkolesnik

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#575]
### GitHub Username
@mkolesnik 

### Code you are requesting Committer rights for
```
*/.github/workflows/*
*/scripts/
*/Makefile*
*/Dockerfile.dapper
submariner/package
```
-any other CI related bits-

### Requirements
- [x] I have reviewed the community membership guidelines (https://submariner-io.github.io/en/contributing/community-membership/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have been actively contributing to Submariner for at least 3 months
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mangelajo
- @Oats87 

### List of required reviews to Submariner project PRs
- At least 20 PRs to the relevant codebase that you reviewed
- At least 5 PRs to the relevant codebase for which you were the primary reviewer

https://github.com/submariner-io/submariner/pulls?q=is%3Apr+reviewed-by%3Amkolesnik
https://github.com/submariner-io/submariner-operator/pulls?q=is%3Apr+reviewed-by%3Amkolesnik
https://github.com/submariner-io/lighthouse/pulls?q=is%3Apr+reviewed-by%3Amkolesnik

**Comment by mangelajo** [comment]
I'm opening this in the name of @mkolesnik I will let him fill in the form stuff, we need to look for another sponsor, I believe we need to automate somehow the PRs listing ':/

**Comment by mangelajo** [comment]
@Oats87 would you mind sponsoring mike too? he's been doing an amazing work with the CI scripts & shipyard and around all the projects, he knows better than anyone.

**Comment by Oats87** [comment]
@mangelajo I can sponsor Mike

**Comment by mkolesnik** [comment]
Thanks @Oats87 

@mangelajo also need .github/workflows/* :)

**Comment by mangelajo** [comment]
https://github.com/submariner-io/submariner/pull/686
https://github.com/submariner-io/submariner-operator/pull/500
https://github.com/submariner-io/coastguard/pull/15
https://github.com/submariner-io/lighthouse/pull/186
https://github.com/submariner-io/admiral/pull/75
