### ISSUE TITLE
Datastore interface in Submariner is ignoring the colorCodes and returns all the clusters

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#579]
**What happened**:
As per the datastore interface, WatchClusters and WatchEndpoints should only return the clusters/endpoints that we are interested in. However, in the current implementation [*], these APIs simply ignore the color code thereby returning all the clusters/endpoints.

[*] Current implementation of WatchClusters https://github.com/submariner-io/submariner/blob/1aba088eb78062f22850f847eea1befc187bb0b0/pkg/datastore/kubernetes/kubernetes.go#L109

type Datastore interface {
...
// Watches all clusters and calls the passed in function on cluster change
WatchClusters(ctx context.Context, selfClusterID string, colorCodes []string, onClusterChange OnClusterChange) error

// Performs a watch of all endpoints and calls the passed in function based on information
WatchEndpoints(ctx context.Context, selfClusterID string, colorCodes []string, onEndpointChange OnEndpointChange) error
...
}

**What you expected to happen**:
Ideally the interface should return only the clusters that match the respective colorCodes.

**Comment by tpantelis** [comment]
I expect the `Datastore` interface to go away when we migrate to the admiral syncer API. We can implement color code support on top of that.
