### ISSUE TITLE
Report status of endpoints that are skipped 

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#597]
**What happened**:
As part of https://github.com/submariner-io/submariner/issues/545, Submariner avoids making changes to local cluster when remote subnets overlap with local cluster CIDRs.

**What you expected to happen**:
It would be helpful to reflect the status of skipped endpoints to the operator/user so that they are aware of the situation instead of having to look at the logs. This issue is to track the associated changes.

**Comment by sridhargaddam** [comment]
@mangelajo JFYI

**Comment by mangelajo** [comment]
Thanks @sridhargaddam ! :)
