### ISSUE TITLE
GKE (and other VPC-cni clusters) do not allow remote-destined traffic to route

### ISSUE THREAD

**Issue by Oats87** [submariner-io/submariner#6]
When examining the network flow between two clusters (AWS and GKE), it was observed that while IPsec tunnels could be established between the clusters, remote destined traffic to GKE pods that were not on the gateway node was not passed. Looking at this further, the GKE gateway node was trying to pass on traffic with the source IP being the remote (AWS) cluster gateway node, and thus the GKE VPC gateway was rejecting this traffic due to the "bogus" source IP (as it should).

In order to resolve this, we should examine putting an iptables SNAT rule into place on the destination node in order to NAT traffic from the remote cluster to the gateway node IP. Before we do this, we should examine any potential issues that may occur due to this change, and see if we should universally make the change. Otherwise, the change may be introduced as a flag.

The rule that was put into place to conduct this traffic was:
```
iptables -t nat -A POSTROUTING -s <remote-endpoint-ip>/32 -d <cluster/service-cidr> -j SNAT --to-source <local-endpoint-ip>
```

Thank you to @sagargulabanicldcvr for reporting this issue and working with me to debug it

**Comment by Oats87** [comment]
Something to note is that service IP's are already generally NAT'ed through iptables via the kube-proxy rules poked into place, so we don't need to add a SNAT rule for service CIDR's

**Comment by DBarthe** [comment]
Hello @Oats87,

Not sure I understood everything, do you mean submariner always NAT traffic between clusters ?
I guess this would break applications like cassandra that needs direct source IP, or 1:1 NAT equivalent.

**Comment by mangelajo** [comment]
This would be fixed by: https://github.com/submariner-io/submariner/pull/140 I believe, it removes NAT on the datapath
