### ISSUE TITLE
libreswan:  HostNetworking on GW to remote pod not on gateway

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#635]
**What happened**:

Test fails: "[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:139
"

**What you expected to happen**:

Test to pass

**How to reproduce it (as minimally and precisely as possible)**:

Deploy 2 openshift clusters, install submariner, run:
```
subctl verify --only connectivity kubeconfig1 kubeconfig2
```

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
subctl version: dev
built from git ref: v0.4.0-rc2
- Cloud provider or hardware configuration: ocp 4.6 on AWS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`): `4.18.0-147.8.1.el8_1.x86_64`

**Comment by sridhargaddam** [comment]
@mangelajo @skitt 
Okay, I had a look at the setup and the issue is that from the sourcePod (with HostNetworking), traffic is making its way to the destinationPod on remoteCluster. 
However, the source-ip of the pod is the IPAddress of the Host and **NOT** the CNIInterface IP. Because of this, the return traffic is not able to make its way to the source cluster (which is the expected behavior).
The same use-case is working fine in KIND because KIND setup uses a flat network for both the clusters.

I can think of the following two ways to address this issue:

**Solution1:**
On the Gateway Node, add an explicit route to support HostNetworking.
ip route add <remote Pod/SvcCIDR> dev eth0 proto static src <localCNIIfaceIP>
Note: we can also use a specific table like 220, if required.

**Solution2:**
On the Gateway Node, use ipMark to mark remote traffic (i.e., remote Pod/Svc CIDRs)
i.e., iptables -t nat <submariner-chain> -d remoteCidr -j MARK --set-mark <submarinerMark>
Program iptable rule in SUBMARINER-POSTROUTING chain to modify the sourceIP of the traffic to localCNIInterfaceIP for packets that have the <submarinerMark>. This is something similar to what we are doing on non-Gw nodes but instead of using vx-submariner as an identifier we will be using Mark'ing.
i.e., iptables -I SUBMARINER-POSTROUTING -p all -t nat -m mark --mark <submarinerMark> -j SNAT --to <localCNIIfaceIP>

I verified both the solutions and they seem to work fine. 
Before I start making any changes, I'd like to hear your comments and the solution that you prefer (either the ones mentioned above or any other suggestion).

**Comment by skitt** [comment]
Thanks for the detailed analysis @sridhargaddam! I prefer solution 1, or perhaps better still, something can remain Libreswan-specific: it has a `leftsourceip` setting which specifies the source address for packets from the gateway host. I’ll try that out tomorrow; it might even allow us to drop the host-subnet and host-host tunnels...

**Comment by sridhargaddam** [comment]
IMO whatever solution we pursue should go into the route-agent code (just like how its handling the use-case on the non-Gateway node) and not the cable engine. This way, cableEngine will be abstracted from the CNIInterfaceIP stuff. I remember @deanlorenz sharing similar thoughts. 
Thoughts?

**Comment by skitt** [comment]
Right, so the route-agent would take care of _all_ the routing, and the cable engine would only be tasked with providing the point-to-point links between gateways. Would that make sense?
It would also help with the “trusted” scenarios — I’m thinking of a dummy cable engine for cases where the point-to-point link is already present and doesn’t need encryption...

**Comment by mangelajo** [comment]
@sridhargaddam awesome investigation, as usual! :)

I think solution 1 would be more inline with what strongswan & wireguard do.

**Comment by sridhargaddam** [comment]
> Right, so the route-agent would take care of _all_ the routing, and the cable engine would only be tasked with providing the point-to-point links between gateways. Would that make sense?

Exactly!! The job of cableEngine should only be to setup tunnels and anything associated to connectivity. It should not bother about CNIInterface blah blah...
 
> It would also help with the “trusted” scenarios — I’m thinking of a dummy cable engine for cases where the point-to-point link is already present and doesn’t need encryption...

When you say dummy cable driver, I hope you are talking about some Overlay solution like VxLAN/IPInIP etc (as we have to preserve the source-ips).

**Comment by skitt** [comment]
> > It would also help with the “trusted” scenarios — I’m thinking of a dummy cable engine for cases where the point-to-point link is already present and doesn’t need encryption...
> 
> When you say dummy cable driver, I hope you are talking about some Overlay solution like VxLAN/IPInIP etc (as we have to preserve the source-ips).

Yes, “direct” would be a better name than “dummy”!

**Comment by sridhargaddam** [comment]
> @sridhargaddam awesome investigation, as usual! :)
 
Thanks @mangelajo. 

> I think solution 1 would be more inline with what strongswan & wireguard do.

Right, even I'm inclined towards solution-1.

**Comment by sridhargaddam** [comment]
> > > It would also help with the “trusted” scenarios — I’m thinking of a dummy cable engine for cases where the point-to-point link is already present and doesn’t need encryption...
> > 
> > 
> > When you say dummy cable driver, I hope you are talking about some Overlay solution like VxLAN/IPInIP etc (as we have to preserve the source-ips).
> 
> Yes, “direct” would be a better name than “dummy”!

Or we can even say, VxLAN CableEngine (or IPinIP CableEngine) etc.

**Comment by deanlorenz** [comment]
@mangelajo @skitt @sridhargaddam 

- I prefer Option 1 as Option2 is more likely to have a conflict with CNI

- WG is using option 1, with no `src` option, on `dev subwg0`, table 220
  - CNI-Interface addr is set as source of `subwg0`
  - `subwg0` link is recreated on driver startup, so any associated routes with old link are deleted

- I support @sridhargaddam suggestion to have RA setup routes, and to use table 220
  - much easier to cleanup and be consistent for all cables
    WG is relying on table 220 being cleaned up by RA
  - RA seems the better place to interact with CNI, not only to figure out CNI-interface
    e.g. Calico's no-nat option may be relevant here
  - RA should probably also manage (if needed) the iptable rules to allow tunnel traffic -- make sure incoming traffic to UDP:port for the cable is not dropped or mangled
  - need to figure out what should be `dev` -- WG uses `subwg0`, as it create a new interface; I am not sure using `eth0` for LS is always right, perhaps `l0` can be used -- in any case it will depend both on the cable driver and the network setup for the host

- @skitt not sure what `leftsourceip` does, but in WG there is a separate src for the non-encapsulated pakcets (going into `subwg0`) and the encapsulated UDP (going into `eth0`). WG lets the host choose the latter. The former is used only if the packet does not have a source addr -- e.g., if we have routing rules with `dev subwg0` but no `src` option

**Comment by sridhargaddam** [comment]
Pushed the following PR in Submariner route-agent which implements the necessary changes.
https://github.com/submariner-io/submariner/pull/656

**Sample rules on KIND cluster2 GatewayNode:**
ip rule add prio 150 table 150 
ip route add 10.243.0.0/16 dev eth0 proto static table 219 src 10.242.128.0
ip route add 100.93.0.0/16 dev eth0 proto static table 219 src 10.242.128.0

Where 150 is the priority as well as the table-Id. Strongswan programs rules in table 220, so we have to choose something that has higher priority over the strongswan rules.
10.243.0.0/16 and 100.93.0.0/16 -> remote subnets
device eth0 is obtained from util.defaultHostIface() API.
src 10.242.128.0 is the CNIInterfaceIP on the GatewayNode.

I verified the changes with Strongswan, libreswan with/without Globalnet and they are working fine.
@deanlorenz I could not verify the changes with wireguard as I do not have the setup. Can you please take a look at the PR and see if it works fine with wireguard? Thanks.
