### ISSUE TITLE
Cluster and endpoint information should be cleaned up

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#636]
**What would you like to be added**:

Some way to expire broker CRs which are no longer relevant.

**Why is this needed**:

Currently, clusters which stop running remain in the broker, which causes new clusters to try to set up tunnels to them, unsuccessfully. This includes previous incarnations of re-joining clusters, which means clusters can end up spending significant amounts of time trying to set tunnels up to themselves...

**Comment by mangelajo** [comment]
Makes sense, I'd propose a mechanism similar to :
https://github.com/submariner-io/submariner/blob/master/pkg/cableengine/syncer/syncer.go

https://github.com/submariner-io/submariner/blob/master/pkg/cableengine/syncer/syncer.go#L125

With a bigger TTL time

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
@skitt this one is one year old now. If it's important, let's prioritize for this/next sprint

**Comment by dfarrell07** [comment]
We talked about this on the PR scrub today. It still seems important, and it seems related-but-different from the ongoing Uninstall Epic (https://github.com/submariner-io/enhancements/issues/50). This is more about destroyed/missing clusters.

**Comment by dfarrell07** [comment]
Closing in favor of https://github.com/submariner-io/enhancements/issues/39, which tracks the same thing.
