### ISSUE TITLE
REQUEST: New Committer rights request for sridhargaddam

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#638]
### GitHub Username
@sridhargaddam 

### Code you are requesting Committer rights for
submariner/pkg/globalnet
submariner/pkg/routeagent
submariner/pkg/cable/strongswan

### Requirements
- [x] I have reviewed the community membership guidelines (https://submariner-io.github.io/en/contributing/community-membership/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have been actively contributing to Submariner for at least 3 months
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mangelajo
- @Oats87 
- @tpantelis 

### List of required reviews to Submariner project PRs
- At least 20 PRs to the relevant codebase that you reviewed

![9](https://user-images.githubusercontent.com/6574656/84247098-3afcb100-ab25-11ea-9831-02102557dd78.jpg)

- At least 5 PRs to the relevant codebase for which you were the primary reviewer
https://github.com/submariner-io/submariner/pulls?q=is%3Apr+reviewed-by%3Asridhargaddam

**Comment by mangelajo** [comment]
https://github.com/submariner-io/submariner/pull/685
