### ISSUE TITLE
subctl --service-discovery to create ServiceExport 

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#639]
As discussed in https://github.com/submariner-io/submariner/issues/627
Can we add SeviceExport creation into Subctl as implicit or explicit action, as part of `subctl --service-discovery` command ?

This would ease the use of service-discovery, where such command should both apply and verify the creation of: 

```
kubectl -n {namespace} apply -f - <<EOF
apiVersion: lighthouse.submariner.io/v2alpha1
kind: ServiceExport
metadata:
  name: {service name}
EOF
```

**Comment by vthapar** [comment]
Creation of service export can't be implicit, it has to be an explicit command. I'll be adding something like `subctl create service-export <service-name> -n <namespace>`

**Comment by tpantelis** [comment]
This is being worked in the submariner-operator project: https://github.com/submariner-io/submariner-operator/pull/466.
