### ISSUE TITLE
Rollout status for ServiceExport (on current cluster config)

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#640]
After creating the ServiceExport:

```
$ oc describe serviceexport.lighthouse.submariner.io/nginx-cl-b -n test-submariner-cl-b-new

Name:         nginx-cl-b
Namespace:    test-submariner-cl-b-new
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"lighthouse.submariner.io/v2alpha1","kind":"ServiceExport","metadata":{"annotations":{},"name":"nginx-cl-b","namespace":"tes...
API Version:  lighthouse.submariner.io/v2alpha1
Kind:         ServiceExport
Metadata:
  Creation Timestamp:  2020-06-09T11:42:11Z
  Generation:          1
  Resource Version:    85079
  Self Link:           /apis/lighthouse.submariner.io/v2alpha1/namespaces/test-submariner-cl-b-new/serviceexports/nginx-cl-b
  UID:                 56d5c3ff-109e-423c-a57d-aa653afa39e0
Events:                <none>
```

I tried to check status with "wait", but it failed on timeout:
`$ oc wait "serviceexport.lighthouse.submariner.io/nginx-cl-b" --for condition=available -n test-submariner-cl-b-new`

And with "rollout" it also failed, since ServiceExport is not registered:

```
$ oc rollout status "serviceexport.lighthouse.submariner.io/nginx-cl-b" -n test-submariner-cl-b-new
error: no kind "ServiceExport" is registered for version "lighthouse.submariner.io/v2alpha1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
```

Please add `kubectl rollout status` for ServiceExport (which should give status for the current cluster config).

_Originally posted by @manosnoam in https://github.com/submariner-io/submariner/issues/627#issuecomment-641253565_

**Comment by aswinsuryan** [comment]
The serviceExport status is added with https://github.com/submariner-io/lighthouse/issues/164

**Comment by manosnoam** [comment]
This is related to https://github.com/submariner-io/submariner-website/issues/191

I'm reopening this bug for review by QE.

@aswinsuryan , @vthapar , @sridhargaddam 
as discussed with @nyechiel and the team, please do not close my bugs (or other UX bugs).
Instead, add label "**QE**", and **assign to me** - I will review and close. 

Thanks!

**Comment by manosnoam** [comment]
@nyechiel 
Although @aswinsuryan added option to see the status of serviceExport with "describe" command (submariner-io/lighthouse#164 )
the original issue here is referring to the usage of "rollout status" or "wait" commands, that does not yet work:

```
$ subctl export service "nginx-cl-b" 
Service exported successfully

$ oc rollout status "serviceexport.lighthouse.submariner.io/nginx-cl-b"
error: no kind "ServiceExport" is registered for version "lighthouse.submariner.io/v2alpha1"

# oc wait --timeout=3m --for=condition=ready serviceexport  "nginx-cl-b" 
error: timed out waiting for the condition on serviceexports/nginx-cl-b
```

**Comment by aswinsuryan** [comment]
> oc wait --timeout=3m --for=condition=ready serviceexport

@manosnoam The wait command can be supported if set a ready status filed for export status. I have raised an issue in Lighthouse submariner-io/lighthouse#226

**Comment by aswinsuryan** [comment]
This shall be done as a part of submariner-io/lighthouse#336 or after the changes related to this issue is merged.

**Comment by aswinsuryan** [comment]
> This shall be done as a part of [submariner-io/lighthouse#336](https://github.com/submariner-io/lighthouse/issues/336) or after the changes related to this issue is merged.

This shall be used instead `until [[ $SECONDS -gt 5 ]] || [[ $(kubectl get svcex nginx1 -o jsonpath='{.status.conditions[?(@.status=="True")].type}') == "Valid" ]] ; do echo "waiting for ServiceExport" && sleep 1; done`

**Comment by aswinsuryan** [comment]
we can use the workaround above or continue to use the way we check this now in tests and close this issue.
