### ISSUE TITLE
libreswan: NAT-T does not work when one side has no public IP.

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#642]
**What happened**:

NAT traversal from an on-prem deployment to a public cloud doesn't work when the on-prem deployment has no public/floating-ip.

**What you expected to happen**:

To work, as in strongswan.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy with libreswan cabledriver, and check the gateway connection list with
kubectl get Gateways -A -o yaml

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mangelajo** [comment]
@manosnoam be aware of this when you are testing ^ let me know if you experience it during your testing with libreswan and if you can provide more details.

**Comment by manosnoam** [comment]
I've installed subctl 0.4.0 RC2 with Libreswan, and I see HA is passive on Cluster B (cluster on-premise OSP):

```
Name:         default-cl1-9vgwj-worker-bq8rt
11:25:28 Namespace:    submariner-operator
11:25:28 Labels:       <none>
11:25:28 Annotations:  update-timestamp: 1592209423
11:25:28 API Version:  submariner.io/v1
11:25:28 Kind:         Gateway
11:25:28 Metadata:
11:25:28   Creation Timestamp:  2020-06-15T08:23:44Z
11:25:28   Generation:          1
11:25:28   Resource Version:    2834031
11:25:28   Self Link:           /apis/submariner.io/v1/namespaces/submariner-operator/gateways/default-cl1-9vgwj-worker-bq8rt
11:25:28   UID:                 c5a419dd-ab09-44fb-9665-689ad0aca164
11:25:28 Status:
11:25:28   Connections:
11:25:28   Ha Status:  passive
11:25:28   Local Endpoint:
11:25:28     Backend:      libreswan
11:25:28     cable_name:   submariner-cable-nmanos-cluster-b-10-166-0-26
11:25:28     cluster_id:   nmanos-cluster-b
11:25:28     Hostname:     default-cl1-9vgwj-worker-bq8rt
11:25:28     nat_enabled:  true
11:25:28     private_ip:   10.166.0.26
11:25:28     public_ip:    66.187.233.202
11:25:28     Subnets:
11:25:28       169.254.32.0/19
11:25:28   Status Failure:  
11:25:28   Version:         v0.4.0-rc2
11:25:28 Events:            <none>
11:25:28 
11:25:28 (conda-test) submariner_status=DOWN
11:25:28 (conda-test) subctl info
11:25:28     Discovered network details:
11:25:28         Network plugin:  OpenShift
11:25:28         Service CIDRs: [100.96.0.0/16]
11:25:28         Cluster CIDRs: [10.252.0.0/14]
```

BTW, swanctl on Cluster A  (AWS) worked:
```
swanctl --list-sas --uri unix:///var/run/charon.vici
 submariner-cable-nmanos-cluster-b-10-166-0-26: #1, CONNECTING, IKEv2, 8a5a315dd3c224db_i* 0000000000000000_r
 local  '%any' @ 10.166.22.131[501]
 remote '%any' @ 66.187.233.202[4501]
 active:  IKE_VENDOR IKE_INIT IKE_NATD IKE_CERT_PRE IKE_AUTH IKE_CERT_POST IKE_CONFIG CHILD_CREATE IKE_AUTH_LIFETIME
```
But on Cluster B (OSP) failed:
```
swanctl --list-sas --uri unix:///var/run/charon.vici
  connecting to 'unix:///var/run/charon.vici' failed: No such file or directory
  Error: connecting to 'unix:///var/run/charon.vici' URI 
```

**Comment by mangelajo** [comment]
Apparently this is a timing issue on the libreswan driver, I'm proposing a patch to handle it. NAT-T actually works fine.

And it seems like @manosnoam report was a mix between strongswan and libreswan which we don't support.

**Comment by mangelajo** [comment]
I verified this in 0.4.0-rc3 and it's working perfectly.
