### ISSUE TITLE
Test Libreswan cable-driver (will be the default in future release of Subctl)

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#647]

**Comment by tpantelis** [comment]
This is labeled as part of the 0.5.0 project.  Has it been completed or should it be moved to 0.6.0?

**Comment by manosnoam** [comment]
Moving to 0.6.0, as LibreSwan does not yet work with non default ports:
https://github.com/submariner-io/submariner/issues/683

**Comment by manosnoam** [comment]
@skitt @nyechiel  
I will keep this issue open until we change the the default cable driver from "StrongSwan" to "LibreSwan".
This would happen only when @mangelajo libreswan fix is merged to LibreSwan official release.

For now, in order to use LibreSwan on On-Prem cluster (with NAT), we have to explicitly add `--version libreswan-git`.

**Comment by skitt** [comment]
@manosnoam just to be clear, this isn’t Miguel’s fix, we’re testing a pre-release of Libreswan which fixes the NAT port issue but the fix is provided by upstream.

**Comment by nyechiel** [comment]
bump

**Comment by nyechiel** [comment]
Ready for testing now that https://github.com/submariner-io/submariner/pull/904 is merged

**Comment by manosnoam** [comment]
Libreswan cable driver is working great in subctl version v0.7.0-53-g7c6a09f:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-Globalnet/4/Test-Report/
