### ISSUE TITLE
REQUEST: New Committer rights request for skitt

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#662]
### GitHub Username
skitt

### Code you are requesting Committer rights for

    submariner/pkg/cable/libreswan/\*
    submariner/package/\*
    submariner-operator/\*
    \*/go.mod
    \*/go.sum

### Requirements
- [X] I have reviewed the community membership guidelines (https://submariner-io.github.io/en/contributing/community-membership/)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [X] I have been actively contributing to Submariner for at least 3 months
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- mangelajo
- tpantelis

### List of required reviews to Submariner project PRs
* Libreswan: I wrote the Libreswan cable driver and have reviewed all the PRs on it so far.
* Submariner packaging: I authored most of the commits there, here are some I’ve reviewed:
  * https://github.com/submariner-io/submariner/pull/637
  * https://github.com/submariner-io/submariner/pull/616
  * https://github.com/submariner-io/submariner/pull/513
  * https://github.com/submariner-io/submariner/pull/474
  * https://github.com/submariner-io/submariner/pull/427
* Operator: I’ve written most of the code in the operator, and contributed most of the commits, and reviewed most of the PRs: https://github.com/submariner-io/submariner-operator/graphs/contributors

**Comment by mangelajo** [comment]
Can I suggest you go for packages/*  too ? :-)

**Comment by mangelajo** [comment]
Sorry to bother again. can I also add you to go.mod and go.sum ? :)

**Comment by mangelajo** [comment]
@skitt  ^

**Comment by skitt** [comment]
> Sorry to bother again. can I also add you to go.mod and go.sum ? :)

Done, I went for “all projects” for those two ;-).

**Comment by mangelajo** [comment]
submariner-operator: https://github.com/submariner-io/submariner-operator/pull/499

**Comment by mangelajo** [comment]
submariner: #684
submariner-operator: submariner-io/submariner-operator#499
shipyard: submariner-io/shipyard#222
admiral: submariner-io/admiral#74
lighthouse: submariner-io/lighthouse#185
coastguard: submariner-io/coastguard#14
submariner-bot: submariner-io/submariner-bot#11
