### ISSUE TITLE
VxLAN bridge ip address

### ISSUE THREAD

**Issue by Tarjei400** [submariner-io/submariner#668]
I have 2 node cluster on digital ocean, and network traffic cannot be send to other cluster from a node that is not a gate way node. I was investigating problem a little, and I noticed that gateway node has followin bridge fdb entry : 

![image](https://user-images.githubusercontent.com/1921727/85288079-75efd480-b495-11ea-9e7d-7ce36aef0ac8.png)
Which is from VPC network. and points to both nodes.

However other node, has this bridge ip set to public address of gateway node: 
![image](https://user-images.githubusercontent.com/1921727/85288352-e1d23d00-b495-11ea-86c0-598cb4020bbd.png)

I have 2 questions: 
1) Shouldn't ip on second node come from vpc network ip range? 
2) Is it possible to somehow change that bridge setting manually? ( I tried bridge fdb replace with RTNETLINK answers: operation not supported)

@Update 
I was able to change bridge ip, I figured out it is taken from edpoint crd from private_ip node, so I just edited this field : 

```
  **private_ip: 10.110.0.3**
  public_ip: 161.35.95.40

```

Now it shows this in bridge fdb : 
![image](https://user-images.githubusercontent.com/1921727/85297581-34febc80-b4a3-11ea-96f6-1bf4de748411.png)

However I get message Host is Unreachable if I try to use netcat or tracepath to pods from other clusters connected with submariner, whats interesting connection in other direction works

**Comment by mangelajo** [comment]
Did you open port 4800/UDP between your worker nodes?, that's the port vx-submariner will use?

If that doesn't do the trick, ping me on our slack channel [1] and let's look at it. 

[1] https://kubernetes.slack.com/archives/C010RJV694M

**Comment by mangelajo** [comment]
The endpoint is automatically created and maintained by the submariner-gateway.

So according to your message may be there's a bug in detecting the gw interface for vxlan (which , as you said, it may be the internal address).

@sridhargaddam  ^

**Comment by Tarjei400** [comment]
@mangelajo looks I am need invitation for that slack channel.  Anyway I checked firewalls as first thing yesterday. It looks submariner creates iptables correctly allowing all craffic on 4800 ports on both nodes. I will try to create clean firewall rules on digital ocean and give an update here (Y).

**Comment by nyechiel** [comment]
@Tarjei400 We use the Kubernetes Slack instance. You can request an invite here: https://slack.k8s.io/

**Comment by Tarjei400** [comment]
Just in case, made firewall wide spread open: 
![image](https://user-images.githubusercontent.com/1921727/85390281-e4da3580-b548-11ea-8892-696f03bbbbcc.png)
Although its hard for me to say where exactly traffic gets stuck

**Comment by sridhargaddam** [comment]
> I have 2 node cluster on digital ocean, and network traffic cannot be send to other cluster from a node that is not a gate way node. I was investigating problem a little, and I noticed that gateway node has followin bridge fdb entry :
> 
> ![image](https://user-images.githubusercontent.com/1921727/85288079-75efd480-b495-11ea-9e7d-7ce36aef0ac8.png)
> Which is from VPC network. and points to both nodes.
> 
> However other node, has this bridge ip set to public address of gateway node:
> ![image](https://user-images.githubusercontent.com/1921727/85288352-e1d23d00-b495-11ea-86c0-598cb4020bbd.png)
> 
> I have 2 questions:
> 
> 1. Shouldn't ip on second node come from vpc network ip range?

Submariner only configures the FDB entries on the Gateway nodes and NOT on the worker nodes. 
On worker nodes, when the vx-submariner tunnel interface is created, the remote group will be configured to point to the Gateway node IP from VPC network range. I'm not sure who is creating the FDB entry on the worker nodes, please check.

> 2. Is it possible to somehow change that bridge setting manually? ( I tried bridge fdb replace with RTNETLINK answers: operation not supported)

Submariner does a period sync (30 secs) to ensure that vx-submariner and associated routes are as per the configuration. If you try to modify the vx-submariner outside of submariner, it will be overridden with the submariner values. So the right way IMO is to understand the issue and fix it properly (in Submariner itself if its submariner issue).

> 
> @update
> I was able to change bridge ip, I figured out it is taken from edpoint crd from private_ip node, so I just edited this field :
> 

Actually its taken from the defaultHostInterface, please see this...
https://github.com/submariner-io/submariner/blob/3af209d79094c4ed820d17b2d5229cbe9004e291/pkg/routeagent/controllers/route/route.go#L388

> ```
>   **private_ip: 10.110.0.3**
>   public_ip: 161.35.95.40
> ```
> 
> Now it shows this in bridge fdb :
> ![image](https://user-images.githubusercontent.com/1921727/85297581-34febc80-b4a3-11ea-96f6-1bf4de748411.png)
> 
> However I get message Host is Unreachable if I try to use netcat or tracepath to pods from other clusters connected with submariner, whats interesting connection in other direction works

**Comment by Tarjei400** [comment]
After some chat it turned out that most probably root couse of network traffic being lost somewhere is that on digital ocean, managed cluster has cilium deployed as network provider. When deployed cluster from rancher with Flannel as network provider issue seems to be gone. Thank you for help. I think ticket can be closed

**Comment by sridhargaddam** [comment]
Thanks for the update @Tarjei400. As discussed over slack, currently we do not support Cilium CNI. Good to know that you now have a Submariner deployment.
