### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#678]
**What would you like to be added**:

The various Submariner components should export metrics which can then be used with _e.g._ Prometheus. Useful information includes gateway reachability, error rates, transfer rates (bytes rx/tx, packets rx/tx etc.).

**Why is this needed**:

Prometheus metrics are commonly used to monitor K8s clusters. Providing these means we can piggy-back on the Prometheus-based ecosystem for graphs, alerts etc.

IMO this is worth bearing in mind for https://github.com/submariner-io/submariner-operator/issues/359, at least the parts thereof which will affect the information provided by cable drivers and the `Gateway` object.

**Cross cluster connection**

- [x] (p1) RX/TX bytes and packets between gateway nodes: https://github.com/submariner-io/submariner/pull/846 

- [x] (p1) Connected/not connected 	(We have the number of connections.) — number of connections and corresponding status (as labels), with connection details as labels (endpoint IPs): [#942]( https://github.com/submariner-io/submariner/pull/942
)
- [x] (p1) Connection  uptime: [#942]( https://github.com/submariner-io/submariner/pull/942
)

- [x] (p1) Connection latency: [#978 ](https://github.com/submariner-io/submariner/pull/978)

**Comment by tpantelis** [comment]
bump

**Comment by roytman** [comment]
Should we add a number of reconnects in last 24hs or something like this. I mean that "Connection uptime" can be not enough.

**Comment by skitt** [comment]
> Should we add a number of reconnects in last 24hs or something like this. I mean that "Connection uptime" can be not enough.

Prometheus keeps the history for us; we’d see multiple reconnects as the uptime graph starting from zero several times. This gives a more global view than can be tracked in the cable driver only: it will show for example reconnects which come from the whole pod restarting, or the gateway node changing.

**Comment by skitt** [comment]
When we’re tracking connection states, we need to reset the states at each iteration, otherwise Prometheus will remember old states for us. We can’t do this globally because the metrics track multiple cable drivers potentially; instead, we’ll require each cable driver to explicitly set unused statuses to 0.

**Comment by skitt** [comment]
We need to check whether it’s useful to measure the active gateway’s uptime from Submariner: since the engine is recording the metrics, it can only see itself, and not other gateways. We already track something similar to this in the operator.

**Comment by maayanf24** [comment]
Additional metrics definition in Epic: https://github.com/submariner-io/submariner-operator/issues/745
