### ISSUE TITLE
REQUEST: New Committer rights request for vthapar 

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner#688]
### GitHub Username
@vthapar 

### Code you are requesting Committer rights for
lighthouse/\*

### Requirements
- [x] I have reviewed the community membership guidelines (https://submariner-io.github.io/en/contributing/community-membership/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have been actively contributing to Submariner for at least 3 months
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mangelajo 
- @tpantelis 

### List of required reviews to Submariner project PRs
- At least 20 PRs to the relevant codebase that you reviewed
- At least 5 PRs to the relevant codebase for which you were the primary reviewer
 https://github.com/submariner-io/lighthouse/pulls?q=is%3Apr+reviewed-by%3Avthapar

**Comment by mangelajo** [comment]
Sorry this wasn't handled, adding vthapar to CODEOWNERS in lighthouse.

**Comment by skitt** [comment]
This was taken care of a while ago.
