### ISSUE TITLE
Aligning Globalnet to LightHouse ServiceExport objects

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#720]
Currently, Globalnet annotates every service in a Cluster. This enhancement request is to modify globalnet implementation to annotate only exported services and NOT every service. This will make Globalnet implementation aligned with latest Lighthouse code as well.

**Comment by sridhargaddam** [comment]
Related fix: https://github.com/submariner-io/submariner-operator/pull/571

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
@vthapar this one needs docs update

**Comment by nyechiel** [comment]
> @vthapar this one needs docs update

https://github.com/submariner-io/submariner-website/issues/434
