### ISSUE TITLE
Globalnet changes to support Headless Services

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner#732]
**What would you like to be added**:
Globalnet changes to support headless services

**Why is this needed**:
Support for Headless services will be added to lighthouse in 0.6.0 This requires pod IPs to be reachable across clusters. Currently globalnet only annotates services with globalIP on the ingress side. To support Headless Services it will need to annotate pods behind a Headless Service too.

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
It probably makes sense to look at this in the broader context of https://github.com/submariner-io/submariner/issues/652.

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
@sridhargaddam I think this should be tracked as part of the Globalnet v2 work?

**Comment by tpantelis** [comment]
bump
