### ISSUE TITLE
wrong helm repo url in README.MD

### ISSUE THREAD

**Issue by 290760647** [submariner-io/submariner#743]
a wrong helm repo url in  README,
![image](https://user-images.githubusercontent.com/42170674/88611827-7b57c480-d0bc-11ea-8d72-a8ead9fc5e5a.png)
when use https://releases.rancher.com/submariner-charts/latest ,deploy will be failed.
shoud change the right repo url : https://submariner-io.github.io/submariner-charts/charts

**Comment by sridhargaddam** [comment]
Thank you for reporting the issue @290760647 

If you have plans to push a PR that updates the URL and need any info/help, do let us know.
