### ISSUE TITLE
Move redundancy framework to Shipyard

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner#745]
**What would you like to be added**:
Move the infra bits of redundancy E2E framework to Shipyard

**Why is this needed**:
Submariner E2E has redundancy tests. There are some framework bits that can be reused for similar redundancy tests in other projects like Lighthouse. e.g. Disconnect a cluster, connect a cluster etc. This will avoid duplication of infra framework code in multiple repos.

**Comment by tpantelis** [comment]
@vthapar Can you be more specific as to what framework bits to move to Shipyard? You mentioned "_Disconnect a cluster, connect a cluster_"  but I'm not sure what that refers to. In looking at the submariner `Framework` code, there's functions related to `Gateways`.

**Comment by tpantelis** [comment]
bump
