### ISSUE TITLE
Submariner Engine on OSP cluster - packets were not received

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#755]
After installing latest submariner (devel), on cluster A (AWS) I see on the engine pod that packet were received as expected:
```
2020-08-06T19:29:18.109932483Z 16[NET] sending packet: from 10.166.78.120[501] to 66.187.233.202[4501] (500 bytes)
2020-08-06T19:29:18.109932483Z 14[NET] received packet: from 66.187.233.202[501] to 10.166.78.120[4501] (500 bytes)
```

However, on Cluster B (OSP), I don't see packets received anymore (and it was there on previous submariner versions for sure).

Here's full test report:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/debug_job/194/Test-Report/ (edited) 

You can find pod logs collection on the last step.

**Environment**:
A clean AWS Cluster (just installed now):
Client Version: 4.5.4
Server Version: 4.5.4
Kubernetes Version: v1.18.3+012b3ec

A clean OSP Cluster (just installed now):
Client Version: 4.5.4
Server Version: 4.4.3
Kubernetes Version: v1.17.1

**Comment by sridhargaddam** [comment]
@manosnoam Did you install with Strongswan or Libreswan? Also, JFYI the above logs are not accessible.

**Comment by manosnoam** [comment]
It happened with LibreSwan cable driver. 
But now I have re-run with latest subctl-devel, and this problem was not reproduce, so I'm closing issue.
