### ISSUE TITLE
Multicast support?

### ISSUE THREAD

**Issue by m4ce** [submariner-io/submariner#770]
Since submariner implements a layer2 overlay using VXLAN, it could easily add support for a multicast infrastructure?

It would nice if one could allocate a multicast subnet per cluster and run pimd on the gateway nodes?

**Comment by nyechiel** [comment]
Hi @m4ce. Can you please share more details about your use case and why/how multicast is intended to be used? FWIW, we use VXLAN within the cluster to carry the traffic to the gateways node, and then route over IPsec to other remote clusters, i.e we don't use VXLAN end-to-end between the clusters.

**Comment by m4ce** [comment]
Hi @nyechiel, thanks for the reply. We would like to use multicast to distribute market data internally in between clusters. We could be publishing market data from Asia and subscribing to the data in Europe. Multicast technology is widely used in the financial markets for this type of use-case. It works really well. The idea would be to allocate a `multicastCidr` for each cluster (e.g. 239.b.c.d/16). Publishing into the multicast address space is only allowed in the cluster where the CIDR is allocated. Subscribing is allowed from anywhere to any multicast address space. To give you an idea, AWS recently added support for multicast to the Transit Gateway. However, if you look closely and you try that tech, is very limiting. First, they don't support inter-region multicast routing. Secondly, you can only have one (static) publisher (as in, one AWS EC2 instance) and multiple static subscribers. It doesn't just allow you to make use of multicast full capabilities. I'd be happy to chat more to give you more flavour.

**Comment by nyechiel** [comment]
bump

**Comment by m4ce** [comment]
@nyechiel - we have not talked about this any further. I personally believe that adding such feature to submariner would add even more value to the product. WeaveNet only has some limited support for multicast and it's quite inefficient anyway. Multicast support in the cloud is one of the main blockers for a lot of companies in finance to migrate into the cloud without giving up speed in electronic trading.

**Comment by nyechiel** [comment]
> @nyechiel - we have not talked about this any further. I personally believe that adding such feature to submariner would add even more value to the product. WeaveNet only has some limited support for multicast and it's quite inefficient anyway. Multicast support in the cloud is one of the main blockers for a lot of companies in finance to migrate into the cloud without giving up speed in electronic trading.

Indeed, hence I did not want to close this Issue. I think that we need a further analysis of what is required exactly, and where the gaps are. It would be great if you can provide an example of a specific app that leverage a multi-cluster topology we can refer to. 

From a technical standpoint, assuming that IP Multicast information is sent by one or more senders to a particular group of receivers across different clusters, we will need something like PIM to support this use case. It's true that currently Submariner implements a layer 2 overlay using VXLAN locally within the cluster, but then we tunnel the inter-cluster traffic between the Gateway nodes using IPsec. I think that this would break the Multicast feed, unless we introduce something like PIM and handle the Multicast routing.

**Comment by m4ce** [comment]
@nyechiel - to be honest, I am not able to provide any commercial application that require multicast for the use-cases I have experience with. When it comes to multicast, it alway proprietary code which is developed and remains in-house..
