### ISSUE TITLE
Load balance between 2 datacenters using submariner

### ISSUE THREAD

**Issue by ryzam** [submariner-io/submariner#772]
Hi guys,

I know from the example there is nginx demo running in one datacenter and connected through submariner broker using netshoot from another datacenter. But is it possible for us to deploy multi-node Nginx across datacenter and load balance them.

![image](https://user-images.githubusercontent.com/597759/91134690-6765a980-e6e0-11ea-8d8e-289db47007eb.png)

**Comment by mangelajo** [comment]
Do you mean, like a global Load Balancer?  (North/South outside of k8s?)

Or do you mean, load balancing, when a consumer is trying to get to the service from DC1 or DC2 ? 

With the service discovery you will get that for now via DNS in a limited way, from any consumer DC.

**Comment by ryzam** [comment]
I thought submariner can be used to set up load balancing to get services from DC1 and DC2 otherwise, we need to use global load balancing like CloudFlare WARP.

**Comment by ssider** [comment]
it is a wonderful idea

**Comment by sridhargaddam** [comment]
> I thought submariner can be used to set up load balancing to get services from DC1 and DC2 otherwise, we need to use global load balancing like CloudFlare WARP.

What @mangelajo is trying to understand is whether your client/application trying to access the Nginx service is in one of the connected clusters or is it an external application outside of your clusters?

In case its the former, then yes, as part of the [Lighthouse](https://submariner.io/architecture/service-discovery/) project we support DNS Loadbalancing of requests to backend Nginx services where the services can be present in multiple connected clusters.

**Comment by mangelajo** [comment]
The thing is that submariner scope is, at least currently, the E/W (East/West cluster to cluster) communication, and discovery.

I find the N/S (North/South consumer to clusters) a very necessary complement of what submariner does, hopefully something that we could integrate well with "ServiceExports", ... I believe @vthapar told me this is something being discussed upstream.

I don't know if we have capacity to integrate N/S as part of submariner itself. In this case we'd be load balancing Ingresses or Routes (not "Services" like submariner currently handles), may be we would need something like IngressExport or RouteExport which would be posted to the broker, where the a GLB could integrate with, and consume, ideally with drivers (cloudfare, aws, google cloud, opensource run in VMs...)

But we have lots of things ahead that need work first (network policies, support for other network plugins... a more robust history around NATT configuration..). I don't know. 

May be this is something that we can bring up in the weekly meeting , or talk about it on the #submariner channel, see here: https://submariner.io/contributing/ we are open to more contributing parties.

**Comment by mangelajo** [comment]
Have you looked at https://projectcontour.io/ ?
