### ISSUE TITLE
Submariner without Globalnet - another cluster submariner-lighthouse-agent err

### ISSUE THREAD

**Issue by ssider** [submariner-io/submariner#786]
l am install two 1.8 k8s clusters (chain6 and chain7)  by kubeadm, and install broker  on cluster chain6, chain6 and chain7 are both join the submariner connections.  cluster chain 6 is the first joined, but when l join the cluster 7,the submariner-lighthouse-agent status is err ,it cannot running ..  

cluster chain6 exec next command, its configuration seems ok
$ subctl show all

Showing information for cluster "kubernetes-admin@kubernetes":
    Discovered network details:
        Network plugin:  generic
        Service CIDRs:   [10.96.0.0/12]
        Cluster CIDRs:   [10.122.0.0/16]

CLUSTER ID          ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
chain6              10.206.16.34    119.45.143.179  strongswan          local           
chain7              10.206.16.37    119.45.45.182   strongswan          remote          

GATEWAY                         CLUSTER                 REMOTE IP       CABLE DRIVER        SUBNETS                                 STATUS          
chainseven                      chain7                  10.206.16.37    strongswan          169.254.32.0/19                         connected       

NODE                HA STATUS       SUMMARY                         
chainsix            active          All connections (1) are established

COMPONENT                       REPOSITORY                                            VERSION         
submariner                      quay.io/submariner                                    0.6.0           
submariner-operator             quay.io/submariner                                    0.6.0           
service-discovery               quay.io/submariner                                    0.6.0

Cluster chain7 find the question, the component submariner-lighthouse-agent cannot running, 
$ kubectl  -n submariner-operator get po
NAME                                            READY   STATUS             RESTARTS   AGE
submariner-gateway-xqk7v                        1/1     Running            0          163m
submariner-globalnet-qwxb6                      1/1     Running            0          163m
submariner-lighthouse-agent-586c6fc8b9-h5w2r    0/1     CrashLoopBackOff   32         163m
submariner-lighthouse-coredns-c4665c87f-v7tst   1/1     Running            0          163m
submariner-lighthouse-coredns-c4665c87f-xzp5n   1/1     Running            0          163m
submariner-operator-9fdb987f9-r5gxw             1/1     Running            0          163m
submariner-routeagent-558pw                     1/1     Running            0          163m

the submariner-lighthouse-agent-586c6fc8b9-h5w2r pod logs is shown below:
$ kubectl -n submariner-operator logs submariner-lighthouse-agent-586c6fc8b9-h5w2r
+ trap 'exit 1' SIGTERM SIGINT
+ LIGHTHOUSE_VERBOSITY=1
+ '[' '' == true ']'
+ DEBUG=-v=1
+ exec lighthouse-agent -v=1 -alsologtostderr
I0904 05:47:06.188352       1 main.go:34] AgentSpec: {chain7 submariner-operator true}
W0904 05:47:06.188478       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0904 05:47:06.188594       1 main.go:51] Starting submariner-lighthouse-agent {chain7 submariner-operator true}
F0904 05:47:47.793578       1 main.go:58] Failed to create lighthouse agent: Get "https://10.206.16.34:6443/apis/lighthouse.submariner.io/v2alpha1/namespaces/submariner-k8s-broker/serviceimports": dial tcp 10.206.16.34:6443: i/o timeout

it seems like that is cannot connect cluster chain6 apiserver,but l cannot find the reason. ping the cluster chain6 physical machine， it connected well ,so is it a  problems??? l cannot find the reason........

**Comment by sridhargaddam** [comment]
CC: @vthapar @aswinsuryan

**Comment by ssider** [comment]
> CC: @vthapar @aswinsuryan

do you reproduce the bug？

**Comment by ssider** [comment]
？？？

**Comment by aswinsuryan** [comment]
Was the join/deploy broker done more than once after a cleanup?

Did you try with the latest and is the error still happening? if not could you try with  0.6.1 or 0.7.0-rc2.

**Comment by ssider** [comment]
0.6.1 have the same problems, and l try it many times after a cleanup, but l  se the following method to clean the submariner ,it command is ..
  kubectl delete ns submariner submariner-operator submariner-k8s-broker
  kubectl delete crd clusters.submariner.io endpoints.submariner.io gateways.submariner.io multiclusterservices.lighthouse.submariner.io servicediscoveries.submariner.io serviceexports.lighthouse.submariner.io serviceimports.lighthouse.submariner.io submariners.submariner.io
is it true ???? @aswinsuryan

**Comment by aswinsuryan** [comment]
> 0.6.1 have the same problems, and l try it many times after a cleanup, but l se the following method to clean the submariner ,it command is ..
> kubectl delete ns submariner submariner-operator submariner-k8s-broker
> kubectl delete crd clusters.submariner.io endpoints.submariner.io gateways.submariner.io multiclusterservices.lighthouse.submariner.io servicediscoveries.submariner.io serviceexports.lighthouse.submariner.io serviceimports.lighthouse.submariner.io submariners.submariner.io
> is it true ???? @aswinsuryan

@ssider These clusterroles and clusterrolebinding need to be deleted too.

submariner-operator:globalnet
submariner-operator:lighthouse
submariner-operator

**Comment by ssider** [comment]
> > 0.6.1 have the same problems, and l try it many times after a cleanup, but l se the following method to clean the submariner ,it command is ..
> > kubectl delete ns submariner submariner-operator submariner-k8s-broker
> > kubectl delete crd clusters.submariner.io endpoints.submariner.io gateways.submariner.io multiclusterservices.lighthouse.submariner.io servicediscoveries.submariner.io serviceexports.lighthouse.submariner.io serviceimports.lighthouse.submariner.io submariners.submariner.io
> > is it true ???? @aswinsuryan
> 
> @ssider These clusterroles and clusterrolebinding need to be deleted too.
> 
> submariner-operator:globalnet
> submariner-operator:lighthouse
> submariner-operator

ok l will try,but l reset the k8s cluster, and get the same questions, l think it maybe not the clusterrolebinding question

**Comment by aswinsuryan** [comment]
> > > 0.6.1 have the same problems, and l try it many times after a cleanup, but l se the following method to clean the submariner ,it command is ..
> > > kubectl delete ns submariner submariner-operator submariner-k8s-broker
> > > kubectl delete crd clusters.submariner.io endpoints.submariner.io gateways.submariner.io multiclusterservices.lighthouse.submariner.io servicediscoveries.submariner.io serviceexports.lighthouse.submariner.io serviceimports.lighthouse.submariner.io submariners.submariner.io
> > > is it true ???? @aswinsuryan
> > 
> > 
> > @ssider These clusterroles and clusterrolebinding need to be deleted too.
> > submariner-operator:globalnet
> > submariner-operator:lighthouse
> > submariner-operator
> 
> ok l will try,but l reset the k8s cluster, and get the same questions, l think it maybe not the clusterrolebinding question

Oh ok,  is it just the lighthouse agent that fails to connect to api-server? are the clusters and endpoints crds distributed?

```
kubectl get endpoints.submariner.io -n submariner-operator
kubectl get clusters.submariner.io -n submariner-operator
```

**Comment by mangelajo** [comment]
That timeout could be because the worker node IPs of your clusters are overlapping with any of your other clusters Pod/Service  CIDRs.

We need to add some check in submariner to avoid problems with this,
