### ISSUE TITLE
REQUEST: New membership request for SteveMattar

### ISSUE THREAD

**Issue by SteveMattar** [submariner-io/submariner#792]
### GitHub Username
SteveMattar

### Requirements
- [x] I have reviewed the community membership guidelines (https://submariner.io/contributing/community-membership/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have multiple contributions to Submariner that meet the requirements listed in the community membership guidelines
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nyechiel 
- @skitt 

### List of contributions to the Submariner project
* Participating on the upstream meetings.
* submariner-io/submariner-website#179
* submariner-io/lighthouse#227
* operator-framework/community-operators#2132
* operator-framework/community-operators#2195
* submariner-io/submariner-website#265
* submariner-io/submariner-operator#682

**Comment by mangelajo** [comment]
Adding @SteveMattar as he's an active participant of the project, and he meets all the criteria.

**Comment by SteveMattar** [comment]
joined thanks
