### ISSUE TITLE
Remove "legacy" GH Org Members, have folks apply via current process

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#803]
**What would you like to be added**:

Remove all "legacy" folks in the Submariner-io Org Members group (https://github.com/orgs/submariner-io/people) who were added before we implemented the Community Membership process (https://submariner.io/contributing/community-membership/). Work with folks to [properly apply](https://github.com/submariner-io/submariner/issues/new?template=membership.md&title=REQUEST%3A%20New%20membership%20request%20for%20%3Cyour-GH-handle%3E) via the current process.

**Why is this needed**:

To put us in alignment with our Community Membership practices.

**Comment by skitt** [comment]
@dfarrell07 is this still needed?

**Comment by dfarrell07** [comment]
@skitt Good question, I was also trying to decide what to do with this one after stalebot's prompting.

A while back @mangelajo said, and the consensus seemed to be, that this wasn't worth the effort. Maybe we should close it for now and re-visit if it becomes a better value/work trade-off later?
