### ISSUE TITLE
Add in-repo CODE-OF-CONDUCT.md, CONTRIBUTING.md files to all repos

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#804]
**What would you like to be added**:

Consider if each repo should have an explicit copy of (at least) the CODE-OF-CONDUCT.md and CONTRIBUTING.md.

**Why is this needed**:

It seems like most CNCF-related projects do this, even if the same docs also appear on their website. We currently only show these docs on our website.

**Comment by skitt** [comment]
I suspect part of the point of having these in-repo is that GitHub handles them specially.

**Comment by dfarrell07** [comment]
This is done for the main Submariner repo, but I guess I'll leave it open to track the TODO of repeating for other repos.
