### ISSUE TITLE
Add automation to verify go.[mod|sum] are up-to-date

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#805]
**What would you like to be added**:

~~Automation that runs `go mod tidy` and proposes a PR with updates, if there are any.~~

~~Possible tool: https://github.com/marketplace/actions/go-mod-tidy-pr~~

Update: run `go mod tidy; go mod vendor`, verify no difference.

**Why is this needed**:

~~To keep `go.mod` up-to-date without periodic human intervention to do this very simple process.~~

Update: to validate these files are correct. Dependency version bumping will typically be managed Dependabot.

**Comment by dfarrell07** [comment]
Also https://github.com/submariner-io/submariner/pull/848

**Comment by dfarrell07** [comment]
It might be the case that dependabot now supports this, I'll dig in.

**Comment by dfarrell07** [comment]
This has been implemented in Dependabot, but it doesn't seem to be running for us yet. I asked here: https://github.com/dependabot/dependabot-core/issues/2229#issuecomment-728962639.

**Comment by mkolesnik** [comment]
I'm also adding this as part of releases repo, FYI

**Comment by dfarrell07** [comment]
> I'm also adding this as part of releases repo, FYI

Nice! No reply to my upstream question yet, so that might be the first/best option.

**Comment by dfarrell07** [comment]
We discussed this on the Automation sync today and made progress.

With @mangelajo's login (at least), we can access a Dependabot interface and have the bot auto-generate PRs like https://github.com/submariner-io/submariner/pull/1033 to update Dependabot's version to one that should include this feature.

To prevent folks from incorrectly manually editing go.mod/go.sum, we also want to resurrect https://github.com/submariner-io/shipyard/pull/218, make a few changes (like path-triggering on go.[mod|sum]), and propagate it to the GHAs all of the other repos.
