### ISSUE TITLE
Improvement to UI when adding cluster

### ISSUE THREAD

**Issue by vkruoso** [submariner-io/submariner#807]
The UI to request CIDR details of the cluster when the network details are not detected automatically makes it hard to enter data. Here is a demonstration of it:

<img width="401" alt="Screen Shot 2020-09-11 at 17 41 34" src="https://user-images.githubusercontent.com/293572/93024184-ead13700-f5ca-11ea-9fcc-25f3b7b88f71.png">

**What would you like to be added**:
Update the UI to have a clear question when requesting user input.

**Why is this needed**:
It is hard to figure out the CIDR the question is about.

**Comment by nyechiel** [comment]
@maayanf24 would it make sense for you to look at this one?

**Comment by maayanf24** [comment]
@nyechiel @mangelajo , I think this is the same issue:
https://github.com/submariner-io/submariner-operator/issues/660

**Comment by skitt** [comment]
> @nyechiel @mangelajo , I think this is the same issue:
> [submariner-io/submariner-operator#660](https://github.com/submariner-io/submariner-operator/issues/660)

Ah yes, I thought I’d seen this before...

**Comment by nyechiel** [comment]
Thanks for reporting this, @vkruoso. This is a valid bug but apparently we already have it tracked [here](https://github.com/submariner-io/submariner-operator/issues/660) hence I am closing this Issue.
