### ISSUE TITLE
How to uninstall submariner purely

### ISSUE THREAD

**Issue by ssider** [submariner-io/submariner#823]
How to uninstall submariner purely？ l didnot find this in github or https://submariner.io？ is it exist？

**Comment by mangelajo** [comment]
We don't have that on the website, and it's slightly different depending on the cable driver you have, I'm adding this to the backlog so we can secure time on following sprints to handle it.

**Comment by nyechiel** [comment]
FWIW, this Issue has more information on how to manually remove the Submarine resources from a cluster: https://github.com/submariner-io/submariner-website/issues/272

We still need to automate this and integrate into subctl/Operator, etc.

**Comment by Jaanki** [comment]
Closing this against https://github.com/submariner-io/submariner-website/issues/272
