### ISSUE TITLE
Handle external-ip changes on Gateway node

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#826]
**What happened**:
When Submariner is deployed in a Cluster with NAT disabled, the local endpoint of the cluster includes the external-ip (aka public-ip) of the active gateway node. The active gateway node of the cluster updates the endpoint info on the Broker which is subsequently sync'ed by all the member clusters. The member clusters then try to connect to the public-ip configured in the endpoint CRD to setup IPsec tunnels. So far, everything is fine.

In one of the OpenShift deployments on AWS, it was seen that when the external-ip is modified on the Active Gateway node of the cluster, the endpoint is properly updated with the new public-ip. However, this use-case is not handled properly in the  CableEngine.

**What you expected to happen**:
When the external-ip (or public-ip) of the active Gateway node is changed, tunnels should be reconfigured successfully with the new public-ip.

**How to reproduce it (as minimally and precisely as possible)**:

Steps
1. Say we have two clusters - cluster1 and cluster2 on AWS
2. Deploy Submariner and join both the clusters.
3. Wait for IPsec tunnels to be setup and verify that Gateway status shows "connected" for both the clusters.
4. On the active gateway node of cluster1, remove the external-ip and reconfigure a new external-ip.
5. SubmarinerEnginePod on cluster1 notices this change and updates its EndpointCRD with the new public-ip.
6. The updated endpoint is pushed to the Broker cluster as well.
7. Cluster2 gets notified on the updated endpoint on cluster1.
8. Ideally it should tear down the previous IPsec tunnel and re-establish a new IPsec tunnel that points to the new public-ip of cluster1. This is not happening for the following reasons.

In step number 7 shown above, when cluster2 gets notification of updated endpoint, it queries the CableDriver for the GetActiveConnections() which returns the cable name (aka submariner-cable-cluster1-10-0-26-36). The CableName is constructed as follows - "submariner-cable-<clusterID>-<privateIP>". The CableEngine InstallCable API simply checks the cable name[*] and assumes that connection is already established to that endpoint. 
 
[*] https://github.com/submariner-io/submariner/blob/507166f7c5ab4f9d4a1eac0386f082e9973de695/pkg/cableengine/cableengine.go#L114

**Anything else we need to know?**:
This was seen with Strongswan Driver but since its a common code, it most likely will affect other drivers too.

**Environment**:
Showing information for cluster "cluster1":
COMPONENT                       REPOSITORY                                            VERSION         
submariner                      quay.io/submariner                                          devel          
submariner-operator             quay.io/submariner                                    devel           
service-discovery               quay.io/submariner                                       devel

**Comment by sridhargaddam** [comment]
This issue can be addressed in multiple ways.
An easy solution AFAICT is to update the CableName to include public-ip as well [here](https://github.com/submariner-io/submariner/blob/507166f7c5ab4f9d4a1eac0386f082e9973de695/pkg/util/util.go#L97). But it can have an impact on existing brownfield deployments.

**Comment by manosnoam** [comment]
Well done @sridhargaddam 
I tested this feature with Subctl 0.7 RC2 - It works great:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS/850/Test-Report/

Before VM reboot of the Gatewy node on nmanos-cluster-a, the Gateway public IP = 3.101.103.140 :
```
08:51:47     gateways:
08:51:47     - connections:
08:51:47       - endpoint:
08:51:47           backend: strongswan
08:51:47           cable_name: submariner-cable-nmanos-cluster-a-10-166-106-214
08:51:47           cluster_id: nmanos-cluster-a
08:51:47           hostname: ip-10-166-106-214
08:51:47           nat_enabled: true
08:51:47           private_ip: 10.166.106.214
08:51:47           public_ip: 3.101.103.140
08:51:47           subnets:
08:51:47           - 169.254.0.0/19
08:51:47         status: connected
08:51:47         statusMessage: Connected to 3.101.103.140:4501 - encryption alg=AES_GCM_16,
08:51:47           keysize=128 rekey-time=14364
08:51:47       haStatus: active
08:51:47       localEndpoint:
08:51:47         backend: strongswan
08:51:47         cable_name: submariner-cable-default-cl1-10-166-0-235
08:51:47         cluster_id: default-cl1
08:51:47         hostname: default-cl1-k7hcq-worker-g2cnf
08:51:47         nat_enabled: true
08:51:47         private_ip: 10.166.0.235
08:51:47         public_ip: 66.187.232.129
08:51:47         subnets:
08:51:47         - 169.254.32.0/19
08:51:47       statusFailure: ""
08:51:47       version: v0.7.0-rc2-2-ga9021c5-dev
08:51:47     globalCIDR: 169.254.32.0/19
```

After VM reboot  - Gateway on same cluster had public IP = 13.56.77.149 :
```
08:53:39   Gateways:
08:53:39     Connections:
08:53:39       Endpoint:
08:53:39         Backend:      strongswan
08:53:39         cable_name:   submariner-cable-nmanos-cluster-a-10-166-106-214
08:53:39         cluster_id:   nmanos-cluster-a
08:53:39         Hostname:     ip-10-166-106-214
08:53:39         nat_enabled:  true
08:53:39         private_ip:   10.166.106.214
08:53:39         public_ip:    13.56.77.149
08:53:39         Subnets:
08:53:39           169.254.0.0/19
08:53:39       Status:          connected
08:53:39       Status Message:  Connected to 13.56.77.149:4501 - encryption alg=AES_GCM_16, keysize=128 rekey-time=13086
08:53:39     Ha Status:         active
08:53:39     Local Endpoint:
08:53:39       Backend:      strongswan
08:53:39       cable_name:   submariner-cable-default-cl1-10-166-0-235
08:53:39       cluster_id:   default-cl1
08:53:39       Hostname:     default-cl1-k7hcq-worker-g2cnf
08:53:39       nat_enabled:  true
08:53:39       private_ip:   10.166.0.235
08:53:39       public_ip:    66.187.232.129
08:53:39       Subnets:
08:53:39         169.254.32.0/19
08:53:39     Status Failure:  
08:53:39     Version:         v0.7.0-rc2-2-ga9021c5-dev
08:53:39   Global CIDR:       169.254.32.0/19
```

+ @nyechiel
