### ISSUE TITLE
How to safely remove a k8s-cluster from submariner

### ISSUE THREAD

**Issue by Hitesh-Agrawal** [submariner-io/submariner#84]
Hi Guys,
I see instructions on how to install submariner, but there are no instructions on how to remove it. Will `helm delete submariner` remove a k8s-cluster config safely from an existing setup of 4 different cluster connected via submariner.

Thanks

**Comment by dimaunx** [comment]
From my experience to remove subm safely, run the following on each gateway cluster:
* helm del --purge submariner
* kubectl delete crd clusters.submariner.io endpoints.submariner.io 

To remove subm from broker cluster just:
* kubectl delete crd clusters.submariner.io endpoints.submariner.io

**Comment by Hitesh-Agrawal** [comment]
Hello dimaunx,
I tried the steps above to delete the submariner from one of my connected k8s cluster ( which needs to be decommissioned) , but now I see other submariners trying to establish the tunnel to this decommissioned cluster.

Processing endpoint object: submariner/submariner-cable-xxx-xxx-xxx-xxx
7/1/2019 10:13:56 AM I0701 04:43:56.430060       1 datastoresyncer.go:236] The updated endpoint object was not for this cluster, skipping updating the datastore
7/1/2019 10:13:56 AM I0701 04:43:56.432339       1 ipsec.go:169] Installing cable submariner-cable-xxx-xxx-xxx-xxx

**Comment by Oats87** [comment]
@Hitesh-Agrawal you should remove the endpoint objects related to that cluster from the broker cluster, i.e. `kubectl delete endpoint submariner-cable-xxx-xxx-xxx-xxx -n submariner-k8s-broker`. Submariner should reconcile that change (as it will see the deleted endpoint) and should delete its local copy and cease trying to establish a connection.

**Comment by Hitesh-Agrawal** [comment]
@Oats87 Thx buddy that worked perfectly. Removed the endpoints from the broker cluster and the cluster is out of submariner connectivity now. Can we have these steps documented in the readme for the submariner project.

**Comment by sridhargaddam** [comment]
This will be addressed as part of the following issue - https://github.com/submariner-io/submariner-operator/issues/88
