### ISSUE TITLE
Make options seems to have broken

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#850]
**What happened**:
When trying to build and deploy Submariner using "make deploy using=libreswan,helm" command, it is seen that cableDriver is selected as "Strongswan" instead of "libreswan"

**What you expected to happen**:
Since we are specifying cabledriver as libreswan (via using=libreswan), Submariner should be deployed with libreswan.

**Comment by skitt** [comment]
Libreswan isn’t yet supported when deploying with Helm, see https://github.com/submariner-io/submariner-charts/issues/33.

**Comment by skitt** [comment]
This is still relevant.
