### ISSUE TITLE
Simulate scale testing

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner#861]
We want to experiment with simulating some scalability testing of Submariner by running a large number of kind clusters and/or kind clusters with many nodes.

**Comment by nyechiel** [comment]
We might also want to look at https://github.com/submariner-io/submariner/issues/517 as part of this. /cc @tpantelis

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
I can work on this for the upcoming 0.9.0 release.

**Comment by nyechiel** [comment]
> I can work on this for the upcoming 0.9.0 release.

Thanks Daniel. Can you sync with @mangelajo on this, please? He also wanted to dedicate some for this during the 0.9 cycle, and have access to some hardware we should be able to utilize.

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
@mkolesnik do you want to use this one for your planned 0.12 work?

**Comment by mkolesnik** [comment]
Closed in favor of https://github.com/submariner-io/enhancements/issues/49
