### ISSUE TITLE
Discovering network details CIDR for your cluster?

### ISSUE THREAD

**Issue by ameyaagashe** [submariner-io/submariner#867]
ec2-user@ip-10-0-0-59 ~]$ subctl join --kubeconfig /home/ec2-user/.kube/config broker-info.subm
* broker-info.subm says broker is at: https://6E23D7565331B5BEE5DD851EEFF1E19E.gr7.ap-southeast-2.eks.amazonaws.com
? What is your cluster ID? d837265
X Sorry, your reply was invalid: Value is required
⠈⠁ Discovering network details CIDR for your cluster?
Error determining the service CIDR: interruptcluster?

It remains in this state forever. I tried with --disable-nat option too but had no luck.

Can someone please assist

**Comment by mangelajo** [comment]
can you try passing    --clustercidr string   and --servicecidr during join?

For some reason it must not be detecting the EKS settings. Please ping me on the submariner slack channel if you want some assistance.

Please note that your cluster CIDRs should not be overlapping, otherwise, you need to do deploy-broker with --globalnet enabled.

**Comment by mangelajo** [comment]
As for the question overlapped with the spinner, I think it's been fixed and will be available for 0.7.0

**Comment by ameyaagashe** [comment]
@mangelajo 
Thanks for the response. I could get submariner deployed on my external VM. I am however, still not get that node to join to eks cluster.

**Comment by ameyaagashe** [comment]
Just for information for everyone else, the correct command to join an external node to the existing EKS cluster is as below:

```
subctl join --kubeconfig /home/ec2-user/.kube/config broker-info.subm --clustercidr "192.168.0.0/16" --servicecidr="10.0.0.0/24
```
Where
```
clustercidr=EKS Cluster CIDR address
servicecdr=External node VPC CIDR address
```
