### ISSUE TITLE
Routing table 150 increases on gateway node as time goes by

### ISSUE THREAD

**Issue by orimanabu** [submariner-io/submariner#868]
**What happened**:
Routing rule 150 increases infinitely on an active gateway node as time goes by.

Here is how many rule 150 exists on my environment.
The gateway pod was deployed about 16 hours ago.
```
[centos@site2-gw1 ~]$ ip rule show
0:      from all lookup local 
150:    from all lookup 150 
150:    from all lookup 150 
<snip>
150:    from all lookup 150 
150:    from all lookup 150 
220:    from all lookup 220 
32766:  from all lookup main 
32767:  from all lookup default 
```

```
[centos@site2-gw1 ~]$ ip rule show | grep '^150:' | wc -l
1916
```

**What you expected to happen**:
There exists only one routing rule 150.

**How to reproduce it (as minimally and precisely as possible)**:
1. `subctl deploy-broker --kubeconfig ${kubeconfig} --globalnet true`
2. `subctl join --kubeconfig ${kubeconfig} broker-info.subm --clusterid ${cluster} --disable-nat`

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): 0.6.1
- Kubernetes version (use `kubectl version`): 1.19.2
- Cloud provider or hardware configuration: KVM
- OS (e.g: `cat /etc/os-release`): CentOS7.6.1810
- Kernel (e.g. `uname -a`): 3.10.0-957.27.2.el7.x86_64
- Install tools: kubeadm 1.19.2
- Network plugin and version (if this is a network-related bug): Weave 2.7.0
- Others:

**Comment by mangelajo** [comment]
@orimanabu can you try the --cable-driver libreswan ? 

We are planning to deprecate strongswan once we get a new version of libreswan and some extra testing, and looks like an strongswan specific bug.

**Comment by orimanabu** [comment]
@mangelajo I tried libreswan cable driver, but got the same result (increased rule 150 table every 30 seconds).

But...updating the entire OS to latest resolved the issue!
I updated to CentOS 7.8.2003, then I see only one rule 150, with strongswan and libreswan cable driver.

**Comment by sridhargaddam** [comment]
@orimanabu thanks for updating that it's fixed after upgrading the OS. 

Ideally, if the rule already exists, the library should simply return an error saying it exists. Looks like it was not happening on the platform. Anyways, we recently Optimized the route-agent code and the Gateway transitions are handled only once.

```
  err := netlink.RuleAdd(rule)
  if err != nil && !os.IsExist(err) {
	return fmt.Errorf("failed to add ip rule %s: %v", rule, err)
  }
```
