### ISSUE TITLE
Investigate CI in multiple cloud providers

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#907]
**What would you like to be added**:

CI that runs in various different cloud providers, and across multiple cloud providers.

**Why is this needed**:

To validate that Submariner works out-of-the-box in whatever hybrid cloud configuration folks want to use.

**Comment by dfarrell07** [comment]
I think @mangelajo is going to work with @ccamacho to do this using https://github.com/Kubeinit/kubeinit.

**Comment by ccamacho** [comment]
When https://github.com/submariner-io/submariner-operator/pull/974 passes we should be able to close this issue.

**Comment by tpantelis** [comment]
bump

**Comment by ccamacho** [comment]
bump!

**Comment by ccamacho** [comment]
I added many many improvements to the automation to get this done, I'm also testing what is shipped in main/master. I'll try to ping you for a follow up on this. We now support cdk,okd,ocp,rke,k8s, and eks.

**Comment by dfarrell07** [comment]
Talking on the PR/Issue scrub, this is something we might be able to get budget for once we go Incubation in the CNCF. Also, Red Hat is testing this downstream. Happy to do this eventually, but not something we see a way to do soon.
