### ISSUE TITLE
Publish ARM builds

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#925]
**What would you like to be added**:

We should build and publish for ARM.

**Why is this needed**:

Wider adoption. This was requested (at least) by attendees at @mangelajo's recent K8s on the Edge conference talk.

**Comment by nyechiel** [comment]
@dfarrell07 @skitt I see some PRs opened that should close this. Can you link/update this Issue? Also, let's remove this from 0.8.0. Thanks!

**Comment by skitt** [comment]
https://github.com/submariner-io/submariner/pull/964 and https://github.com/submariner-io/submariner/pull/965 help with this, without providing a complete solution — they allow us to build ARM images, but we need to decide how we want to push them automatically.

**Comment by nyechiel** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by skitt** [comment]
This is still relevant.

**Comment by nyechiel** [comment]
@skitt I took the liberty to move this into the 0.12 board. Please further triage and link to an epic if needed.

**Comment by skitt** [comment]
https://github.com/submariner-io/shipyard/pull/723 allows us to publish ARM images; we’ll still need to fix up some projects.

**Comment by dfarrell07** [comment]
> [submariner-io/shipyard#723](https://github.com/submariner-io/shipyard/pull/723) allows us to publish ARM images; we’ll still need to fix up some projects.

It seems like we're not trying to get this merged soon (https://github.com/submariner-io/shipyard/pull/723#issuecomment-1056543161), so should we move this off the 0.12 board?

**Comment by nyechiel** [comment]
Done for 0.13.
