### ISSUE TITLE
GKE: get Submariner working by configuring reverse path filtering on the nodes

### ISSUE THREAD

**Issue by LaumiH** [submariner-io/submariner#934]
**What happened**:
When deploying Submariner on GKE [VPC-native and routes-based](https://cloud.google.com/kubernetes-engine/docs/concepts/types-of-clusters#vpc-clusters) clusters, the two clusters connect to each other as verifiable by `subctl show connections`, but TCP traffic between gateway and non-gateway nodes is not successful and the `subctl verify` tests fail.

**What you expected to happen**:
The tests are successful and Submariner can be deployed on GKE.

**How to reproduce it (as minimally and precisely as possible)**:
Setup two GKE clusters. I am using
```
gcloud container  clusters create "<name>" \
        --zone "europe-west3-a" \
        --cluster-version "1.17.13-gke.1400" \
        --username "admin" \
        --machine-type "g1-small" \
        --image-type "UBUNTU" \
        --disk-type "pd-ssd" \
        --disk-size "15" \
        --num-nodes "3" \
        --network "default" \
        --no-enable-ip-alias (optional, creates routes based cluster)
```
Setup Submariner using `subctl`. Verify the deployment using `subctl verify` and run into the failing tests.

**Anything else we need to know?**:
Thanks to the fantastic help of @mangelajo and @sridhargaddam the problem is identified and a workaround is available. Please refer to [this script](https://github.com/sridhargaddam/k8sscripts/blob/5e1f44f9530ad8b7e7a758349802f9fc21461db5/rp_filter_settings/update-rp-filter.sh) until the Submariner team has implemented it.

**Environment**:
- Submariner version (use `subctl version`): v0.7.0
- Kubernetes version (use `kubectl version`): v1.19.3
- Cloud provider or hardware configuration: GKE routes based cluster, see above
- OS (e.g: `cat /etc/os-release`): Manjaro Linux
- Kernel (e.g. `uname -a`): 5.9.3
- Install tools: subctl
- Network plugin and version (if this is a network-related bug): standard GKE native CNI

**Comment by sridhargaddam** [comment]
What would you like to be added:
The CNI on GKE clusters uses plain routing instead of overlay tunnels. So, reverse_path filtering needs to be configured to loose mode on each node of the clusters as described in the GKE quick start guide. This configuration ideally is best handled in the Submariner route-agent just like how we are doing it for other CNIs.

**Comment by sridhargaddam** [comment]
This is still valid and needs to be handled in GKE specific route-agent driver (TBD)

**Comment by sridhargaddam** [comment]
bump

**Comment by sridhargaddam** [comment]
bump

**Comment by danibachar** [comment]
This workaround is not feasible anymore, the lowest version supported by GKE is - 1.18.20-gke.4100 also -  Since GKE node version 1.19, the Docker container runtime is deprecated...

Nodes don't have eth0 link anymore so the script does not work. Does Submariner depends on `eth0` link? 

outputs of `ifconfig`
```
cbr0      Link encap:Ethernet  HWaddr B6:38:ED:5D:80:0B
          inet addr:10.108.0.1  Bcast:10.108.0.255  Mask:255.255.255.0
          inet6 addr: fe80::b438:edff:fe5d:800b/64 Scope:Link
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1460  Metric:1
          RX packets:6451 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6588 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:830028 (810.5 KiB)  TX bytes:2588789 (2.4 MiB)

docker0   Link encap:Ethernet  HWaddr 02:42:80:E8:59:CF
          inet addr:169.254.123.1  Bcast:169.254.123.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ens4      Link encap:Ethernet  HWaddr 42:01:0A:9C:00:2A
          inet addr:10.156.0.42  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: fe80::4001:aff:fe9c:2a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:947445 errors:0 dropped:0 overruns:0 frame:0
          TX packets:68217 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1348317200 (1.2 GiB)  TX bytes:12109153 (11.5 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:7771 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7771 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4146589 (3.9 MiB)  TX bytes:4146589 (3.9 MiB)

veth5e2f67fc Link encap:Ethernet  HWaddr 8A:1B:95:7F:BE:91
          inet6 addr: fe80::881b:95ff:fe7f:be91/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:235 errors:0 dropped:0 overruns:0 frame:0
          TX packets:234 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:19897 (19.4 KiB)  TX bytes:273861 (267.4 KiB)

veth80e09529 Link encap:Ethernet  HWaddr EA:8C:DF:A6:01:9C
          inet6 addr: fe80::e88c:dfff:fea6:19c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:6216 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6363 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:900445 (879.3 KiB)  TX bytes:2315654 (2.2 MiB)

vx-submariner Link encap:Ethernet  HWaddr 0A:A9:FE:2F:8A:39
          inet addr:240.156.0.42  Bcast:240.255.255.255  Mask:255.0.0.0
          inet6 addr: fe80::8a9:feff:fe2f:8a39/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:4 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:300 (300.0 B)  TX bytes:376 (376.0 B)
```

I tried settings all links with rp_filter=2 and disabled the shielded node features on GKE with no help ): (I applied the changes before deploying submariner)

outputs of `sysctl -a 2>/dev/null | grep "\.rp_filter"` within the node
```
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.cbr0.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.docker0.rp_filter = 2
net.ipv4.conf.ens4.rp_filter = 2
net.ipv4.conf.lo.rp_filter = 0
net.ipv4.conf.veth80e09529.rp_filter = 2
```

@sridhargaddam - I have seen the work you guys have been doing with cloud prepare, and I'm not sure it is related. But if you have some time to guide me I'd like to try and help to push this fix forward...
```
gcloud container clusters create "cluster-a" \
    --zone "europe-west3-a" \
    --enable-ip-alias \
    --machine-type "g1-small" \
    --image-type "UBUNTU" \
    --disk-type "pd-ssd" \
    --disk-size "15" \
    --num-nodes "3" \
    --no-enable-shielded-nodes \
    --no-shielded-integrity-monitoring \
    --no-shielded-secure-boot \
    --cluster-version "1.18.20-gke.4100"
```

I also have the `subctl gather all` output
[submariner-20210903172658.zip](https://github.com/submariner-io/submariner/files/7108954/submariner-20210903172658.zip)

**Comment by maayanf24** [comment]
This has been discussed on the issue scrub meeting and decided to close for now.
If this will become a priority it can be reopened
