### ISSUE TITLE
Option to use existing OCP node as gateway

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#951]
Currently `prep_for_subm.sh` creates a new node on the cluster, for Submariner gateway.

**What would you like to be added**:
Please add option to pass an existing node (id) to be used for the gateway.

**Why is this needed**:
In case there's no permissions to create new nodes for existing manged clusters (e.g. in ACM).

**Comment by nyechiel** [comment]
With IPI-based deployment, there is no way to assign a public/external IP to an existing worker node, therefore we deploy a dedicated node for the Submariner gateway today. This a limitation/security design on the OpenShift side, so there is not much we can do about this.

One thing we are exploring for 0.9 is to place a LoadBalancer type service in front of the gateway-label node(s), which is something that would eliminate the need for an extra dedicated node. This is being tracked here: https://github.com/submariner-io/submariner/issues/1071
