### ISSUE TITLE
get familiar with acm+ Submariner

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/submariner#959]
$subject

**Comment by pinikomarov** [comment]
following documentatoin here : 
https://github.com/open-cluster-management/deploy

**Comment by pinikomarov** [comment]
requesting access on their slack ...

**Comment by pinikomarov** [comment]
@nyechiel Hi ,  I'm following the steps in the acm docs and I'm hitting this error : 
how did you w/a this ? 
adding @manosnoam as well here ..

[r@r20 deploy]$ ./start.sh 
* Testing connection
./start.sh: line 80: oc: command not found
ERROR: Make sure you are logged into an OpenShift Container Platform before running this script
[r@r20 deploy]$ ./start.sh --help

did you change the script to point to a kubectl instead ? use a live oc env ?

**Comment by MaxBab** [comment]
I have an issues to get a working inter cluster connectivity on submariner-addon with a kind deployment.
Opened an issue: https://github.com/open-cluster-management/submariner-addon/issues/22

**Comment by nyechiel** [comment]
@pinikomarov please check this section: https://github.com/open-cluster-management/deploy#prereqs

You need to have an OCP cluster up and running and `oc` properly configured. This cluster will be used as the ACM Hub, and from there you can spawn and manage additional clusters.

**Comment by nyechiel** [comment]
> I have an issues to get a working inter cluster connectivity on submariner-addon with a kind deployment.
> Opened an issue: [open-cluster-management/submariner-addon#22](https://github.com/open-cluster-management/submariner-addon/issues/22)

This is a different issue than the one reported by Pini. Let's discuss in the other Issue you reported and not mix the two :)

**Comment by pinikomarov** [comment]
ok so I got past the oc binary part, 
@nyechiel @MaxBab can you explain how you got  to oc login to your respective ocp clusters ? 
did you oc login to the kind cluster ? if so how ? or to a different local / remote cluster ? 
Thanks

**Comment by pinikomarov** [comment]
src: https://github.com/open-cluster-management/labs/blob/master/multicloud-deployment/labs/2.md

- [ ] AWS account with proper permissions
- [ ] DNS configured on AWS
- [ ] Pull secret from try.openshift.com
- [ ] Get the latest OCP installer and CLI tools.

- [ ] Create an install config. Give it an appropriate name, like <engineer>-hub.<engineer>.sysdeseng.com.
        ./openshift-install create install-config --dir=acm-hub
- [ ] Modify the worker node size.
       aws: type: m4.2xlarge
- [ ] Provision the cluster.
       ./openshift-install create cluster --dir=acm-hub
- [ ] continue to 'deploy': 
      https://github.com/open-cluster-management/deploy
- [ ] deploy submariner
- [ ] testing and feedback

**Comment by pinikomarov** [comment]
got the acm install to deploy succesfully  on upshift cluster and with an access point : 
* Red Hat ACM URL: https://multicloud-console.apps.default-cl1.devcluster.openshift.com
problem is : I can't log in  with my kerb user and pass

**Comment by nyechiel** [comment]
@pinikomarov I want to clean the v0.8 board. Is there any reason to keep this one open? I get that you want to track your personal tasks, but I don't think there is anything actionable for us in here, unless you have an actual issue you want to report.

**Comment by pinikomarov** [comment]
that's ok we can close , I'll track it personally
