### ISSUE TITLE
OVN: host-network to remote pod/service does not work

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#993]
**What happened**:

When deploying with ovn-kubernetes, and running subctl verify, hostNetwork based tests will fail.

**What you expected to happen**:

All tests to pass.

**How to reproduce it (as minimally and precisely as possible)**:

1) Deploy at least one cluster with OVN
2) Install submariner
3) subctl verify ovn-cluster another-cluster

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): 0.8.0-rc0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mangelajo** [comment]
Something like this needs to be done in every worker/gw node, considering that 10.132.0.0 and 172.31.0.0/16 are remote cluster CIDRs. also 10.128.2.1 is the local router for that worker node, which can be found by listing ip routes. Every worker node has it's own router ip.
```
# ip r list
default via 10.0.128.1 dev br-ex proto dhcp metric 800 
10.0.128.0/19 dev br-ex proto kernel scope link src 10.0.133.75 metric 800 
10.128.0.0/14 via 10.128.2.1 dev ovn-k8s-mp0 
10.128.2.0/23 dev ovn-k8s-mp0 proto kernel scope link src 10.128.2.2 
169.254.0.0/20 dev ovn-k8s-gw0 proto kernel scope link src 169.254.0.1 
172.30.0.0/16 via 10.128.2.1 dev ovn-k8s-mp0 
# ip r add 10.132.0.0/14 via 10.128.2.1   
# ip r add 172.31.0.0/16 via 10.128.2.1  
```

**Comment by mangelajo** [comment]
Thanks @sridhargaddam for giving a hand on this

**Comment by nyechiel** [comment]
Verified on 0.8.0-rc1
