### ISSUE TITLE
E2e redundancy test failing in KIND Globalnet env with Wireguard driver

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#996]
**What happened**:
In KIND Setup with Globalnet enabled, when e2e tests are run, one of the redundancy tests is failing randomly

[redundancy] Gateway fail-over tests when a new node is labeled as a gateway node and the label on the existing gateway node is removed 
  should start a submariner engine on the new gateway node and be able to connect from another cluster
  /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/submariner/test/e2e/redundancy/gateway_failover.go:37
STEP: Creating namespace objects with basename "gateway-redundancy"
STEP: Generated namespace "e2e-tests-gateway-redundancy-l9rhp" in cluster "cluster1" to execute the tests in
STEP: Creating namespace "e2e-tests-gateway-redundancy-l9rhp" in cluster "cluster2"
STEP: Found gateway node "cluster1-worker" on "cluster1"
STEP: Found non-gateway node "cluster1-worker2" on "cluster1"
STEP: Found submariner engine pod "submariner-gateway-frbsg" on "cluster1"
STEP: Deleting namespace "e2e-tests-gateway-redundancy-l9rhp" on cluster "cluster1"
STEP: Deleting namespace "e2e-tests-gateway-redundancy-l9rhp" on cluster "cluster2"

• Failure [240.147 seconds]
[redundancy] Gateway fail-over tests
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/submariner/test/e2e/redundancy/gateway_failover.go:18
  when a new node is labeled as a gateway node and the label on the existing gateway node is removed
  /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/submariner/test/e2e/redundancy/gateway_failover.go:36
    should start a submariner engine on the new gateway node and be able to connect from another cluster [It]
    /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/submariner/test/e2e/redundancy/gateway_failover.go:37

    Failed to find the submariner endpoint for cluster1. No endpoint found
    Unexpected error:                                                                                                                                                                         
        <*errors.errorString | 0xc0002e6200>: {                                                                                                                                               
            s: "timed out waiting for the condition",                                                                                                                                         
        }                                                                                                                                                                                     
        timed out waiting for the condition                                                                                                                                                   
    occurred                                                                                                                                                                                  

    /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416

**What you expected to happen**:
All e2e tests should pass consistently

**Environment**:
- Submariner version (use `subctl version`): v0.8.0-rc0 
- Kubernetes version (use `kubectl version`): v1.19.0
- Cloud provider or hardware configuration: KIND
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): Libreswan
- Others:

**Comment by aswinsuryan** [comment]
Before the wireguard driver configuration is complete Pinger starts , this cause pinger to have incorrect translation for the outbound packet and a connect as entry is created. Even after wireguard tunnel is up, since the connrack entry exists the packet fails to reach the destination
`icmp     1 29 src=10.1.1.1 dst=10.2.96.0 type=8 code=0 id=31762 [UNREPLIED] src=10.2.96.0 dst=172.17.0.7 type=0 code=0 id=31762 mark=0 secctx=system_u:object_r:unlabeled_t:s0 use=1`

But if initiate a new ping from the g/w pods CLI it works. 
icmp     1 28 src=10.1.1.1 dst=10.2.96.0 type=8 code=0 id=42684 src=10.2.96.0 dst=10.1.1.1 type=0 code=0 id=42684 mark=0 secctx=system_u:object_r:unlabeled_t:s0 use=1

So the pinger logic shall be changed to create a new pinger on failure rather than reusing the same connection.
