### ISSUE TITLE
Submariner Engine metrics are not exposed properly

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner#999]
**What happened**:

Looking at the OpenShift Metrics UI, I am not able to query the ones exposed from the Engine (e.g `gateway_rx_bytes`, `gateway_tx_bytes`, and so on). `submariner_gateways` and `submariner_connections` work as expected.

**What you expected to happen**:

The metrics to be discoverable.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy Submariner across two OCP clusters
2. Enable user workload monitoring in the cluster-monitoring-config configmap 

**Anything else we need to know?**:

Looking at the metrics services within the submariner-operator namespace, it seems like `submariner-engine-metrics` is exposed on 8080/TCP and not 8383/TCP,8686/TCP like `submariner-operator-metric`:

```
$ kubectl get svc -n submariner-operator
NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
submariner-engine-metrics       ClusterIP   172.30.253.50    <none>        8080/TCP            33m
submariner-lighthouse-coredns   ClusterIP   172.30.35.242    <none>        53/UDP              33m
submariner-operator-metrics     ClusterIP   172.30.174.198   <none>        8383/TCP,8686/TCP   33m
```

**Environment**: 

 OCP 4.6.1, subctl 0.8.0-rc0

**Comment by sridhargaddam** [comment]
As discussed on the slack, we should capture notes saying that GatewayNode should not be running any process that listens on the same port (tcp/8080) that's used for metrics.

**Comment by skitt** [comment]
> As discussed on the slack, we should capture notes saying that GatewayNode should not be running any process that listens on the same port (tcp/8080) that's used for metrics.

I’ve added this to the prerequisites in https://github.com/submariner-io/submariner-website/pull/392

**Comment by nyechiel** [comment]
Thanks @skitt. In addition to the the prerequisites, I think that we should also add this info to the OCP-IPI tool (https://github.com/submariner-io/submariner/tree/master/tools/openshift/ocp-ipi-aws) and OpenShift quickstarts (https://github.com/submariner-io/submariner-website/blob/master/src/resources/shared/openshift/download_prep_for_subm.md).

**Comment by skitt** [comment]
> I think that we should also add this info to the OCP-IPI tool (https://github.com/submariner-io/submariner/tree/master/tools/openshift/ocp-ipi-aws)

https://github.com/submariner-io/submariner/pull/1006, thanks for the suggestion.

**Comment by skitt** [comment]
> OpenShift quickstarts (https://github.com/submariner-io/submariner-website/blob/master/src/resources/shared/openshift/download_prep_for_subm.md).

https://github.com/submariner-io/submariner-website/pull/396
